Form context clean breaking with hoc
plone/volto pull request #1711
Opened 2020-07-30 18:33 UTC by tiberiuichim

Yet another iteration on the form context, PR, based on the "breaking" variety. 

This time I've restructured the context provider as a HOC.

2020-08-03 19:58 UTC, tiberiuichim commented
It seems that uploading an image breaks the form. I'm guessing it's because of https://github.com/plone/volto/issues/1654

2020-08-14 12:58 UTC, tiberiuichim commented
A sort of "technology demo" of what the form state context enables, a new plugin: https://www.youtube.com/watch?v=iTaPsWLGTSQ https://github.com/eea/volto-tabsblock

2020-08-17 08:30 UTC, tiberiuichim commented
The image upload problem will be fixed by https://github.com/plone/volto/pull/1730

2020-08-18 10:35 UTC, nzambello commented
I like this, but I will look after this to test it

2020-08-26 16:00 UTC, avoinea requested changes

2020-08-26 16:00 UTC, avoinea commented on src/components/manage/Form/FormContext.jsx
> +};
Docs would be appreciated

2020-08-26 17:01 UTC, tiberiuichim commented on src/components/manage/Form/Form.jsx
> -    }
good catch. Bad git merge

2020-09-04 09:38 UTC, nzambello requested changes
I agree with @avoinea comments and I added another one

2020-09-04 09:38 UTC, nzambello commented on src/components/manage/Blocks/LeadImage/Edit.jsx
> +          <LeadImageSidebar {...{ ...this.props, properties }} />
```suggestion
          <LeadImageSidebar {...this.props} {...properties} />
```
This leads to the same result but it would be more readable IMHO

2020-09-18 13:14 UTC, tiberiuichim commented
I don't think it's a good idea to merge this PR right now.

The problem is that the "form state context" is not a generic concept. Now that I've started working on the idea of "subforms", I realize that we don't want to deal with multiple states when editing a page. If I'm editing a "subform" (represented as a column), I want to treat that subform as a stateless input component: it gets its content (value) as a prop, it calls a parent-provided callback to pass its changes. To have its own state would introduce concurency problems, I don't want to have those problems. 

I've stated to go at a different path: taking @nzambello idea of `onChangeFormData`, I'm not keeping form state in the parent. This leads to neat code, like in the ColumnsBlockEdit component here: https://github.com/eea/volto-columns-block/blob/b65e4f71c4071eea263b8a389d2caab887fac552/src/ColumnsBlock/ColumnsBlockEdit.jsx#L51

2020-09-22 08:46 UTC, closed without merging