add shouldComponentUpdate to blocks
plone/volto pull request #1715
Opened 2020-08-06 07:33 UTC by nileshgulia1

related #1694

2020-08-24 18:37 UTC, nileshgulia1 commented on src/components/manage/Blocks/Text/Edit.jsx
> +    return this.props.data.text !== nextProps.data.text;
Changed to using lodash `isEqual` method. Thanks for reporting :)

2020-09-08 14:34 UTC, tiberiuichim commented on src/components/manage/Blocks/Text/Edit.jsx
> +    return !isEqual(this.props.data.text, nextProps.data.text);
Why not use `props.selected` here, too?

2020-09-10 15:48 UTC, tiberiuichim requested changes
In the interest of brevity, maybe we can change it like:

Instead of:
```
  shouldComponentUpdate(nextProps) {
    if (this.props.selected) {
      return true;
    }
    return !isEqual(this.props.data, nextProps.data);
  }
```

have:

```
  shouldComponentUpdate(nextProps) {
    return this.props.selected || !isEqual(this.props.data, nextProps.data);
  }
```

2020-09-10 18:52 UTC, nileshgulia1 commented
@tiberiuichim I have refactored some methods. You can have a look now :)

2020-09-10 18:57 UTC, tiberiuichim commented
Nice! I'll test the code tomorrow

2020-09-10 19:01 UTC, tiberiuichim commented
I'll test the code tomorrow.

2020-09-11 10:32 UTC, tiberiuichim approved these changes

2020-10-13 09:28 UTC, tisto commented
todo:

- @tiberiuichim solves the merge conflict
- @sneridagh and @nzambello review it
- eau de web tests it in the alpha2

2020-10-15 03:09 UTC, tisto commented
@nileshgulia1 @tiberiuichim @avoinea if one of you can resolve the merge conflict we can merge and release another alpha.

2020-10-15 07:16 UTC, nileshgulia1 commented
@tisto Done !

2020-11-05 05:28 UTC, nileshgulia1 commented
@plone/volto-team is there still any blocker for this PR, or something I could look into?

2020-11-10 10:15 UTC, tisto commented
@plone/volto-team decision: this will go into 9.x.x. @tiberiuichim will create an issue regarding react.Memo.

2020-12-18 19:27 UTC, tiberiuichim commented
@sneridagh Should be good to go, if cypress tests pass.

2021-01-26 15:07 UTC, merged