Fixing file-preview other than image
plone/volto pull request #1763
Opened 2020-08-24 14:25 UTC by iFlameing

2020-08-24 14:34 UTC, tisto commented on src/components/manage/Widgets/FileWidget.jsx
> +const fileExtension = ['image/png', 'image/jpeg', 'image/webp', 'image/jpg'];
@iFlameing what about gif?

2020-08-24 14:51 UTC, tiberiuichim requested changes

2020-08-24 14:51 UTC, tiberiuichim commented on src/components/manage/Widgets/FileWidget.jsx
> +const fileExtension = ['image/png', 'image/jpeg', 'image/webp', 'image/jpg'];
Better name, `imageMimetypes` ?

2020-08-24 14:54 UTC, iFlameing commented on src/components/manage/Widgets/FileWidget.jsx
> +const fileExtension = ['image/png', 'image/jpeg', 'image/webp', 'image/jpg'];
yeah!!

2020-08-25 06:37 UTC, tisto approved these changes

2020-08-25 06:37 UTC, merged