Add Style component and AlignWidget
plone/volto pull request #1816
Opened 2020-09-14 19:03 UTC by tiberiuichim

The `<Style>` component is a wrapper that reads the `AlignWidget` information, which just wraps the AlignBlock helper.

I think we also should have a SizeWidget counterpart, not done yet.

2020-09-15 20:19 UTC, avoinea requested changes

2020-09-15 20:19 UTC, avoinea commented on src/components/manage/Widgets/AlignWidget.jsx
> +      )}
Not needed anymore. Moved to `FormFieldWrapper`

2020-09-15 20:39 UTC, avoinea approved these changes

2020-10-01 16:52 UTC, sneridagh reviewed
@tiberiuichim may I be picky about naming? :P
Isn't `Style` too generic? Since we want (and we should) to have a SizeWidget, why don't name it accordingly? Like `SizeWrapper` or `SizerWrapper`. Just sayin'!

For the rest, LGTM.

2020-10-02 08:53 UTC, tiberiuichim commented
@sneridagh the Style component reads and applies both the size and align information.

Very high on my todo list for today is to come up with a generic styling framework for all blocks. I want to have a easily reusable component that can give me this: 

- when I edit a block, I want to chose a style for the block, from a palette of predefined styles. Think "quote block" type, or "green block" that would apply a specific background to the block, and so on. 
- I also want to be able to float blocks around, set their size, etc. (But this part is easy if the first part is done).

2020-10-03 17:27 UTC, tiberiuichim commented on src/components/manage/Widgets/AlignWidget.jsx
> +      <AlignBlock
Needs a `<div className="align-tools">` around it.

2020-10-11 09:07 UTC, sneridagh approved these changes
LGTM
@tiberiuichim we should open an issue about all the things that we need to document like this one.

2020-10-12 20:18 UTC, nzambello approved these changes

2020-10-13 09:27 UTC, nzambello commented
WARNING: this will merge the CHANGELOG entries in a past release

2020-10-13 10:57 UTC, merged