Upgrade react dropzone to v11.1.0
plone/volto pull request #1821
Opened 2020-09-15 16:53 UTC by nileshgulia1

We're using quite old react-dropzone package. The latest being 11.1.0 and we were still at v5.x.

2020-09-15 16:58 UTC, nileshgulia1 commented on src/components/manage/Contents/ContentsUploadModal.jsx
> +                            src={`${flattenToAppURL(
@tiberiuichim Latest react-dropzone package hasn't has `preview` property. How do we internally handle image previews when images are coming not from `@image` endpoints?

2020-09-15 18:13 UTC, nileshgulia1 commented on src/components/manage/Contents/ContentsUploadModal.jsx
> +                            src={`${flattenToAppURL(
https://github.com/plone/volto/blob/88b6ea08580436f7a3614f07cab52711238acd97/src/components/manage/Widgets/FileWidget.jsx#L66

2020-09-15 19:17 UTC, nileshgulia1 commented on src/components/manage/Contents/ContentsUploadModal.jsx
> +                            src={`${flattenToAppURL(
4bee4f2 fixes it.

2020-09-22 08:43 UTC, tiberiuichim requested changes
There's an error in the folder contents multi-upload, it happens when uploading multiple images. Only one of them is properly previewed, when I try to remove the "broken" ones I get this error:

```
(TypeError): Cannot set property 'src' of null
(anonymous function)
src/components/manage/Contents/ContentsUploadModal.jsx:128
  125 | getUrl = (file) => {
  126 |   readAsDataURL(file).then((data) => {
  127 |     const fields = data.match(/^data:(.*);(.*),(.*)$/);
> 128 |     this.previewRef.current.src = fields[0];
      | ^  129 |   });
  130 | };
  131 | /**
```

2020-09-25 14:33 UTC, iFlameing approved these changes

2020-09-25 14:34 UTC, iFlameing commented
@tiberiuichim I fixed the problem which you mentioned. Can you please review it once again??

2020-09-25 15:08 UTC, tisto commented
@tiberiuichim can you do another review of this PR? @iFlameing would like to work on the upload drop zone highlighting feature which depends on this PR to be merged.

2020-09-25 16:08 UTC, nileshgulia1 reviewed
LGTM. Thanks @iFlameing

2020-09-25 16:24 UTC, tiberiuichim commented
@tisto @iFlameing @nileshgulia1  now the upload works as expected, but:

I don't know if it's just my system, I get a console error:

```
React Intl] Error formatting the default message for: "Upload {count, plural, one {# file} other {# files}}"
Error: The intl string context variable "undefined" was not provided to the string "undefined"
```

and the tooltip for the accept button seems to have something broken in its message formatting.
![Screenshot 2020-09-25 082430](https://user-images.githubusercontent.com/141568/94291758-aea3bc00-ff64-11ea-9e7d-82cefc83942b.png)

2020-09-25 16:24 UTC, tiberiuichim commented
![Screenshot 2020-09-25 192424](https://user-images.githubusercontent.com/141568/94291806-bcf1d800-ff64-11ea-9521-50e68a2fdb87.png)

2020-09-25 17:38 UTC, iFlameing commented
@tiberiuichim I also found the same error in my machine also. But I didn't know why it is giving error I haven't change anything to formating message.

2020-09-25 18:39 UTC, iFlameing commented
@tiberiuichim @tisto @nileshgulia1 This error is not introduced by this pr. You can see the same error in master also.

2020-09-25 18:46 UTC, tiberiuichim approved these changes

2020-09-25 19:28 UTC, iFlameing commented
@tisto @nileshgulia1 @tiberiuichim I fixed the translation issue. Ready for merge :)

2020-10-05 17:09 UTC, iFlameing commented
@tisto It is ready for merge :)

2020-10-06 08:29 UTC, tisto commented on locales/de/LC_MESSAGES/volto.po
> -msgstr "Lade {count, plural, one {# Datei} other {# Dateien}} hoch"
@nileshgulia1 we should keep the German translation here if possible. :)

2020-10-06 08:42 UTC, merged

2020-10-06 08:49 UTC, tisto commented on locales/de/LC_MESSAGES/volto.po
> -msgstr "Lade {count, plural, one {# Datei} other {# Dateien}} hoch"
@nileshgulia1 FYI: I re-added the translation myself. Will do a release now.

2020-10-07 21:23 UTC, avoinea commented
@tisto Unfortuantely this was a breaking feature https://github.com/plone/volto/issues/1682#issuecomment-661057986. 

Upgrading my votlo app from @plone/volto `8.2.2` to `8.2.3` I get the following error in Edit mode:

![2020-10-08-002328_1008x846_scrot](https://user-images.githubusercontent.com/323385/95389441-815bf400-08fc-11eb-91f9-5207c5db43f5.png)

2020-10-08 03:09 UTC, tisto commented
@avoinea can you provide steps to reproduce? Does this happen in vanilla Volto? We had to amend some code in our project as well. We might have to consider to revert this then and re-release a new mayor version of Volto.

2020-10-08 03:52 UTC, nileshgulia1 commented
As this was a major version upgrade of react-dropzone, this will cause a
breaking change in volto projects using older versions of react-dropzone.

On Thu, Oct 8, 2020, 08:39 Timo Stollenwerk <notifications@github.com>
wrote:

> @avoinea <https://github.com/avoinea> can you provide steps to reproduce?
> Does this happen in vanilla Volto? We had to amend some code in our project
> as well. We might have to consider to revert this then and re-release a new
> mayor version of Volto.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/plone/volto/pull/1821#issuecomment-705302969>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFJ7VRN4M2ASRA65LRBPFWDSJUUO3ANCNFSM4RNNTHMQ>
> .
>

2020-10-08 03:53 UTC, tisto commented
@nileshgulia1 could you start writing a PR with an update to the Volto upgrade guide describing this?

2020-10-08 05:21 UTC, avoinea commented
Sorry, the issue was introduced in `8.2.2`

2020-10-08 07:02 UTC, nileshgulia1 commented
@tisto Sure, will do.

2020-10-08 09:45 UTC, tiberiuichim commented
@tisto It's not a breaking change, it's just something that belongs to our internal "kitchen". We've had a package that depended on react-dropzone, but we haven't specified react-dropzone as dependency. Addon authors, beware. :-)