Tel link and improve UniversalLink
plone/volto pull request #1946
Opened 2020-10-26 13:06 UTC by giuliaghisini

added the ability to enter phone numbers in links in draftJs and UrlWidget.

Fixed UniversalLink component to work with emails and tel link

2020-10-26 13:39 UTC, nzambello approved these changes
LGTM, nice job

2020-10-26 17:07 UTC, tiberiuichim requested changes

2020-10-26 17:07 UTC, tiberiuichim commented on src/components/manage/AnchorPlugin/utils/URLUtils.js
> +  normalizeTelephone(tel) {
normalise or normalize? I see both versions in this code.

2020-10-26 17:07 UTC, tiberiuichim commented on src/helpers/Url/Url.js
> +  return url.indexOf(settings.apiPath) === 0
Is it relevant here to also use settings.internalApiPath? We use both of them, as frontend comunicates with the backend through settings.internalApiPath.

2020-11-23 05:52 UTC, tiberiuichim approved these changes

2020-12-16 08:48 UTC, cekk commented
@tisto @sneridagh is it ok for you?

2020-12-16 10:12 UTC, tiberiuichim reviewed
The LinkView starts to get complicated with lots of ifs and by implementing "some" use cases we open the question: what if I have other cases?

Can we make this configurable with a registry of "link parsers to component renderer"?

2021-01-15 13:25 UTC, giuliaghisini commented
@sneridagh @tisto can we merge in master?

2021-01-18 08:22 UTC, sneridagh approved these changes
LGTM, @cekk @giuliaghisini didn't this was related to some change in restapi needed to be merged? If it's already merged we can do it right away.

2021-01-18 08:45 UTC, cekk commented
I don't find anything related in my restapi prs, so it's a green button from me.

2021-01-19 17:28 UTC, merged