Search depth
plone/volto pull request #2032
Opened 2020-11-30 11:39 UTC by giuliaghisini

Added search **depth** in listing blocks. 
The depth field shows up only if there's at least one 'path' criteria in query.

2020-12-03 12:01 UTC, nzambello approved these changes

2020-12-04 10:22 UTC, sneridagh requested changes

2020-12-04 10:22 UTC, sneridagh commented on src/actions/querystringsearch/querystringsearch.js
>              ? data.b_size * (page - 1)
Missing data -> d ?
I'm not a fan of using such short var names, I see that the naming here might be redundant, but still... Can we stick  to meaningful name vars?

2020-12-04 18:29 UTC, sneridagh approved these changes

2020-12-04 18:47 UTC, merged