Lazy load react-dropzone
plone/volto pull request #2044
Opened 2020-12-02 18:35 UTC by nileshgulia1

lazy loading stuffs... https://github.com/plone/volto/issues/1932

2020-12-03 11:41 UTC, tiberiuichim commented
LGTM.

I've been looking to see if the `waitFor(() => {})` pattern can be improved, but it looks like that, as long as we use snapshot based testing, we have to live with it?

https://github.com/testing-library/dom-testing-library/issues/484#issuecomment-601950328

2020-12-03 11:42 UTC, tiberiuichim approved these changes

2020-12-03 18:36 UTC, tiberiuichim requested changes

2020-12-03 18:47 UTC, nileshgulia1 commented on src/components/manage/Widgets/FileWidget.test.jsx
> +import { render, waitFor, screen } from '@testing-library/react';
We use it below.

2020-12-03 19:24 UTC, tiberiuichim approved these changes

2020-12-04 10:11 UTC, sneridagh approved these changes

2020-12-04 18:21 UTC, merged