Removing id from form field wrapper
plone/volto pull request #2102
Opened 2021-01-05 09:42 UTC by iFlameing

I think that we don't need this or we have to change the "field" to something like "wrapper" so that if someone doesn't pass the fieldset we are assigning two ids with the same value. The Form.Field and label  you can see by visiting these two links
https://github.com/plone/volto/blob/master/src/components/manage/Widgets/FormFieldWrapper.jsx#L106
https://github.com/plone/volto/blob/master/src/components/manage/Widgets/FormFieldWrapper.jsx#L113

2021-01-05 09:59 UTC, tisto commented
Either the wrapper should have a unique ID or the field, not both.

2021-01-06 08:13 UTC, tisto requested changes
@iFlameing seems you need to amend a Cypress test. I am actually wondering why we only have to amend one Cypress test. Seems we do not have a good forms test coverage.

2021-01-07 09:39 UTC, tisto commented
Note: we remove the id from the wrapper. We have to make sure the fieldset is in the ID of the input field itself to avoid collisions when using the same form fields in different fieldsets.

2021-01-09 14:42 UTC, tiberiuichim approved these changes

2021-01-09 15:28 UTC, sneridagh commented
@plone/volto-team Timo and I think that the PR might be potentially breaking since someone might rely on the ids for their acceptance tests, so I marked it as breaking and schedule it for the next major.

2021-01-19 18:31 UTC, sneridagh commented
@iFlameing please can you write docs about this breaking change? docs/source/upgrade-guide/index/md

2021-01-20 17:19 UTC, iFlameing commented
@sneridagh yes!

2021-01-26 09:30 UTC, tisto commented on docs/source/upgrade-guide/index.md
> +add `.react-select-container` instead of your id.
@iFlameing maybe we can show an example diff here or at least point to this PR, so people can check what actually changed.

2021-01-26 09:31 UTC, tisto approved these changes
I'd add a link to this PR in the upgrade guide. Apart from this the PR looks good!

2021-01-26 09:37 UTC, merged