Inserted a dimmer with the loading message in the form when the statu…
plone/volto pull request #2218
Opened 2021-02-18 11:44 UTC by damiDev8

The dimmer with the loading message has been inserted in the rename and workflow change forms. To do this, two props have been set up in the ModalForm to understand if it is loading and the loading message to show. a problem with modal overflow is fixed

2021-02-19 08:39 UTC, giuliaghisini requested changes

2021-02-19 08:39 UTC, giuliaghisini commented on locales/it/LC_MESSAGES/volto.po
> +msgstr ""
@damiDev8 add italian translation

2021-02-19 08:39 UTC, giuliaghisini commented on locales/it/LC_MESSAGES/volto.po
> +msgstr ""
@damiDev8 add italian translation

2021-02-19 08:39 UTC, giuliaghisini commented on locales/it/LC_MESSAGES/volto.po
> +msgstr ""
@damiDev8 add italian translation

2021-02-19 08:39 UTC, giuliaghisini commented on locales/it/LC_MESSAGES/volto.po
> +msgstr ""
@damiDev8 add italian translation

2021-02-19 09:47 UTC, tiberiuichim requested changes

2021-02-19 09:47 UTC, tiberiuichim commented on src/components/manage/Contents/Contents.jsx
> +    id: 'Item(s) workflow has been updated.',
The modal dialog says "Change state", the Contents toolbar says "Change state", we should keep the wording. Editors may not exactly know what "workflow" means.

2021-02-22 09:32 UTC, tiberiuichim approved these changes

2021-03-01 09:33 UTC, damiDev8 commented
hi, now the request should be ready to be merged @sneridagh

2021-03-03 15:53 UTC, sneridagh approved these changes

2021-03-03 15:54 UTC, merged