Translations german: Reset Password
plone/volto pull request #2221
Opened 2021-02-20 09:26 UTC by ksuess

just a little change to prevent confusion about what is sent: link not password itself.

2021-02-20 15:49 UTC, tisto commented on locales/de/LC_MESSAGES/volto.po
> +msgstr "Mein Benutzername / meine E-Mail-Adresse lautet"
@ksuess wouldn't that be upper-case "Meine E-Mail-Adresse"?

2021-02-20 15:50 UTC, tisto requested changes
LGTM. Apart from the one minor issue that I mentioned. I am wondering if it would be possible to show a message dependent if email-usernames are enabled or not.

2021-03-31 14:14 UTC, ksuess commented
> LGTM. Apart from the one minor issue that I mentioned. I am wondering if it would be possible to show a message dependent if email-usernames are enabled or not.

Maybe I'm wrong, but I think the info about email or username authentication is not available for anonymous.

2021-04-26 06:46 UTC, ksuess commented
Test failure seems to be unrelated:

```
Run actions/upload-artifact@v1
Error: Path does not exist /home/runner/work/volto/volto/cypress/videos
Error: Exit code 1 returned from process: file name '/home/runner/runners/2.278.0/bin/Runner.PluginHost', arguments 'action "GitHub.Runner.Plugins.Artifact.PublishArtifact, Runner.Plugins"'.

```

2021-04-29 08:09 UTC, sneridagh approved these changes

2021-04-29 08:48 UTC, merged