Added SidebarPopup component for extra sidebar handling
plone/volto pull request #2284
Opened 2021-03-18 22:03 UTC by avoinea

- Custom Generic Sidebar outside Blocks scope.
- Extra configuration for widgets within SidebarPortal.

2021-03-19 04:14 UTC, tiberiuichim approved these changes
We might need a special doc chapter on things we include that are not directly used in Volto?

2021-03-19 07:27 UTC, nileshgulia1 approved these changes

2021-03-19 08:24 UTC, tiberiuichim requested changes

2021-03-19 08:24 UTC, tiberiuichim commented on src/components/index.js
> +export SidebarPopup from '@plone/volto/components/manage/Sidebar/SidebarPopup';
I'm not sure we want this line. Would webpack drop this component from the bundle if we don't do this? In theory only addons that use this component would activate the inclusion of the module in the bundle.

2021-03-22 10:24 UTC, tiberiuichim approved these changes

2021-03-23 11:26 UTC, sneridagh commented on src/components/manage/Sidebar/SidebarPopup.jsx
> +          key="sidebarpopup"
Now I see it here :)

2021-03-23 11:26 UTC, sneridagh approved these changes

2021-03-25 12:08 UTC, sneridagh approved these changes

2021-03-25 12:08 UTC, merged