Added cookiesExpire prop to configure the cookie expiration
plone/volto pull request #3061
Opened 2022-02-11 16:33 UTC by giuliaghisini

2022-02-11 16:41 UTC, nileshgulia1 commented
How about adding some documentation for this setting in config registry?: https://docs.voltocms.com/configuration/how-to/#the-configuration-registry

2022-02-14 09:06 UTC, stevepiercy requested changes
Improve English grammar.

This docs changes should also be backported to `plone6-docs` after merging.

2022-02-14 10:48 UTC, stevepiercy approved these changes

2022-02-14 10:50 UTC, stevepiercy commented
@giuliaghisini would you please add a CHANGELOG.md entry? Then it should be good to go. Thank you!

2022-02-16 14:18 UTC, sneridagh approved these changes

2022-02-16 14:19 UTC, merged