Refactor language syncronizer. Remove it from the React tree, integra…
plone/volto pull request #3104
Opened 2022-02-25 17:59 UTC by sneridagh

…te it into the Api Redux middleware.

This one is much better than https://github.com/plone/volto/pull/3103

2022-02-26 12:15 UTC, tiberiuichim requested changes

2022-02-26 12:15 UTC, tiberiuichim commented on cypress/tests/multilingual/basic-multilingual.js
> +  it.only('Language coming from SSR', function () {
it.only

2022-02-26 16:28 UTC, sneridagh commented on cypress/tests/multilingual/basic-multilingual.js
> +  it.only('Language coming from SSR', function () {
Done

2022-02-26 16:28 UTC, sneridagh commented
Even with server-side support now.

2022-02-28 07:40 UTC, giuliaghisini reviewed
I just have a doubt .. what happens in the babel view?

2022-02-28 07:59 UTC, sneridagh commented
Good question, the TranslationObject has the means for trigger the translation. The tests pass, so it works as expected.

2022-02-28 08:46 UTC, reebalazs approved these changes

2022-02-28 10:03 UTC, tiberiuichim approved these changes

2022-02-28 10:20 UTC, merged