[Bug #3124] - clipped dropdown menu in Contents view
plone/volto pull request #3158
Opened 2022-03-15 14:03 UTC by mihaislobozeanu

2022-03-16 17:05 UTC, avoinea requested changes

2022-03-22 17:08 UTC, tiberiuichim commented on theme/themes/pastanaga/modules/popup.overrides
> +.dropdown-popup-trigger{
I think this file needs prettier for formatting. Usually there's a space before curlies.

2022-03-24 10:10 UTC, avoinea approved these changes

2022-03-29 10:37 UTC, pnicolli commented on src/helpers/index.js
> +export Popup from './Popup/Popup';
I thought about it after the team meeting today and I'm not a fan of having an actual component in the helpers folder. I would personally prefer moving it to the components folder. Just my 2 cents on this.

2022-03-29 10:47 UTC, avoinea commented on theme/themes/pastanaga/extras/contents.less
> +    //#3124 - dropdown menus are clipped when table has few or no records
I think this is a leftover. @mihaislobozeanu

2022-03-29 11:16 UTC, tiberiuichim commented
@pnicolli We already have some components in helpers. https://github.com/plone/volto/blob/master/src/helpers/ScrollToTop/ScrollToTop.jsx and https://github.com/plone/volto/blob/master/src/helpers/BodyClass/BodyClass.jsx

I'm ok with moving it in another place. Maybe components/theme/PopupWrapper ?

2022-03-31 18:18 UTC, sneridagh commented
I think also that it's not a helper, but a component... I would re-place it, what do you think? 

Also, but this is another question, what when we get rid of SemanticUI (eg. projects that do not use it at all? :)

2022-04-01 05:40 UTC, tiberiuichim commented
> Also, but this is another question, what when we get rid of SemanticUI (eg. projects that do not use it at all? :)

when we get rid of semantic-ui we'll have other, bigger, things to worry about :-)

In any case, we'd begin with a refactoring of the Contents component and move it to react-table or something like that. I think that's something we should already start doing.

2022-04-01 07:13 UTC, avoinea commented
@pnicolli @tiberiuichim What we agreed on this one?

2022-04-01 08:04 UTC, sneridagh commented
If everybody agrees, we refactor it and move it to the components folder, then it's good to go?

2022-04-01 10:05 UTC, pnicolli commented
> If everybody agrees, we refactor it and move it to the components folder, then it's good to go?

Agreed

2022-04-01 10:12 UTC, tiberiuichim commented
I still don't think components/theme is the right place to put it, as it's a helper component that can be used even outside Volto. I can agree that src/helpers is not the best location, but there's no other existing place for it. Maybe a new `src/components/ui`. But I'm fine with placing it in src/components/theme, so +1 from me.

2022-04-01 10:21 UTC, sneridagh commented
@tiberiuichim I agree with you that it's a new kind of component, and that ideally should be "separated" from the structural ones. I also thought in having this new category in the components folder for Quanta. See

https://github.com/plone/volto/pull/3086/files#diff-9837e4844c73b95722bd37d81ab4ce85e00a07552905224cfd7d9041e62703daR1

I initially called that "core", but naming... again. We can start doing it that now, or reorder them later.

2022-04-01 11:58 UTC, tiberiuichim commented
In any case, we expose components through the `@plone/volto/components` index, so if we decide that we need to move it later, we can do that without too much breakage. Let's put it in components/theme.

2022-04-06 10:06 UTC, sneridagh commented
@mihaislobozeanu could you please take care of the decision? Thanks!

2022-04-06 14:31 UTC, mihaislobozeanu commented
> 

Resolved

2022-05-06 06:25 UTC, giuliaghisini approved these changes

2022-05-06 07:19 UTC, sneridagh reviewed
@mihaislobozeanu LGTM, sorry for the pickiness, but could you take a look at the last thing? then let's merge.

2022-05-06 07:19 UTC, sneridagh commented on src/components/manage/Contents/Contents.jsx
> +    //event.stopPropagation();
Are we sure about this one? and if so, let's remove it.

2022-05-06 14:04 UTC, merged