Added language in codeblocks
plone/volto pull request #3165
Opened 2022-03-16 10:59 UTC by ktsrivastava29

I'm adding languages to codeblocks in md files. There are a few code blocks that don't have a language for their lexer, and Pygments isn't always smart enough to figure out what language is intended.
The language should be stated as follows: 
````
```language

code

```
````
fix: https://github.com/plone/volto/issues/3090
also see: https://github.com/plone/volto/pull/3155

2022-03-16 11:38 UTC, stevepiercy requested changes
Please see individual comments.

This will also need a review from a maintainer.

2022-03-16 11:38 UTC, stevepiercy commented on docs/source/recipes/creating-project.md
>  1. Open a terminal and execute:
For this numbered list, the syntax is a little tricky. Any content in a list must be indented. I also prefer to indent everything 4 spaces and have it aligned, including the content after a number or bullet. For example:

````
1.  Open a terminal and execute:

    ```shell
    npm install -g yo @plone/generator-volto
    yo @plone/volto
    ```
````

...will render nicely with the code-block within the context of item 1. Please apply the same to this list, and use `make docs-livehtml` to watch the changes as you edit them in real time.

2022-03-16 11:38 UTC, stevepiercy commented on docs/source/recipes/creating-project.md
>  ```
````suggestion
```shell
````

2022-03-16 11:38 UTC, stevepiercy commented on docs/source/recipes/creating-project.md
>  $ yarn start
Purge all prompts.

```suggestion
yarn start
```

2022-03-16 11:38 UTC, stevepiercy commented on docs/source/recipes/i18n.md
>  1. Import the following necessary methods:
See above comment about indentation of list items.

2022-03-16 11:38 UTC, stevepiercy commented on docs/source/recipes/i18n.md
>  ```
````suggestion
```html
````

2022-03-16 11:38 UTC, stevepiercy commented on docs/source/recipes/i18n.md
>  ```
I'm not sure, but I think this is `jsx`.

````suggestion
```jsx
````

2022-03-16 11:38 UTC, stevepiercy commented on docs/source/recipes/i18n.md
> +```shell
This is output, not a shell command. For output, we use `console`.

````suggestion
```console
````

2022-03-16 11:38 UTC, stevepiercy commented on docs/source/recipes/i18n.md
> +
See above comment about indenting list items with code-blocks.

2022-03-16 11:38 UTC, stevepiercy commented on docs/source/recipes/i18n.md
>  ```
This one needs a language. I am not sure which. Is it Python?

2022-03-16 11:38 UTC, stevepiercy commented on docs/source/recipes/i18n.md
>  ```
````suggestion
```js
````

2022-03-16 11:38 UTC, stevepiercy commented on docs/source/recipes/lazyload.md
>  ```bash
We want to replace all instances of the bash language with shell so that we are shell-neutral.

````suggestion
```shell
````

2022-03-17 11:14 UTC, stevepiercy requested changes

2022-03-17 11:14 UTC, stevepiercy commented on docs/source/recipes/creating-project.md
>  1. Open a terminal and execute:
The code-block still does not indent properly. See the build preview:

https://deploy-preview-3165--volto.netlify.app/recipes/creating-project.html

Compare that code block to the code-blocks in https://deploy-preview-3165--volto.netlify.app/getting-started/install.html#install-nvm-nodejs-version-manager.

You can also look at the source of that file if you need further guidance.

2022-03-17 11:15 UTC, stevepiercy commented
You will also need to resolve merge conflicts with `master` again.

2022-03-17 17:19 UTC, ktsrivastava29 commented
@stevepiercy I've now fixed the indent and have also resolved the conflicts

2022-03-19 11:26 UTC, stevepiercy commented
@ktsrivastava29 please check the preview build and note the list is now broken.

https://deploy-preview-3165--volto.netlify.app/recipes/creating-project.html

Please build the docs locally, and inspect a preview locally, before pushing more commits.

2022-03-20 11:39 UTC, ktsrivastava29 commented
@stevepiercy I've fixed that, please let me know how can I make it better

2022-03-21 01:59 UTC, stevepiercy commented
@ktsrivastava29 again, please check the preview. And not just for this one file, but for all files you have touched.

https://deploy-preview-3165--volto.netlify.app/recipes/creating-project.html

Before pushing any more commits to this pull request, and asking for another review, first build the docs locally and preview them to ensure that they render correctly.

2022-03-22 02:25 UTC, ktsrivastava29 commented
@stevepiercy I sincerely apologize for bothering you again; actually, I went through each file I edited and fixed the indent where necessary; locally, everything was great, but when I pushed, the test failed; could you kindly assist me in resolving this error?

2022-03-22 11:22 UTC, stevepiercy commented
@ktsrivastava29 the failure can be resolved by rebasing your branch onto `master`, then force pushing it. We recently added the linkcheck requirement in GitHub Actions, but it is not in your branch's `Makefile`.

2022-03-22 12:11 UTC, stevepiercy requested changes
When you build the docs locally, please check warnings and visually inspect the build before pushing commits and asking for my review. I have to assume you are not doing that, based on what I see in this review round. This PR still needs work. It is not OK to repeatedly say that you have addressed suggestions, but have actually not addressed them.

2022-03-22 12:46 UTC, nileshgulia1 reviewed
@ktsrivastava29 There's a simple command `make docs-livehtml` https://github.com/plone/volto/blob/master/Makefile#L127 which will save you a lot of time while developing on this PR. Please use it before pushing further commits.

2022-03-26 04:32 UTC, ktsrivastava29 commented
@stevepiercy I've fixed all and double-checked everything; I apologise for taking up so much of the time. Actually previously, I was receiving some HTTPS errors, which took me a day to resolve, and then I got an error due to the improper directory name; after resolving all of these, I was able to go through the suggested changes and then modify it.

2022-03-26 09:40 UTC, stevepiercy requested changes
We're almost there! All the lists look good now. There is a file that should not be included in this PR, and a couple of other minor changes, a few which were overlooked.

2022-03-26 09:40 UTC, stevepiercy commented on docs/source/recipes/creating-project.md
> +4.  The project is ready to be started, `@plone/generator-volto` already has run the
Let's keep the sentence together on one line.

```suggestion
4.  The project is ready to be started, `@plone/generator-volto` already has run the dependencies installations for you.
```

2022-03-26 09:40 UTC, stevepiercy commented on docs/source/recipes/creating-project.md
>     dependencies installations for you.
```suggestion
```

2022-03-26 09:40 UTC, stevepiercy commented on docs/source/recipes/environment-variables.md
> +```shell
Please also wrap lines 12 and 17 above as shell commands.

2022-03-26 09:40 UTC, stevepiercy commented on lib64
> +lib
This file should not be committed to the repository. Please remove.

2022-03-26 13:40 UTC, ktsrivastava29 commented
@stevepiercy I've made the changes you recommended; please take a look now.

2022-03-27 06:27 UTC, stevepiercy requested changes
One more change, please.

2022-03-27 06:27 UTC, stevepiercy commented on .gitignore
> +lib64
This is Python related, not Node. Please move this line under the #Python section, following its sorting and leading slash patterns.

2022-03-27 08:27 UTC, ktsrivastava29 commented
@stevepiercy Oh, I'm sorry, I wrongly placed it; I've fixed it now.

2022-03-27 08:38 UTC, ktsrivastava29 commented
@stevepiercy Previously, only one test failed; now, two have failed. I haven't made any changes since the last push, except for the minor change in the gitignore file that you suggested.

2022-03-27 09:02 UTC, stevepiercy approved these changes

2022-03-27 09:08 UTC, stevepiercy commented
The [failing docs build](https://github.com/plone/volto/runs/5708574282?check_suite_focus=true) will be fixed in https://github.com/plone/volto/pull/3196. We can ignore that failure.

For the [failing core sandbox tests build](https://github.com/plone/volto/runs/5708574126?check_suite_focus=true#step:8:738), I am not sure. @tiberiuichim or @sneridagh, have you got any idea? I restarted that failure to see if it was just a temporary connection issue. Let's see if it fails again. I restarted that failed build for my PR, and it just now passed.

2022-03-27 09:09 UTC, stevepiercy commented
We just merged https://github.com/plone/volto/pull/3196, so the docs build should now pass, I think.

2022-03-27 09:11 UTC, stevepiercy commented
meh, nm, docs build still breaks because this PR has not switched to use plain old `docs-linkcheck`. The docs build failure may be ignored.

2022-03-27 09:17 UTC, nileshgulia1 commented
@ktsrivastava29 You can try rebasing your PR with master.

2022-03-27 09:20 UTC, stevepiercy requested changes

2022-03-27 09:20 UTC, stevepiercy commented on lib64
> +lib
This file still exists in your PR. Please remove it from the PR.

2022-03-27 09:42 UTC, stevepiercy approved these changes
Excellent. Thank you!

Would you please also either merge `master` into your branch or rebase your branch on `master` and force push? Then that should get the failing docs build to pass, and should allow you to merge your own pull request.

2022-03-27 09:44 UTC, stevepiercy commented
Oops, actually, it looks like the docs test now passes. Nevermind about rebasing or merging. Let's wait for all green, then you can merge.

2022-03-27 09:53 UTC, ktsrivastava29 commented
@stevepiercy @nileshgulia1 Thank you; this is my third PR in this organisation, and I'm overjoyed as after 10 days it finally got approved. I'm learning a lot from your experiences. I'm eager to learn and contribute as much as I can.

2022-03-27 10:29 UTC, stevepiercy commented
@ktsrivastava29 please do the honor of merging your PR.

2022-03-27 14:19 UTC, ktsrivastava29 commented
@stevepiercy Sorry, you will have to do it because the base branch restricts merging to me, perhaps only the core team is authorized to merge into master.

2022-03-27 18:23 UTC, merged