added meta html values
plone/volto pull request #3213
Opened 2022-03-30 17:25 UTC by ktsrivastava29

fix: #3033 

**Problem**
The html_meta values were missing from most of the pages. These values are used to improve SEO. Omitting them results in errors when building the docs with Sphinx.

**Solution offered**
 I've added the meta html values in every page with the exception of three pages, as their documentation is currently being built.

2022-03-30 19:54 UTC, stevepiercy commented
@ktsrivastava29 please add a changelog entry.

2022-03-31 04:40 UTC, ktsrivastava29 commented
@stevepiercy Sorry, I missed adding that earlier, I've added it now

2022-03-31 06:31 UTC, stevepiercy requested changes

2022-03-31 06:31 UTC, stevepiercy commented on docs/source/blocks/introduction.md
> +  "keywords": "Volto, Plone, frontend, React"
```suggestion
  "keywords": "Volto, Plone, frontend, React, blocks"
```

2022-03-31 06:31 UTC, stevepiercy commented on docs/source/blocks/settings.md
> +  "description": "How to configure a new block"
```suggestion
  "description": "How to configure custom blocks"
```

2022-03-31 06:31 UTC, stevepiercy commented on docs/source/blocks/settings.md
> +  "property=og:description": "How to configure a new block"
```suggestion
  "property=og:description": "How to configure custom blocks"
```

2022-03-31 06:31 UTC, stevepiercy commented on docs/source/blocks/ssr.md
> +  "keywords": "Volto, Plone, frontend, React, Render, async-block"
```suggestion
  "keywords": "Volto, Plone, frontend, React, Render, async, block"
```

2022-03-31 06:31 UTC, stevepiercy commented on docs/source/configuration/backend.md
> +  "description": "Prepare the Plone backend content API for volto in order to fully support all volto features"
```suggestion
  "description": "Prepare the Plone backend content API for Volto in order to fully support all Volto features"
```

2022-03-31 06:31 UTC, stevepiercy commented on docs/source/configuration/backend.md
> +  "property=og:description": "Prepare the Plone backend content API for volto in order to fully support all volto features"
```suggestion
  "property=og:description": "Prepare the Plone backend content API for Volto in order to fully support all Volto features"
```

2022-03-31 06:31 UTC, stevepiercy commented on docs/source/configuration/expanders.md
> +  "description": "Learn to configure the API expanders Volto uses using the `settings.apiExpanders` like this"
```suggestion
  "description": "Configure the API expanders in Volto using the `settings.apiExpanders`"
```

2022-03-31 06:31 UTC, stevepiercy commented on docs/source/configuration/expanders.md
> +  "property=og:description": "Learn to configure the API expanders Volto uses using the `settings.apiExpanders` like this"
```suggestion
  "property=og:description": "Configure the API expanders in Volto using the `settings.apiExpanders`"
```

2022-03-31 06:31 UTC, stevepiercy commented on docs/source/configuration/locking.md
> +  "description": "Content edit locking feature is to prevent simultaneous conflicting edits of the same content."
```suggestion
  "description": "Content edit locking prevents simultaneous conflicting edits of the same content."
```

2022-03-31 06:31 UTC, stevepiercy commented on docs/source/configuration/locking.md
> +  "property=og:description": "Content edit locking feature is to prevent simultaneous conflicting edits of the same content."
```suggestion
  "property=og:description": "Content edit locking prevents simultaneous conflicting edits of the same content."
```

2022-03-31 06:31 UTC, stevepiercy commented on docs/source/configuration/richeditor-settings.md
> +  "description": "In this chapter we will learn how to change settings for the Rich Text Editor."
```suggestion
  "description": "How to change settings for the rich text editor."
```

2022-03-31 06:31 UTC, stevepiercy commented on docs/source/configuration/richeditor-settings.md
> +  "property=og:description": "In this chapter we will learn how to change settings for the Rich Text Editor."
```suggestion
  "property=og:description": "How to change settings for the rich text editor."
```

2022-03-31 06:31 UTC, stevepiercy commented on docs/source/contributing/index.md
> +  "description": "Since the very beginning, Volto has been developed with a set of principles in mind, brought from the years of experience developing Plone"
```suggestion
  "description": "Volto design principles"
```

2022-03-31 06:31 UTC, stevepiercy commented on docs/source/contributing/index.md
> +  "property=og:description": "Since the very beginning, Volto has been developed with a set of principles in mind, brought from the years of experience developing Plone"
```suggestion
  "property=og:description": "Volto design principles"
```

2022-03-31 06:31 UTC, stevepiercy commented on docs/source/deploying/index.md
> +  "description": "A guide to deployment"
```suggestion
  "description": "A guide to Volto frontend deployment"
```

2022-03-31 06:31 UTC, stevepiercy commented on docs/source/deploying/index.md
> +  "property=og:description": "A guide to deployment"
```suggestion
  "property=og:description": "A guide to Volto frontend deployment"
```

2022-03-31 06:31 UTC, stevepiercy commented on docs/source/deploying/simple.md
> +  "description": "Volto is a Node application that runs on your machine/server and listens to a port. Once you are ready to deploy it, you should build it running:"
```suggestion
  "description": "Simple deployment of a Volto application"
```

2022-03-31 06:31 UTC, stevepiercy commented on docs/source/deploying/simple.md
> +  "property=og:description": "Volto is a Node application that runs on your machine/server and listens to a port. Once you are ready to deploy it, you should build it running:"
```suggestion
  "property=og:description": "Simple deployment of a Volto application"
```

2022-03-31 06:31 UTC, stevepiercy commented on docs/source/developer-guidelines/acceptance-tests.md
> +  "keywords": "Volto, Plone, frontend, React, helper command, redux"
```suggestion
  "keywords": "Volto, Plone, frontend, React, helper command, redux, acceptance, tests, Cypress"
```

2022-03-31 06:31 UTC, stevepiercy commented on docs/source/developer-guidelines/design-principles.md
> +  "description": "Volto has been developed with a set of principles in mind,
```suggestion
  "description": "Volto design principles"
```

2022-03-31 06:31 UTC, stevepiercy commented on docs/source/developer-guidelines/design-principles.md
> +brought from the years of experience developing Plone core and implementing projects on
```suggestion
```

2022-03-31 06:31 UTC, stevepiercy commented on docs/source/developer-guidelines/design-principles.md
> +it."
```suggestion
```

2022-03-31 06:31 UTC, stevepiercy commented on docs/source/developer-guidelines/design-principles.md
> +  "property=og:description": "Volto has been developed with a set of principles in mind,
```suggestion
  "property=og:description": "Volto design principles"
```

2022-03-31 06:31 UTC, stevepiercy commented on docs/source/developer-guidelines/design-principles.md
> +brought from the years of experience developing Plone core and implementing projects on
```suggestion
```

2022-03-31 06:31 UTC, stevepiercy commented on docs/source/developer-guidelines/design-principles.md
> +it."
```suggestion
```

2022-03-31 06:31 UTC, stevepiercy commented on docs/source/developer-guidelines/linting.md
> +  "description": "Volto developers can enjoy a lot of freedom in their choice of text editors and
```suggestion
  "description": "Code linting in Volto"
```

2022-03-31 06:31 UTC, stevepiercy commented on docs/source/developer-guidelines/linting.md
> +IDEs"
```suggestion
```

2022-03-31 06:31 UTC, stevepiercy commented on docs/source/developer-guidelines/linting.md
> +  "property=og:description": "Volto developers can enjoy a lot of freedom in their choice of text editors and
```suggestion
  "property=og:description": "Code linting in Volto"
```

2022-03-31 06:31 UTC, stevepiercy commented on docs/source/developer-guidelines/linting.md
> +IDEs"
```suggestion
```

2022-03-31 06:31 UTC, stevepiercy commented on docs/source/getting-started/roadmap.md
> +  "description": "A roadmap to learn Volto."
```suggestion
  "description": "Volto developer roadmap"
```

2022-03-31 06:31 UTC, stevepiercy commented on docs/source/getting-started/roadmap.md
> +  "property=og:description": "A roadmap to learn Volto."
```suggestion
  "property=og:description": "Volto developer roadmap"
```

2022-03-31 06:31 UTC, stevepiercy commented on docs/source/recipes/appextras.md
> +  "description": "The `AppExtras` component is a general use insertion point for things like
```suggestion
  "description": "The `AppExtras` component is a general use insertion point for general purpose code spanning the whole application or for third party services code."
```

2022-03-31 06:31 UTC, stevepiercy commented on docs/source/recipes/appextras.md
> +analytics, general purpose code spanning the whole application or third party services code."
```suggestion
```

2022-03-31 06:31 UTC, stevepiercy commented on docs/source/recipes/appextras.md
> +  "property=og:description": "The `AppExtras` component is a general use insertion point for things like analytics, general purpose code spanning the whole application or third party services code."
```suggestion
  "property=og:description": "The `AppExtras` component is a general use insertion point for general purpose code spanning the whole application or for third party services code."
```

2022-03-31 06:31 UTC, stevepiercy commented on docs/source/recipes/creating-project.md
> +  "description": "Gain an understanding of how to create a new Volto project."
```suggestion
  "description": "Creating a new Volto project"
```

2022-03-31 06:31 UTC, stevepiercy commented on docs/source/recipes/creating-project.md
> +  "property=og:description": "Gain an understanding of how to create a new Volto project."
```suggestion
  "property=og:description": "Creating a new Volto project"
```

2022-03-31 06:31 UTC, stevepiercy commented on docs/source/recipes/creating-views.md
> +  "description": "In this chapter we are going to create a new type of view for displaying
```suggestion
  "description": "Creating Volto views"
```

2022-03-31 06:31 UTC, stevepiercy commented on docs/source/recipes/creating-views.md
> +contents in a folder. We will call this view `full view`."
```suggestion
```

2022-03-31 06:31 UTC, stevepiercy commented on docs/source/recipes/creating-views.md
> +  "property=og:description": "In this chapter we are going to create a new type of view for displaying contents in a folder. We will call this view `full view`."
```suggestion
  "property=og:description": "Creating Volto views"
```

2022-03-31 06:31 UTC, stevepiercy commented on docs/source/recipes/customizing-views.md
> +  "description": "Learn how to customize volto views."
```suggestion
  "description": "Customize Volto views."
```

2022-03-31 06:31 UTC, stevepiercy commented on docs/source/recipes/customizing-views.md
> +  "property=og:description": "Learn how to customize volto views."
```suggestion
  "property=og:description": "Customize Volto views."
```

2022-03-31 06:31 UTC, stevepiercy commented on docs/source/recipes/express.md
> +  "keywords": "Volto, Plone, frontend, React, middleware"
```suggestion
  "keywords": "Volto, Plone, frontend, React, custom, express, middleware"
```

2022-03-31 06:31 UTC, stevepiercy commented on docs/source/recipes/express.md
> +  "description": "Volto uses the popular Express server for its Server-Side Rendering implementation and static resource serving."
```suggestion
  "description": "Volto uses the popular Express server for its server-side rendering implementation and static resource serving."
```

2022-03-31 06:31 UTC, stevepiercy commented on docs/source/recipes/express.md
> +  "property=og:description": "Volto uses the popular Express server for its Server-Side Rendering implementation and static resource serving."
```suggestion
  "property=og:description": "Volto uses the popular Express server for its server-side rendering implementation and static resource serving."
```

2022-03-31 06:31 UTC, stevepiercy commented on docs/source/recipes/folder-structure.md
> +  "description": "Volto is based on React, Redux, and React-Router. All of the
```suggestion
  "description": "Volto is based on React, Redux, and React-Router and follows its convention of resource location."
```

2022-03-31 06:31 UTC, stevepiercy commented on docs/source/recipes/folder-structure.md
> +code is located in the `src` folder."
```suggestion
```

2022-03-31 06:31 UTC, stevepiercy commented on docs/source/recipes/folder-structure.md
> +  "property=og:description": "Volto is based on React, Redux, and React-Router. All of the
```suggestion
  "property=og:description": "Volto is based on React, Redux, and React-Router and follows its convention of resource location."
```

2022-03-31 06:31 UTC, stevepiercy commented on docs/source/recipes/folder-structure.md
> +code is located in the `src` folder."
```suggestion
```

2022-03-31 06:31 UTC, stevepiercy commented on docs/source/recipes/ie11compat.md
> +  "keywords": "Volto, Plone, frontend, React, legacy browser support"
```suggestion
  "keywords": "Volto, Plone, frontend, React, legacy browser support, IE11 compatability, polyfills"
```

2022-03-31 06:31 UTC, stevepiercy commented on docs/source/recipes/ie11compat.md
> +  "description": "Legacy Browser Support (IE11 compatibility): Polyfills, babel-env, Pre-transpiling"
```suggestion
  "description": "Legacy browser support with polyfills, babel-env, and pre- and post-transpiling"
```

2022-03-31 06:31 UTC, stevepiercy commented on docs/source/recipes/ie11compat.md
> +  "property=og:description": "Legacy Browser Support (IE11 compatibility): Polyfills, babel-env, Pre-transpiling"
```suggestion
  "property=og:description": "Legacy browser support with polyfills, babel-env, and pre- and post-transpiling"
```

2022-03-31 06:31 UTC, stevepiercy commented on docs/source/recipes/ie11compat.md
> +  "property=og:title": "Legacy Browser Support"
```suggestion
  "property=og:title": "Legacy Browser Support (IE11 compatibility)"
```

2022-03-31 06:31 UTC, stevepiercy commented on docs/source/recipes/index.md
> +  "description": "Recipes: Development"
```suggestion
  "description": "Volto development recipes"
```

2022-03-31 06:31 UTC, stevepiercy commented on docs/source/recipes/index.md
> +  "property=og:description": "Recipes: Development"
```suggestion
  "property=og:description": "Volto development recipes"
```

2022-03-31 06:31 UTC, stevepiercy commented on docs/source/recipes/lazyload.md
> +  "description": "A guide to lazy-loading libraries as these libraries are not as straight-forward as with the React components."
```suggestion
  "description": "A guide to lazy-loading libraries in Volto."
```

2022-03-31 06:31 UTC, stevepiercy commented on docs/source/recipes/lazyload.md
> +  "property=og:description": "A guide to lazy-loading libraries as these libraries are not as straight-forward as with the React components."
```suggestion
  "property=og:description": "A guide to lazy-loading libraries in Volto."
```

2022-03-31 13:03 UTC, ktsrivastava29 commented
@stevepiercy Thank you for bringing up the required edits; I've now made the changes you suggested.

2022-03-31 13:16 UTC, stevepiercy requested changes
One more round of corrections.

Do you know that you can simply click a button in GitHub to accept the suggestion? That avoids unnecessary manual fixes.

2022-03-31 13:16 UTC, stevepiercy commented on docs/source/blocks/settings.md
> +  "description": "How to configure custom block"
```suggestion
  "description": "How to configure custom blocks"
```

2022-03-31 13:16 UTC, stevepiercy commented on docs/source/blocks/settings.md
> +  "property=og:description": "How to configure custom block"
```suggestion
  "property=og:description": "How to configure custom blocks"
```

2022-03-31 13:16 UTC, stevepiercy commented on docs/source/recipes/folder-structure.md
> +  "description": ""Volto is based on React, Redux, and React-Router and follows its convention of resource location."
```suggestion
  "description": "Volto is based on React, Redux, and React-Router and follows its convention of resource location."
```

2022-03-31 13:16 UTC, stevepiercy commented on docs/source/recipes/folder-structure.md
> +  "property=og:description": ""Volto is based on React, Redux, and React-Router and follows its convention of resource location."
```suggestion
  "property=og:description": "Volto is based on React, Redux, and React-Router and follows its convention of resource location."
```

2022-03-31 17:19 UTC, ktsrivastava29 commented
@stevepiercy  Yes, actually since there were so many changes, I felt that I should do it locally first. 
Now I've incorporated the changes using the way you advised.

2022-04-01 08:47 UTC, stevepiercy approved these changes

2022-04-01 08:48 UTC, merged

2022-04-01 08:48 UTC, stevepiercy commented
Thank you!