React 18 - and all that fun
plone/volto pull request #3221
Opened 2022-04-02 14:37 UTC by sneridagh

2022-04-02 14:42 UTC, tiberiuichim commented
Looks like somebody's itching :)

2024-01-19 21:43 UTC, sneridagh commented
@tiberiuichim there's a last test that is failing. I thin you wrote it. I have no clue why it's failing, it seems fine from the user perspective, but the test says that inside the data structure is not ok. Could be a timing issue, difficult to figure out. Putting waits does not work :( Could you please take a look?

The idea is to upgrade to 18 in Volto 18... Makes sense especially after all these years. Then at least we are in the last React "stable" published.

2024-02-29 12:51 UTC, sneridagh commented
GREEEEEEN!!!!

🟢🟢🟢🟢🟢🟢🟢🟢🟢🟢🟢🟢

2024-02-29 13:03 UTC, tiberiuichim approved these changes
This is a major achievement, many many thanks for this work!

2024-02-29 13:11 UTC, sneridagh commented
@stevepiercy some docs, please review!

2024-02-29 13:18 UTC, stevepiercy requested changes
Minor tweaks on docs.

2024-02-29 13:18 UTC, stevepiercy commented on docs/source/upgrade-guide/index.md
> +We have updated Volto for use React 18. This has been the latest published stable version since June 2022.
```suggestion
We have updated Volto to use React 18.
This has been the latest published stable version since June 2022.
```

2024-02-29 13:18 UTC, stevepiercy commented on docs/source/upgrade-guide/index.md
> +- New hooks (useId, useTransition, useDeferredValue, useSyncExternalStore and others)
```suggestion
- New hooks `useId`, `useTransition`, `useDeferredValue`, `useSyncExternalStore`, and other hooks
```

2024-02-29 13:18 UTC, stevepiercy commented on docs/source/upgrade-guide/index.md
> +The Volto code that relied on it was mainly CMSUI components.
```suggestion
The Volto code that relied on it was mainly CMS UI components.
```

2024-02-29 13:18 UTC, stevepiercy commented on docs/source/upgrade-guide/index.md
> +If your project relies on it either your code or the shadowed components you may have, you should update to use the standard React API: `createPortal`.
```suggestion
If your project relies on it, either in your code or the shadowed components you may have, you should update to use the standard React API, `createPortal`.
```

2024-02-29 13:40 UTC, ichim-david approved these changes
@sneridagh I would of expected more work besides the portal replacement and isClient and the test changes for slate, this is awesome, thank you as well.

2024-02-29 13:40 UTC, ichim-david commented on packages/volto/src/components/manage/Form/Form.jsx
> +              // debugger;
```suggestion
```

2024-02-29 13:40 UTC, ichim-david commented on packages/volto/src/helpers/Utils/usePagination.test.js.removed
Is this meant to be removed and that's it?

2024-02-29 14:31 UTC, sneridagh commented on packages/volto/src/helpers/Utils/usePagination.test.js.removed
I left it here in case someone wants to retake the work. Since it has a Cypress test, it's redundant. We can remove it as well...

2024-02-29 14:32 UTC, sneridagh commented
> I would of expected more work besides the portal replacement and isClient and the test changes for slate, this is awesome, thank you as well.

This one was not easy, I tell you. Sweating blood in buckets at some moments, but it's done.

2024-02-29 19:22 UTC, davisagli approved these changes
@sneridagh I few very minor comments, but basically looks good.

2024-02-29 19:22 UTC, davisagli commented on packages/registry/news/3221.feature
Should be 3221.breaking?

2024-02-29 19:22 UTC, davisagli commented on packages/volto/src/components/manage/Blocks/Block/BlocksForm.jsx
> +    // debugger;
```suggestion
```

2024-02-29 19:22 UTC, davisagli commented on packages/volto/src/helpers/Utils/usePagination.test.js.removed
I don't think it's useful to keep the file.

2024-03-01 08:29 UTC, merged