Used UniversalLink and PreviewImage components where needed, to right…
plone/volto pull request #3266
Opened 2022-04-22 14:18 UTC by giuliaghisini

… handle link and images.

2022-04-22 14:19 UTC, giuliaghisini commented
if it were possible, I would give a rather high urgency to this PR. We need it as soon as possible for a client

2022-04-22 14:59 UTC, tiberiuichim commented on src/components/manage/UniversalLink/UniversalLink.jsx
> +  const isTelephone =
I think this code should be placed inside helpers/Url.js, as it's also used by the Link plugin for draft. https://github.com/plone/volto/blob/2b80b6c3f9811c5fbe069ee25236d41f762a8191/src/helpers/Url/Url.js#L231

2022-04-22 15:46 UTC, sneridagh commented
@giuliaghisini could you take care of @tiberiuichim suggestion? I can merge and release as soon it's ready.

2022-04-22 21:03 UTC, stevepiercy requested changes
3 reversions and request to fix something that got broken in the conversion to MyST.

2022-04-22 21:03 UTC, stevepiercy commented on docs/source/recipes/customizing-components.md
>  ```jsx hl_lines="20"
It appears that this code highlighting directive is not being honored. Let's fix it!

```suggestion
```{code-block) jsx
:emphasize-lines: 20
```

This line appears before the change in the code block, so it should still highlight this line:

```
      Tags:
```

https://github.com/plone/volto/pull/3266/files#diff-b8133ecc81246c0e39589e6ca0088d0b3b443bfb3cda9f055946e6b9965e7933R75

2022-04-22 21:03 UTC, stevepiercy commented on docs/source/recipes/customizing-views.md
> +  'keywords': 'Volto, Plone, frontend, React, views'
Please revert the above changes.

2022-04-26 11:06 UTC, giuliaghisini commented
@tiberiuichim i've added checkAndNormalizeUrl in Url Helper and used it in UniversalLink, AddLinkForm of AnchorPlugin and in UrlWidget

2022-04-28 13:11 UTC, giuliaghisini commented
@sneridagh @tiberiuichim what about to merge and release this fixes?

2022-04-28 21:30 UTC, stevepiercy approved these changes
Thank you!

2022-04-29 07:10 UTC, tiberiuichim approved these changes

2022-04-29 07:53 UTC, merged