add a RedirectBlock
plone/volto pull request #3305
Opened 2022-05-03 14:38 UTC by erral

Fixes #3303 

If a RedirectBlock is added to any content, the page issues a 302 Redirect for anonymous users.

2022-05-05 09:10 UTC, nileshgulia1 reviewed
Nice. It would be great to have some tests for this new block components.

2022-05-05 15:51 UTC, sneridagh requested changes
I'm ok with this one, please fix the typo!

2022-05-05 15:51 UTC, sneridagh commented on src/components/manage/Blocks/Redirect/schema.js
> +        llowExternals: true,
typo!

2022-05-10 09:51 UTC, fredvd commented
As mentionned in the Volto team meeting: creating 'functional' blocks that are not for the blocks layout visual but modify the content item behavior sounds more like a behavior or in this case sticking an instance behavior to the context.   So then you have functional and visual blocks. 

Doing this seems like starting a visual programming editor/tool where you drag 'actions' onto the canvas and then they are active. I'm afraid that mixing these different purposes for the blocks editor will confuse editors with a too big conceptual load of how to understand the UI. 

Understanding the use case: is this a 'default page' light returning to Volto, so you can stick it on a folderish page?

2022-05-10 12:36 UTC, erral commented
Sorry I was not able to attend the Volto team meeting to discuss this.

This PR tries to bring to Volto the following feature that exists in Classic Plone: 

- Create a Folder
- Create a link inside a folder
- Select the link as a default page for the Folder

With this scenario one can add content in the site, place it on menus, or whatever, and get redirects to another place of the site or even to external site. The main use case is the one described in the issue.

2022-05-13 13:26 UTC, erral commented
I added some tests

2024-03-11 07:28 UTC, closed without merging