Link Integrity
plone/volto pull request #3317
Opened 2022-05-04 15:16 UTC by danielamormocea

Solves #2396

Requires plone.restapi (https://github.com/plone/plone.restapi/pull/953)

![image](https://user-images.githubusercontent.com/38378382/166714694-1816f739-1079-41e5-a49f-090e7f156f49.png)

2022-05-05 08:48 UTC, avoinea requested changes

2022-05-05 08:48 UTC, avoinea commented on src/components/manage/Contents/Contents.jsx
> +                              By deleting this item, you will break links that
@danielamormocea Please use i18n messages here.

2022-05-05 08:48 UTC, avoinea commented on src/actions/content/content.js
> +  FC_DELETE,
@danielamormocea Maybe we can find a better name, more self-explenatory, for this action.

2022-05-05 16:11 UTC, sneridagh commented
It seems we already had a rotten PR going on: https://github.com/plone/volto/pull/2783 😫 that did the same thing.

@danielamormocea could you take a look and try to merge them (if there's something valuable, that I'm not aware now, i18n maybe?) there that we could reuse in this one? I'm biassed to use this one though, make sure that the i18n is also in sync.

As soon as we have the PR merged in p.restapi we can merge this one.

2022-05-06 08:19 UTC, avoinea approved these changes

2022-05-06 08:45 UTC, cekk commented
@danielamormocea @avoinea we changed the endpoint method from POST to GET, so i think that you have to change something in the frontend call

2022-05-06 09:51 UTC, sneridagh commented
@danielamormocea I think they are changing the backend PR a bit. Please talk to @cekk to adjust

2022-05-06 14:13 UTC, sneridagh approved these changes
LGTM, when the restapi is merged we can merge this.

2022-05-06 15:02 UTC, tisto commented
@danielamormocea awesome work! I just added the plone.restapi checkout to this PR. I would love to see a Cypress test that covers the basic use cases:

- delete object that is referenced by a text block link
- delete object that is referenced by an attribute reference
- delete parent object of an object that is referenced by a link (either text or attribute or maybe even both)

2022-05-07 09:29 UTC, tisto commented
@danielamormocea the link integrity feature works very well. I'd just have a few suggestions for the UX:

![Contents (1)](https://user-images.githubusercontent.com/632105/167248274-877efac5-8545-4a26-bb6c-a030e6fd62eb.png)

2022-05-07 09:34 UTC, tisto commented
@danielamormocea nested folder structures are taken into account, which is good. Though, the system currently does not show the right breaches:

![Contents (2)](https://user-images.githubusercontent.com/632105/167248467-04fc239f-fd45-41a2-964a-ac2111ac8ac3.png)

2022-05-12 16:36 UTC, danielamormocea commented
> @danielamormocea the link integrity feature works very well. I'd just have a few suggestions for the UX:
> 
> ![Contents (1)](https://user-images.githubusercontent.com/632105/167248274-877efac5-8545-4a26-bb6c-a030e6fd62eb.png)

In terms of UI, I have no better idea than to simply mention again before listing the items, that those are going to be deleted (although it seems redundant), or to add a separator again after the first list of items (but for me that looks uglier).

Furthermore, regarding the breaches, if there is a page inside a page that is referenced somewhere, the response won't give me that information, so the main page (the one selected) is the only "reference" I get, therefore the only page I can show to the user.

2022-05-12 18:55 UTC, danielamormocea commented
@tisto I also added the test for the reference, but unfortunately the linkintegrity api part does not detect objects referenced by a text block link

2022-05-13 07:04 UTC, tisto commented
@danielamormocea I was suspecting that Plone and the restapi are the issue here. Then I guess we have to specify in plone.restapi how the backend is supposed to work and then work on the implementation there.

2022-05-16 06:12 UTC, tisto commented
@danielamormocea would you be able to create a PR in plone.restapi documenting the missing functionality in a Python unit test?

FYI: Acceptance tests and code analysis are failing for this PR.

2022-05-23 14:09 UTC, danielamormocea commented
@tisto  Acceptance tests are failing because there is no linkintegrity api for deleting items from contents (the failing tests are in content.js and folder-contents.js)

2022-08-16 02:28 UTC, rohnsha0 approved these changes

2022-10-02 21:20 UTC, sneridagh commented
@danielamormocea I hope that now that we have the backend side, we are green and ready to merge.

2022-10-03 07:22 UTC, sneridagh commented
@danielamormocea we have a test that fails, could you please take a look? Thanks!

2022-10-06 14:17 UTC, sneridagh commented
@danielamormocea I fixed the Cypress test (it was using draftJS still). 
However, I can't see the @linkintegrity call happening... Could you please take a look?

I'd like to have this for Volto 16 which will happen next week for sure.

/cc @avoinea @alecghica

2022-10-20 14:17 UTC, sneridagh commented
@avoinea I still couldn't take a look at this, it should work now but it keeps failing. Should be a silly thing.

2022-10-21 12:33 UTC, merged