Added preconnect link tag to speed up google font retrieval
plone/volto pull request #3384
Opened 2022-05-22 21:51 UTC by pnicolli

Fixes #3328 

Add preconnect link tag as suggested by lighthouse. The current semantic UI configuration requests 4 different font files from this origin, this preconnect should help optimize the connection.

2022-05-23 18:50 UTC, ichim-david commented
@pnicolli @sneridagh although this improves the current google fonts font loading I wish we could have  a pluggable section in the head to add any needed pre-fetching without having to customize HTML.jsx.
We miss the slots from plone classic main_template where you could of added many things without resorting to
any overrides.

2022-05-25 09:05 UTC, sneridagh approved these changes

2022-05-25 09:08 UTC, sneridagh commented
@ichim-david agreed. We tried it in the past, but we can't use Pluggables here (they are not SSR-able). 
I could imagine a setting with an array or `Map()` of components, then render them all in order? So multiple add-ons could subscribe to it?

/cc @tiberiuichim ?

2022-05-25 09:51 UTC, tiberiuichim commented
We could use a similar model as the AppExtras, where we register in configuration components that will be rendered in that "slot".

2022-05-26 08:15 UTC, sneridagh commented
@tiberiuichim oh sure, I didn't recall that we refactored the `appExtras` in such a way. 😅

The question that I have now is that if @pnicolli addition should go into such a slot, or has sense to be always there by its own.

However, I would like to have such a slot in place soon, tbh.

2022-05-26 12:05 UTC, mamico requested changes

2022-05-26 14:16 UTC, tiberiuichim commented
Slots can have "static" components as well. Maybe it's the moment to introduce them, at least the configuration and the static part? https://github.com/plone/volto/blob/slots_quanta_split_form_undo_prefix_path/src/config/slots.js#L4

2022-07-21 09:21 UTC, pnicolli commented
This could be superseded by #3492 and #3493 
I will either close or move this forward based on the result of those two.

2022-10-15 11:17 UTC, closed without merging