Simplify over the existing Component Registry API, The `component` ke…
plone/volto pull request #3561
Opened 2022-08-15 16:06 UTC by sneridagh

…y has been flattened for simplification and now it's mapped directly to the `component` argument of `registerComponent`.

2022-08-15 21:14 UTC, stevepiercy requested changes
I reviewed docs only. A few minor changes.

2022-08-15 21:14 UTC, stevepiercy commented on CHANGELOG.md
> +See https://docs.voltocms.com/upgrade-guide/ for more information.
```suggestion
See https://6.dev-docs.plone.org/volto/upgrade-guide/index.html for more information.
```

2022-08-15 21:14 UTC, stevepiercy commented on CHANGELOG.md
> +See https://docs.voltocms.com/upgrade-guide/ for more information.
I hate to use a temporary URL for this, but I don't know what else we could do. We don't have a proper redirect on `docs.voltocms.com` either.

2022-08-15 21:14 UTC, stevepiercy commented on docs/source/upgrade-guide/index.md
> +````{note}
```suggestion
````{versionchanged} 16.0.0-alpha.23
```

2022-08-15 21:14 UTC, stevepiercy commented on docs/source/upgrade-guide/index.md
> +The `component` argument changed in alpha 23. The `component` key has been flattened for simplification and now it's mapped directly to the `component` argument of `registerComponent`:
```suggestion
The `component` argument changed in 16.0.0-alpha.23.
The `component` key has been flattened for simplification and now it's mapped directly to the `component` argument of `registerComponent`:
```

2022-08-16 07:09 UTC, tiberiuichim approved these changes

2022-08-16 07:52 UTC, sneridagh commented
@stevepiercy thanks!

2022-08-16 08:24 UTC, stevepiercy approved these changes
Nice work!

2022-08-16 08:24 UTC, stevepiercy commented
I love these versionchanged directives!

https://deploy-preview-3561--volto.netlify.app/upgrade-guide/index.html#registry-getcomponent-signature-changes

2022-08-16 08:33 UTC, sneridagh commented
@stevepiercy nice indeed!

2022-08-16 08:33 UTC, merged