Bring back "Guidelines for Contributing"
plone/volto pull request #3644
Opened 2022-09-16 07:09 UTC by ksuess

2022-09-16 07:28 UTC, sneridagh approved these changes

2022-09-16 07:52 UTC, stevepiercy commented
We now have a [Plone GitHub organization `CONTRIBUTING.md`](https://github.com/plone/.github/blob/main/CONTRIBUTING.md). When a repo, including Volto, lacks a `CONTRIBUTING.md` file in its repo, then this will be displayed. Clearly this is _not_ what we want.

I would suggest that we add a `CONTRIBUTING.md` file at the root of this repo, that contains only the following:

```
# Contributing to Volto

See [Contributing to Volto](https://6.dev-docs.plone.org/volto/developer-guidelines/contributing.html).
```

More information about GitHub Community Health Files, specifically [About contributing guidelines](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors).

2022-09-16 08:25 UTC, stevepiercy requested changes
Lots of obsolete stuff needed changing.

Feedback appreciated.

2022-09-16 08:25 UTC, stevepiercy commented on docs/source/developer-guidelines/contributing.md
> +When in doubt, create one in the [CMFPlone issue tracker](https://github.com/plone/Products.CMFPlone/issues "CMFPlone issue tracker").
```suggestion
When in doubt, create one in the [CMFPlone issue tracker](https://github.com/plone/Products.CMFPlone/issues).
```

2022-09-16 08:25 UTC, stevepiercy commented on docs/source/developer-guidelines/contributing.md
> +Please specify a few things:
```suggestion
In your report, please specify a few things:
```

2022-09-16 08:25 UTC, stevepiercy commented on docs/source/developer-guidelines/contributing.md
> +- What steps reproduce the problem?
```suggestion
- What are the steps to reproduce the problem?
```

2022-09-16 08:25 UTC, stevepiercy commented on docs/source/developer-guidelines/contributing.md
> +- What do you expect when you do that?
```suggestion
- What do you expect when you follow those steps?
```

2022-09-16 08:25 UTC, stevepiercy commented on docs/source/developer-guidelines/contributing.md
> +- What happens instead?
```suggestion
- What do you observe?
```

2022-09-16 08:25 UTC, stevepiercy commented on docs/source/developer-guidelines/contributing.md
> +
```suggestion
```

2022-09-16 08:25 UTC, stevepiercy commented on docs/source/developer-guidelines/contributing.md
> +If it is a visual issue, can you add a screenshot?
```suggestion
- Include relevant screenshots, error messages, and stack traces.
```

2022-09-16 08:25 UTC, stevepiercy commented on docs/source/developer-guidelines/contributing.md
> +Legally, you can NOT contribute code unless you have signed the contributor agreement.
```suggestion
You must sign the [Plone Contributor Agreement](https://plone.org/foundation/contributors-agreement) to contribute code and documentation to any Plone project.
```

2022-09-16 08:25 UTC, stevepiercy commented on docs/source/developer-guidelines/contributing.md
> +This means that we can NOT accept pull requests from you unless this is done, so please
```suggestion
This means that we can NOT accept pull requests from you until you do this.
```

2022-09-16 08:25 UTC, stevepiercy commented on docs/source/developer-guidelines/contributing.md
> +don’t put the code reviewers at risk and do it anyways.
```suggestion
```

2022-09-16 08:25 UTC, stevepiercy commented on docs/source/developer-guidelines/contributing.md
> +For new features, an addition to documentation is probably needed.
```suggestion
All pull requests must include a note under the `(unreleased)` version under the appropriate subheading of [CHANGELOG.md](https://github.com/plone/volto/blob/master/CHANGELOG.md).
Do not edit already released versions.
```

2022-09-16 08:25 UTC, stevepiercy commented on docs/source/developer-guidelines/contributing.md
> +If the feature includes a breaking change, you should also add the breaking and how to
```suggestion
If the feature includes a breaking change, you must include instructions for how to upgrade in the [upgrade guide](../upgrade-guide/index.md).
```

2022-09-16 08:25 UTC, stevepiercy commented on docs/source/developer-guidelines/contributing.md
> +upgrade in the [upgrade guide](../upgrade-guide/index.md).
```suggestion
```

2022-09-16 08:25 UTC, stevepiercy commented on docs/source/developer-guidelines/contributing.md
> +strings as translatable as defined in the [i18n guide](../recipes/i18n.md)
```suggestion
strings as translatable as defined in the [i18n guide](../recipes/i18n.md).
```

2022-09-16 08:25 UTC, stevepiercy commented on docs/source/developer-guidelines/contributing.md
> +
Replace everything below this comment with the following.

```
## Code Quality

All pull requests must pass tests, documentation builds, and other code quality checks.
Contributors are strongly encouraged to run these checks locally before creating a pull request.
These checks are enforced automatically on every pull request, so you might as well save time and frustration by doing these checks locally first.

Specifically:

-   {doc}`./linting`
-   {doc}`./testing`
-   {doc}`./acceptance-tests`
```

If after reading this you become hesitant, don't worry.
You can always create a pull request, mark it as "Draft", and improve the above points later, requesting help from the community.

Welcome to the Plone community, and thank you for contributing!

2022-09-16 09:20 UTC, stevepiercy approved these changes
Thank you! LGTM!

2022-09-16 20:23 UTC, merged

2022-09-17 09:03 UTC, sneridagh commented
Thanks!