Press Enter in some blocks does not focus on the text block below
plone/volto pull request #3659
Opened 2022-09-19 15:27 UTC by dobri1408

Fixes https://github.com/plone/volto/issues/3647.
I saw that all the time when  onAddBlock was executed, also the onSelectBlock was because we wanted to select the added block, but with an exception, that I fixed it now.

2022-09-19 15:44 UTC, wesleybl approved these changes
I had seen just that. So LGTM!

2022-09-19 19:54 UTC, tiberiuichim approved these changes
It would be nice if this would be tested with cypress.

2022-09-20 05:58 UTC, nileshgulia1 approved these changes

2022-09-20 09:55 UTC, dobri1408 commented
Hi @tiberiuichim, great idea, I am on it!

2022-09-20 12:31 UTC, dobri1408 commented
I added the cypress tests

2022-09-20 12:50 UTC, tiberiuichim approved these changes

2022-09-20 12:50 UTC, wesleybl requested changes

2022-09-20 12:50 UTC, wesleybl commented on cypress/tests/core/blocks/blocks-autofocus.js
> +    cy.get('button.block-add-button').click();
I don't understand cypress, but it seems that this lines can stay in the `beforeEach` function, since they are the same in all tests.

2022-09-20 12:51 UTC, tiberiuichim commented
There is a conceptual issue with the HTML block, in that it should handle Enter key on its own, but I think it's a different discussion. For context, see https://community.plone.org/t/how-does-volto-handle-the-enter-key/15663

2022-09-20 16:04 UTC, wesleybl approved these changes
LGTM

2022-09-21 07:29 UTC, nileshgulia1 approved these changes

2022-09-21 07:46 UTC, sneridagh commented
Not sure on this one, I think it could break quite a few blocks out there. Did you tested in all stock blocks? If we are "breaking" the behavior in HTML block, we should fix it as well. How about nested ones?

2022-09-21 08:08 UTC, sneridagh commented
Also, another thing I just realised... How do you create a new block below your block, if ENTER now selects the next one?
Food for thought...

2022-09-21 08:14 UTC, dobri1408 commented
Hi @sneridagh, the initial target of the pr was to solve the issue with the unfocused new blocks. This issue is solved just by adding the function onSelectBlock where was supposed to be. If you consider that the tests are not good, I can remove them, and let just the fix be merged. The tests have the scope to select each block press enter and see if the newly added block is focused. If the tests are a good idea, but there is a problem with the HTML block, I can remove the HTML block.

2022-09-21 08:15 UTC, sneridagh commented
@dobri1408 ok! let me test it, I might be wrong in my assumption. Please bare with me!

2022-09-21 14:06 UTC, wesleybl commented
> If we are "breaking" the behavior in HTML block, we should fix it as well.

@sneridagh hhe HTML block is broken in master, regardless of the code of this PR. It must be fixed in another PR. It's a different problem.

> How do you create a new block below your block, if ENTER now selects the next one?

Enter is already creating a new block. But this new block is not getting the focus (cursor in text block input). This PR makes the course stay in the text block that is already created.

2022-09-23 10:45 UTC, sneridagh approved these changes
LGTM!

2022-09-23 13:50 UTC, merged