Update email widget validation regex
plone/volto pull request #3664
Opened 2022-09-21 09:15 UTC by instification

Fixes #3663 

Regex was taken from https://stackoverflow.com/questions/42827054/how-do-i-run-a-single-test-using-jest which provides an up to date regex to correctly identify email addresses.

Also included an additional test to show the longer domain TLD being correctly validated.

2022-09-21 10:28 UTC, stevepiercy requested changes

2022-09-21 10:28 UTC, stevepiercy commented on src/helpers/FormValidation/FormValidation.js
> +      const emailRegex = /^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/;
We should add a comment about why we chose this version of a regex, and provide a link to its source. Your commit message is good for this.

2022-09-21 19:16 UTC, stevepiercy approved these changes

2022-09-21 19:17 UTC, stevepiercy commented
Let's get one more reviewer from someone who is more familiar with Volto than I before merging.

2022-09-23 13:51 UTC, sneridagh approved these changes

2022-09-23 13:51 UTC, merged