Remove sentry
plone/volto pull request #3777
Opened 2022-10-16 05:40 UTC by tiberiuichim

See https://github.com/collective/volto-sentry for the moved code

2022-10-16 08:02 UTC, davisagli reviewed
LGTM, aside from a couple docs tweaks and of course finishing the addon.

2022-10-19 09:29 UTC, sneridagh commented
@tiberiuichim how is this going? What's missing? the upgrade guide? the volto add-on?

2022-10-19 11:41 UTC, tiberiuichim commented
@sneridagh I've created the `@plone-collective/volto-sentry` package, here https://github.com/collective/volto-sentry

There was a script in the Volto source code root, it needs to be exposed as bin script.

And testing. Alec told me that we can have one of our guys taking care of this, I'll bring this to attention.

2022-10-27 15:45 UTC, sneridagh commented on CHANGELOG.md
> +- Moved all sentry-related code from Volto to the `@plone-collective/volto-sentry` package. See the Upgrade Guide  @tiberiuichim
I did it.

2022-10-27 15:46 UTC, sneridagh approved these changes

2022-10-27 16:12 UTC, sneridagh commented
If everybody is ok, I will merge this tomorrow.

/cc @alecghica @avoinea @tiberiuichim

2022-10-27 17:51 UTC, stevepiercy requested changes
A few English grammar tweaks, and a little MyST syntax polish.

2022-10-27 17:51 UTC, stevepiercy commented on CHANGELOG.md
> +- The listing block icon has been improved to avoid confusions with the normal text list @sneridagh
```suggestion
- The listing block icon has been improved to avoid confusion with the normal text list. @sneridagh
```

2022-10-27 17:51 UTC, stevepiercy commented on docs/source/configuration/settings-reference.md
>  ```
This needs to be moved down to enclose the next glossary entry.

```suggestion
```

2022-10-27 17:51 UTC, stevepiercy commented on docs/source/configuration/settings-reference.md
> +
Include this entry in the Glossary.

````suggestion
```

````

2022-10-27 17:51 UTC, stevepiercy commented on docs/source/upgrade-guide/index.md
> +The integration with Sentry was implemented in Volto core since back in the day Volto didn't provide a good add-on story.
```suggestion
The Sentry integration was implemented in Volto core at a time when Volto did not provide a good add-on story.
```

2022-10-27 17:51 UTC, stevepiercy commented on docs/source/upgrade-guide/index.md
> +Now makes sense that the feature is extracted to its own add-on.
```suggestion
Since then, the add-on story has improved.
It now makes sense to extract this feature into its own add-on.
```

2022-10-27 17:51 UTC, stevepiercy commented on docs/source/upgrade-guide/index.md
> +You can find it in [@collective/volto-sentry](https://github.com/collective/volto-sentry).
```suggestion
You can find it in [`@collective/volto-sentry`](https://github.com/collective/volto-sentry).
```

2022-10-27 22:23 UTC, davisagli approved these changes

2022-10-28 09:01 UTC, merged

2022-10-30 18:54 UTC, pnicolli commented
@sneridagh @tiberiuichim If I understand correctly, the add-on has not yet been released, therefore making it more difficult to use sentry with latest released volto. Am I missing something?

2022-10-30 19:33 UTC, tiberiuichim commented
@pnicolli No, that's correct. Still waiting for my colleague to start work on https://github.com/collective/volto-sentry

As far as I remember, the only thing missing (outside of testing and docs) that I was aware was to set a bin script so that this https://github.com/collective/volto-sentry/blob/main/scripts/create-sentry-release.sh could be accessed as a nodejs script rather then a module inside Volto's code. I don't know how it gets integrated further, I'm not privy to that info.

2022-10-31 20:55 UTC, alecghica commented
@pnicolli the work on https://github.com/collective/volto-sentry is in progress and will be finalized soon.