Spanish translation
plone/volto pull request #3789
Opened 2022-10-22 02:40 UTC by macagua

- Updated Spanish translation

2022-10-22 13:11 UTC, erral requested changes

2022-10-22 13:11 UTC, erral commented on locales/es/LC_MESSAGES/volto.po
> +msgstr "Acción cambiado"
Acción modificada

2022-10-22 13:11 UTC, erral commented on locales/es/LC_MESSAGES/volto.po
> +msgstr "Reglas de contenido activo en esta página"
activas

2022-10-22 13:11 UTC, erral commented on locales/es/LC_MESSAGES/volto.po
> +msgstr "Configure content rule"
???

2022-10-22 13:11 UTC, erral commented on locales/es/LC_MESSAGES/volto.po
> +msgstr "Habilitar"
Activar?

2022-10-22 13:11 UTC, erral commented on locales/es/LC_MESSAGES/volto.po
> +msgstr "Habilitado"
activado

2022-10-22 13:11 UTC, erral commented on locales/es/LC_MESSAGES/volto.po
> +msgstr "¿Habilitado aquí?"
Activado aquí

2022-10-22 13:11 UTC, erral commented on locales/es/LC_MESSAGES/volto.po
> +msgstr "¿Habilitado?"
Activado

2022-10-22 13:11 UTC, erral commented on locales/es/LC_MESSAGES/volto.po
> +msgstr "Salir"
Logged out será 'ha salido correctamene'? habrá que ver dónde sale esto...

2022-10-22 13:11 UTC, erral commented on locales/es/LC_MESSAGES/volto.po
> +msgstr "Realice las siguientes acciones:"
Realice o realizar? hay que ver dónde sale

2022-10-22 13:11 UTC, erral commented on locales/es/LC_MESSAGES/volto.po
> +msgstr "Estatus"
Estado

2022-10-29 18:40 UTC, macagua commented on locales/es/LC_MESSAGES/volto.po
> +msgstr "Realice las siguientes acciones:"
Done with commit caa1d88

2022-10-29 18:41 UTC, macagua commented on locales/es/LC_MESSAGES/volto.po
> +msgstr "Acción cambiado"
@erral Done with commit :partying_face:  caa1d88

2022-10-29 18:48 UTC, macagua commented on locales/es/LC_MESSAGES/volto.po
> +msgstr "Salir"
@erral es parte de componente "Login container" en components/theme/Logout/Logout

Entiendo que quiero decir: "salir", "desconectarse", o "cerrar sesión"

2022-11-01 07:02 UTC, avoinea approved these changes

2022-11-01 17:29 UTC, merged