Improve collapsing of whitespace on paste in slate block
plone/volto pull request #3806
Opened 2022-10-27 15:13 UTC by tiberiuichim

2022-10-27 15:19 UTC, davisagli commented on packages/volto-slate/src/editor/deserialize.js
> +        .replace(/(?<=\s)\n/g, '') // remove \n follows a space
@tiberiuichim not supported in Safari: https://caniuse.com/js-regexp-lookbehind

Instead you could do `(\s)\n` and replace it with the captured character

2022-10-27 15:19 UTC, davisagli commented on packages/volto-slate/src/editor/extensions/insertData.js
> +
?

2022-10-27 15:22 UTC, davisagli commented
@tiberiuichim Might be worth having a few tests?

2022-10-27 17:54 UTC, stevepiercy requested changes
Fix name and spell out JavaScript

2022-11-10 10:18 UTC, tiberiuichim commented
@sneridagh Please test this in client project

2022-11-10 14:50 UTC, sneridagh commented
@tiberiuichim confirmed the two bugs (the space leading the pasted text and the other with the double spaces) are gone using this PR

2022-11-17 09:42 UTC, sneridagh approved these changes
@tiberiuichim looks good for me. 

The problem is gone.

Do we want to leave the console.debug statements?

2022-11-18 16:00 UTC, tiberiuichim commented
@sneridagh no, the console.debug calls stay. We need them in case we encounter more weird pasting behavior. They shouldn't affect regular users.

2022-11-23 18:12 UTC, tiberiuichim commented
@sneridagh Assuming tests pass, this should be good to go.

2022-11-24 16:21 UTC, merged