Update documentation of Sentry integration.
plone/volto pull request #3927
Opened 2022-11-19 16:01 UTC by ksuess

Needs to be fixed: https://github.com/collective/volto-sentry/issues/3

2022-11-19 16:20 UTC, ksuess commented
This is about keeping a configuration option with a remark why it's removed.

2022-11-19 19:34 UTC, stevepiercy requested changes
Good catch! Minor clean up on the Glossary entry, and it's good to go.

2022-11-19 19:34 UTC, stevepiercy commented on docs/source/configuration/settings-reference.md
> +    Sentry integration is moved to add-on [`@plone-collective/volto-sentry`](https://www.npmjs.com/package/@plone-collective/volto-sentry). Please see {doc}`../deploying/sentry` for Sentry integratio
````suggestion
    In Volto 16.0.0.alpha.45, Sentry integration was moved from core to the add-on [`@plone-collective/volto-sentry`](https://www.npmjs.com/package/@plone-collective/volto-sentry).

    ```{seealso}
    See {doc}`../deploying/sentry` for Sentry integration.
    ```
````

2022-11-19 21:03 UTC, stevepiercy approved these changes

2022-11-20 09:33 UTC, sneridagh approved these changes

2022-11-20 09:34 UTC, merged