Document how to change the base font and the font for headings. Descr…
plone/volto pull request #4014
Opened 2022-12-01 20:01 UTC by ksuess

…ibe how to host the font.

Fix https://github.com/plone/volto/issues/4013

2022-12-02 07:02 UTC, stevepiercy requested changes
Add some more details about the nifty tool.

2022-12-02 07:02 UTC, stevepiercy commented on docs/source/theming/custom-styling.md
> +  If you are for Google fonts, check [google-webfonts-helper](https://gwfh.mranftl.com/fonts) for generating font-face code.
Nifty tool!

```suggestion
  If you choose Google fonts, check [google-webfonts-helper](https://gwfh.mranftl.com/fonts) to generate `font-face` CSS code and download font files to include in your project.
```

2022-12-02 09:31 UTC, stevepiercy approved these changes

2022-12-02 10:25 UTC, tiberiuichim approved these changes

2022-12-03 08:37 UTC, sneridagh approved these changes

2022-12-03 08:37 UTC, merged