docs additions for external add-ons usage
plone/volto pull request #4233
Opened 2023-01-05 20:54 UTC by cguardia

This information was very helpful to me when dealing with some add-ons (thanks Tiberiu Ichim for the blog post about untranspiled dependencies). I believe it would be good to have this in the docs.

2023-01-05 21:10 UTC, stevepiercy requested changes
Good stuff!

Minor syntax fixes, and a question about the lexer.

2023-01-05 21:10 UTC, stevepiercy commented on docs/source/addons/index.md
> +## problems with untranspiled add-on dependencies
```suggestion
## Problems with untranspiled add-on dependencies
```

2023-01-05 21:10 UTC, stevepiercy commented on docs/source/addons/index.md
> +```js
Is this js or console output? If the latter, then:

````suggestion
```console
````

2023-01-05 21:10 UTC, stevepiercy commented on docs/source/addons/index.md
> +modules to be transpiled. This can be accomplished by customizing the Webpack
They actually lowercase their own name.

```suggestion
modules to be transpiled. This can be accomplished by customizing the webpack
```

2023-01-05 21:10 UTC, stevepiercy commented on docs/source/addons/index.md
> +First we need some setup to get the webpack config from Volto's configuration. Once
```suggestion
First we need some setup to get the webpack configuration from Volto's configuration. Once
```

2023-01-05 21:10 UTC, stevepiercy commented on docs/source/addons/index.md
> +we have that, we just need to resolve the path to the desired add-ons and push it
```suggestion
we have that, we need to resolve the path to the desired add-ons, and push it
```

2023-01-05 21:21 UTC, cguardia commented
@stevepiercy Thanks a lot. Made suggested changes.

2023-01-05 21:23 UTC, stevepiercy approved these changes

2023-01-10 18:02 UTC, sneridagh approved these changes

2023-01-10 18:02 UTC, merged