[WIP] Save edit form as draft using localStorage
plone/volto pull request #4252
Opened 2023-01-11 16:47 UTC by tiberiuichim

2023-01-11 16:52 UTC, tiberiuichim commented
@sneridagh Take a look at the UX, let me know how it feels to you.

How to test: 

- edit a content item
- make some changes
- click the X cancel toolbar button
- edit again
- you'll see a "Autosave found, load it?" confirm dialog. If yes, it loads the saved value, otherwise the form is left intact

2023-01-11 17:55 UTC, tiberiuichim commented
Some things to discuss:

- do we want this for the Add item screen? It may be useful in have some cases, but I have concerns about dates saved in the form and disregarded by the editors
- do we want to configure the autosave interval (at 300ms right now)
- do we want to make it disable-able for some scenarios? Content types, user roles, etc

2023-01-11 22:57 UTC, stevepiercy commented
> - you'll see a "Autosave found, load it?" confirm dialog. If yes, it loads the saved value, otherwise the form is left intact

It would be nice to see a Cypress test with a video, else a video capture of your own screen. That would help me comment on the above item.

> do we want this for the Add item screen? It may be useful in have some cases, but I have concerns about dates saved in the form and disregarded by the editors

I would weigh this against the current situation, where not having autosave would be much worse. Closing a browser window by accident happens all too often. In the scenario you describe, the worst thing that would happen is that dates do not get updated, but they could still be corrected by editors.

> do we want to configure the autosave interval (at 300ms right now)

I would want to make it configurable with a sensible default value. I don't have an opinion of "sensible" now, so use your best judgment.

Also there are two parameters to consider: absolute interval (every N ms) and idle interval (duration of no keyboard or mouse activity in the active window). The latter might be too tricky to achieve, but it would reduce bandwidth (assuming autosave sends an HTTP request) and writes to persistent storage.

> do we want to make it disable-able for some scenarios? Content types, user roles, etc

I cannot think of any scenario where it would be useful to disable autosave. Can you think of a common use case?

2023-01-12 06:08 UTC, tiberiuichim commented
@stevepiercy Thanks for the input! Sorry for not including any other visual clues, I didn't want to spend too much effort if the approach is not correct.

> Also there are two parameters to consider: absolute interval (every N ms) and idle interval (duration of no keyboard or mouse activity in the active window). The latter might be too tricky to achieve, but it would reduce bandwidth (assuming autosave sends an HTTP request) and writes to persistent storage.

I used a debounce technique to handle this case. Whenever the user changes the form state, we schedule a future "commit" (while canceling any active scheduling). If there's no keyboard input, there's no state change. We don't use an interval-based save.

2023-01-12 06:11 UTC, tiberiuichim commented
@stevepiercy Ok, so about the add screen. Do we want the saved values to be restricted to the location, or can we say "I wanted to add a Document at location /x, but I gave up, moved to location /y, I want the previous values entered to be restored".

2023-01-12 07:47 UTC, stevepiercy commented
I think I need a little more background before I can comment on the "restore autosaved item" feature.

Let's say a content type gets autosaved. Would it show up in that location's folder, such as this screenshot? 

![Screen Shot 2023-01-11 at 11 32 39 PM](https://user-images.githubusercontent.com/102112/212005141-c6c6959c-20e3-4b6d-967b-71b20a2211b2.png)

In that screenshot, I created a News content type at `/` with the title of "Test Title". Would an autosaved item appear here, and if so, what would it look like?

Sorry for coming late to the party, if you have already discussed this piece.

If I understand what you are proposing, I prefer to avoid unexpected dialogs in the UI. For example, if I navigate to a location, then click `Add`, I want to add something and not be asked if I want to recover something else. If I want to resume work on something, I would navigate to the directory listing. There I can manage it as usual.

I can see where it would be helpful for an editor to be prompted to recover what was autosaved, but it would also annoy the heck out of people who just want to add a new item.

2023-01-12 08:15 UTC, tiberiuichim commented
@stevepiercy no no, this feature doesn't interact with the server, it only saves entered fields in the browser of  the editor.


https://user-images.githubusercontent.com/141568/212013483-4e644e07-03b4-441b-85de-9f2b2df103a9.mp4

2023-01-12 09:01 UTC, stevepiercy commented
Ah, OK, I see now. I would love to see autosave implemented server-side in another PR.

For this PR, is the alert a React component with potential UI options (two buttons, not just one), and not a JavaScript alert with limited UI options? The source code changes appear to be the former.

Assuming that is the case, then here is what I would suggest.

For autosaved content, save one maximum of each content type per location. Assume the following:

- `/a` has 1 News and 1 Page
- `/b` has 1 Event

1. The editor navigates to `/a` and clicks Add > News, they would see the alert, "You have a previously autosaved News item. [Edit] [Delete]" (two buttons).
2. If instead they click Add > Event, it would not display an alert and go straight into editing mode.
3. The editor navigates to `/b`, and clicks Add > Event, they would see, "You have a previously autosaved Event item. [Edit] [Delete]".

I think more than one content type per location would be unmanageable and impractical. I hope I understand what the intent is now. Please let me know.

2023-01-12 14:11 UTC, tisto commented
@tiberiuichim w00t! Awesome that you started to work on this!

Am I assuming correctly that we autosave a version even when the user clicks on the "X" button just for the purpose of showing that it works in a PoC? I wouldn't expect the system to save a version that I explicitly discarded as a user.

2023-01-12 19:31 UTC, tiberiuichim commented
@tisto Something like that. I've actually tested with the "discard my saved form when I click cancel", it's this commented line: https://github.com/plone/volto/blob/4fd716a7071be65e839333dc89e91534afae5e12/src/components/manage/Form/Form.jsx#L439

The problem is that the Users don't have a way of going back to the View page of an item, except either by the Cancel or by Save buttons.  So it's up to us to decide how we want this whole thing to work, what its meaning should be in the overall workflow.

As a side discussion, I have another idea for UX, for the Confirm() dialog that restores the saved state. Rather then letting the user decide what to do about the saved state, what if we just load that state and show a Toast message saying something like "Found a previous unsaved version, it is now loaded. You can **undo** and load the saved version".

2023-01-12 20:10 UTC, ksuess commented
> * you'll see a "Autosave found, load it?"

This needs a check if the page has been edited since, doesn't it?

2023-01-12 20:20 UTC, tiberiuichim commented
@ksuess Indeed, it would be a good idea to check last modification times, in case another user edited a document.

2023-01-13 06:40 UTC, davisagli commented
@tiberiuichim Thanks for starting work on this!

> As a side discussion, I have another idea for UX, for the Confirm() dialog that restores the saved state. Rather then letting the user decide what to do about the saved state, what if we just load that state and show a Toast message saying something like "Found a previous unsaved version, it is now loaded. You can undo and load the saved version".

I like this idea.

Do we need any special considerations for how it interacts with edit locking?

2023-01-13 07:29 UTC, tiberiuichim commented
@davisagli no, it all happens client side based on saved data in the localstorage.

The current internal behavior is like this:

- user opens edit form
- on any change, we schedule a debounced localStorage.save()
- when there's no activity from the user, the current form content is comitted to localstorage
- if the user clicks Save, the localstorage is removed. If they click Cancel, it is not removed (to be decided on this behavior).
- if the user reopens the Edit page, the localstorage is compared with the current formData. If they're different, the user is prompted what to do: either load or dump the previous saved version.

As the key for the localstorage, we use this algorithm:

```
const getFormId = (props) => {
  const { type, pathname, isEditForm } = props;

  const id = isEditForm
    ? ['form', type, pathname].join('-')
    : type
    ? ['form', 'add', type].join('-')
    : ['form', pathname].join('-');

  return id;
};
```

2023-01-13 10:48 UTC, stevepiercy commented
> if the user clicks Save, the localstorage is removed. If they click Cancel, it is not removed (to be decided on this behavior).

Third option: the user quits the browser, closes the tab, or otherwise navigates away (clicks a browser bookmark). What happens? In this scenario, an alert of "Are you sure you want to destroy your work?" would be super helpful to prevent accidents. Let's call it "diaper mode".

2023-01-13 11:31 UTC, tiberiuichim commented
@stevepiercy the "form unload handler", plone classic has it. We can model behavior based on that one, though this implementation is kind of a substitution for that one. Maybe we can combine them.

2023-01-13 15:11 UTC, davisagli commented
@tiberiuichim I think what I meant about locking was the same point Katja raised about making sure the saved draft can't overwrite a more recent change. Sounds like you have a plan for that.

@stevepiercy It seems to me that if this autosave exists, then it's not necessary to show a "Are you sure you want to destroy your work?" message, because your work is not going to be destroyed even if you leave the page. I guess we could show that message, but it might be annoying when you're actually leaving the page intentionally.

2023-06-29 10:27 UTC, rexalex commented
Hello, I took over the feature from @tiberiuichim.

Current version has:
- Show a toast to tell user that a local version was found (OK will apply, Cancel will delete, Close will do nothing)
- Saving the form will delete the specific local data form
- Cancel will not delete (we need a decision about if it should)
- Add new content is also autosaved specific for each item and content type
- If local data is less recent than the server version, the toast will show a different message suggesting it, the user can choose the local or keep the server version - they can also undo and redo
- It will also autosave comments

2023-06-29 10:27 UTC, rexalex commented
Demo for how autosave removes storage on Save form or Cancel load saved data:

https://user-images.githubusercontent.com/7466122/247877147-d83070e9-4c47-4d1a-85f5-908d8839684d.mov

2023-06-29 10:28 UTC, rexalex commented
Demo for how autosave manages stale data (content gets edited more recently than the local saved data):

https://user-images.githubusercontent.com/7466122/247877882-5fc3efb3-cf3e-4abc-a649-0c78a8a89d16.mov

2023-06-29 10:28 UTC, rexalex commented
Demo for how autosave adds new content type:

https://user-images.githubusercontent.com/7466122/247878398-7eb4e22b-f748-4fa4-8254-451e69949738.mov

2023-06-29 10:29 UTC, rexalex commented
Demo for how autosave handles accidental refresh in edit and add modes:

https://user-images.githubusercontent.com/7466122/247879058-1c7d1954-111e-468f-b456-198e3bfdd9b0.mov

2023-06-29 10:29 UTC, rexalex commented
Demo for comments autosave:

https://user-images.githubusercontent.com/7466122/249213695-16ac7fa1-b3a2-44f2-929e-69e382b8c08f.mov

2023-06-29 11:14 UTC, stevepiercy commented
@rexalex thank you for picking up this PR.

This PR will need docs to describe what this new killer feature is and does.

Videos are good, but they need to be shown in a narrow portal of [no more than 743 pixels](https://6.docs.plone.org/contributing/documentation/myst-reference.html#width-of-media) and embedded into docs per https://6.docs.plone.org/contributing/documentation/myst-reference.html#video.

I am not certain where docs should go for this feature. It might be a new page. I think a new page would be good because it would boost SEO for the autosave feature of Volto, a truly "killer feature" amongst CMSs. I also think this feature is primarily for the user who edits content, not so much the developer. I think it belongs in the [User Manual](https://6.docs.plone.org/volto/user-manual/index.html). What do y'all think?

2023-06-30 11:11 UTC, tiberiuichim commented on src/components/manage/Form/Form.jsx
> +  // first call will ignore are setState passed through callbacks
unclear comment

2023-07-06 12:02 UTC, stevepiercy requested changes
Thank you so much for writing docs. This makes me so happy. Most of the suggestions are minor English and MyST syntax and grammar.

I think we should have a friendly competition with Classic UI to see which team can generate the most pages of user manual documentation. Classic UI was quick out of the gate but has stalled, while Volto is quickly catching up.

2023-07-06 12:04 UTC, stevepiercy commented
Also add an entry to `docs/source/user-manual/index.md` for `autosave`.

2023-07-18 09:46 UTC, stevepiercy commented
@rexalex please resolve merge conflicts with `master` branch.

2023-07-18 09:49 UTC, stevepiercy commented on docs/source/user-manual/autosave.md
> +    "description": "User manual for how Volto autosaves data in Plone 6 frontend."
This one was resolved without comment or action. Please respond.

2023-07-18 09:52 UTC, stevepiercy commented on docs/source/user-manual/autosave.md
> +- If local data is found for the specific content a toast is shown that allows you to either load (OK) or discard (Cancel).
Is it possible to add a screenshot of the toast?

2023-07-18 09:56 UTC, stevepiercy requested changes
Just one grammar fix, and a couple of omitted suggestions to address. Please let me know. Thank you!

2023-07-18 09:56 UTC, stevepiercy commented on docs/source/user-manual/autosave.md
> +Changing the form will update the `localStorage` with a new complete copy of the Form.
```suggestion
Changing the form will update the `localStorage` with a new complete copy of the form.
```

2023-07-20 06:54 UTC, stevepiercy approved these changes
I approve the docs. Let's get a maintainer to review the code. Thank you!

2023-07-20 06:56 UTC, stevepiercy commented
@rexalex please resolve merge conflicts with master branch.

2023-08-02 06:49 UTC, rexalex commented
@stevepiercy done

2023-08-02 07:13 UTC, stevepiercy commented
@tiberiuichim @sneridagh @davisagli @ksuess  this is ready for review.

2023-09-14 09:13 UTC, stevepiercy requested changes
Tweak messages to be more user friendly.

2023-09-14 09:13 UTC, stevepiercy commented on src/helpers/Utils/withSaveAsDraft.js
> +    id: 'Autosave found',
```suggestion
    id: 'Autosaved content found',
```

2023-09-14 09:13 UTC, stevepiercy commented on src/helpers/Utils/withSaveAsDraft.js
> +    defaultMessage: 'Autosave found',
```suggestion
    defaultMessage: 'Autosaved content found',
```

2023-09-14 09:13 UTC, stevepiercy commented on src/helpers/Utils/withSaveAsDraft.js
> +    id: 'Do you want to load it?',
```suggestion
    id: 'Do you want to load the autosaved content?',
```

2023-09-14 09:13 UTC, stevepiercy commented on src/helpers/Utils/withSaveAsDraft.js
> +    defaultMessage: 'Do you want to load it?',
```suggestion
    defaultMessage: 'Do you want to load the autosaved content?',
```

2023-09-14 09:13 UTC, stevepiercy commented on src/helpers/Utils/withSaveAsDraft.js
> +      'The version found is less recent than the server, do you want to load it (you can undo if you change your mind)?',
```suggestion
      'The version of the autosaved content I found in your browser is older than that stored on the server. Do you want to load the autosaved content? (You can undo the autosaved content and revert to the server version.)',
```

2023-09-14 09:13 UTC, stevepiercy commented on src/helpers/Utils/withSaveAsDraft.js
> +      'The version found is less recent than the server, do you want to load it (you can undo if you change your mind)?',
```suggestion
      'The version of the autosaved content I found in your browser is older than that stored on the server. Do you want to load the autosaved content? (You can undo the autosaved content and revert to the server version.)',
```

2023-09-14 09:16 UTC, sneridagh commented
@rexalex @tiberiuichim some minor text tweaks and let's merge it!

2023-09-14 23:16 UTC, stevepiercy approved these changes
Thank you!

2023-09-14 23:18 UTC, stevepiercy commented
@rexalex @tiberiuichim it looks like the autosave tests need to be updated to reflect the changes in the messages, too.

2023-09-16 07:56 UTC, tisto commented
@sneridagh I get an error when trying to build this branch locally (backend):

````
An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/Users/timo/workspace/plone/volto/api/lib/python3.8/site-packages/zc/buildout/buildout.py", line 2252, in main
    getattr(buildout, command)(args)
  File "/Users/timo/workspace/plone/volto/api/lib/python3.8/site-packages/zc/buildout/buildout.py", line 856, in install
    installed_files = self[part]._call(recipe.install)
  File "/Users/timo/workspace/plone/volto/api/lib/python3.8/site-packages/zc/buildout/buildout.py", line 1652, in _call
    return f()
  File "/Users/timo/workspace/dotfiles/.buildout/eggs/zc.recipe.testrunner-3.0-py3.8.egg/zc/recipe/testrunner/__init__.py", line 46, in install
    eggs, ws = self.egg.working_set(('zope.testrunner', ))
  File "/Users/timo/workspace/dotfiles/.buildout/eggs/zc.recipe.egg-2.0.7-py3.8-macosx-13.3-arm64.egg/zc/recipe/egg/egg.py", line 78, in working_set
    ws = self._working_set(
  File "/Users/timo/workspace/dotfiles/.buildout/eggs/zc.recipe.egg-2.0.7-py3.8-macosx-13.3-arm64.egg/zc/recipe/egg/egg.py", line 161, in _working_set
    ws = zc.buildout.easy_install.install(
  File "/Users/timo/workspace/plone/volto/api/lib/python3.8/site-packages/zc/buildout/easy_install.py", line 971, in install
    return installer.install(specs, working_set)
  File "/Users/timo/workspace/plone/volto/api/lib/python3.8/site-packages/zc/buildout/easy_install.py", line 717, in install
    req = self._constrain(current_requirement)
  File "/Users/timo/workspace/plone/volto/api/lib/python3.8/site-packages/zc/buildout/easy_install.py", line 664, in _constrain
    requirement = _constrained_requirement(constraint,
  File "/Users/timo/workspace/plone/volto/api/lib/python3.8/site-packages/zc/buildout/easy_install.py", line 1641, in _constrained_requirement
    if version not in requirement:
  File "/Users/timo/workspace/plone/volto/api/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3201, in __contains__
    return self.specifier.contains(item, prereleases=True)
  File "/Users/timo/workspace/plone/volto/api/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/specifiers.py", line 902, in contains
    item = Version(item)
  File "/Users/timo/workspace/plone/volto/api/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/version.py", line 197, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: '5.3.1 # without this volto is not building locally'
make: *** [.installed.cfg] Error 1
make: *** Deleting file `.installed.cfg'
````

I guess this is not related to this PR at all...

2023-09-16 07:59 UTC, sneridagh commented
I almost never use the local build anymore… I always spin a container for
the backend. I think Alok found this the other day in a PR, could be that
it didn’t get merged yet. It was about a dep (again) in buildout.

On Sat, 16 Sep 2023 at 09:56, Timo Stollenwerk ***@***.***>
wrote:

> @sneridagh <https://github.com/sneridagh> I get an error when trying to
> build this branch locally (backend):
>
> An internal error occurred due to a bug in either zc.buildout or in a
> recipe being used:
> Traceback (most recent call last):
>   File "/Users/timo/workspace/plone/volto/api/lib/python3.8/site-packages/zc/buildout/buildout.py", line 2252, in main
>     getattr(buildout, command)(args)
>   File "/Users/timo/workspace/plone/volto/api/lib/python3.8/site-packages/zc/buildout/buildout.py", line 856, in install
>     installed_files = self[part]._call(recipe.install)
>   File "/Users/timo/workspace/plone/volto/api/lib/python3.8/site-packages/zc/buildout/buildout.py", line 1652, in _call
>     return f()
>   File "/Users/timo/workspace/dotfiles/.buildout/eggs/zc.recipe.testrunner-3.0-py3.8.egg/zc/recipe/testrunner/__init__.py", line 46, in install
>     eggs, ws = self.egg.working_set(('zope.testrunner', ))
>   File "/Users/timo/workspace/dotfiles/.buildout/eggs/zc.recipe.egg-2.0.7-py3.8-macosx-13.3-arm64.egg/zc/recipe/egg/egg.py", line 78, in working_set
>     ws = self._working_set(
>   File "/Users/timo/workspace/dotfiles/.buildout/eggs/zc.recipe.egg-2.0.7-py3.8-macosx-13.3-arm64.egg/zc/recipe/egg/egg.py", line 161, in _working_set
>     ws = zc.buildout.easy_install.install(
>   File "/Users/timo/workspace/plone/volto/api/lib/python3.8/site-packages/zc/buildout/easy_install.py", line 971, in install
>     return installer.install(specs, working_set)
>   File "/Users/timo/workspace/plone/volto/api/lib/python3.8/site-packages/zc/buildout/easy_install.py", line 717, in install
>     req = self._constrain(current_requirement)
>   File "/Users/timo/workspace/plone/volto/api/lib/python3.8/site-packages/zc/buildout/easy_install.py", line 664, in _constrain
>     requirement = _constrained_requirement(constraint,
>   File "/Users/timo/workspace/plone/volto/api/lib/python3.8/site-packages/zc/buildout/easy_install.py", line 1641, in _constrained_requirement
>     if version not in requirement:
>   File "/Users/timo/workspace/plone/volto/api/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3201, in __contains__
>     return self.specifier.contains(item, prereleases=True)
>   File "/Users/timo/workspace/plone/volto/api/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/specifiers.py", line 902, in contains
>     item = Version(item)
>   File "/Users/timo/workspace/plone/volto/api/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/version.py", line 197, in __init__
>     raise InvalidVersion(f"Invalid version: '{version}'")
> pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: '5.3.1 # without this volto is not building locally'
> make: *** [.installed.cfg] Error 1
> make: *** Deleting file `.installed.cfg'
>
> I guess this is not related to this PR at all...
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/plone/volto/pull/4252#issuecomment-1722169318>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AADW4D367JK5UPXVE6URW73X2VLT3ANCNFSM6AAAAAATYIBNDE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-09-16 14:58 UTC, tisto commented
@sneridagh ok, I gave this a shot locally. When I click on the "yes" icon in the modal nothing happens and I see an error trace in the JS console:

<img width="1469" alt="Screenshot 2023-09-16 at 16 47 56" src="https://github.com/plone/volto/assets/632105/3b2f49eb-c456-4efb-a2b6-2e6c5652f1f9">

Some other observations:

- as @tiberiuichim suggested, we might want to not show the autosave modal when the user intention was to drop the content and click on the "x" cancel option
- the modal shows up very briefly, I'd say this is important enough to stay
- as a user I am clueless what my latest changes were, when I have no way of seeing the differences, it might be very tough decision, especially if I am not sure if the system would replace my current version with the restored version. the question that arises is: do I have to save afterwards or do I make a final decision here
- the go/cancel icons are too far from each other and the "x" right to those buttons is confusing, we show two different "x" icons to the user, this needs an UI overhaul

<img width="585" alt="Screenshot 2023-09-16 at 16 49 23" src="https://github.com/plone/volto/assets/632105/66a42d9c-b5e6-4060-949e-89b33dc027dd">

- I'd also improve the modal text explaining what happened and what the options are, maybe we need to be more explicit here and we shouldn't use the Volto save/cancel buttons at all

2023-09-16 15:12 UTC, sneridagh commented
> @sneridagh ok, I gave this a shot locally. When I click on the "yes" icon in the modal nothing happens and I see an error trace in the JS console:
> 
> <img alt="Screenshot 2023-09-16 at 16 47 56" width="1469" src="https://user-images.githubusercontent.com/632105/268454382-3b2f49eb-c456-4efb-a2b6-2e6c5652f1f9.png">
> Some other observations:
> 
> * as @tiberiuichim suggested, we might want to not show the autosave modal when the user intention was to drop the content and click on the "x" cancel option

You are proposing to do *not* autosave when the user intention was "cancel", thus discard all the changes made until that moment, right? I'm +1 to change the flow in this way.

> * the modal shows up very briefly, I'd say this is important enough to stay

I agree, it should be permanent, I'd say, until the user makes up his mind.

> * as a user I am clueless what my latest changes were, when I have no way of seeing the differences, it might be very tough decision, especially if I am not sure if the system would replace my current version with the restored version. the question that arises is: do I have to save afterwards or do I make a final decision here

As one of the videos shows, the user can undo-redo the changes to see them. The decision is not final, and you can always not save, load again the server version. And if for some reason someones changes its mind after save, then you can revert the change in the history view.

> * the go/cancel icons are too far from each other and the "x" right to those buttons is confusing, we show two different "x" icons to the user, this needs an UI overhaul

I agree, any proposal? 

> 
> <img alt="Screenshot 2023-09-16 at 16 49 23" width="585" src="https://user-images.githubusercontent.com/632105/268454543-66a42d9c-b5e6-4060-949e-89b33dc027dd.png">
> * I'd also improve the modal text explaining what happened and what the options are, maybe we need to be more explicit here and we shouldn't use the Volto save/cancel buttons at all

Any suggestion? Steve already reviewed that and it seemed to him enough explicit. At the end the options are not that complicated, apply the saved changes or not. Saying I don't think is right or correct is not enough.

2023-09-16 15:14 UTC, sneridagh commented
@rexalex could you please take care of the things mentioned above, and the error @tisto found? It seems an easy one, a rendering of a non allowed element  inside a `<p>`.

2023-09-18 06:28 UTC, tisto commented
One thing that I would like to discuss is the wording. When I hear "autosave" I think about the autosave functionality in Google Docs, which is not what we implemented here. What about calling this "content recovery"? Any other ideas? @rexalex @stevepiercy @tiberiuichim @sneridagh @davisagli @ksuess

2023-09-18 09:04 UTC, stevepiercy commented
Recovery is not the right term because the content was never lost. The autosaved content is a version of stored content.

2023-09-18 14:52 UTC, sneridagh commented
@tisto @stevepiercy How about "local autosave" to clarify it's not being persisted in server?

2023-09-18 21:03 UTC, stevepiercy commented
I don't see a problem with plain old "autosave". Most end users won't know the difference of where content is autosaved. If you qualify it with "local" or "remote", that could increase confusion.

2023-09-19 06:34 UTC, tisto commented
@stevepiercy say you are working on something in an application (like LibreOffice) and your OS crashes. The application will ask you next time you open it if you want to "recover the document", see LibreOffice:

![libreoffice-document-recovery](https://github.com/plone/volto/assets/632105/c1db6603-7125-4311-bc83-867da15e66fa)

I never saw a modal asking if I wanted to access my "autosaved document". I am not a native speaker. Our use case and what it solves is similar to the document recovery (the browser crashes or is closed, we ask the user if she wants it back).

2023-09-19 06:59 UTC, davisagli commented
@stevepiercy I think @tisto has a point. When I hear "autosave", I assume that means that I never have to click a save button because it always happens automatically. That's not what this feature is.

2023-09-19 07:25 UTC, stevepiercy commented
@davisagli I thought this feature always autosaves content locally after the user stops interacting with the content after a defined duration, right?

I think the question is what do you call the process of loading that autosaved content? Did the user close the browser window or navigate away from the page without saving the content first? Did the app or browser crash? Was the user's intent deliberate, accidental, or completely outside their control?

"Recover" is appropriate in the LIbreOffice context. It attempts to recover lost data from a fatal disaster outside the user's intent. Recovery does not happen if the user deliberately closes the file.

Perhaps the term "restore" would be a more appropriate verb than "load" and "recover"? Google Drive uses "restore" not "recover" in its version history feature. Its autosave feature is similar to my understanding of this feature in Volto. For example, in a Google Doc, if I type something and immediately close the document before it saves to the remote drive, then the changes are not autosaved. If the changes get autosaved, either because there was sufficient time or I have Edit Offline turned on, then I can restore an autosaved version, albeit only the last autosaved version.

From the Merriam-Webster site:

https://www.merriam-webster.com/dictionary/restore

![Screenshot 2023-09-19 at 12 23 04 AM](https://github.com/plone/volto/assets/102112/74029e83-d783-4018-a6b7-60f160cc499e)

https://www.merriam-webster.com/dictionary/recover

![Screenshot 2023-09-19 at 12 22 40 AM](https://github.com/plone/volto/assets/102112/d56dcd79-32b1-4c5d-b27c-e00f38be9097)

2023-09-25 07:26 UTC, sneridagh commented
@tisto @stevepiercy I'd like to move forward on this one, and release it right away. Right now it's blocking 17, and we are approaching the PC quickly.

Could we get to an agreement? Tomorrow we have the Volto Team Meeting.

Thanks!

2023-09-25 09:32 UTC, stevepiercy commented
@sneridagh I'm awaiting a response from @davisagli or @tisto to my most recent comment. I might be wrong about what this feature actually does.

2023-09-26 09:58 UTC, sneridagh commented
Volto Team Meeting (2023-09-26) decisions:
- We settled in "Restore" as the term to use in all literals (as opposite of "autosave").
- We had the feeling that it needs more polishment, especially in the UX interactions, so we will not rush and wait for the next alpha phase and slate it for 18.
- If it seems sensible, add a diff view feature in case of conflict with the current "saved in server" version, if any (at the moment of the meeting we didn't know if that could even happen at some point).
- Try to determine if it would be also an option as a complement to this feature to introduce a "form unload" protection mechanism.
- It seems sensible to put this feature under a feature flag

2023-09-27 02:52 UTC, djay commented
> As a side discussion, I have another idea for UX, for the Confirm() dialog that restores the saved state. Rather then letting the user decide what to do about the saved state, what if we just load that state and show a Toast message saying something like "Found a previous unsaved version, it is now loaded. You can undo and load the saved version".

I think @tiberiuichim idea got lost somehow.

This feature should not be a recovery from saved version choice like libreoffice (I hate this UI). You are giving the user a choice while giving them no information on how to make the choice.

Instead this should be considered the *"resume unsaved" feature* and it could work like this:

- if you edit then close the browser and then later reedit 
    - you get a toast to say "you are editing unsaved content x days old. click cancel to revert to the saved version"
- if you edit and close the browser and someone else tried to edit
    - they can't. it's locked
- if you edit and close the browser and someone overrides the lock and edits and then you go back in and edit 
   - you get a toast to say you lost your changes. bad luck. later this can be improved with an option to save as a working copy maybe.
- if you edit and then cancel
   - I suspect the best thing to do is just abandon the local changes. The user is explicitly cancelling. Putting up a dialog each time they cancel to explain that they can come back to where they left off might be a pain if what they are trying to do is revert to the saved copy. Instead click off the page could put up a toast that their changes were saved in their browser and they will learn.  but I'm 50/50 on this. a back button + cancel button is maybe the best option.

All of this means we can avoid having diffs of the local version until later and the changes to this PR to include it earlier are very minimal both technically and to the current user flows @davisagli @tisto @sneridagh ?

But later it would be nice to move the history view into editmode and then you can diff your unsaved changes against the saved version or any other. No special diff mode is needed.
or... if there is a back button then you don't need to move history view into edit mode. The user clicks back, goes to history, views the history (which includes unsaved changes at the top), goes back to edit and they are working where they left off.

Later an indicator can be added to show you have unsaved changes on both the toolbar and the contents view. But that's not needed now.

2023-09-27 06:57 UTC, stevepiercy commented
I replaced "load" with "restore" and added "autosave" to Vale to silence errors.

2023-09-27 07:22 UTC, stevepiercy commented
I fixed a couple of i18n issues, but I have no idea of how to fix the remaining few. https://github.com/plone/volto/actions/runs/6322673648/job/17168722091?pr=4252

Is that a release manager task?

2024-03-02 17:55 UTC, mister-roboto commented
rexalex, ALEXANDRU MEDESAN your emails are not known to GitHub and thus it is impossible to know if you have signed the Plone Contributor Agreement, which is required to merge this pull request.

Learn about the Plone Contributor Agreement: https://plone.org/foundation/contributors-agreement How to add more emails to your GitHub account: https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/adding-an-email-address-to-your-github-account

2025-03-11 10:48 UTC, pnicolli commented
During the Volto Team meeting today we decided to bring this discussion up during the upcoming Bucharest Sprint.

2025-05-20 09:26 UTC, pnicolli commented
Closed, implemented in #6864

2025-05-20 09:26 UTC, closed without merging