Bugfix : Responsive Error in login page
plone/volto pull request #4309
Opened 2023-01-24 20:08 UTC by suman9893

Bugfix #3250

2023-01-29 16:53 UTC, suman9893 commented
May I know the reason why my PR is not getting merged? So that I can improve the PR accordingly.

2023-01-29 21:11 UTC, stevepiercy requested changes

2023-01-29 21:11 UTC, stevepiercy commented on news/3250.bugfix
> +Fix for responsive error in the login page when the width of the screen decreases.
Please add your username to the news item.
```suggestion
Fix for responsive error in the login page when the width of the screen decreases. @suman9893
```

2023-01-30 09:43 UTC, stevepiercy approved these changes
I approve, but it needs further review from the @plone/volto-team .

2023-09-09 16:04 UTC, merged

2023-09-09 16:05 UTC, davisagli commented
@suman9893 Thank you, and sorry it took us so long to review and merge this.

2023-09-10 11:48 UTC, suman9893 commented
> @suman9893 Thank you, and sorry it took us so long to review and merge this.

May you please check #4513 ? I think this can also get merged. @davisagli