Add filter to remove entries with empty msgstr
plone/volto pull request #4316
Opened 2023-01-26 19:44 UTC by danalvrz

Regarding: [Issue 3735](https://github.com/plone/volto/issues/3735)
- Added filter to function `poToJson()` to remove entries with empty `msgstr`

2023-01-26 19:48 UTC, davisagli requested changes

2023-01-26 19:48 UTC, davisagli commented on news/4316.bugfix
> +Added filter to function poToJson() to remove entries with empty msgstr @danalvrz
```suggestion
Fixed i18n script to avoid overwriting translations with an empty msgstr @danalvrz
```

2023-01-26 19:48 UTC, davisagli commented on packages/scripts/i18n.cjs
> +    items = [...items].filter((item) => item.msgstr[0] !== ''); // Remove entries with msgstr = “”
```suggestion
    items = items.filter((item) => item.msgstr[0] !== ''); // Remove entries with msgstr = “”
```

2023-01-26 19:51 UTC, davisagli approved these changes

2023-01-27 06:58 UTC, erral commented
I have some doubts here.

In some languages some msgstr-s are left untranslated on purpose or with an empty space for instance, because the language doesn't need that translation.

For instance there are several msgstr-s left empy in the calendar recurrence widget left untranslated in basque, because the langue structure doesn't need them.

What would happen with such translations?

See: https://github.com/plone/volto/blob/master/locales/eu/LC_MESSAGES/volto.po#L4288

2023-01-27 07:25 UTC, davisagli commented
@erral Well, this doesn't change anything about how a msgstr with a space is handled.

But I think you're right that we need to be a bit more careful so that we don't lose the defaultMessage if all msgstrs are empty.

2023-01-27 07:28 UTC, tiberiuichim commented
@erral My first guess is that the basque translation issue is a smell, probably the intl message in that place is improperly formed and should use dynamic var places to incorporate the values, rather then using some connecting words as separate entities.

2023-01-27 10:08 UTC, sneridagh commented
@davisagli @danalvrz 

If I understood the use case, is that:
- We have a translation for a msgid in place
- An add-on that reuses the msgid for some reason does not have that translation
- Then, as the add-ons are processed by the `addons` list order, could be that one translation gets overwritten.

Here could be a legit question: Do we want that add-ons overwrite the core translations? or other add-ons translations? I'd say we want this to happen, and let the add-on order to determine who wins.

If we want to fix the issue, I think that the placement of the fix is wrong. We have to fine tune the merging of the .po-s instead of the final output to the .json file.

2023-01-27 15:17 UTC, erral commented
> @erral My first guess is that the basque translation issue is a smell, probably the intl message in that place is improperly formed and should use dynamic var places to incorporate the values, rather then using some connecting words as separate entities.

the recurrence widget is indeed the hell for translators. There are several widgets with prepositions to translate. Something like this:

Every 2nd Tuesday

Which is handled like

Every: msgid
2: dropdown
nd: msgid
Tuesday: dropdown

Which in Basque, but I am pretty sure in some other language aswell is:

2. Astearte guztietan

There is no translation for Every, 2nd is a dot and not a word, and we need an additional word after Tuesday.

It is a corner case indeed, but we need to support those empty strings.

2023-01-27 16:31 UTC, tiberiuichim commented
@erral bah. Maybe we should refactor that widget, to be easier to translate.

2023-03-05 05:38 UTC, davisagli commented
@erral @sneridagh We updated the implementation so that it allows empty translations to be overwritten, but does not lose them if they are empty everywhere. Does it look okay now?

2023-03-14 12:19 UTC, sneridagh approved these changes
LGTM, @erral ?

2023-03-15 10:35 UTC, merged