Provide disable props to all widget and pass disable props in babel view
plone/volto pull request #4398
Opened 2023-02-16 14:12 UTC by iFlameing

2023-02-17 08:43 UTC, sneridagh approved these changes
LGTM

2023-02-17 19:22 UTC, ksuess requested changes
Maybe one line of documentation: "On these conditions, these widgets need to be disabled. This can be done by …"

2023-02-18 00:47 UTC, stevepiercy requested changes

2023-02-18 00:47 UTC, stevepiercy commented on news/4396.feature
> +Provide disable props to all widget and pass disable props in babel view @iFlameing
```suggestion
Provide disabled props to all widgets, and pass disabled props in to babel views. @iFlameing
```

2023-02-20 08:48 UTC, sneridagh commented
@iFlameing please take a look at suggestions.

2023-02-21 12:47 UTC, iFlameing commented
@sneridagh add the documentation as suggested.

2023-02-21 14:35 UTC, merged