Add /ok route as an express middleware
plone/volto pull request #4432
Opened 2023-02-24 11:23 UTC by erral

Fixes #4375 adding an Express middleware

This supersedes #4429

2023-02-24 12:20 UTC, tiberiuichim approved these changes

2023-02-25 07:43 UTC, tiberiuichim requested changes
In Plone the ok view is namespaced by the `@@` symbols, so there's no chance to overlap something else. Let's do something similar here. Maybe `/_ok` ? 

Also, I don't think there's a need for a setting for this, if we solve the namespacing problem.

@plone/volto-team thoughts on this?

2023-02-25 16:58 UTC, davisagli commented
How about something like `.well-known/volto/ok` (based on https://en.wikipedia.org/wiki/Well-known_URI)?

Whatever it is, it should be mentioned in the docs.

2023-03-10 09:45 UTC, avoinea commented
> In Plone the ok view is namespaced by the `@@` symbols, so there's no chance to overlap something else. Let's do something similar here. Maybe `/_ok` ?
> 
> Also, I don't think there's a need for a setting for this, if we solve the namespacing problem.
> 
> @plone/volto-team thoughts on this?

Well, it also works with `/ok` in Plone Classic and we're doing all health-checks to this path `/ok`. Thus, I would stick to `/ok`. Or use the `.well-known` approach as @davisagli suggested.

2023-03-15 10:32 UTC, sneridagh commented
We need a consensus here. I'm ok with using both `/ok` and `.well-known/volto/ok` the reasoning behind both seems ok (no pun intended) for me. Everybody is ok? 😂

2023-03-15 10:47 UTC, tiberiuichim commented
I'm +1 on adopting the industry standard.

2023-03-17 16:47 UTC, erral commented
I don't see a ok URL under the well-known URLs right? I mean I don't mind using the .well-known approach, but right know there's no such standard for ok right?

We can start having the ok like we have in classic and evolve to whatever is stablished later on.

2023-03-17 21:23 UTC, davisagli commented
I was the one who brought up the `.well-known` idea, but I don't see any big problem with `/ok`: it is unlikely to conflict with content, and if it does there is the setting. So I would go ahead with this the way it is. The one thing I am missing in the PR is documentation of the new setting.

2023-03-17 23:38 UTC, stevepiercy commented
> The one thing I am missing in the PR is documentation of the new setting.

Would that go here?

https://6.docs.plone.org/volto/configuration/settings-reference.html#server-specific-serverconfig

2023-07-01 09:15 UTC, erral commented
I have realized that I was missing the documentation part on this PR as requested by @stevepiercy :facepalm: so I have added it :wink:

2023-07-01 09:43 UTC, stevepiercy requested changes
Thanks for the docs. Mostly MyST and English syntax and grammar.

2023-07-01 09:43 UTC, stevepiercy commented on docs/source/configuration/settings-reference.md
> +````
This is the closing fence for the opening glossary fence at the start of the page. It should be moved after your new glossary entry.

```suggestion
```

2023-07-01 09:43 UTC, stevepiercy commented on docs/source/configuration/settings-reference.md
> +Volto provides a `/ok` URL where it respondes with a text/plain ok response (with an `HTTP 200` status code) to signal third-party health-check services that the Volto process is running correctly.
Indent glossary definitions.

```suggestion
    Volto provides an `/ok` URL where it responds with a `text/plain ok` response, with an `HTTP 200` status code, to signal third party health check services that the Volto process is running correctly.
```

2023-07-01 09:43 UTC, stevepiercy commented on docs/source/configuration/settings-reference.md
> +Using this setting one can modify such an URL and configure to respond in some other URL.
```suggestion
    Using this setting, one can modify such an URL and configure it to respond with another URL.
```

2023-07-01 09:43 UTC, stevepiercy commented on docs/source/configuration/settings-reference.md
> +The provided default matches the existing Plone Classic URL.
```suggestion
    The provided default matches the existing Plone Classic UI URL.
```

2023-07-01 09:43 UTC, stevepiercy commented on docs/source/configuration/settings-reference.md
> +
```suggestion
```

2023-07-01 09:43 UTC, stevepiercy commented on docs/source/configuration/settings-reference.md
> +    ```
Close glossary fence.

````suggestion
    ```
```
````

2023-07-02 08:02 UTC, erral commented
> Thanks for the docs. Mostly MyST and English syntax and grammar.

thank you as always!

2023-07-02 10:17 UTC, stevepiercy approved these changes
Looks good! https://deploy-preview-4432--volto.netlify.app/configuration/settings-reference.html#term-okRoute

2023-07-02 10:20 UTC, stevepiercy commented
It is OK to ignore the failing docs job. He Who Shall Not Be Named has once again pulled more feathers from the bird site, now requiring authentication to view a user's twerks.

2023-07-18 07:55 UTC, sneridagh approved these changes

2023-07-18 07:55 UTC, merged