fix: unresponsive content page
plone/volto pull request #4500
Opened 2023-03-11 05:22 UTC by sudhanshu1309

The menu for contents page was unresponsive on mobile devices Fixed this by changing the menu overflow to scroll.
closes #4493

2023-03-11 05:43 UTC, stevepiercy requested changes
Simplify the news item. Otherwise LGTM.

Silly mister-roboto. Sorry about that confusion.

2023-03-11 05:43 UTC, stevepiercy commented on news/4492.bugfix
> +In `theme/themes/pastanaga/extras/contents.less` file added a `overflow-x: scroll;` to make overflow content to scroll.  @sudhanshu1309
```suggestion
```

2023-03-11 05:43 UTC, stevepiercy commented on news/4492.bugfix
> +The menu for the contents page was unresponsive on mobile devices. Fixed this by changing the menu overflow to scroll.
```suggestion
The menu for the contents page was unresponsive on mobile devices. Fixed this by changing the menu overflow to scroll. @sudhanshu1309

```

2023-03-11 05:43 UTC, stevepiercy commented on news/4492.bugfix
> +In `theme/themes/pastanaga/extras/contents.less` file added a `overflow-x: scroll;` to make overflow content to scroll.  @sudhanshu1309
This is obvious in the code diff.

2023-03-11 07:37 UTC, stevepiercy approved these changes

2023-03-15 10:57 UTC, sneridagh approved these changes

2023-03-15 11:03 UTC, merged