fix: unresponsive add page
plone/volto pull request #4507
Opened 2023-03-12 10:41 UTC by sudhanshu1309

The tabs  for the add page was unresponsive on mobile devices. Fixed this by changing flex-wrap property
closes #4506

2023-03-14 04:08 UTC, stevepiercy requested changes
GitHub likes a final line break as an EOF indicator, else it shows a red circle with a slash through it.

Also delete extra space.

2023-03-14 04:08 UTC, stevepiercy commented on theme/themes/pastanaga/extras/sidebar.less
> +}
```suggestion
}

```

2023-03-14 08:18 UTC, stevepiercy requested changes

2023-03-14 08:18 UTC, stevepiercy commented on news/4506.bugfix
> +The tabs  for the add page was unresponsive on mobile devices. Fixed this by changing flex-wrap property. @sudhanshu1309
I don't know why this was missed.

```suggestion
The tabs for the add page was unresponsive on mobile devices. Fixed this by changing flex-wrap property. @sudhanshu1309
```
```suggestion
The tabs  for the add page was unresponsive on mobile devices. Fixed this by changing flex-wrap property. @sudhanshu1309
```

2023-03-14 09:14 UTC, stevepiercy approved these changes

2023-03-14 09:14 UTC, stevepiercy commented
This needs review by a core Volto developer before merging.

2023-05-10 14:22 UTC, sneridagh approved these changes
I guess this is good to go.

2023-05-10 14:24 UTC, merged