Replace Links
plone/volto pull request #4511
Opened 2023-03-14 05:58 UTC by Tishasoumya-02

Replace links to https://training.plone.org/5/volto/index.html with https://training.plone.org/volto/index.html

2023-03-14 07:55 UTC, sudhanshu1309 commented
Pull requests must include a towncrier news item. This is a file that is placed in the root of the repository directory at /news.
https://6.docs.plone.org/volto/developer-guidelines/contributing.html#create-a-pull-request

2023-03-14 08:39 UTC, Tishasoumya-02 commented on news/#4511.bug
> +Fix urls from .plone.org/5/volto/ to .plone.org/volto/ @Tishasoumya-02
Yes @stevepiercy

2023-03-14 09:17 UTC, stevepiercy commented
Let's wait to see the response from the Volto team regarding [@ksuess's question](https://github.com/plone/training/issues/672#issuecomment-1467426883), as we are not certain about the status of the Volto training.

2023-03-14 10:49 UTC, stevepiercy requested changes

2023-03-14 10:49 UTC, stevepiercy commented on news/4511.documentation
> +Fix URLs from `training.plone.org/5/volto/` to `training.plone.org/volto/` @Tishasoumya-02
```suggestion
Fix URLs from `training.plone.org/5/volto/` to `2022.training.plone.org/volto/` @Tishasoumya-02
```

2023-03-14 10:49 UTC, stevepiercy commented on news/4511.documentation
> +Fix URLs from `training.plone.org/5/volto/` to `training.plone.org/volto/` @Tishasoumya-02
I forgot to update this as well.

2023-03-14 10:55 UTC, Tishasoumya-02 commented on packages/generator-volto/generators/app/templates/README.md
> +A training on how to create your own website using Volto is available as part of the Plone training at [https://training.plone.org/volto/index.html](https://training.plone.org/volto/index.html).
I don't know if it's only me but this https://2022.training.plone.org/volto/index.html  isn't working for me.

2023-03-14 11:24 UTC, stevepiercy commented on packages/generator-volto/generators/app/templates/README.md
> +A training on how to create your own website using Volto is available as part of the Plone training at [https://training.plone.org/volto/index.html](https://training.plone.org/volto/index.html).
It does not yet, but it is in the plan. See https://github.com/plone/training/issues/672.

We will hold merging this PR until we set up the new hostname.

2023-03-14 12:07 UTC, Tishasoumya-02 commented on packages/generator-volto/generators/app/templates/README.md
> +A training on how to create your own website using Volto is available as part of the Plone training at [https://training.plone.org/volto/index.html](https://training.plone.org/volto/index.html).
Okay Understood,will make the changes

2023-03-15 19:41 UTC, stevepiercy commented
Closing as duplicate of https://github.com/plone/volto/pull/4523

2023-03-15 19:41 UTC, closed without merging

2023-03-15 19:46 UTC, stevepiercy commented
Apologies @Tishasoumya-02, I did not realize that you and @yahya-cloud were both working on the same issue and duplicating efforts, as I am handling a flood of reviews. To prevent this in the future, it is best practice to:

- Create an issue to describe the problem
- Assign yourself to the issue, claiming it
- Submit a pull request, including the following:
  - Include "Closes #IssueNumber" in a GitHub comment to automatically close the original issue number.
  - Include the issue number in the PR's title for easy reference.
  - Include the issue number being closed in the news item.

I will also try to pay closer attention to what is actually being worked on. Thank you for both of your collaboration and contributions to Plone!