Update /5/ url and Deleted double import of a component
plone/volto pull request #4512
Opened 2023-03-14 08:04 UTC by yahya-cloud

Updated the url as suggested in plone/training issue [#740](https://github.com/plone/training/issues/740) and also deleted double import of single component

2023-03-14 08:49 UTC, stevepiercy commented
We need to wait to a response to [@ksuess's question](https://github.com/plone/training/issues/672#issuecomment-1467426883) to determine the status of the Volto training and whether this is the best link to use going forward.

2023-03-14 09:30 UTC, stevepiercy requested changes

2023-03-14 09:30 UTC, stevepiercy commented on news/4512.documentation
> +Deleted second import and fixed training urls
Give yourself credit!

```suggestion
Deleted second import and fixed training URLs. @yahya-cloud

```

2023-03-14 15:20 UTC, yahya-cloud commented
@stevepiercy if I'm correct this training is archived right and it'll be  https://training.plone.org/5/ to https://2022.training.plone.org/

2023-03-14 21:40 UTC, stevepiercy requested changes

2023-03-14 21:40 UTC, stevepiercy commented on packages/generator-volto/generators/app/templates/README.md
> +A training on how to create your own website using Volto is available as part of the Plone training at [https://2022.training.plone.org/volto/index.html](https://2022.training.plone.org/volto/index.h
I apologize for the last-minute change of plans. We decided that the default Volto training should be the following.

```suggestion
[Volto Hands-On](https://training.plone.org/voltohandson/index.html) is a training on how to create your own website.
```

2023-03-15 07:36 UTC, yahya-cloud commented
thank you for help, I've made the requested changes can you please check

2023-03-15 12:30 UTC, stevepiercy approved these changes

2023-03-15 12:35 UTC, stevepiercy commented
@yahya-cloud I think that you need to open a PR in the `plone/volto` repo, instead of from your fork, to run all the required CI builds. This PR cannot be merged until all the GitHub Actions pass.

2023-03-15 13:33 UTC, yahya-cloud commented
thank you for your help this far, i have opened the new PR [#4523](https://github.com/plone/volto/pull/4523)

2023-03-15 18:04 UTC, davisagli commented
Closing this PR since it was replaced by #4523

2023-03-15 18:04 UTC, closed without merging