3553 datetime value
plone/volto pull request #4516
Opened 2023-03-14 15:40 UTC by tedw87

https://github.com/plone/volto/issues/3553
Formated the UTC timezone to local time in `DatetimeWidget` view component.

2023-03-14 17:44 UTC, tiberiuichim requested changes
moment should be injected as a lazy library

2023-03-15 10:39 UTC, sneridagh commented
@tedw87 can't be done with vanilla JS?

https://dockyard.com/blog/2020/02/14/you-probably-don-t-need-moment-js-anymore

2023-03-17 18:56 UTC, erral commented
I haven't tested if the implementation fulfills this but either we go with moment or vanilla JS, please be aware that user's browser locale and application's locale do not always match.

I can have my browser in Spanish but browse an English page and expect dates to be in English locale.

2026-05-21 09:48 UTC, avoinea commented
I think this is obsolete. Closing.

2026-05-21 09:48 UTC, closed without merging

2026-05-21 10:05 UTC, avoinea commented
Fixed by #8236