Support RelationList field with StaticCatalogVocabulary and SelectWidget.
plone/volto pull request #4614
Opened 2023-03-25 15:37 UTC by ksuess

2023-03-25 15:46 UTC, ksuess commented
How To:
https://deploy-preview-4614--volto.netlify.app/recipes/widget.html#relation-fields

2023-03-25 16:01 UTC, ksuess commented
Please test with https://github.com/plone/plone.restapi/pull/1605

2023-03-25 19:29 UTC, stevepiercy requested changes
A few enhancements, grammar and spelling fixes, and suggestions.

I am not sure if I got the introductory descriptions of each relation field exactly correct. Feel free to revise them to be more accurate.

2023-03-25 19:29 UTC, stevepiercy commented on docs/source/recipes/widget.md
> +## Relation fields
Section headings without narrative text should be avoided. They should either:

- have introductory general text describing their sub-sections, or
- be removed and their sub-sections demoted.

2023-03-25 19:29 UTC, stevepiercy commented on docs/source/recipes/widget.md
> +Relation field with named `StaticCatalogVocabulary`and `Select` widget:
```suggestion
The following example is a single relation choice field with the named vocabulary of `StaticCatalogVocabulary` as a `Select` widget:
```

2023-03-25 19:29 UTC, stevepiercy commented on docs/source/recipes/widget.md
> +This allowes the relations control panel to respect the defined restrictions to potential relation targets.
```suggestion
This allows the {guilabel}`relations` control panel to respect the defined restrictions to potential relation targets.
```

2023-03-25 19:29 UTC, stevepiercy commented on docs/source/recipes/widget.md
> +
```suggestion
```

2023-03-25 19:29 UTC, stevepiercy commented on docs/source/recipes/widget.md
> +
```suggestion
```

2023-03-25 19:29 UTC, stevepiercy commented on docs/source/recipes/widget.md
> +The directive is by now default and can be ommitted.
```suggestion
By following this guidance, the directive is set by default and can be omitted as shown below.
```

2023-03-25 19:29 UTC, stevepiercy commented on docs/source/recipes/widget.md
> +Multi relation field with named `StaticCatalogVocabulary`and `Select` widget:
```suggestion
Similar to {ref}`single-relation-field-label`, the following example is a multi relation choice field with the named vocabulary of `StaticCatalogVocabulary` as a `Select` widget:
```

2023-03-25 19:29 UTC, stevepiercy commented on docs/source/recipes/widget.md
> +
```suggestion

(single-relation-field-label)=

```

2023-03-25 19:29 UTC, stevepiercy commented on docs/source/recipes/widget.md
> +
```suggestion

(multi-relation-field-label)=

```

2023-03-27 06:27 UTC, stevepiercy requested changes
Nice revision. This is much clearer. Minor spelling and grammar fixes, and the docs are good to go. Thank you!

2023-03-27 06:27 UTC, stevepiercy commented on docs/source/recipes/widget.md
> +A relation field is either a single relation field to hold at most one content object, `RelationChoice`, or a multi relation field `RelationList`, that can hold more than one content object.
```suggestion
A relation field is either a single relation field to hold at most one content object, `RelationChoice`, or a multi relation field, `RelationList`, that can hold more than one content object.
```

2023-03-27 06:27 UTC, stevepiercy commented on docs/source/recipes/widget.md
> +The restriction on content types, workflow states, e.a. can be done with a `StaticCatalogVocabulary`.
```suggestion
The restriction on content types, workflow states, and so on can be done with a `StaticCatalogVocabulary`.
```

2023-03-27 06:27 UTC, stevepiercy commented on docs/source/recipes/widget.md
> +There are other vocabulary types and other widgets like the `ObjectBrowser` widget.
```suggestion
There are other vocabulary types and other widgets, including the `ObjectBrowser` widget.
```

2023-03-27 06:27 UTC, stevepiercy commented on docs/source/recipes/widget.md
> +Therefore the directive can be ommitted.
```suggestion
Therefore the directive can be omitted.
```

2023-03-27 06:27 UTC, stevepiercy commented on docs/source/recipes/widget.md
> +Therefore the directive can be ommitted.
```suggestion
Therefore the directive can be omitted.
```

2023-03-27 07:54 UTC, stevepiercy approved these changes
Docs approved. Code should be reviewed by a core maintainer.

2023-03-27 08:11 UTC, tiberiuichim approved these changes
Awesome work @ksuess !

2023-03-31 11:09 UTC, sneridagh approved these changes
LGTM! Awesome work @ksuess !!! Very much needed!

I'll merge as soon we have a release in p.restapi. I'll push for it.

2023-04-11 15:26 UTC, merged