3092 improve spellcheck
plone/volto pull request #4633
Opened 2023-04-01 16:27 UTC by utkkkarshhh

improved spellcheck and consistency for spelling by adding "NodeJS and JavaScript" to "accept.txt" and others in "reject.txt"

2023-04-01 16:27 UTC, mister-roboto commented
@utkkkarshhh you need to sign the Plone Contributor Agreement to merge this pull request. 

Learn about the Plone Contributor Agreement: https://plone.org/foundation/contributors-agreement

2023-04-01 17:23 UTC, utkkkarshhh commented
How to add entry in Changelog verifier? Also i've already sent an email with Plone Contributors Agreement to agreements@plone.org.

2023-04-01 21:12 UTC, stevepiercy commented
@utkkkarshhh for change log see https://6.docs.plone.org/volto/developer-guidelines/contributing.html#create-a-pull-request

A human will review your PCA and notify you when you are approved within a few business days. Please post a comment here when you are approved. Thank you!

2023-04-02 05:28 UTC, mister-roboto commented
@utkkkarshhh you need to sign the Plone Contributor Agreement to merge this pull request. 

Learn about the Plone Contributor Agreement: https://plone.org/foundation/contributors-agreement

2023-04-02 05:30 UTC, mister-roboto commented
@utkkkarshhh you need to sign the Plone Contributor Agreement to merge this pull request. 

Learn about the Plone Contributor Agreement: https://plone.org/foundation/contributors-agreement

2023-04-03 09:43 UTC, utkkkarshhh commented
I've been added as a contributor to the Plone Organisation.

2023-04-03 09:51 UTC, stevepiercy requested changes

2023-04-03 09:51 UTC, stevepiercy commented on news/3092.documentation
> +Added JavaScript and NodeJS to "styles\Vocab\Plone\accept.txt" and "Javascript, js, javascript, nodejs and node" to "styles\Vocab\Plone\reject.txt" to improve spellcheck and consistency of spellings.
Brevity is better. Also give yourself credit!

```suggestion
Added `JavaScript` and `NodeJS` as accepted spellings, and deviations of them as rejected spellings. @utkkkarshhh
```

2023-04-03 10:11 UTC, stevepiercy approved these changes

2023-04-03 10:12 UTC, stevepiercy commented
Thank you @utkkkarshhh. I will merge as soon as the jobs all pass.

2023-04-03 10:20 UTC, merged

2023-04-03 10:21 UTC, stevepiercy commented
@utkkkarshhh if you would like to ensure that this change also gets imported into the main documentation, would you please submit a PR in https://github.com/plone/documentation?