fixed the issue #4660 - shouldn't use a hook like function name for a variable
plone/volto pull request #4693
Opened 2023-04-13 15:48 UTC by Kaku-g

changed the name of the variable from hook like function name  to normal variable name.

2023-05-06 09:29 UTC, sneridagh commented
@Kaku-g thanks for the contribution, but I don't think it's relevant issue for now.

2023-05-06 16:54 UTC, davisagli commented
@sneridagh It was in response to an issue Tiberiu opened -- should we close #4660 as well?

2023-05-09 13:25 UTC, sneridagh commented
@davisagli Uh, I missed that Tiberiu was asking for it... in that case, let's consider it again.

2023-05-09 13:27 UTC, sneridagh requested changes
@Kaku-g It needs a Towncrier changelog entry too. Thanks!

2023-05-10 12:55 UTC, Kaku-g commented
@sneridagh done the requested changes!

2023-05-10 14:01 UTC, Kaku-g commented on packages/volto-slate/src/blocks/Text/SlashMenu.jsx
> +  const allowedBlockSection  = !isEmpty(allowedBlocks);
Updated the required changes

2023-05-23 16:46 UTC, sneridagh approved these changes

2023-05-23 16:46 UTC, merged