feat(Url.js): add getFieldURL helper function to get the url value of a field based on its structure
plone/volto pull request #4731
Opened 2023-04-26 15:39 UTC by razvanMiu

https://github.com/plone/volto/issues/2252

This pr adds a simple helper function that can be used to get the url of a field.
The field can have the following structures:

I.
```
buttonLink: {
   url: '/some/path'
}
```

II.
```
buttonLink: {
  "@id": '/some/path'
}
```

III.
```
buttonLink: {
   "@type": "URL",
   value: '/some/path'
}
```

It is meant to be used alongside a new deserialization method of URL type fields, like this one from here https://github.com/plone/plone.restapi/pull/1595.

2023-05-06 09:05 UTC, sneridagh requested changes
LGTM, but please add some unit tests for the new helper. Thanks!

2023-05-26 14:05 UTC, razvanMiu commented
@sneridagh I added unit tests, can you take a look now?

2023-06-16 12:34 UTC, avoinea approved these changes

2023-07-19 09:39 UTC, sneridagh approved these changes

2023-07-19 09:39 UTC, merged