added documentation regarding the static middleware #4518
plone/volto pull request #4736
Opened 2023-05-04 18:25 UTC by BhardwajAditya-github

Added documentation of static middleware

2023-05-05 00:30 UTC, stevepiercy requested changes
Thank you! This looks good.

My suggestions and questions pertain only to English and MyST grammar, formatting, syntax, and style.

A core contributor should also review the content for accuracy.

2023-05-05 00:30 UTC, stevepiercy commented on docs/source/recipes/express.md
>  visited and it will return the simple string and not the usual Volto pages.
These two lines must be placed immediately after the code example that it references.

2023-05-05 00:30 UTC, stevepiercy commented on docs/source/recipes/express.md
> +## Static Middleware
Docs style is to use "sentence case" for headings.

```suggestion
## Static middleware
```

2023-05-05 00:30 UTC, stevepiercy commented on docs/source/recipes/express.md
> +The `setHeaders()` function is used to update the response headers for a file. It takes the path of the file being served as an argument and adds the response headers to that file. It uses the `confi
One sentence per line, and some punctuation.

```suggestion
The `setHeaders()` function is used to update the response headers for a file.
It takes the path of the file being served as an argument, and adds the response headers to that file.
It uses the `config` object specified in `config.settings.serverConfig.staticFiles` to determine which response headers should be added to the file.
```

2023-05-05 00:30 UTC, stevepiercy commented on docs/source/recipes/express.md
> +- `headers`: an object containing the headers added if the match is successful.
Convert this to a [definition list](https://myst-parser.readthedocs.io/en/latest/syntax/typography.html#definition-lists-and-glossaries).

```
`id`
: a string identifier for the static file rule

`match`
: a regular expression that evaluates the path of the requested resource

`headers`
: an object containing the headers added if the match is successful
```

2023-05-05 00:30 UTC, stevepiercy commented on docs/source/recipes/express.md
> +To add response header Cache-Control: public, max-age=3600 to a file named styles.css located in BUILD_DIR/PUBLIC directory:
```suggestion
The following example shows how to add the response header `Cache-Control: public, max-age=3600` to a file named {file}`styles.css` located in the `BUILD_DIR/PUBLIC` directory:
```

2023-05-05 00:30 UTC, stevepiercy commented on docs/source/recipes/express.md
> +
```suggestion
```

2023-05-05 00:30 UTC, stevepiercy commented on docs/source/recipes/express.md
> +
```suggestion
```

2023-05-05 00:30 UTC, stevepiercy commented on docs/source/recipes/express.md
> +    ...,{
This code example should be run through whatever JavaScript linter Volto uses. I think this example would be reformatted.

2023-05-05 00:30 UTC, stevepiercy commented on docs/source/recipes/express.md
> +Current default rules add headers per browser cache of 365 days for resources under the `/static` path and 60 seconds for the others
```suggestion
The default rules add headers that set the browser cache to 365 days for resources under the `/static` path and 60 seconds for all other paths.
```

2023-05-05 13:28 UTC, BhardwajAditya-github commented on docs/source/recipes/express.md
> +The `staticMiddleware` is for serving static files (such as stylesheets and client-side JavaScript files) in the `BUILD_DIR/PUBLIC` or `PUBLIC_DIR` directory. It uses the `express.static()` function
```js
import { settings as defaultSettings } from '@plone/volto/config';
import express from 'express';

const settings = { ...defaultSettings };

if (__SERVER__) {
    const customStaticMiddleware = express.static('test/static/files');

    function setCustomHeaders(req, res, next) {
        res.setHeader('Cache-Control', 'public, max-age=3600');
        next();
    }

    customStaticMiddleware.setHeaders = setCustomHeaders;
    customStaticMiddleware.id = 'custom-static-middleware';

    settings.expressMiddleware = [
        ...defaultSettings.expressMiddleware,
        customStaticMiddleware,
    ];
}
```
I am not sure if this is correct. Please confirm

2023-05-05 21:25 UTC, stevepiercy commented on docs/source/recipes/express.md
> +The `staticMiddleware` is for serving static files (such as stylesheets and client-side JavaScript files) in the `BUILD_DIR/PUBLIC` or `PUBLIC_DIR` directory. It uses the `express.static()` function
@sneridagh @nileshgulia1 @ksuess or any other qualified person could we get a review of this Express middleware code example?

2023-05-05 21:30 UTC, stevepiercy approved these changes
Thanks for making the changes. I approve the English and MyST syntax and style fixes.

We need a maintainer or other qualified person to review the code example and the rest of the content for accuracy, and then we can merge it.

2023-05-05 21:31 UTC, stevepiercy commented
Oops, this PR needs a towncrier entry. See https://6.docs.plone.org/contributing/index.html#change-log-entry

2023-05-05 23:29 UTC, stevepiercy requested changes

2023-05-05 23:29 UTC, stevepiercy commented on news/4518.documentation
> +Added documentation regarding the static middleware. @stevepiercy
Give yourself credit!

```suggestion
Added documentation regarding the static middleware. @BhardwajAditya-github
```

2023-05-05 23:38 UTC, stevepiercy approved these changes

2023-05-06 08:31 UTC, sneridagh commented on docs/source/recipes/express.md
> +The `staticMiddleware` is for serving static files (such as stylesheets and client-side JavaScript files) in the `BUILD_DIR/PUBLIC` or `PUBLIC_DIR` directory. It uses the `express.static()` function
LGTM, maybe we can add this piece of code to the docs too.

2023-05-06 08:31 UTC, sneridagh reviewed
LGTM overall, let's add the code sample to the docs as well and it's mergeable.

2023-05-09 13:14 UTC, sneridagh approved these changes

2023-05-09 13:14 UTC, merged