feat(slate): Add css identifier to slate style menu options
plone/volto pull request #4847
Opened 2023-06-06 13:23 UTC by razvanMiu

Closes #4846

2023-06-06 13:36 UTC, avoinea approved these changes

2023-06-06 20:41 UTC, stevepiercy requested changes
Minor tweak on the news item. Keep in mind that these news items get automatically converted to documentation, thus the nitpicking formality.

2023-06-06 20:41 UTC, stevepiercy commented on news/4846.feature
> +Add css identifier to slate style menu options @razvanMiu
```suggestion
Added a CSS identifier to the Slate style menu options. @razvanMiu
```

2023-06-09 10:23 UTC, sneridagh approved these changes

2023-06-09 10:23 UTC, merged