Logout Refactor
plone/volto pull request #4860
Opened 2023-06-09 13:28 UTC by Tishasoumya-02

2023-06-19 07:18 UTC, nileshgulia1 commented on cypress/tests/core/basic/logout.js
> +    cy.get('#toolbar-logout').click();
Maybe just assert if we have `auth_token`? 
https://docs.cypress.io/api/commands/getcookie

2023-06-19 07:37 UTC, nileshgulia1 commented on src/components/theme/Logout/Logout.jsx
> +    if (token) {
You can split this into a different useEffect to keep it straightforward and separate concerns.

2023-06-19 07:42 UTC, nileshgulia1 commented on src/components/theme/Logout/Logout.jsx
> +  purgeMessages: PropTypes.func.isRequired,
Unnecessary props?

2023-06-19 07:42 UTC, nileshgulia1 commented on src/components/theme/Logout/Logout.test.jsx
> +            purgeMessages={purgeMessages}
https://github.com/plone/volto/pull/4860/files#r1233651508

2023-06-19 09:39 UTC, JeffersonBledsoe requested changes
@Tishasoumya-02 Could we get a test/ include as part of one of the tests you have written already a check for the `returnUrl` feature of this component?

2023-06-19 10:24 UTC, Tishasoumya-02 commented
Sorry @JeffersonBledsoe  , I am not able to understand

2023-06-19 10:33 UTC, JeffersonBledsoe commented
> Sorry @JeffersonBledsoe , I am not able to understand

@Tishasoumya-02 Your current code looks like this:

```jsx
useEffect(() => {
    dispatch(logout());
    dispatch(purgeMessages());
});
```

This code means that the effect will run every time the component renders (more info in the [React docs for useEffect](https://react.dev/reference/react/useEffect#useeffect)). You probably want something like this which has the array of dependencies for the effect: 

```jsx
useEffect(() => {
    dispatch(logout());
    dispatch(purgeMessages());
}, [dispatch]);
```

While it's unlikely that this component will be around long enough for the effect to run multiple times, it is a possibility(and is even something [React will do in dev mode](https://react.dev/reference/react/StrictMode#fixing-bugs-found-by-double-rendering-in-development)).

2023-06-24 10:02 UTC, nileshgulia1 commented on src/components/theme/Logout/Logout.jsx
> +import { useToken } from '@plone/volto/hooks/userSession/useToken';
```suggestion
import { useToken } from '@plone/volto/hooks';
```

2023-06-26 06:13 UTC, nileshgulia1 approved these changes

2023-06-26 06:39 UTC, nileshgulia1 requested changes

2023-06-26 06:39 UTC, nileshgulia1 commented on src/components/theme/Logout/Logout.jsx
> +    if (token) {
!token?

2023-08-14 07:18 UTC, nileshgulia1 requested changes

2023-08-14 07:18 UTC, nileshgulia1 commented on src/hooks/userSession/useToken.js
> +export function useToken() {
I see you are accessing directly from redux state in your component. We can remove this!

2023-08-14 07:38 UTC, Tishasoumya-02 commented on src/hooks/userSession/useToken.js
> +export function useToken() {
Yes sure, I might have missed it

2023-08-24 15:54 UTC, sneridagh approved these changes

2023-08-24 15:54 UTC, merged