Refactor Register
plone/volto pull request #4861
Opened 2023-06-09 15:09 UTC by Tishasoumya-02

2023-06-19 09:59 UTC, nileshgulia1 commented on src/components/theme/Register/Register.jsx
> +    message: PropTypes.string,
You can remove these propTypes.

2023-06-19 10:00 UTC, nileshgulia1 commented on src/components/theme/Register/Register.jsx
> +export default compose(withRouter)(Register);
withRouter will be deprecated in react-router v6 in favour of useLocation , useHistory hooks. I think we should refrain from using it.

2023-06-19 10:01 UTC, nileshgulia1 commented on src/components/theme/Register/Register.test.jsx
> +          <Register createUser={createUser} loaded={false} loading={false} />
same as in https://github.com/plone/volto/pull/4861/files#r1233820804

2023-06-19 10:02 UTC, nileshgulia1 requested changes
Let's fix the comments.

2023-06-26 06:18 UTC, nileshgulia1 commented on src/components/theme/Register/Register.jsx
>  import { Helmet } from '@plone/volto/helpers';
Please fix this import.

2023-07-08 16:38 UTC, JeffersonBledsoe commented
@Tishasoumya-02 The refactor looks good here, but the actual component seems like it was broken before refactoring.
It is unable to actually succeed in a form submission due to the backend call return an error as the form doesn't send a `password` value or the `sendPasswordReset` option. If you could write a test that should pass (i.e. the form sends successfully and the toast appears) but actually fails that would be great and we can go from there on getting this merged.

cc @sneridagh @nileshgulia1 For visibility

## Returned error

```
{
  "error": {
    "errors": [
      {
        "field": "username", 
        "message": "Property 'User Name' is required."
      }, 
      {
        "field": "sendPasswordReset", 
        "message": "You have to either send a password or sendPasswordReset."
      }
    ], 
    "message": "Error in fields. Property 'User Name' is required. You have to either send a password or sendPasswordReset.", 
    "type": "WrongParameterError"
  }
}
```

2023-08-14 07:46 UTC, nileshgulia1 approved these changes
I approve it on the context of refactor. We still have to take care of original fix, maybe in a different PR?

2024-07-26 01:33 UTC, JeffersonBledsoe commented
@plone/volto-team Updated to the lastest main. Happy for this to be merged?

2024-08-05 06:08 UTC, ichim-david commented on packages/volto/news/4861.feature
> +Refactor Register Component -@Tishasoumya-02
@Tishasoumya-02 you will need for your other pull requests to modify the changelog.

In summary, the changelog needs to have two characteristics:
1. a bit more information as Refactor Component isn't enough to say what was refactored
2. The changelog ends with a period and not a dash.

This is my proposal, @stevepiercy what do you think about my proposal? Anything you would add?

2024-08-05 06:40 UTC, stevepiercy commented on packages/volto/news/4861.feature
> +Refactor Register Component -@Tishasoumya-02
I edited it for grammar and to be concise.

2024-08-05 09:30 UTC, stevepiercy approved these changes

2024-08-05 09:38 UTC, stevepiercy commented
I restarted failed checks, which I think are flaky.

I also created a new issue from @JeffersonBledsoe's comment in https://github.com/plone/volto/issues/6233.

This PR is concerned only with refactoring.

2024-08-05 18:58 UTC, stevepiercy commented
@Tishasoumya-02 I'm not clear what that error has to do with this PR. Can you elaborate?

Also please [do not paste images of error messages](https://meta.stackoverflow.com/questions/285551/why-should-i-not-upload-images-of-code-data-errors). Paste the entire text into a comment surrounded by triple backticks to format it.

````
```
error message
```
````

2024-08-07 10:05 UTC, Tishasoumya-02 commented
Sorry for the noise ! I was getting this error every time I was trying to create a new document, after `make clean` then `make install` , it started working !

2024-08-07 10:06 UTC, Tishasoumya-02 commented
> @Tishasoumya-02 I'm not clear what that error has to do with this PR. Can you elaborate?
> 
> Also please [do not paste images of error messages](https://meta.stackoverflow.com/questions/285551/why-should-i-not-upload-images-of-code-data-errors). Paste the entire text into a comment surrounded by triple backticks to format it.
> 
> ```
> ```
> error message
> ```
> ```

Yes, will keep in mind! Thanks :)

2024-08-13 00:37 UTC, davisagli approved these changes

2024-08-13 00:38 UTC, merged