make defaultShowFacet as fallback
plone/volto pull request #4863
Opened 2023-06-12 10:10 UTC by tedw87

#4579
Use `defaultShowFacet` as a fallback for facet types.

2023-06-19 04:47 UTC, davisagli approved these changes
This looks useful.

2023-06-27 12:30 UTC, avoinea requested changes

2023-06-27 12:32 UTC, avoinea commented on src/components/manage/Blocks/Search/components/Facets.jsx
> +const defaultShowFacet = (index) => {
Hmm... :thinking:  Or maybe not :thinking:

2023-06-27 12:44 UTC, avoinea approved these changes

2023-07-16 16:12 UTC, merged