Refactor Search Widget
plone/volto pull request #4864
Opened 2023-06-13 05:12 UTC by Tishasoumya-02

2023-06-19 10:29 UTC, nileshgulia1 commented on src/components/theme/SearchWidget/SearchWidget.jsx
> +export default compose(withRouter)(SearchWidget);
Ref: https://github.com/plone/volto/pull/4861#discussion_r1233822418

2023-06-26 06:28 UTC, nileshgulia1 commented on src/components/theme/SearchWidget/SearchWidget.jsx
> +const SearchWidget = ({ pathname }) => {
```suggestion
const SearchWidget = () => {
const { pathname } = useLocation() 
```

2023-06-26 06:29 UTC, nileshgulia1 commented on src/components/theme/SearchWidget/SearchWidget.jsx
> -    pathname: PropTypes.string,
W can remove the proptypes.

2023-06-26 06:29 UTC, nileshgulia1 requested changes

2023-06-26 06:29 UTC, nileshgulia1 commented on src/components/theme/SearchWidget/SearchWidget.jsx
> +  pathname: PropTypes.string.isRequired,
We can remove since its not a prop anymore.

2023-06-26 09:42 UTC, nileshgulia1 requested changes

2023-06-26 09:42 UTC, nileshgulia1 commented on src/components/theme/SearchWidget/SearchWidget.jsx
> +  const pathname = useLocation();
```suggestion
  const { pathname } = useLocation();
```

2023-07-10 11:39 UTC, nileshgulia1 commented on src/components/theme/SearchWidget/SearchWidget.jsx
> -      this.props.pathname?.length > 0
As discussed with @JeffersonBledsoe , this component cares about pathname as a prop. Hence it should be made compatible to use it instead. Also I don't see `location.pathname` used in the component, thus we don't need the fallback to `useLocation()`

2023-07-10 11:39 UTC, nileshgulia1 requested changes

2023-07-10 11:39 UTC, nileshgulia1 commented on src/components/theme/SearchWidget/SearchWidget.jsx
> +  const pathname = useLocation();
we can remove this.

2023-07-10 17:41 UTC, nileshgulia1 approved these changes
lgtm

2023-07-12 09:49 UTC, sneridagh approved these changes

2023-07-12 09:49 UTC, merged