Refactor Comment
plone/volto pull request #4874
Opened 2023-06-15 05:10 UTC by Tishasoumya-02

2023-06-19 17:20 UTC, nileshgulia1 commented on src/components/theme/Comments/Comments.jsx
> -    { addComment, deleteComment, listComments, listMoreComments },
Please remove proptypes which are not passed up in the parent and are from mapStateToProps as we are now using hooks

2023-06-26 07:28 UTC, nileshgulia1 approved these changes

2023-07-10 17:50 UTC, nileshgulia1 requested changes

2023-08-14 09:14 UTC, nileshgulia1 approved these changes

2023-08-24 16:06 UTC, sneridagh approved these changes

2023-08-24 16:06 UTC, merged