Refactor CommentEdit
plone/volto pull request #4875
Opened 2023-06-15 05:15 UTC by Tishasoumya-02

2023-06-19 17:00 UTC, nileshgulia1 commented on src/components/theme/Comments/CommentEditModal.jsx
> +  updateComment: PropTypes.func.isRequired,
updateComment proptype needs to be removed as well.

2023-06-19 17:19 UTC, nileshgulia1 requested changes

2023-06-19 17:19 UTC, nileshgulia1 commented on src/hooks/comments/useComments.js
> +  return { request };
```suggestion
  return request;
```
return just a request object not `{request: request}`

2023-06-26 07:56 UTC, nileshgulia1 approved these changes

2023-07-12 09:43 UTC, sneridagh approved these changes

2023-07-12 09:47 UTC, sneridagh approved these changes

2023-07-12 09:47 UTC, merged