Refactor Navigation
plone/volto pull request #4876
Opened 2023-06-15 05:23 UTC by Tishasoumya-02

2023-06-19 17:22 UTC, nileshgulia1 commented on src/hooks/intl/useIntls.js
> +export function useIntls() {
maybe rename it to useLang?

2023-06-19 17:28 UTC, nileshgulia1 commented on src/components/theme/Navigation/Navigation.jsx
> +  getNavigation: PropTypes.func.isRequired,
Unnecessary proptype.

2023-06-19 17:31 UTC, nileshgulia1 commented on src/components/theme/Navigation/Navigation.jsx
> +  token: null,
This needs to be removed.

2023-06-20 08:59 UTC, sneridagh requested changes
Some small changes. Let me thing about the dispatches.

2023-06-26 08:02 UTC, nileshgulia1 approved these changes

2023-07-10 18:02 UTC, nileshgulia1 approved these changes

2023-09-11 14:25 UTC, sneridagh approved these changes

2023-09-11 14:25 UTC, merged