fix back button on search block to update the search results for #4402
plone/volto pull request #4879
Opened 2023-06-15 14:31 UTC by MihaelaCretu11

2023-06-15 19:58 UTC, stevepiercy requested changes

2023-06-15 19:58 UTC, stevepiercy commented on news/4402.bugfix
> +Fix back button in the search block to execute the search by adding two useEffects that update the facets and search data based on the current URL.
Give yourself credit!

```suggestion
Fix back button in the search block to execute the search by adding two useEffects that update the facets and search data based on the current URL. @MihaelaCretu11
```

2023-06-16 07:08 UTC, mister-roboto commented
@MihaelaCretu11 you need to sign the Plone Contributor Agreement to merge this pull request. 

Learn about the Plone Contributor Agreement: https://plone.org/foundation/contributors-agreement

2023-06-27 07:55 UTC, andreiggr approved these changes

2023-06-28 14:45 UTC, erral approved these changes
Perfect, thanks! It works perfectly! 

Fixes #4402

2023-09-08 07:15 UTC, avoinea approved these changes

2023-09-12 07:27 UTC, tiberiuichim approved these changes

2023-09-12 07:39 UTC, merged