Toc responsive
plone/volto pull request #4912
Opened 2023-06-23 12:11 UTC by MihaelaCretu11

2023-06-26 10:25 UTC, MihaelaCretu11 commented
How the Table of Contents block worked before:
![before](https://github.com/plone/volto/assets/68827085/d154f1f1-7f56-4b86-aa65-7d7dba90d800)
How the Table of Contents block works now:
![after](https://github.com/plone/volto/assets/68827085/11098c5e-6ec8-4a26-811b-50ec5c9a863a)

2023-06-26 12:55 UTC, stevepiercy commented
This is so good, that it should be added to the User Manual.

https://6.docs.plone.org/volto/user-manual/blocks.html#table-of-contents-block

If possible, please see https://6.docs.plone.org/contributing/documentation/myst-reference.html#width-of-media for how to capture videos.

Please and thank you!

2023-06-28 11:04 UTC, stevepiercy requested changes
Thanks for the contribution. For embedding them, please see our guide on how to make videos usable on all devices.

https://6.docs.plone.org/contributing/documentation/myst-reference.html#video

Also for all media, width is preferred to be at 740 pixels.

https://6.docs.plone.org/contributing/documentation/myst-reference.html#width-of-media

If you are unable to use a smaller size, I will take what I can get. Thank you!

2023-06-28 23:34 UTC, stevepiercy reviewed
I would like to see one of the videos, `docs/source/_static/user-manual/blocks/table-of-contents-block-with-dropdown.mp4`, embedded into https://6.docs.plone.org/volto/user-manual/blocks.html#table-of-contents-block

It looks like the other video demonstrates a bug, but I am not sure.

2023-06-28 23:35 UTC, stevepiercy commented
There are conflicts that need to be resolved in `theme/themes/pastanaga/extras/main.less`.

2023-06-29 08:29 UTC, stevepiercy requested changes
This looks good. I have only minor MyST syntax corrections.

Indentation is necessary after the first colon for a definition list definition.

I also added an alt tag for the video.

You can see a preview: https://deploy-preview-4912--volto.netlify.app/user-manual/blocks.html#table-of-contents-block

2023-06-29 08:29 UTC, stevepiercy commented on docs/source/user-manual/blocks.md
> +: The horizontal variation also adds a dropdown button, if necessary, so the items that won't fit would be displayed in the dropdown list
```suggestion
  The horizontal variation also adds a dropdown button, if necessary, so the items that won't fit would be displayed in the dropdown list.
```

2023-06-29 08:29 UTC, stevepiercy commented on docs/source/user-manual/blocks.md
> +```{video} /_static/user-manual/blocks/table-of-contents-block-with-dropdown.mp4
````suggestion
  ```{video} /_static/user-manual/blocks/table-of-contents-block-with-dropdown.mp4
````

2023-06-29 08:29 UTC, stevepiercy commented on docs/source/user-manual/blocks.md
> +```
````suggestion
  :alt: Table of contents block with dropdown menu.
  ```
````

2023-06-29 08:55 UTC, stevepiercy approved these changes
I approve docs only. A core maintainer should review the code. Thank you! This looks great!

2023-07-16 16:31 UTC, sneridagh approved these changes

2023-07-16 16:31 UTC, sneridagh commented
@plone/ai-team can we add @MihaelaCretu11 to the developers team? Thanks!

2023-07-16 16:31 UTC, merged

2023-07-16 18:01 UTC, fredvd commented
@sneridagh @MihaelaCretu11 Sorry, I'm messing up again.  :-$

 I wanted to add a note: I have added @MihaelaCretu11 to Developers,  by accident I modify @sneridagh 's comment, and I when I try to revert my comment I've reverted the last commit :-O

But I have no clue now how I can revert my accidental revert

2023-07-16 21:30 UTC, stevepiercy commented
@fredvd perhaps not through GitHub UI, but try pulling the remote branch down and editing it locally, and so on?

2023-07-17 09:41 UTC, mauritsvanrees commented
I have removed branch `revert-4912-toc-responsive`.  Seems fine now.

BTW, there are 514 branches, with some being years old.  I am sure lots could be removed.  But if this does not bother anyone, we can leave them.