Refactor Messages
plone/volto pull request #4926
Opened 2023-06-28 05:07 UTC by Tishasoumya-02

#4460

2023-07-24 09:28 UTC, nileshgulia1 requested changes

2023-07-24 09:28 UTC, nileshgulia1 commented on src/hooks/index.js
> -export useClipboard from '@plone/volto/hooks/clipboard/useClipboard';
@Tishasoumya-02 Why did you remove this?

2023-07-24 09:28 UTC, nileshgulia1 commented on src/components/manage/Messages/Messages.jsx
> +  const onDismiss = ({ value }) => {
```suggestion
  const onDismiss = (event, { value }) => {
```

2023-08-14 09:48 UTC, nileshgulia1 approved these changes

2023-09-11 14:26 UTC, sneridagh approved these changes

2023-09-11 14:27 UTC, merged