Update Pluggables Framework Documentation
plone/volto pull request #4948
Opened 2023-07-05 11:23 UTC by Akshat2Jain

## Description:

This PR updates the documentation for the Pluggables framework to provide a clearer understanding of its capabilities and limitations. The changes aim to improve the clarity and accuracy of the information provided to developers.

## Changes Made:

Added a note highlighting that Pluggables are not compatible with server-side rendering (SSR) and are better suited for visual enhancements rather than handling critical data during the loading process.

This Pr is related to the issue #4735

2023-07-05 11:24 UTC, Akshat2Jain commented
The major change is at line no `60` .

2023-07-05 11:33 UTC, stevepiercy requested changes
Revert `html_meta` changes and some grammar fixes. Thank you!

2023-07-05 11:33 UTC, stevepiercy commented on docs/source/recipes/pluggables.md
> +    'keywords': 'Pluggables, framework, React, portal'
Revert the above changes, and configure your editor accordingly.

2023-07-05 11:33 UTC, stevepiercy commented on docs/source/recipes/pluggables.md
> +Note: It is important to note that while Pluggables are a powerful framework for enhancing component integration, they are currently not compatible with server-side rendering (SSR). They excel in pro
Use MyST syntax and one sentence per line for docs.

````suggestion
```{note}
While Pluggables are a powerful framework for enhancing component integration, they are currently not compatible with server-side rendering (SSR).
They excel in providing dynamic visual enhancements for the user interface, such as client components and widgets.
However, when it comes to handling critical data that needs to load quickly, alternative approaches may be more suitable.
```
````

2023-07-05 11:35 UTC, stevepiercy commented
@Akshat2Jain this PR needs a change log entry: https://6.docs.plone.org/contributing/index.html#change-log-entry

You can ignore the failed docs build, which should be fixed in https://github.com/plone/volto/pull/4941

2023-07-08 08:15 UTC, stevepiercy commented
@Akshat2Jain you need to merge the latest changes from `master` into this branch. There should be a button in the GitHub UI. The failing docs check will pass after you do so.

![Screen Shot 2023-07-08 at 1 14 24 AM](https://github.com/plone/volto/assets/102112/9b237b23-175a-4d8d-b482-fbee8ccd16b5)

2023-07-08 08:19 UTC, stevepiercy requested changes
A few quick and easy MyST fixes, and it is good to go!

FYI you can preview the built docs either by doing `make docs-html` or `make docs-livehtml` or looking at it in the [Netlify link in the pull request in GitHub](https://github.com/plone/volto/pull/4948#issuecomment-1621562873).

2023-07-08 08:19 UTC, stevepiercy commented on docs/source/recipes/pluggables.md
> +
Remove extra lines. A blank line causes a new paragraph.

```suggestion
```

2023-07-08 08:19 UTC, stevepiercy commented on docs/source/recipes/pluggables.md
> +
```suggestion
```

2023-07-08 08:19 UTC, stevepiercy commented on docs/source/recipes/pluggables.md
> +
```suggestion
```

2023-07-08 08:19 UTC, stevepiercy commented on docs/source/recipes/pluggables.md
> +	```
This closing fence must be at the same indentation as the opening fence.

````suggestion
```
````

2023-07-08 21:08 UTC, stevepiercy requested changes
Docs changes look good. However, I just noticed that you should restore the deleted change log entry.

[news/4932.bugfix](https://github.com/plone/volto/pull/4948/files#diff-876681cc6263aed16b184ad56486b48cd44c06efbedc27cd39f4ea3418c9d75b)

2023-07-08 21:08 UTC, stevepiercy commented on news/4932.bugfix
Do not delete change log entries. They will be removed by the release manager. Please restore this file.

2023-07-09 08:39 UTC, stevepiercy requested changes
Almost there! This tidies up the change log.

2023-07-09 08:39 UTC, stevepiercy commented on news/4932.bugfix
> +Add a marker in the props passed to `RenderBlocks` in the Grid block view @sneridagh
Remove trailing space.

```suggestion
Add a marker in the props passed to `RenderBlocks` in the Grid block view @sneridagh
```

2023-07-09 09:56 UTC, stevepiercy approved these changes
Thank you! If it is all green, then it can be merged.

2023-07-09 09:56 UTC, stevepiercy commented
@sneridagh this is docs only, and I approve. I'll let you merge and release.

2023-07-16 16:04 UTC, sneridagh approved these changes

2023-07-16 16:05 UTC, merged