Refactor PersonalTool component
plone/volto pull request #4954
Opened 2023-07-08 09:03 UTC by Tishasoumya-02

#4460

2023-07-24 17:48 UTC, nileshgulia1 approved these changes

2023-07-24 17:49 UTC, nileshgulia1 requested changes
@Tishasoumya-02 I get this error while clicking on PeronsalTools "preferences ":
```
TypeError: setPushed is not a function
push
src/components/manage/Toolbar/PersonalTools.jsx:59
  56 | }, [dispatch, userId]);
  57 | 
  58 | const push = (selector) => {
> 59 |   setPushed(true);
     | ^  60 |   props.loadComponent(selector);
  61 | };
  ```

2023-08-23 10:11 UTC, nileshgulia1 approved these changes

2023-09-19 10:41 UTC, sneridagh approved these changes

2023-09-19 10:41 UTC, merged