Refactor Blocks/Image/Edit component
plone/volto pull request #4957
Opened 2023-07-08 09:12 UTC by Tishasoumya-02

#4460

2023-07-25 07:26 UTC, nileshgulia1 commented
@Tishasoumya-02 Could you please take care of conflicts?

2023-08-07 10:17 UTC, nileshgulia1 approved these changes

2023-08-28 14:36 UTC, iFlameing commented on src/components/manage/Blocks/Image/Edit.jsx
> +                              e.preventDefault();
We should move this in seperate function.

2023-09-19 10:51 UTC, sneridagh requested changes
@Tishasoumya-02 @nileshgulia1 @iFlameing When the size is changed, the image flickers twice or three times. It does not happen in the class based. Could you please take a look? Thanks!

2024-08-12 13:57 UTC, Tishasoumya-02 commented
This component is already refactored to functional . Closing this PR.

2024-08-12 13:57 UTC, closed without merging