Refactor Blocks/LeadImage/Edit component
plone/volto pull request #4959
Opened 2023-07-08 09:16 UTC by Tishasoumya-02

#4460

2023-07-25 07:50 UTC, nileshgulia1 approved these changes

2023-07-25 07:52 UTC, nileshgulia1 commented
@Tishasoumya-02 Can you pls take care of conflicts?

2023-08-07 10:27 UTC, nileshgulia1 approved these changes

2023-08-08 09:42 UTC, nileshgulia1 approved these changes

2023-08-28 14:18 UTC, iFlameing commented on src/components/manage/Blocks/LeadImage/Edit.jsx
> +  const placeholder = useMemo(
useMemo is not needed. we are not making significant improvements in performance here.

2023-08-28 14:34 UTC, iFlameing commented
@sneridagh I am not able to test it locally because the backend is providing the data. 
@Tishasoumya-02 @nileshgulia1 can you please tell me the steps to see the lead image locally? In this way, I will be sure everything works like old ways. please!

2023-08-28 14:57 UTC, nileshgulia1 commented
> @sneridagh I am not able to test it locally because the backend is providing the data. @Tishasoumya-02 @nileshgulia1 can you please tell me the steps to see the lead image locally? In this way, I will be sure everything works like old ways. please!

@iFlameing Try to add a image in Lead image behaviour in your content-type and then add a lead image block.

2024-08-13 00:19 UTC, davisagli requested changes

2024-08-13 00:19 UTC, davisagli commented on packages/volto/src/components/manage/Blocks/LeadImage/Edit.jsx
> +const Edit = React.memo((props) => {
Remove React.memo

2024-08-13 00:19 UTC, davisagli commented on packages/volto/src/components/manage/Blocks/LeadImage/Edit.jsx
> -            })()}
The old code defined a function and called it immediately. We need to do the same thing in the new code. (This is why the snapshot changed, but it should not.)

2024-08-13 22:49 UTC, davisagli approved these changes

2024-08-13 22:49 UTC, merged