Refactor Blocks/ToC/Edit component
plone/volto pull request #4961
Opened 2023-07-08 09:20 UTC by Tishasoumya-02

#4460

2023-07-25 08:15 UTC, nileshgulia1 approved these changes

2023-07-25 09:20 UTC, nileshgulia1 approved these changes
lgtm

2023-08-28 13:23 UTC, iFlameing commented on src/components/manage/Blocks/ToC/variations/DefaultTocRenderer.jsx
> +            <a href={`#${slug}`}>{title}</a>
What is the benefit of this code?

2023-08-28 13:23 UTC, iFlameing commented on src/components/manage/Blocks/ToC/variations/HorizontalMenu.jsx
> +              <a href={`#${slug}`}>{title}</a>
same here.

2024-08-13 00:09 UTC, davisagli requested changes
I don't understand this change. I can't reproduce the error from https://github.com/plone/volto/issues/5020, and I think we want the table of contents links to still work in edit mode, if possible.

2024-09-08 02:10 UTC, davisagli commented
This was done in #6167, so I'll close the PR.

2024-09-08 02:10 UTC, closed without merging