Refactor Block/Table Cell component
plone/volto pull request #4963
Opened 2023-07-10 13:35 UTC by Tishasoumya-02

#4460

2023-08-23 17:27 UTC, nileshgulia1 requested changes

2023-08-23 17:27 UTC, nileshgulia1 commented on src/components/manage/Blocks/Table/Cell.jsx
> +    setEditorState(onChange(row, cell, editorState));
@Tishasoumya-02 It's an unnecessary state reset here. The setEditorState doesn't accept a callback like setState. You need to explicitly listen for state change inside a useEffect.

2023-08-28 07:33 UTC, nileshgulia1 commented
TODO: all other components in Blocks/Table/ should be refactor in this PR

2024-09-08 02:13 UTC, davisagli commented
This was the DraftJS-based table block, which was removed from Volto, so I'll close the PR.

2024-09-08 02:13 UTC, closed without merging