Refactor ControlPanel Aliases
plone/volto pull request #4985
Opened 2023-07-19 07:53 UTC by Tishasoumya-02

#4460

2023-08-25 10:48 UTC, nileshgulia1 commented on src/components/manage/Controlpanels/Aliases.jsx
> +    dispatch(
@Tishasoumya-02 I get duplicate calls to @aliases in /controlpanel/aliases. This is due to multiple useEffect calls. The useEffect can itself serve purpose of all lifecycle methods of class based components. In many cases, there can be one useEffect for componentDidMount and componentDidUpdate.

2023-08-25 10:52 UTC, nileshgulia1 requested changes

2023-08-25 10:52 UTC, nileshgulia1 commented on src/components/manage/Controlpanels/Aliases.jsx
> +                            <Checkbox
For some reason, the checkboxes no longer works when selecting multiple alias urls.

2023-08-25 10:52 UTC, nileshgulia1 commented on src/components/manage/Controlpanels/Aliases.stories.jsx
> +export default {
This is good. Some styles fixes would be better!


![Screenshot 2023-08-25 at 4 14 35 PM](https://github.com/plone/volto/assets/22280901/d333ec2b-fe52-4dab-af55-ca603b7fbefd)

2024-08-07 14:17 UTC, Tishasoumya-02 commented
The branch is updated with main, @JeffersonBledsoe , it's good for review

2024-08-10 04:51 UTC, davisagli approved these changes

2024-08-10 04:51 UTC, merged