fix: fixed utc problems in RecurrenceWidget
plone/volto pull request #5002
Opened 2023-07-21 09:22 UTC by giuliaghisini

Fixed utc errors in RecurrenceWidget for:

- default until date
- recurrence start date

2023-07-23 10:30 UTC, pnicolli requested changes
Is the function `getUTCDate` not used anymore with these changes? If it is not, I would also remove that. I am currently on my phone, so I don't see it easily.

2023-07-23 10:30 UTC, pnicolli commented on src/components/manage/Widgets/RecurrenceWidget/RecurrenceWidget.jsx
> +      ? moment(new Date(this.props.formData?.end)).format('YYYY-MM-DD')
Checking `formData?` with the `?` is not needed because it is already checked in the previous line.

2023-07-24 07:10 UTC, giuliaghisini commented
> 

the getUTCDate is used in componentDidUpdate

2023-08-08 07:52 UTC, pnicolli approved these changes

2023-08-08 16:18 UTC, pnicolli requested changes

2023-08-08 16:18 UTC, pnicolli commented on .env.local
> +RAZZLE_LEGACY_TRAVERSE=true
Remove this whole file. Use the `.env` name without `.local` when developing core volto.

2023-11-04 09:35 UTC, sneridagh approved these changes
Sorry, this got buried in the PR avalanche. Is it ready?

2023-11-06 08:54 UTC, giuliaghisini commented
> Sorry, this got buried in the PR avalanche. Is it ready?

yes

2023-12-21 23:41 UTC, stevepiercy commented
@giuliaghisini would you please resolve the merge conflicts?

2024-01-05 21:20 UTC, davisagli commented
@sneridagh I'm confused, this was merged for 17.x (#5555) but not for main?

2024-01-14 11:40 UTC, stevepiercy requested changes
Just suggestions on comments and news items. This still needs review from a core contributor.

2024-01-14 11:40 UTC, stevepiercy commented on packages/volto/news/5002.bugfix
> +Fixed utc problems in RecurrenceWidget
Exactly what problems are fixed?

Give yourself credit!

```suggestion
Fixed UTC problems in `RecurrenceWidget`. @giuliaghisini
```

2024-01-14 11:40 UTC, stevepiercy commented on packages/volto/src/components/manage/Widgets/RecurrenceWidget/RecurrenceWidget.jsx
> +        // let end = this.getUTCDate(this.props.formData?.end).toDate();
Commented code is evil code.

```suggestion
```

2024-01-14 11:40 UTC, stevepiercy commented on packages/volto/src/components/manage/Widgets/RecurrenceWidget/RecurrenceWidget.jsx
> +    const _start = new Date(start); //The date is already in utc from plone, so this is not necessary: this.getUTCDate(start).startOf('day').toDate();
This is more concise.

```suggestion
         // The `start` date from Plone is in UTC
        const _start = new Date(start);
```

2024-01-14 11:42 UTC, stevepiercy commented
Also per @davisagli's comment, the suggestions should be applied to the backport of this PR in https://github.com/plone/volto/pull/5555

2024-05-07 08:47 UTC, sneridagh commented
@giuliaghisini what's the status of this one? Did we merge it in 17.x but not in main? Can we push forward this one?

2024-07-01 13:06 UTC, stevepiercy commented
@giuliaghisini there's a merge conflict that needs to be resolved. I'm not sure what to do with this.

2024-07-10 08:49 UTC, giuliaghisini commented
> @giuliaghisini there's a merge conflict that needs to be resolved. I'm not sure what to do with this.

resolved

2024-07-10 09:23 UTC, stevepiercy commented
@giuliaghisini can you run lint and push? See https://6.docs.plone.org/volto/contributing/linting.html, and if the instructions are not correct, would you please let me know what needs correction so I can update them? Thank you!

2024-07-10 09:58 UTC, giuliaghisini commented
> https://6.docs.plone.org/volto/contributing/linting.html

thanks.
Done.

this command
"pnpm lint:fix"
mentioned in the docs doesn't exists. Maybe docs or package.json commands needs to be updated

2024-07-10 10:42 UTC, stevepiercy commented
Do you have pre-commit installed? I think that that will automatically run commands for you when you stage a commit. Otherwise you can look in `.lintstagedrc` to find the command:

`pnpm --filter @plone/volto lint:husky`

I have not been keeping up with the rapid changes. @sneridagh can you help out with this?

@giuliaghisini meanwhile, would you please add a [Change log entry](https://6.docs.plone.org/contributing/index.html#change-log-entry)? 

I'm also not sure why the acceptance tests failed. I restarted them.

2024-07-12 13:44 UTC, merged