Storybook views
plone/volto pull request #5086
Opened 2023-08-13 03:33 UTC by Tishasoumya-02

2023-10-03 13:09 UTC, tiberiuichim requested changes
RenderBlocks should be moved to Internal Components

2025-04-25 20:58 UTC, stevepiercy requested changes
Minor tweaks to strings. Still needs a technical review. Looks good. Thank you!

2025-04-25 20:58 UTC, stevepiercy commented on packages/volto/news/5086.feature
> +storybook of View components-@Tishasoumya
```suggestion
Add Storybook of View components. @Tishasoumya
```

2025-04-25 20:58 UTC, stevepiercy commented on packages/volto/src/components/theme/View/NewsItemView.stories.jsx
> +    data: '<p>Hello World!',
Should this have a closing p tag?

```suggestion
    data: '<p>Hello World!</p>',
```

2025-04-25 20:58 UTC, stevepiercy commented on packages/volto/src/components/theme/View/RenderBlocks.stories.jsx
> +      description: 'Patter in which block content will be placed',
```suggestion
      description: 'Pattern in which to place block content',
```

2025-04-25 20:58 UTC, stevepiercy commented on packages/volto/src/components/theme/View/SummaryView.stories.jsx
> +      description: 'Content in the page ',
```suggestion
      description: 'Content in the page',
```

2025-04-25 21:06 UTC, stevepiercy commented
@pnicolli I added this item to https://github.com/orgs/plone/projects/19.

2025-05-06 10:14 UTC, stevepiercy requested changes
Check the location of the news file. Otherwise LGTM.

2025-05-06 10:14 UTC, stevepiercy commented on packages/volto/news/5086.feature
I think this needs to be moved into `components/theme/news`.

2026-04-20 01:04 UTC, davisagli approved these changes

2026-04-20 01:04 UTC, merged