Blockmap storybook
plone/volto pull request #5090
Opened 2023-08-13 03:52 UTC by Tishasoumya-02

2023-10-03 12:53 UTC, tiberiuichim requested changes
I think "Public components" is not the proper location for this story, maybe "Internal components/Maps/" ?

2025-04-25 13:23 UTC, Tishasoumya-02 commented
@tiberiuichim @nileshgulia1 updated PR, please review!

2025-04-25 21:04 UTC, stevepiercy requested changes
Minor tweaks to text strings. Still needs a technical review. Thank you!

2025-04-25 21:04 UTC, stevepiercy commented on packages/volto/news/5090.feature
> +Storybook block/maps-@Tishasoumya
```suggestion
Add Storybook for maps block. @Tishasoumya
```

2025-04-25 21:04 UTC, stevepiercy commented on packages/volto/src/components/manage/Blocks/Maps/MapsSidebar.stories.jsx
> +      description: 'Alt text of Map',
```suggestion
      description: 'Alternative text of the map block',
```

2025-04-25 21:04 UTC, stevepiercy commented on packages/volto/src/components/manage/Blocks/Maps/MapsSidebar.stories.jsx
> +      description: 'Url of the Map',
```suggestion
      description: 'URL of the map block',
```

2025-05-06 10:12 UTC, stevepiercy approved these changes
LGTM, but still needs a technical review from @plone/volto-team

2025-05-06 10:20 UTC, stevepiercy commented
Why does mr-roboto complain about the lack of a change log entry? It's in the right place.

2025-06-14 13:56 UTC, wesleybl commented
> I think "Public components" is not the proper location for this story, maybe "Internal components/Maps/" ?

@Tishasoumya-02 @tiberiuichim  Maybe it would be better to create an area for the blocks?

`Blocks/Maps/`

Blocks have an internal part and an external part. And it would be good to group the Blocks in one place.

2025-06-22 15:57 UTC, sneridagh commented
@wesleybl I agree, let's create one. Also, in VLT I'm adding a wrapper for blocks, that even pulls the `StyleWrapper` for the blocks. @Tishasoumya-02 maybe it would be useful to backport it.

2025-06-25 12:56 UTC, Tishasoumya-02 commented
@wesleybl @sneridagh I moved this to Blocks/Maps. Also I added the BlockWrapper in packages/volto/src/stories as in VLT, if it's not the right place , where should I place this file? Also if some other feedbacks?

2025-06-25 21:55 UTC, stevepiercy commented
@Tishasoumya-02 I just started digging into configuration options for Storybook in another issue at https://github.com/plone/volto/issues/3672#issuecomment-3003794123, and I learned a few things. There are new features in v9 that I think are worth exploring, including [codePanel](https://storybook.js.org/docs/writing-docs/code-panel) to show the code that gets rendered into the widget, component and accessibility tests, and writing more narrative text with MDX. There is more configuration that we haven't even explored. See https://storybook.js.org/docs/writing-docs. As a developer, would any of these configuration options or practices be useful or burdensome?

Perhaps I should create a new issue to discuss what we want out of a Storybook, and not hijack this PR discussion?

2025-06-25 21:55 UTC, stevepiercy requested changes

2025-06-25 21:55 UTC, stevepiercy commented on packages/volto/news/5090.feature
> +Add Storybook for maps block @Tishasoumya-02
```suggestion
Add Storybook for maps block. @Tishasoumya-02
```

2025-06-26 12:13 UTC, Tishasoumya-02 commented
@stevepiercy, as far as I understood from there docs, these storybook features are mostly plug-and-play and don’t require much rewriting or refactoring to take advantage of. I could try a mini pilot to see how it fits. Some of these features are already used in VLT. Enabling MDX, autodocs and accessibility checks here could really improve how we document components and onboard others. We’d just need to make sure the right addons (like @storybook/addon-docs and @storybook/addon-a11y) are enabled — setup should be pretty straightforward.

2026-04-20 01:11 UTC, davisagli commented
This is failing with an error on the MapsSidebar story ("onChangeBlock is not a function"). And we probably need a broader effort to be consistent about storybook pages for all blocks. I'll close this since it's old.

2026-04-20 01:11 UTC, closed without merging