Selectwidget Refactor
plone/volto pull request #5094
Opened 2023-08-14 05:22 UTC by Tishasoumya-02

#4460

2023-10-07 14:58 UTC, JeffersonBledsoe commented
@Tishasoumya-02 Looks like the 'edit' and 'clear' buttons are being double-rendered. Not sure from a glance at this PR why, I'll have a deeper look later. 
<img width="413" alt="Screenshot 2023-10-07 at 4 54 47 pm" src="https://github.com/plone/volto/assets/30210785/7116c403-34ee-4ec4-8204-1f395ce99893">
<img width="441" alt="Screenshot 2023-10-07 at 4 54 58 pm" src="https://github.com/plone/volto/assets/30210785/c6865fdd-739a-4fbd-9314-97436ad37f14">

2024-09-25 17:31 UTC, nileshgulia1 requested changes
@Tishasoumya-02 The refactor PLIP(https://github.com/plone/volto/issues/4460) is in the future roadmap. Would be great if you continue some work here as well. 

Right now this component throws an error while editing the page, looks like we have infinite rendering occurring in the widget. I can look too, let me know if you need any help.

```
Sorry, something went wrong with your request 
Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.

    at SelectWidget (http://localhost:3001/static/js/Widgets.chunk.js:12874:5)
    at handleStoreChange (http://localhost:3001/static/js/client.js:173187:7)
    at InnerLoadable (http://localhost:3001/static/js/client.js:1430:34)
    at UnconnectedField (http://localhost:3001/static/js/Form.chunk.js:2361:3)
    at Field (http://localhost:3001/static/js/Form.chunk.js:2442:30)
    at injectIntl(Field)
    at InnerLoadable (http://localhost:3001/static/js/client.js:1430:34)
    at div
    at Segment (http://localhost:3001/static/js/client.js:211907:24)
    at div
    at AccordionContent (http://localhost:3001/static/js/client.js:214483:22)
    at div
    at div
    at AccordionAccordion (http://localhost:3001/static/js/client.js:214327:29)
    at Accordion (http://localhost:3001/static/js/client.js:214218:25)
    ```

2025-04-28 04:32 UTC, davisagli commented
@Tishasoumya-02 I think something went wrong when you updated this branch, because the "File changed" tab is only showing the changelog entry, and not changes in SelectWidget itself.

I wonder if it's easier to make a new branch at this point?

2025-05-14 09:47 UTC, Tishasoumya-02 commented
Yes, will close this PR and continue in a new PR

2025-05-14 09:47 UTC, closed without merging