Fix load addon translations: last addon translations wins
plone/volto pull request #5113
Opened 2023-08-23 08:14 UTC by giuliaghisini

2023-08-23 08:34 UTC, erral approved these changes
Documentation-wise, this is what I was saying.

2023-08-23 10:42 UTC, stevepiercy requested changes
Minor MyST and English syntax and grammar fixes. Otherwise looks good. Thank you!

2023-08-23 10:42 UTC, stevepiercy commented on docs/source/addons/i18n.md
>  ---
Please revert the above changes, and adjust your editor's settings not to reformat quotes.

2023-08-23 10:42 UTC, stevepiercy commented on docs/source/addons/i18n.md
> -
Please do not remove deliberate white space. It makes it easier for authors to quickly find sections. Revert.

2023-08-23 10:42 UTC, stevepiercy commented on docs/source/addons/i18n.md
> +The workflow allows you to override translations from your project scope, so the addon's translations "always win".
```suggestion
The workflow allows you to override translations from your project scope, so the add-on's translations "always win".
```

2023-08-23 10:42 UTC, stevepiercy commented on docs/source/addons/i18n.md
> +If you have multiple addons installed in your project, the translations are loaded in the order of addons definitions, so the last addon wins.
```suggestion
If you have multiple add-ons installed in your project, the translations are loaded in the order of the add-ons' definitions, so the last defined add-on wins.
```

2023-08-23 11:33 UTC, stevepiercy requested changes
One more correction, that I missed on my first pass.

2023-08-23 11:33 UTC, stevepiercy commented on docs/source/addons/i18n.md
> +If you have multiple add-ons installed in your project, the translations are loaded in the order of add-ons' definitions, so the last defined add-on wins.
Sorry, I missed this on my first pass. I approve once it is fixed. Thank you!

```suggestion
If you have multiple add-ons installed in your project, the translations are loaded in the order of your add-ons' definitions, so the last defined add-on wins.
```

2023-08-23 12:09 UTC, stevepiercy approved these changes
Thank you!

2023-08-23 14:19 UTC, sneridagh approved these changes
LGTM, but I'd like @davisagli and @danalvrz to take a look first, since they were the last that touched that the last time (I think for a similar problem).

2023-08-23 18:01 UTC, davisagli requested changes
The code fix looks right, but I'm proposing a fix to the docs.

2023-08-23 18:01 UTC, davisagli commented on docs/source/addons/i18n.md
> +If you have multiple add-ons installed in your project, the translations are loaded in the order of your add-ons' definitions, so the last defined add-on wins.
```suggestion
If you have multiple add-ons installed in your project, the translations are loaded in the order your add-ons are listed in `package.json`. If two add-ons provide different translations for the same message, then the last defined add-on wins.

When running `yarn i18n` in the context of your project, the project's own locales are processed last and can override translations from any add-on.
```

2023-08-24 11:33 UTC, stevepiercy requested changes

2023-08-24 11:33 UTC, stevepiercy commented on docs/source/addons/i18n.md
> +If you have multiple add-ons installed in your project, the translations are loaded in the order your add-ons are listed in `package.json`. If two add-ons provide different translations for the same
One more nitpick. One sentence per line, and this time I *promise* it is good to go. I apologize for my oversight.

```suggestion
If you have multiple add-ons installed in your project, the translations are loaded in the order your add-ons are listed in `package.json`.
If two add-ons provide different translations for the same message, then the last defined add-on wins.
```

2023-08-24 12:24 UTC, stevepiercy approved these changes
Thank you for your patience with me!

2023-08-24 15:21 UTC, davisagli approved these changes

2023-08-24 15:37 UTC, merged