Updated Spanish translation
plone/volto pull request #5120
Opened 2023-08-23 19:35 UTC by macagua

Updated Spanish translation for Volto

2023-08-23 20:17 UTC, erral requested changes

2023-08-23 20:17 UTC, erral commented on locales/es/LC_MESSAGES/volto.po
> +msgstr "{countofrelation} roto {countofrelation, plural, one {relación} other {relaciones}} de tipo {typeofrelation}"
las variables deben quedar igual relación y relaciones deben sustituirse por sus valores originales

2023-08-23 20:17 UTC, erral commented on locales/es/LC_MESSAGES/volto.po
> +msgstr "<ul><li>Regenerar intIds (tokens de relaciones en el catálogo de relaciones)</li><li>Reconstruir relaciones</li></ul><p>¡Consulte el registro para obtener más detalles!</p><p><b>Advertencia</
debe -> debería ?

2023-08-24 01:48 UTC, macagua commented on locales/es/LC_MESSAGES/volto.po
> +msgstr "<ul><li>Regenerar intIds (tokens de relaciones en el catálogo de relaciones)</li><li>Reconstruir relaciones</li></ul><p>¡Consulte el registro para obtener más detalles!</p><p><b>Advertencia</
Hecho con commit [ba35493]

2023-08-24 01:48 UTC, macagua commented on locales/es/LC_MESSAGES/volto.po
> +msgstr "{countofrelation} roto {countofrelation, plural, one {relación} other {relaciones}} de tipo {typeofrelation}"
Hecho con commit [ba35493]

2023-08-25 12:56 UTC, erral commented
Why do we have so many changes here? It looks like the PR is not properly rebased, right?

2023-08-25 16:08 UTC, macagua commented
@erral Only I made a ``git pull origin master`` and ``git rebase master`` at ``spanish-translation`` branch

2023-09-03 04:27 UTC, davisagli commented
@macagua @erral I rebased the PR to only include the relevant changes. I'm not sure what went wrong with your rebase before, @macagua

2023-09-03 04:27 UTC, davisagli commented
@macagua Needs a changelog entry in the news folder

2023-09-06 13:47 UTC, macagua commented
> @macagua Needs a changelog entry in the news folder

@davisagli done with [feeeea3](https://github.com/plone/volto/pull/5120/commits/feeeea3bd2ff9e182e97349d05b2f58d996ee4d1)

2023-09-07 05:16 UTC, merged

2023-09-08 09:05 UTC, sneridagh commented on locales/es/LC_MESSAGES/volto.po
> +msgstr "Cuadrícula"
@macagua Sinceramente, yo no traduciría "Grid" y lo dejaría en inglés. El término ya es suficientemente abierto a interpretaciones y creo que intentar traducirlo induce a confusiones.

@erral Qué te parece?