Fix default template for content type which contains block with schem…
plone/volto pull request #5159
Opened 2023-09-05 13:51 UTC by iFlameing

…aEnhancer.

Fixes #5158

2023-09-05 20:06 UTC, davisagli requested changes
@iFlameing This doesn't look like the right fix to me. We need to figure out why the schema enhancer breaks and fix it, not disable the enhancers.

2023-09-05 20:36 UTC, davisagli commented
@iFlameing Oh, now I understand. You are turning off schema extenders only for the block settings schema. Let me check whether this is the best place to do it, but that makes more sense.

2023-09-05 20:50 UTC, davisagli reviewed
@iFlameing I refactored so that the logic for whether to apply the enhancers is in BlockDataForm, not withVariationSchemaEnhancer. The job of withVariationSchemaEnhancer is to actually apply the enhancers, not decide whether it's appropriate to do that.

2023-09-05 21:08 UTC, davisagli commented on news/5158.bugfix
> +Fix default template for content type which contains block with schemaEnhancer. @iFlameing
```suggestion
Fix editing layout for blocks using schema enhancers. @iFlameing, @davisagli
```

2023-09-05 21:10 UTC, davisagli approved these changes
@iFlameing I also added tests. I think it's ready now.

2023-09-08 07:12 UTC, avoinea approved these changes

2023-09-08 08:04 UTC, sneridagh approved these changes

2023-09-08 08:04 UTC, merged