fixed issue-5126
plone/volto pull request #5189
Opened 2023-09-15 14:32 UTC by abhinaisai2002

Fixes the issue #5126 
Added the intended labels to the tag from the issue.
Lint :+1: 
Test :+1:

2023-09-15 14:32 UTC, mister-roboto commented
Abhinai Sai your emails are not known to GitHub and thus it is impossible to know if you have signed the Plone Contributor Agreement, which is required to merge this pull request.

Learn about the Plone Contributor Agreement: https://plone.org/foundation/contributors-agreement How to add more emails to your GitHub account: https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/adding-an-email-address-to-your-github-account

2023-09-15 14:57 UTC, mister-roboto commented
Abhinai Sai your emails are not known to GitHub and thus it is impossible to know if you have signed the Plone Contributor Agreement, which is required to merge this pull request.

Learn about the Plone Contributor Agreement: https://plone.org/foundation/contributors-agreement How to add more emails to your GitHub account: https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/adding-an-email-address-to-your-github-account

2023-09-15 15:11 UTC, mister-roboto commented
Abhinai Sai your emails are not known to GitHub and thus it is impossible to know if you have signed the Plone Contributor Agreement, which is required to merge this pull request.

Learn about the Plone Contributor Agreement: https://plone.org/foundation/contributors-agreement How to add more emails to your GitHub account: https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/adding-an-email-address-to-your-github-account

2023-09-15 16:05 UTC, abhinaisai2002 commented
@sneridagh 
Can you help me in this?

2023-09-15 16:52 UTC, sneridagh requested changes
@abhinaisai2002 If you signed alteady the contributor agreement we are good, and it can be merged.

You pushed a npm lock file, please remove it. The changelog need to be only one line, take a look at other PRs as reference. Also please read the contributor guide in plone.org.

@Wagner3UB could you please review the changes?

2023-09-15 17:08 UTC, abhinaisai2002 commented
> @abhinaisai2002 If you signed alteady the contributor agreement we are good, and it can be merged. If not, you need to follow the instructions in the contributor guide.
> 
> You pushed a npm lock file, please remove it. The changelog need to be only one line, take a look at other PRs as reference. Also please read the contributor guide in plone.org.
> 
> @Wagner3UB could you please review the changes?

I have already sign the document actually, but the error was still showing in the workflow checks

2023-09-15 17:21 UTC, abhinaisai2002 reviewed
Did the review changes, all tests were passed

2023-09-18 17:39 UTC, mister-roboto commented
Abhinai Sai your emails are not known to GitHub and thus it is impossible to know if you have signed the Plone Contributor Agreement, which is required to merge this pull request.

Learn about the Plone Contributor Agreement: https://plone.org/foundation/contributors-agreement How to add more emails to your GitHub account: https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/adding-an-email-address-to-your-github-account

2023-09-18 17:42 UTC, abhinaisai2002 commented
@stevepiercy The error is still showing even if i am a member of this organization. How to get rid of this issue,

2023-09-18 21:31 UTC, stevepiercy commented
@abhinaisai2002 it sounds like the emails on your Plone Contributor Agreement and GitHub do not match. Please follow @mister-roboto's helpful advice to resolve it.

2023-09-19 08:51 UTC, Wagner3UB commented on src/components/manage/Sharing/Sharing.jsx
> +                              }`}
Don't use "logged-in-users" as a fixed id/name; instead, use "role.id" to identify them correctly

2023-09-19 12:20 UTC, closed without merging

2023-09-20 12:39 UTC, abhinaisai2002 commented on src/components/manage/Sharing/Sharing.jsx
> +                              aria-labelledby={`make-logged-in-users-as${role.id}`}
yeah but there is no proper space at the check boxes to show the label