Icon for toolbar button "user"
plone/volto pull request #5190
Opened 2023-09-16 10:01 UTC by abhinaisai2002

Fix issue : #5119 
Changed the svg of toolbar icon to gear svg icon.

2023-09-16 10:02 UTC, mister-roboto commented
Abhinai Sai your emails are not known to GitHub and thus it is impossible to know if you have signed the Plone Contributor Agreement, which is required to merge this pull request.

Learn about the Plone Contributor Agreement: https://plone.org/foundation/contributors-agreement How to add more emails to your GitHub account: https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/adding-an-email-address-to-your-github-account

2023-09-18 05:25 UTC, abhinaisai2002 commented
@stevepiercy can you help me in this, I already signed the document

2023-09-18 06:53 UTC, stevepiercy requested changes

2023-09-18 06:53 UTC, stevepiercy commented on news/5109.feature
Please restore this file. Do not delete files from this directory. They are used to generate the change log entries by the release manager. Instead in your local repo, you should pull `master`, then merge `master` to your local branch, and finally push your local branch to GitHub.

2023-09-18 06:53 UTC, stevepiercy commented on news/5119.bugfix
> +changed the icon of toolbar to gear icon.
Always use proper English grammar and syntax, and give yourself credit in news items.

```suggestion
Changed the icon of toolbar to gear icon. @abhinaisai2002
```

2023-09-18 06:53 UTC, stevepiercy commented on src/icons/user.svg
Do not delete icons from this directory. Please restore it. They may be used elsewhere in the UI. See my comment at:

https://github.com/plone/volto/issues/5119#issuecomment-1722841188

What is the source of the gear icon? If you grabbed it from Twitter Bootstrap, do we have a license to use it? We can get in huge trouble with third parties for not following their license.

We already have an icon that looks like a gear, so you do not need to add one from wherever you got it.

Finally I don't think the issue is ready for development, and will require further discussion before any action is taken. Sorry that was not clear.

2023-09-18 06:53 UTC, stevepiercy commented
@abhinaisai2002 per https://6.docs.plone.org/contributing/index.html

> After a member of the Plone Foundation reviews and accepts your signed agreement, your GitHub account will be added to a team in the Plone GitHub organization with appropriate access. This process may take a few business days.

I see that you are now a Member of plone/contributors and Plone Foundation in you GitHub user profile.

What else do you need help with?

2023-09-18 07:01 UTC, abhinaisai2002 commented
@stevepiercy while raising a pr, the workflow is showing a error on contributor document

2023-09-18 09:06 UTC, stevepiercy commented
@abhinaisai2002 that is correct behavior. At the time you pushed the last commit, you were not approved as a member. Once you push new commits, whether in this PR or another, then the message will no longer recur.

2023-09-19 12:14 UTC, Wagner3UB commented
@abhinaisai2002 Are you sure you are working on the right issue here? The Sharing component has no relation to the users button on the sidebar.

2023-09-19 12:20 UTC, closed without merging