Normalize the shape of the image component `item` prop if it contains the serialized object after creation to match the one in the catalog.
plone/volto pull request #5266
Opened 2023-10-03 14:01 UTC by sneridagh

2023-10-03 14:38 UTC, davisagli reviewed
I think it makes sense.

2023-10-07 10:20 UTC, pnicolli requested changes

2023-10-07 10:20 UTC, pnicolli commented on src/helpers/Url/Url.test.js
> +    it('flattenScales test from serialization', () => {
```suggestion
    it('flattenScales test from the catalog', () => {
```
This is actually the catalog test

2023-10-07 10:20 UTC, pnicolli commented on src/helpers/Url/Url.test.js
> +    it('flattenScales test from catalog', () => {
```suggestion
    it('flattenScales test from serialization', () => {
```
This is actually the serialization test

2023-10-11 18:13 UTC, merged