Add note in release notes for Volto 17 final
plone/volto pull request #5281
Opened 2023-10-06 14:13 UTC by sneridagh

2023-10-06 14:24 UTC, davisagli approved these changes

2023-10-06 14:24 UTC, davisagli commented on CHANGELOG.md
> +- Add control panel for relations @ksuess
You could add a link to https://github.com/plone/volto/pull/3382

2023-10-06 18:04 UTC, stevepiercy requested changes
Some gramma and incorporate @davisagli's suggestion.

2023-10-06 18:04 UTC, stevepiercy commented on CHANGELOG.md
> +**This is a Release Notes summary of all the changes happened during the alpha stage of Volto 17.**
```suggestion
**These Release Notes summarize all the changes during the alpha stage of Volto 17.**
```

2023-10-06 18:04 UTC, stevepiercy commented on CHANGELOG.md
> +- Add control panel for relations @ksuess
```suggestion
- Added a control panel for relations. @ksuess [#3382](https://github.com/plone/volto/pull/3382)
```

2023-10-07 08:27 UTC, stevepiercy requested changes

2023-10-07 08:27 UTC, stevepiercy commented on news/5281.documentation
> +Add notice in release notes for Volto 17 final to clarify that it's a summary for all the alpha stage @sneridagh
```suggestion
Added notice in release notes for Volto 17 final to clarify that it's a summary for all changes during the alpha stage. @sneridagh
```

2023-10-07 08:27 UTC, stevepiercy commented on news/5281.documentation
> +Add missing feature for the Relations Control Panel @sneridagh
```suggestion
Added an omitted change log entry for the Relations Control Panel. @sneridagh
```

2023-10-07 08:34 UTC, merged