WIP: title change announcements using MutationObserver (needs testing)
plone/volto pull request #5288
Opened 2023-10-07 14:29 UTC by JeffersonBledsoe

2024-07-02 10:41 UTC, JeffersonBledsoe commented
@plone/volto-accessibility Could we test this / discuss the implementation?

2024-07-03 16:54 UTC, ichim-david commented
hey @JeffersonBledsoe I don't have time until the wk busy with some bugs :( I added a calendar entry so I don't forget about it :)

2024-09-24 15:09 UTC, ichim-david commented
Status report on testing the feature as part of the Salamina sprint:
1. We've tested https://volto.demo.plone.org/ navigating different urls using the keyboard
 and notice the lack of announcement that we have changed url.
 This was using VoiceOver on Mac and NVDA on Windows
2. We've tested the change on Windows and Mac and heard the announcement of the title
which worked until we played with the browser history navigation that Jeff handled today in
https://github.com/plone/volto/pull/5288/commits/86d5b6b5abc9372f0e4ad0658637801d057bc70a
3. We tested https://www.gov.uk where we heard the location change although it was challenging at times
due to the combination of browsers or screen reader technology, it was easier to hear on NVDA then VoiceOver

Tomorrow we will hopefully talk with the A11y expert that Red Turtle has asked to participate and hopefully get some
feedback also from him on this proposal.

2024-09-26 11:24 UTC, JeffersonBledsoe commented
After further discussion with an accessibility consultant at the Salamina sprint, it was concluded that the current behaviour is acceptable. Only with more user testing can we concretely decide what to do with focus and so leaving the focus where it is on page change is an acceptable behaviour for now.

2024-09-26 12:51 UTC, ichim-david requested changes
@JeffersonBledsoe you have locking changes that doesn't belong to this pull request and you also set it.only on locking.js file

2024-09-26 12:52 UTC, ichim-david commented
> @JeffersonBledsoe you have locking changes that doesn't belong to this pull request and you also set it.only on locking.js file

@JeffersonBledsoe you probably needed to change the selector to be more specific, but it.only shouldn't be there still

2024-09-26 12:52 UTC, JeffersonBledsoe commented
Good catch on the `.only`! The other changes are relevant. There are multiple alert on the page at times now so the tests that assumed there was only one need updated

2024-09-27 10:01 UTC, JeffersonBledsoe commented
@ichim-david I applied the fix we discussed at the sprint. It doesn't seem to impact anything but is a good safeguard anyway incase somebody does end up with focus on it somehow

2024-09-29 11:26 UTC, pnicolli commented on packages/volto/src/components/theme/RouteAnnouncer/RouteAnnouncer.jsx
> +  }, []);
By just looking at the code I would say that eslint should complain that this array should at least contain the `updatePage` function. Would it be possible to move it inside the `useEffect` next to `handlePop`?

2024-10-15 09:28 UTC, ichim-david approved these changes

2024-10-15 15:05 UTC, Wagner3UB approved these changes

2024-10-29 11:18 UTC, merged