Special breadcrumb in controlpanel
plone/volto pull request #5292
Opened 2023-10-07 15:10 UTC by tiberiuichim

2023-10-14 00:17 UTC, davisagli approved these changes
LGTM. Needs a towncrier entry

2023-10-16 10:19 UTC, sneridagh approved these changes

2023-10-16 10:29 UTC, tiberiuichim commented
It needs i18n work for the hardcoded breadcrumb

2023-11-27 01:13 UTC, davisagli requested changes

2023-11-27 01:13 UTC, davisagli commented on src/components/theme/Breadcrumbs/Breadcrumbs.jsx
> +    defaultMessage: 'Controlpanel',
In English this text should be "Site Setup", since that is the title shown on /controlpanel

2023-11-27 08:07 UTC, merged