(FIX): put padding so the text is not clipped
plone/volto pull request #5305
Opened 2023-10-11 07:15 UTC by dobri1408

BEFORE: 
<img width="377" alt="Captură de ecran din 2023-10-11 la 10 14 36" src="https://github.com/plone/volto/assets/50819975/a2c42f23-3bde-42be-9987-cd5b5ab297e4">

AFTER:
<img width="416" alt="Captură de ecran din 2023-10-11 la 10 13 20" src="https://github.com/plone/volto/assets/50819975/c789f7f9-e3b6-474e-bc94-ce2a4b843665">

2023-10-12 15:07 UTC, ichim-david requested changes

2023-10-12 15:07 UTC, ichim-david commented on src/components/manage/Blocks/Search/components/SelectStyling.jsx
>      paddingLeft: 0,
@dobri1408  this is redundant given that at line 34 you have padding 0

2023-10-12 15:07 UTC, ichim-david commented on src/components/manage/Blocks/Search/components/SelectStyling.jsx
>      paddingLeft: 0,
@dobri1408 this doesn't fix the fact that you can also have bottom text clipping when you use p or g
see the screenshot
![4px-2-rows-demo](https://github.com/plone/volto/assets/152852/05a7abd8-5fff-4afa-89a6-a7cc93ed15e2)

2023-10-12 16:06 UTC, dobri1408 commented
I made sure that the padding is right now. I have put an 8 px padding on all sides.

2023-10-13 07:05 UTC, dobri1408 commented
I think the best solution is to increase the height of the container as the rows of the content are growing. Because the problem is now shifted to a text of 3 lines, instead of two.  I will try to approach this solution.

2023-10-13 07:28 UTC, ichim-david commented
> I think the best solution is to increase the height of the container as the rows of the content are growing. Because the problem is now shifted to a text of 3 lines, instead of two. I will try to approach this solution.

I've seen that this fixes only 2 lines but you also have to think that it is a placeholder text, at some point, you have to keep it simple enough to be easily translatable and useful, I doubt that someone will use 3 lines of placeholder text.

2023-10-24 14:21 UTC, sneridagh approved these changes

2023-10-24 14:21 UTC, merged