[WIP] Call appyBlockDefaults from addBlock
plone/volto pull request #5320
Opened 2023-10-13 11:20 UTC by tiberiuichim

2023-10-13 11:21 UTC, tiberiuichim commented
@sneridagh @davisagli 

Here's the proposal: we add a new `.initialValue` function to the block configuration, which can be called like this:

```
    value = blocksConfig[type].initialValue({
      id,
      value,
      formData: newFormData,
    });
```

Thoughs on naming and function signature?

2023-10-13 18:51 UTC, stevepiercy requested changes
Some MyST enhancements, formatting, and grammar fixes. Thanks for the addition!

2023-10-13 18:51 UTC, stevepiercy commented on docs/source/blocks/settings.md
> +It is a common pattern to use the block configuration to allow customization of a block's behavior or to provide block-specific implementation of various Volto mechanisms. Some of these "common" opti
```suggestion
It is a common pattern to use the block configuration to allow customization of a block's behavior or to provide block-specific implementation of various Volto mechanisms.
Some of these common options are described in the following sections.
```

2023-10-13 18:51 UTC, stevepiercy commented on docs/source/blocks/settings.md
> +Returns true if the provided block data represents a value for the current block. Required for alternate default block types implementations. See also [Settings reference](/configuration/settings-ref
````suggestion
`blockHasValue` returns `true` if the provided block data represents a value for the current block.
Required for alternate default block types implementations.

```{seealso}
See also [Settings reference](/configuration/settings-reference).
```
````

2023-10-13 18:51 UTC, stevepiercy commented on docs/source/blocks/settings.md
> +A function that can be used to get the initial value for a block. It has the
```suggestion
`initialValue` is a function that can be used to get the initial value for a block.
```

2023-10-13 18:51 UTC, stevepiercy commented on docs/source/blocks/settings.md
> +following signature:
```suggestion
It has the following signature.
```

2023-10-13 18:51 UTC, stevepiercy commented on docs/source/blocks/settings.md
> +`initialValue({id, value, formData, intl}) => newFormData`
````suggestion
```jsx
initialValue({id, value, formData, intl}) => newFormData
```
````

2023-10-13 18:51 UTC, stevepiercy commented on docs/source/blocks/settings.md
> +A must-have for modern Volto blocks, this is a function (or directly the schema object) that returns the schema for the block data. While it's not required, having the schema defined enables the bloc
```suggestion
A must-have for modern Volto blocks, `blockSchema` is a function, or directly the schema object, that returns the schema for the block data.
Although it's not required, defining the schema enables the block to have its initial value based on the default values declared in the schema.
```

2023-10-13 18:58 UTC, davisagli commented
@tiberiuichim btw, each time you press the "commit suggestion" button, it creates a new commit that triggers all the CI workflows. You can avoid this by going to the "Files changed" tab, where you have the option to "Add suggestion to batch" and then make a single commit with multiple suggestions included.

2023-10-13 19:29 UTC, stevepiercy approved these changes
Looks pretty! https://deploy-preview-5320--volto.netlify.app/blocks/settings.html#common-block-options

2023-10-16 10:15 UTC, sneridagh approved these changes

2023-10-16 10:15 UTC, sneridagh commented
@tiberiuichim could you please add the changelog if it's ready? I would merge it right away!

2023-10-24 07:18 UTC, sneridagh commented
@tiberiuichim ping!

2023-10-25 07:40 UTC, merged