Move some files around
plone/volto pull request #5334
Opened 2023-10-24 08:33 UTC by tiberiuichim

2023-10-24 19:13 UTC, stevepiercy commented on docs/source/guides/contextnavigation.md
This file contains both guide and reference material. The list of parameters might belong in a separate reference file. What do you think?

2023-10-24 20:42 UTC, stevepiercy commented on docs/source/guides/express.md
This file has some `config.settings` that might need to be moved into `configuration/settings-reference.md`.

2023-10-24 20:44 UTC, stevepiercy commented on docs/source/guides/express.md
Also there are two different settings keys, and I am not sure whether that is correct:

- `config.settings.serverConfig.staticFiles`
- `config.settings.staticFiles`

2023-10-24 20:57 UTC, stevepiercy requested changes
This is a good start. I made a couple of comments and suggestions. For this first pass, I think moving the files with only a few changes, such as moving chunks of content into a possibly more appropriate place and fixing errors and warnings, is a good strategy. Thank you!

2023-10-24 20:57 UTC, stevepiercy commented on docs/source/guides/ie11compat.md
I think this should be deleted as we don't want to support an EOLed browser, as of 2022-06-15.

2023-10-24 20:57 UTC, stevepiercy commented on docs/source/guides/index.md
> +ie11compat
Buh-bye!

```suggestion
```

2023-10-24 20:57 UTC, stevepiercy commented on docs/source/reference/environment-variables.md
This page actually is a how-to guide, not a reference.

Also let's insert missing MyST `html_meta` stuff.

```markdown
---
myst:
  html_meta:
    "description": "How to use environment variables in Volto"
    "property=og:description": "How to use environment variables in Volto"
    "property=og:title": "How to use environment variables in Volto"
    "keywords": "Volto, Plone, frontend, React, environment variables"
---

```

2023-11-04 08:13 UTC, sneridagh commented
@stevepiercy your comments on this one are more headed to do more in-depth changes (more than just moving some files around). Shouldn't we do this in the other long-lived branch/PR? I'm concerned that we don't step on each other in separated PRs.

2023-11-04 16:29 UTC, stevepiercy commented
@sneridagh this _is_ the long-lived branch. Although these changes would be good to backport to main, too.

2023-11-04 16:34 UTC, stevepiercy commented on docs/source/guides/ie11compat.md
One more thing to consider, although we are hesitant to say what browsers we _do_ support, this would be an example of what we do _not_ support. This would be good to mention in requirements and support policies.

"Volto does not support technologies that are in end-of-life (EOL) or otherwise no longer supported by their maintainers."

2023-11-07 09:51 UTC, stevepiercy commented on docs/source/guides/ie11compat.md
See https://github.com/plone/volto/issues/5380

2023-11-07 09:56 UTC, stevepiercy commented on docs/source/reference/environment-variables.md
OK to leave it where it is, and later extract the guide stuff into a guide.

2023-11-07 09:58 UTC, merged