Release Management Notes
plone/volto pull request #5358
Opened 2023-11-03 11:47 UTC by sneridagh

Definition of breaking

2023-11-03 12:02 UTC, stevepiercy requested changes
Some spelling, grammar, syntax, and style guide improvements.

2023-11-03 12:02 UTC, stevepiercy commented on docs/source/release-management-notes/index.md
> +Even if that upgrade implies a breaking change on itself.
```suggestion
This is true, even if that upgrade implies a breaking change in itself.

```

2023-11-03 12:02 UTC, stevepiercy commented on docs/source/release-management-notes/index.md
> +    "description": "Release Process Information"
```suggestion
    "description": "Release management notes for Volto"
```

2023-11-03 12:02 UTC, stevepiercy commented on docs/source/release-management-notes/index.md
> +    "property=og:description": "Volto Release Notes for the Plone content management system"
```suggestion
    "property=og:description": "Release management notes for Volto"
```

2023-11-03 12:02 UTC, stevepiercy commented on docs/source/release-management-notes/index.md
> +    "property=og:title": "Volto Release Notes"
```suggestion
    "property=og:title": "Volto release management notes"
```

2023-11-03 12:02 UTC, stevepiercy commented on docs/source/release-management-notes/index.md
> +# Release Management Notes
```suggestion
# Release management notes
```

2023-11-03 12:02 UTC, stevepiercy commented on docs/source/release-management-notes/index.md
> +## Definition of Breaking
```suggestion
## Definition of breaking
```

2023-11-15 08:39 UTC, stevepiercy approved these changes
LGTM. Once merged, I would add reference links to it from the PRs:

- https://github.com/plone/volto/pull/5385
- https://github.com/plone/volto/pull/5404

2023-11-23 10:48 UTC, stevepiercy commented
This file needs to be reconciled against the file `RELEASING.md` in the root of the Volto repo or monorepo before merging. See also https://github.com/plone/volto/pull/5409

2024-02-21 10:29 UTC, sneridagh commented
@tisto @mauritsvanrees It's been a while I've started to write this. What do you think? We can merge this, and continue iterating over it, but I think it's good enough for now.

2024-02-21 11:02 UTC, mauritsvanrees approved these changes
Makes sense to me.

One small suggestion on improving the wording.

2024-02-21 11:02 UTC, mauritsvanrees commented on docs/source/release-management-notes/index.md
> +So we prefer give preference to maintain a good user experience over not backporting changes that could be breaking to the product but could be beneficial for the vast majority of use cases.
"prefer give preference" is double.  I don't mind how to fix this, but this is one way:

```suggestion
So we give preference to maintain a good user experience over not backporting changes that could be breaking to the product but could be beneficial for the vast majority of use cases.
```

2024-02-21 13:19 UTC, stevepiercy commented
Should there be references to the following, explaining how all these documents complement one another?

- https://github.com/plone/volto/blob/main/RELEASING.md
- https://plone.org/download/release-schedule

2024-02-23 09:30 UTC, sneridagh commented
@stevepiercy I don't think that the first one needs to reference here.

I guess that it makes sense to have it in: https://plone.org/download/release-schedule

@mauritsvanrees what do you think?

2024-02-23 10:25 UTC, mauritsvanrees commented
> @stevepiercy I don't think that the first one needs to reference here.

Agreed.

> I guess that it makes sense to have it in: https://plone.org/download/release-schedule

Adding a link to the release schedule/policy would indeed be good.  Probably in the paragraph directly under the main 'Release management notes'

2024-02-23 10:32 UTC, stevepiercy requested changes
Here's a suggested phrase and admonition for the link.

2024-02-23 10:32 UTC, stevepiercy commented on docs/source/release-management-notes/index.md
> +
````suggestion

```{seealso}
Read the [Plone Release Schedule](https://plone.org/download/release-schedule) for details of how Volto's release management works in Plone.
```


````

2024-02-26 09:16 UTC, stevepiercy approved these changes
I pushed a commit with some grammar fixes, MyST enhancements, and cross-reference linking.

2024-02-26 10:10 UTC, stevepiercy commented on docs/source/release-management-notes/index.md
> +Any change to a control panel is a breaking change.
Addressed in https://github.com/plone/volto/pull/5358/commits/2fcdcc90fe1689574c2e60aada23c8fbd7d2f03e

2024-02-26 10:43 UTC, merged