updated npm version of node to install volto
plone/volto pull request #5401
Opened 2023-11-14 18:48 UTC by Noobham

Fixes https://github.com/plone/volto/issues/5389

- Documentation Update
- Updated required version of npm(node package manager) in README.md.

I, Shubham Kumar, agree to have this contribution published under Creative Commons 4.0 International License (CC BY 4.0), with attribution to the Plone Foundation.

2023-11-14 22:28 UTC, stevepiercy requested changes

2023-11-14 22:28 UTC, stevepiercy commented on news/5389.documentation
> +Updated npm version required for volto.org . @Noobham
npm is not Node.js. Where did you get `volto.org`?

```suggestion
Updated Node.js version required for Volto. @Noobham
```

2023-11-14 22:28 UTC, stevepiercy commented on README.md
>  - Node.js 20: Supported since Volto 17.
```suggestion
-   Node.js 20 LTS: supported since Volto 17.
```

2023-11-14 22:28 UTC, stevepiercy commented on README.md
>  - Node.js 18 (LTS): Supported since Volto 17.
```suggestion
-   Node.js 18 LTS: supported since Volto 17.
```

2023-11-14 22:28 UTC, stevepiercy commented on README.md
> +We recommend using the current LTS version.
```suggestion
We recommend using the most recent LTS version that Volto supports.
```

2023-11-15 03:13 UTC, stevepiercy approved these changes
@sneridagh this is ready for review and merge.

2023-11-15 03:15 UTC, stevepiercy commented
I don't know why the two CI jobs fail. They are totally unrelated to this PR.

2023-11-17 10:09 UTC, stevepiercy commented
CI passes now. @sneridagh

2023-11-17 10:26 UTC, sneridagh approved these changes

2023-11-17 10:26 UTC, merged