issue-5452 markdown shortcut
plone/volto pull request #5495
Opened 2023-12-05 19:24 UTC by kHAPPY2004

Fixes #5452
Fixes automarkup shortcut bug for heading and blockquote

2023-12-05 23:15 UTC, stevepiercy commented
@kHAPPY2004 do not open and close multiple pull requests for the same issue. See item 3: https://6.docs.plone.org/contributing/first-time.html#things-not-to-do

2023-12-05 23:21 UTC, stevepiercy requested changes

2023-12-05 23:21 UTC, stevepiercy commented on packages/volto-slate/news/5452.bugfix
> +Fixed markup shortcut for heading and blockquote @kHAPPY2004
What exactly was broken, and how was it fixed? Please include some details, such as what was the original broken behavior and what is the new fixed behavior. These change log entries appear in documentation upon release, so they should be helpful to a developer looking to fix a broken behavior that they observed.

2023-12-07 01:18 UTC, stevepiercy requested changes

2023-12-07 01:18 UTC, stevepiercy commented on packages/volto-slate/news/5452.bugfix
> +Fixed markup shortcut for heading and blockquote by passing 'at' to Transforms.setNodes api call for location of node @kHAPPY2004
In change log entries, we need to know only what was broken and is now fixed, not _how_ it was fixed. These are narrative entries that end up in the [Volto Release Notes](https://6.docs.plone.org/volto/release-notes/index.html) where the audience is the general public, whereas the implementation details (how you fixed something) is already explained in the code and targeted to developers only.

```suggestion
In the Slate text block, the markup shortcuts for heading and blockquote work again. @kHAPPY2004
```

2023-12-07 01:57 UTC, stevepiercy commented on packages/volto-slate/news/5452.bugfix
> +Fixed markup shortcut for heading and blockquote by passing 'at' to Transforms.setNodes api call for location of node @kHAPPY2004
I've submitted a PR that provides better guidance, with examples of good and poor change log entries at https://github.com/plone/documentation/pull/1590.

2023-12-07 09:13 UTC, stevepiercy approved these changes
I approve the change log. I'll request that a few contributors review your PR. Thank you!

2023-12-18 10:12 UTC, sneridagh commented
@kHAPPY2004 are you familiar with Cypress tests? Do you imagine to create one for the fix (and for other markdown feature)?

2023-12-18 10:14 UTC, stevepiercy commented
@kHAPPY2004 more information about Cypress, which Volto uses for [Acceptance testing](https://6.docs.plone.org/volto/contributing/acceptance-tests.html).

2023-12-18 10:16 UTC, tiberiuichim approved these changes

2023-12-18 20:23 UTC, razvanMiu approved these changes

2023-12-20 15:31 UTC, kHAPPY2004 commented
> @kHAPPY2004 are you familiar with Cypress tests? Do you imagine to create one for the fix (and for other markdown feature)?

@sneridagh     No I am not familiar with cypress yet...

2024-06-17 18:56 UTC, ichim-david commented
@sneridagh If this works and I assume it works since Tiberiu and Razvan accepted the work I think we can live with merging this fix without having a test in order to get this over with.

2024-06-18 08:20 UTC, merged