Erral sitemap main
plone/volto pull request #5503
Opened 2023-12-06 18:04 UTC by erral

Like #5185 but for `main` branch.

Merge only after #5502

2025-03-27 13:38 UTC, Narcis2005 commented
Looks like merging the main branch solved the failing tests. Needs review

2026-04-14 09:22 UTC, pnicolli commented
@erral we found this and raised awareness about this during the last volto meeting. It only makes sense to complete this and merge this I guess since it's released in v17 already. Do you think it's ready (apart from conflicts)?

2026-04-14 09:31 UTC, erral commented
wow, I had this completely forgotten, I thought that we already merged it!

Yes, if we already merged it for 17, it is ready for main too.

2026-04-14 09:31 UTC, erral commented
I will check the conflicts.

2026-05-02 17:41 UTC, erral commented
@pnicolli ready! I have rebased my changes and adjust them with the latest changes on main.

2026-05-18 10:26 UTC, pnicolli requested changes

2026-05-18 10:26 UTC, pnicolli commented on packages/volto/news/5503.feature
> +[erral]
```suggestion
Use the navroot expander to render the sitemap. @erral
```

2026-05-18 10:27 UTC, pnicolli approved these changes

2026-05-18 10:31 UTC, stevepiercy approved these changes

2026-05-18 10:59 UTC, merged

2026-05-18 14:40 UTC, Ari4ka approved these changes