Fix Typos, Add Terms, and Apply Sentence Case for Improved Documentation
plone/volto pull request #5543
Opened 2023-12-16 00:37 UTC by Sonamla1797

Title:
"Enhance Documentation Quality: Fix Typos, Add Terms, Apply Sentence Case, and Configure Styles for Microsoft Terminology"

Description:
This pull request introduces several enhancements to the documentation:

Fix Typos:

Addressed various typographical errors found in the documentation, promoting accuracy and readability.
Add Terms to Accept.txt:

Included terms in the accept.txt file that previously triggered errors during the vale checks, ensuring a smoother validation process.
Apply Sentence Case for Headings:

Adjusted all headings to use sentence case uniformly, enhancing the consistency and professionalism of the documentation.
Configure Styles for Microsoft Terminology:

Added a Microsoft folder with a .vale.ini file inside the styles directory to configure specific styles for Microsoft terminology. This helps prevent errors that occurred during the vale command execution.
These changes collectively aim to elevate the quality of the documentation and align with the project's guidelines. The addition of the Microsoft folder with a tailored .vale.ini file further refines the documentation for a more comprehensive and error-free experience.

Your feedback on these improvements is highly valued. Please review the changes, and if there are any additional adjustments or considerations, feel free to let me know. Thank you for your time and consideration!

2023-12-16 00:37 UTC, mister-roboto commented
@Sonamla1797 you need to sign the Plone Contributor Agreement to merge this pull request. 

Learn about the Plone Contributor Agreement: https://plone.org/foundation/contributors-agreement

2023-12-16 09:54 UTC, stevepiercy commented
@Sonamla1797 please read and follow [Contributing to Plone](https://6.docs.plone.org/contributing/index.html) and [First-time contributors](https://6.docs.plone.org/contributing/first-time.html). Once you receive confirmation that you have been added to the Plone Contributors team, then post a comment here to notify us that we can start a review. Thank you!

2023-12-20 09:07 UTC, Sonamla1797 commented
Hi @stevepiercy ,
Just to inform you that i have been added to the Plone contributors team would proceed with the review.
Thank you

2023-12-21 23:38 UTC, stevepiercy requested changes
Mostly use backticks ` instead of quotes around terms. Otherwise this is pretty good,

2023-12-21 23:38 UTC, stevepiercy commented on docs/source/client/actions/addons.md
All the terms should not use `"` or `'`, but backticks, to make then inline literals. For example:

```
- `addonId`: string
```

2023-12-21 23:38 UTC, stevepiercy commented on docs/source/client/actions/comments.md
Similar to other file, all the terms should not use " or ', but backticks, to make then inline literals.

2023-12-21 23:38 UTC, stevepiercy commented on docs/source/client/actions/content.md
> +- 'fullObjects:' boolean
```suggestion
- `fullObjects`: boolean
```

2023-12-21 23:38 UTC, stevepiercy commented on docs/source/client/actions/lock.md
> +- 'locktoken': string
```suggestion
- `locktoken`: string
```

2023-12-21 23:38 UTC, stevepiercy commented on docs/source/client/actions/querystringsearch.md
> +- **fullObjects**: boolean
```suggestion
- `fullObjects`: boolean
```

2023-12-21 23:38 UTC, stevepiercy commented on docs/source/client/actions/querystringsearch.md
> +    - `fullObjects: boolean`
```suggestion
    - `fullObjects`: boolean
```

2023-12-21 23:38 UTC, stevepiercy commented on docs/source/client/actions/relations.md
> +- 'onlyBroken': boolean
```suggestion
- `onlyBroken`: boolean
```

2023-12-21 23:38 UTC, stevepiercy commented on docs/source/client/actions/rules.md
> +- 'ruleId': string
```suggestion
- `ruleId`: string
```

2023-12-21 23:38 UTC, stevepiercy commented on docs/source/client/actions/transactions.md
> +    - 'transactionIds': string[]
```suggestion
    - `transactionIds`: string[]
```

2023-12-21 23:38 UTC, stevepiercy commented on docs/source/client/actions/types.md
> +- 'contentPath': string
```suggestion
- `contentPath`: string
```

2023-12-21 23:38 UTC, stevepiercy commented on docs/source/client/actions/types.md
> +- 'contentPath': string
```suggestion
- `contentPath`: string
```

2023-12-21 23:38 UTC, stevepiercy commented on docs/source/client/actions/types.md
> +- 'contentPath': string
```suggestion
- `contentPath`: string
```

2023-12-21 23:38 UTC, stevepiercy commented on docs/source/client/actions/users.md
> +- 'groupsFilter': string[]
```suggestion
- `groupsFilter`: string[]
```

2023-12-21 23:38 UTC, stevepiercy commented on docs/source/client/future-improvements.md
> +3. projects using other frameworks like Vue would need to install `@tanstack/Vue-query` anyway, so we need to have some consistency around frameworks, thus it makes sense that projects with react als
```suggestion
3. projects using other frameworks like Vue would need to install `@tanstack/vue-query` anyway, so we need to have some consistency around frameworks, thus it makes sense that projects with React also bring their own version of the dependency
```

2023-12-21 23:38 UTC, stevepiercy commented on docs/source/client/quick-start.md
> +These functions can be used in other use cases like command line helpers, scripts or programmatic tests.
```suggestion
These functions can be used in other use cases, like command line helpers, scripts, or programmatic tests.
```

2023-12-21 23:38 UTC, stevepiercy commented on styles/Vocab/Base/accept.txt
Delete this file. This is not how to configure custom words in Plone. See [Advanced Vale usage](https://6.docs.plone.org/contributing/documentation/authors.html#advanced-vale-usage).

Additionally, Vale will ignore inline literals (if you wrap them with backticks, of course), and most of these are inline literals. Additionally some of these terms should already exist, and they should always be sorted alphabetically.

2023-12-23 05:57 UTC, closed without merging