fix: dropdown popup positioning in contents page
plone/volto pull request #5571
Opened 2023-12-24 12:32 UTC by HarshitVashisht11

fix the issue #5566 

![image](https://github.com/plone/volto/assets/120767685/3eeb98bb-a514-4f57-9a84-9ef5d7025bd5)

2023-12-24 12:33 UTC, mister-roboto commented
@HarshitVashisht11 you need to sign the Plone Contributor Agreement to merge this pull request. 

Learn about the Plone Contributor Agreement: https://plone.org/foundation/contributors-agreement

2023-12-25 08:32 UTC, mister-roboto commented
@HarshitVashisht11 you need to sign the Plone Contributor Agreement to merge this pull request. 

Learn about the Plone Contributor Agreement: https://plone.org/foundation/contributors-agreement

2023-12-25 08:46 UTC, stevepiercy commented
@HarshitVashisht11 when you receive the email notifying you that you have been added to the Contributors Team, please `@` us to check and review your pull request. Thank you!

2023-12-25 09:39 UTC, sneridagh commented
All menus in Volto has to use PopperJS as in 

https://github.com/plone/volto/blob/main/packages/volto/src/components/manage/BlockChooser/BlockChooserButton.jsx#L84-L104

All other solutions are sub-par.

2023-12-26 13:44 UTC, HarshitVashisht11 commented
Could you kindly share your preferences regarding this? Specifically, should there be a gap between the content and the footer, or would you recommend adjusting the position or size of the popover ?

2023-12-26 17:49 UTC, stevepiercy commented
@HarshitVashisht11 see the demo of the JavaScript library that is used in Volto, as @sneridagh mentioned: https://popper.js.org/. It handles positioning automatically.

2023-12-27 13:56 UTC, HarshitVashisht11 commented
The popup menu is using `sementic-ui-library` so can you please tell how to use `popper-js` 
https://github.com/HarshitVashisht11/volto/edit/main/packages/volto/src/components/manage/Contents/ContentsItem.jsx#L224-L241 which is coming from https://github.com/HarshitVashisht11/volto/blob/main/packages/volto/src/components/theme/Popup/Popup.jsx

2023-12-28 02:42 UTC, stevepiercy commented
@HarshitVashisht11 if I knew off-hand, I would do it myself. 😁 I would suggest looking for examples of its implementation elsewhere in Volto such as the one provided by @sneridagh, and apply that pattern to fix the issue. I don't know why you did not follow his advice already. I hear he's a pretty smart fellow, being the maintainer of Volto. 😉

2024-01-13 06:00 UTC, HarshitVashisht11 commented
![Screenshot (227)](https://github.com/plone/volto/assets/120767685/c09d603d-0197-4b3e-a23a-e04755eb174e)
![Screenshot (226)](https://github.com/plone/volto/assets/120767685/e3e8246e-2208-4ce2-b066-9c779fa10660)
![Screenshot (225)](https://github.com/plone/volto/assets/120767685/7820607f-2d1a-4a9f-aa29-76d9c2fa6872)

2024-01-13 06:03 UTC, HarshitVashisht11 commented
I have tried to add popper js to fix the issue

2024-01-13 08:39 UTC, stevepiercy requested changes

2024-01-13 08:39 UTC, stevepiercy commented on packages/volto/news/5566.bugfix
> +Fixes the dropdwon popup positioning in contents page. @HarshitVashisht11
```suggestion
User popper.js to dynamically position the action menu in the folder contents page. @HarshitVashisht11
```

2024-01-13 08:41 UTC, stevepiercy commented
This pull request must pass all tests. See [Code quality](https://6.docs.plone.org/volto/contributing/index.html#code-quality).

Edit the issue description. See item 2 in [Create a pull request from your fork](https://6.docs.plone.org/contributing/first-time.html#create-a-pull-request-from-your-fork).

2025-01-30 16:24 UTC, ArmanKukreti commented
@stevepiercy is this issue open?

2025-01-30 22:39 UTC, stevepiercy commented
Closing PR as abandoned and not compliant with our contributing guidelines.

@ArmanKukreti this is a PR, not an issue. Please read and follow [First-time contributors](https://6.docs.plone.org/contributing/first-time.html), especially [Things not to do](https://6.docs.plone.org/contributing/first-time.html#things-not-to-do), [Contributing to Plone](https://6.docs.plone.org/contributing/index.html), and [Contributing to Volto](https://6.docs.plone.org/contributing/volto.html).

2025-01-30 22:39 UTC, closed without merging