changed type text to textarea
plone/volto pull request #5572
Opened 2023-12-24 18:06 UTC by Ravi-kumar9347

modified the field type text to textarea.

2023-12-24 19:14 UTC, stevepiercy commented
@Ravi-kumar9347 please read and follow [Change log entry](https://6.docs.plone.org/contributing/index.html#change-log-entry) and [Create a pull request from your fork](https://6.docs.plone.org/contributing/first-time.html#create-a-pull-request-from-your-fork) Item 2. We do not review pull requests until all GitHub checks pass.

2023-12-25 09:40 UTC, Ravi-kumar9347 commented on packages/volto/news/5265.bugfix
> +Changed the field type from text to textarea in comment input field by @Ravi-kumar9347
okay @stevepiercy

2023-12-25 09:47 UTC, Ravi-kumar9347 reviewed
updated

2023-12-25 10:52 UTC, stevepiercy approved these changes
Thank you! A @plone/volto-team member will need to review.

2023-12-26 18:01 UTC, Ravi-kumar9347 commented
@tiberiuichim and @sneridagh , can you check my PR once ?

2023-12-26 18:28 UTC, davisagli requested changes
@Ravi-kumar9347 Your fix here does not work.

I tested like this:
1. Go to http://localhost:8080/Plone/@@discussion-controlpanel and turn on "globally enable comments" and "enable editing of comments"
2. Back in Volto (http://localhost:3000/), add a page and make sure it has "allow discussion" set to "Yes"
3. Add a comment
4. Click the link to edit the comment

Expected: the input for editing the comment text is a textarea
Actual: it is still a single-line text input

<img width="939" alt="Screenshot 2023-12-26 at 10 24 25 AM" src="https://github.com/plone/volto/assets/49014/a95a2a98-ebce-4250-966c-c1042def905f">

In fact, all that is needed is a much simpler fix. We don't need or want a new `type`; you just need to set `widget: 'textarea'` on the `text` field in the CommentEditModal schema.

2023-12-26 20:20 UTC, Ravi-kumar9347 commented
@davisagli, i am new to the open source, so can you please help me the exact path of above image. because i only see this image. where can i find that comment sectoin.
![Screenshot from 2023-12-27 01-49-01](https://github.com/plone/volto/assets/126487842/2f949155-38bf-41cf-a0bb-5665c3a650bf)

2023-12-26 20:51 UTC, closed without merging

2023-12-27 11:41 UTC, Ravi-kumar9347 commented
@stevepiercy  sorry for my things i did, can i reopen this or should i mention why i closed this pr

2023-12-27 12:27 UTC, stevepiercy commented
@Ravi-kumar9347 do whatever you think is best. I already gave you direction in my comment in the other PR.

2023-12-27 12:31 UTC, Ravi-kumar9347 commented
@stevepiercy then would you consider the latest pr