edit recurrence button is aligned properly
plone/volto pull request #5590
Opened 2024-01-02 15:45 UTC by Ravi-kumar9347

solved the bug #5359, aligned the recurrence button in recurrence widget properly

2024-01-02 17:01 UTC, stevepiercy requested changes
Restructure sentence for clarity.

2024-01-02 17:01 UTC, stevepiercy commented on packages/volto/news/5359.bugfix
> +"Edit Recurrence" button in Recurrence widget is aligned properly. @Ravi-kumar9347
```suggestion
In the recurrence widget, set the vertical alignment of the `edit` button to `middle`. @Ravi-kumar9347
```

2024-01-02 17:03 UTC, stevepiercy commented
@Ravi-kumar9347 please edit your issue description to comply with Item 2 in https://6.docs.plone.org/contributing/first-time.html#create-a-pull-request-from-your-fork.

I've also requested review from a couple of core contributors.

2024-01-02 17:29 UTC, Ravi-kumar9347 commented
@stevepiercy, updated the description of issue.

2024-01-02 18:50 UTC, stevepiercy approved these changes
I approve only the news item. This should also be reviewed by a core contributor.

2024-01-02 18:53 UTC, stevepiercy commented
@Ravi-kumar9347 you did not edit this description:

https://github.com/plone/volto/pull/5590#issue-2062600163

You edited a change log entry. Please carefully read and follow [my comment](https://github.com/plone/volto/pull/5590#issuecomment-1874296021).

2024-01-04 08:33 UTC, Ravi-kumar9347 commented
@sneridagh , @davisagli can you please review my pr.

2024-01-04 10:31 UTC, Ravi-kumar9347 commented
@stevepiercy now the description is correct?

2024-01-04 11:06 UTC, stevepiercy commented
> @stevepiercy now the description is correct?

Yes, you got it.

2024-01-05 22:10 UTC, davisagli approved these changes
Thanks, looks good to me.

2024-01-05 22:10 UTC, merged