Added aria-live='polite'
plone/volto pull request #5639
Opened 2024-01-17 05:08 UTC by Hrittik20

Issue: #5617

2024-01-17 14:58 UTC, stevepiercy commented
@Hrittik20 CI checks need to pass. Same for backported PR #5640.

See [Change log entry](https://6.docs.plone.org/contributing/index.html#change-log-entry) and [Code quality](https://6.docs.plone.org/volto/contributing/index.html#code-quality)

2024-01-17 15:24 UTC, Hrittik20 commented
@stevepiercy Sorry, I forgot to add change log entry

2024-01-17 15:37 UTC, stevepiercy requested changes

2024-01-17 15:37 UTC, stevepiercy commented on packages/volto/news/5617.feature
> +Added aria-live='polite' in `Contents.jsx` to improve accessibility. @Hrittik20
```suggestion
Added `aria-live="polite"` in `Contents.jsx` to improve accessibility for the Contents page. @Hrittik20
```

2024-01-17 15:40 UTC, stevepiercy reviewed
This is good. Please check ESLint.

2024-01-17 21:32 UTC, stevepiercy commented
@Hrittik20 do you get notifications from GitHub of failed GitHub workflows? I get them whenever I submit a pull request that breaks them, so I assume you would too. You can click each failed workflow's "Details" link to see what might cause the failure.

Anyway, there are two workflows that you need to address. I would suggest that you run tests locally to save time, effort, and frustration. See [Testing](https://6.docs.plone.org/volto/contributing/testing.html) and [Acceptance testing](https://6.docs.plone.org/volto/contributing/acceptance-tests.html).

2024-01-18 13:39 UTC, Hrittik20 commented
@stevepiercy Yes, I am working on it. I am getting few errors while linting and testing so trying to fix it now

2024-01-18 20:35 UTC, stevepiercy approved these changes
I approve the change log. A core maintainer needs to review the rest.

2024-01-23 14:25 UTC, giuliaghisini approved these changes

2024-01-29 04:46 UTC, davisagli approved these changes

2024-01-29 04:46 UTC, merged

2024-01-29 08:21 UTC, giuliaghisini commented
@davisagli @stevepiercy @Hrittik20 is it possible to have this also in Volto 17?

2024-01-29 08:38 UTC, stevepiercy commented
@giuliaghisini you mean, like in #5640? :wink:

2024-01-29 08:51 UTC, giuliaghisini commented
> @giuliaghisini you mean, like in #5640? 😉

yes!