Blocks Layout Navigator
plone/volto pull request #5642
Opened 2024-01-17 08:01 UTC by sneridagh

Supersedes: #4745

2024-01-17 08:31 UTC, tiberiuichim commented
May I suggest the following UI changes:

- Don't name the tab "Layout", as the term is already used in the "Dexterity Layout" feature
- Hide the block UIDs, show them as a tooltip
- Allow the block configuration to provide a preview component. For example, for the image block, a preview component could look like (pseudo-code):

```
Image (...image title or alt)
```

When hovering over the text, I would get a floating thumbnail of the image.

For the slate text, the preview component could be like:

```
...cropped text (first two words)
```

When hovering over the text, I can get a floating preview of the entire text block.

2024-01-17 08:48 UTC, sneridagh commented
@tiberiuichim no worries, still under development, I just updated it. There are a couple of things to polish and others that do not work well. The UI should be far more fancy, for sure. Now it's debugging mode :)

2024-06-06 07:21 UTC, djay commented
@sneridagh I would be inclined to have it more hidden away. Instead of a tab, it could be inside the block tab at the top as a rolldown. So when collapsed it shows the indent and identity of the current block. uncollapsing it lets you see the current block in context of parents and switch to another block.

2024-06-06 09:46 UTC, sneridagh commented
@djay the block tab is specific and contextual to a single block. This feature is global to the page, same as the "Metadata" tab. IMHO, having this feature in there, also bloating the tab itself it would be wrong. The fact that Elementor and others place this feature globally also confirm that this decision is ok.

2024-06-06 09:49 UTC, robgietema commented
> @djay the block tab is specific and contextual to a single block. This feature is global to the page, same as the "Metadata" tab. IMHO, having this feature in there, also bloating the tab itself it would be wrong. The fact that Elementor and others place this feature globally also confirm that this decision is ok.

I agree with Victor on this one.

2024-06-06 10:30 UTC, djay commented
@sneridagh maybe. But that's only becuase you currently have the mental model of the block tab being there only when the block is selected rather than always being there. 
To me it just clutters up the tabs on the top and will make it harder to use on slim devices like mobile. The fact that there is going to have to be a name for it like blocks or layout signifies this waste of space and I can't see it being clear to the user from whatever name you settle on. 


you also lose the ability to see the breadcrumb or structure of thrr current block while looking at the block. So that would have to added again somewhere else like at the bottom of the screen like on gutenburg, taking up more space. 

Single line at the top of the block tab seems like a good deal to me. It could replace the current label for the block type so there is no loss in space.

2024-06-06 11:15 UTC, sneridagh commented
@djay did you try the last version? Please do.

2024-06-06 11:43 UTC, stevepiercy commented on packages/volto/src/components/manage/Blocks/Block/__snapshots__/BlocksForm.test.jsx.snap
> +    Press space again to drop the item in its new position, or press escape to cancel.
I think this should be translatable.

2024-06-06 11:59 UTC, stevepiercy commented
This is so much better than what we and other CMSs currently have.

> make it harder to use on slim devices like mobile

Who edits a site on mobile? Come on, let's get real. Look at your web stats and tell me what clients are editing your sites 99.9% of the time.

2024-06-06 14:02 UTC, djay commented
@sneridagh I'm not saying to change how it works. It's great and it's an important part of the decoupled editor. 
Im just suggesting making not in another tab and having it be a drop down at the top of the block so it also acts as a single line breadcrumb making it better still.

2024-06-09 08:53 UTC, sneridagh commented
@robgietema I've end up by commenting out the `onFocus` that was stealing the focus from the slate block on creation. 

https://github.com/plone/volto/pull/5642/commits/26b56324d524ea854c7e47868919c620f51fb168

I cannot see any different behavior by removing it, probably I'm missing an edge case. If it's that so, we have to come back to it, but for now, it's good enough for me not to hold it any more.

2024-06-10 08:16 UTC, stevepiercy approved these changes

2024-06-10 08:16 UTC, stevepiercy commented on packages/volto/src/components/manage/Blocks/Block/__snapshots__/BlocksForm.test.jsx.snap
> +    Press space again to drop the item in its new position, or press escape to cancel.
nm, this is a test, not a core UI thing, but the message can be customized:

https://docs.dndkit.com/guides/accessibility#screen-reader-instructions

2024-06-10 08:17 UTC, giuliaghisini approved these changes

2024-06-10 08:17 UTC, giuliaghisini commented on packages/volto/locales/it/LC_MESSAGES/volto.po
> +msgstr ""
```suggestion
msgstr "Ordine"
```

2024-06-10 14:36 UTC, davisagli commented
> Look at your web stats and tell me what clients are editing your sites 99.9% of the time.

@stevepiercy I would not trust the stats for this on a system that does not work well for editing on mobile. See: https://en.wikipedia.org/wiki/Survivorship_bias

2024-06-10 19:59 UTC, stevepiercy commented
@davisagli drag and drop on a tiny mobile screen is difficult to use, if not impossible. It's a matter of choosing the right tool for the job. You can choose not to trust the data and insist that DnD be fixed, but then you would spend significant effort on something that is extremely difficult to implement.

2024-06-10 20:07 UTC, davisagli commented
> You can choose not to trust the data and insist that DnD be fixed, but then you would spend significant effort on something that is extremely difficult to implement.

Oh sorry, I jumped into the conversation in the middle and wasn't trying to argue against merging this PR. I think the new navigator is an improvement over the status quo for all screen sizes, both in terms of usability (it's hard to drag large blocks currently) and maintainability.

2024-06-11 07:23 UTC, sneridagh commented on packages/volto/src/components/manage/Blocks/Block/BlocksForm.jsx
> +import { cloneDeep, includes, isArray, keys, map } from 'lodash';
@pnicolli I am too, I will take a look.

2024-06-11 08:38 UTC, ichim-david requested changes
@sneridagh @robgietema there is no drag handle visible on FF and trying to click and drag within the section where the icon should be doesn't do anything.
The Block is highlighted in the order sidebar and in the main section but no drag ability.
![drag-handle-ff](https://github.com/plone/volto/assets/152852/d03e706d-1137-4a44-875a-e5bd16c421ab)


This doesn't happen in Edge where the drag handle shows up and you can drag.
![drag-handle-edge](https://github.com/plone/volto/assets/152852/43204a0e-2e91-462b-b1fa-c37e0138fbc2)

2024-06-11 08:47 UTC, ichim-david commented
@sneridagh besides the missing functionality altogether on FF there has to be some regression introduced recently as it seems that even on Edge and Safari although I can drag and drop it doesn't change the order, have a look at this screen recording.

https://github.com/plone/volto/assets/152852/bcda59cc-f5a8-4e6d-97dc-76306b2cc5b0

2024-06-11 08:59 UTC, ichim-david commented
@sneridagh sorry for all of these extra comments, I found out why the drag and drop doesn't work on Edge and Safari,
it happens when you have an unknown block, you cannot do any reordering until that unknown block is removed.

https://github.com/plone/volto/assets/152852/9202d1c2-e768-4f87-add2-e881009e079d

Don't know if you want to try to treat this or simply add a documentation entry that it won't work until those blocks
are removed.

2024-06-11 09:26 UTC, sneridagh commented
@ichim-david thanks for the report. 
This is bad news, since Rob is out for the next month.
@plone/volto-team it would be great if someone is up to look into the issues raised. I don't have to tell you how important is this feature to be in core, and what they mean for the user experience.

2024-06-11 09:43 UTC, sneridagh commented
@ichim-david I think I quick fixed the FF problem, please take a look.
I guess the "unknown block" can be addressed lately (if we think it's still a relevant issue).

2024-06-11 10:05 UTC, ichim-david commented
> @ichim-david I think I quick fixed the FF problem, please take a look. I guess the "unknown block" can be addressed lately (if we think it's still a relevant issue).
> <img alt="image" width="286" src="https://private-user-images.githubusercontent.com/486927/338528816-0c9340e3-3523-4b3b-9061-3bef92e38378.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwOTk4NDMsIm5iZiI6MTcxODA5OTU0MywicGF0aCI6Ii80ODY5MjcvMzM4NTI4ODE2LTBjOTM0MGUzLTM1MjMtNGIzYi05MDYxLTNiZWY5MmUzODM3OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMVQwOTUyMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kODk4Zjg0NWIxOWMzZmQxMjAyYWYxNzgxYzUzZWIyODc1ZjJkNjNhMTBhYjI2NDE5NmE2MDM2OTczOTg5MDYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4Rw1aKC_40eZRBvNhl18roUjbnMhaSTVQsxQ-VH2s-A">

@sneridagh  Confirmed working now on FF.   Up to you on how you think we should proceed about the unknown block. For me it's enough to have a doc entry that it doesn't work on pages where you have unknown blocks until you remove them.
We could also give it 1-2 days to see if we can figure out what's the issue there but it might take longer to figure out and we would be ok with this release with info about this limitation.

2024-06-11 10:06 UTC, ichim-david approved these changes

2024-06-12 06:33 UTC, sneridagh commented on packages/volto/src/components/manage/Blocks/Block/BlocksForm.jsx
> +import { cloneDeep, includes, isArray, keys, map } from 'lodash';
Done

2024-06-13 09:53 UTC, merged