PoC - Vite and Tanstack Router, Query and `@plone/client` in SSR mode.
plone/volto pull request #5750
Opened 2024-02-11 16:34 UTC by sneridagh

2024-02-11 21:57 UTC, stevepiercy requested changes
Docs please!

2024-02-11 21:57 UTC, stevepiercy commented on apps/vite/README.md
This file needs to be added to https://github.com/plone/volto/blob/main/.github/workflows/readme-link-check.yml#L23

2024-02-11 21:57 UTC, stevepiercy commented on apps/vite/README.md
> +# Example
```suggestion
# Vite

A package for Volto. (I'm sure you can come up with something better.)

- What does this do?
- Who is it for?
- Add link to Vite site.

## Usage
```

2024-02-12 07:52 UTC, sneridagh commented on apps/vite/README.md
> +# Example
Not a package, a PoC. It's intended for devs interested in the Plone's headless CMS story or in doing things outside Volto (as all the other things in apps folder)

2024-02-12 07:58 UTC, stevepiercy submitted a review, later dismissed
Thanks, minor grammar fixes and a link fix.

2024-02-12 07:58 UTC, stevepiercy commented on apps/vite-ssr/README.md
> +This is a proof of concept of a [Vite](https://https://vitejs.dev) build, using `@plone/client` and `@plone/components` library.
```suggestion
This is a proof of concept of a [Vite](https://vitejs.dev) build, using `@plone/client` and `@plone/components` libraries.
```

2024-02-12 07:58 UTC, stevepiercy commented on apps/vite-ssr/README.md
> +This is intended to serve as both a playground for the development of both packages and as demo of Plone using Vite build with Server Side Rendering (SSR).
```suggestion
This is intended to serve as both a playground for the development of both packages and as a demo of Plone using Vite built with server side rendering (SSR).
```

2024-02-12 07:58 UTC, stevepiercy commented on apps/vite-ssr/README.md
> +It also uses TanStack Router as routing library.
```suggestion
It also uses [TanStack Router](https://tanstack.com/router/latest/docs/framework/react/overview) for its routing library.
```

2024-02-12 14:27 UTC, stevepiercy reviewed
README and CI looks good. Thank you!

2024-02-12 23:29 UTC, stevepiercy reviewed
Nice catch on nextjs/README.md. CI and README looks good.

2024-02-12 23:34 UTC, stevepiercy submitted a review, later dismissed
Try this to workaround the readme check failure.

If it works, then you can remove the whitelist item in the CI that you added in an attempt to get it to pass.

2024-02-12 23:34 UTC, stevepiercy commented on apps/nextjs/README.md
Line 24 fails. The bot incorrectly parses a literal, when it should ignore it. So this workaround might take care of it:
````md
You need to create this environment variable in the Vercel deployment's control panel, specifying the URL where your backend API server is deployed and the route where the API is located as shown.

```shell
API_SERVER_URL=https://my_server_DNS_name/api
```
````

2024-02-13 07:40 UTC, sneridagh commented
@stevepiercy it still fails...

2024-02-13 07:57 UTC, stevepiercy commented
oh lol `_` is not a legal character in a domain name, hence the failure.

2024-02-13 08:36 UTC, stevepiercy commented
I learned to Internet this many years ago 0️⃣ . lol. All right, that readme is good to go now. Just needs a change log and update branch. Back to you @sneridagh.

2024-02-13 09:22 UTC, merged