Add VOLTOCONFIG Env Var
plone/volto pull request #5752
Opened 2024-02-12 07:27 UTC by sneridagh

2024-02-12 07:50 UTC, stevepiercy commented
@sneridagh there is [another open PR for environment variables documentation](https://github.com/plone/volto/pull/5736) that needs some review and love before the docs from this one can be included.

2024-02-13 08:25 UTC, stevepiercy requested changes
Minor tweaks and MyST seasoning.

2024-02-13 08:25 UTC, stevepiercy commented on docs/source/configuration/environmentvariables.md
> +    You can also provide a custom location for `volto.config.js` via an environment variable.
```suggestion
    This environment variable allows you to specify a custom location for {file}`volto.config.js`.
```

2024-02-13 08:25 UTC, stevepiercy commented on docs/source/configuration/environmentvariables.md
> +     VOLTOCONFIG=../../volto.config.js yarn start
```suggestion
    VOLTOCONFIG=../../volto.config.js yarn start
```

2024-02-13 08:25 UTC, stevepiercy commented on docs/source/configuration/volto-config-js.md
> +## Using `VOLTOCONFIG` environment variable
```suggestion
## `VOLTOCONFIG` environment variable usage
```

2024-02-13 08:25 UTC, stevepiercy commented on docs/source/configuration/volto-config-js.md
> +You can also provide a custom location for `volto.config.js` via an environment variable.
```suggestion
This environment variable allows you to specify a custom location for {file}`volto.config.js`.
```

2024-02-13 08:25 UTC, stevepiercy commented on docs/source/configuration/volto-config-js.md
> +you can also do it in core (monorepo):
I think you mean this, but maybe not. I'm not really sure of your intent.

```suggestion
You can also set it from the root of the monorepo:
```

2024-02-13 08:25 UTC, stevepiercy commented on packages/registry/news/5752.feature
> +Add VOLTOCONFIG environment variable @sneridagh
```suggestion
Add `VOLTOCONFIG` environment variable. @sneridagh
```

2024-02-13 08:27 UTC, stevepiercy commented
Outside the scope of this issue, of course, but copy-paste in docs always leads to drift and more maintenance work. I wonder if we should audit the [Configuration](https://6.docs.plone.org/volto/configuration/index.html) section and reorganize it? I can create an issue for future work, and add it to the GSoD draft proposal.

2024-02-13 08:30 UTC, sneridagh commented
@stevepiercy I thought on it already, but it's so small, and it won't change...

2024-02-13 09:22 UTC, merged