Add accordion to metadata form.
plone/volto pull request #5760
Opened 2024-02-13 15:16 UTC by robgietema

This PR add the feature to collapse and expand fieldsets in the metadata form in the sidebar. A helper method is also added which can be used to scroll to a specific field and focus on it.

2024-02-13 16:08 UTC, sneridagh commented
@robgietema can we have some docs on how to use it?

2024-02-13 22:50 UTC, stevepiercy commented
Would this be the appropriate location for developer docs for this feature? [Forms and widgets](https://6.docs.plone.org/volto/recipes/widget.html)

2024-02-16 14:50 UTC, robgietema commented
I've added some docs in the location specified by Steve.

2024-02-16 21:10 UTC, stevepiercy requested changes
A few spelling, grammar, and style fixes. Thank you!

2024-02-16 21:10 UTC, stevepiercy commented on packages/volto/news/5760.feature
> +Ad accordion to metadata form. @robgietema
```suggestion
Add accordion to metadata form. @robgietema
```

2024-02-16 21:10 UTC, stevepiercy commented on docs/source/recipes/widget.md
> +In the edit form a sidebar is used when the form contains block data. There are some helper actions methods which can be used to change the form state.
Avoid passive voice, prefer to address the reader. One sentence per line.

```suggestion
In the edit form, a sidebar is used when the form contains block data.
You can use the following helper action methods to change the form state.
```

2024-02-16 21:10 UTC, stevepiercy commented on docs/source/recipes/widget.md
> +You can use the `setSidebarTab` action to set the current active tab (metadata or block).
```suggestion
You can use the `setSidebarTab` action to set the current active tab, either via metadata or a block.
```

2024-02-21 09:50 UTC, sneridagh approved these changes
LGTM

2024-02-21 09:52 UTC, stevepiercy reviewed
Docs look good. Thank you!

2024-02-21 10:00 UTC, merged