Update volto-slate configuration to indicate it is now part of the core.
plone/volto pull request #5886
Opened 2024-03-16 21:52 UTC by MostafaMagdyy

Fixes #5342 for volto docs to indicate that volto-slate is now part of the core

2024-03-16 22:40 UTC, MostafaMagdyy commented
Please review this pull request. @stevepiercy ,@polyester, could you please take a look and provide your feedback? Thank you!

2024-03-17 00:31 UTC, stevepiercy commented
@MostafaMagdyy you have two pull requests open for the same issue (#5884). Neither will be reviewed until you close one. See Item 3 under [Things not to do](https://6.docs.plone.org/contributing/first-time.html#things-not-to-do).

2024-03-17 00:46 UTC, MostafaMagdyy commented
@stevepiercy Sorry for the inconvenience. I closed the first one because I did not pass the Plone contributor agreement.
Now you will find only one regarding this issue

2024-03-17 08:44 UTC, stevepiercy requested changes
We also need to review and possibly rewrite all the files within the `configuration/volto-slate` directory. I will push some changes for that as well, because they require knowledge of its history.

2024-03-17 08:44 UTC, stevepiercy commented on docs/source/configuration/volto-slate/index.md
> +`volto-slate` is an interactive default text editor for Volto, integrated into the core system and developed on top of {term}`Slate`.
I think the more important clause should go first, although the lesser is a good addition for clarity.

```suggestion
`volto-slate` is an interactive default text editor for Volto, developed on top of {term}`Slate` and integrated into the core system.
```

2024-03-17 08:44 UTC, stevepiercy commented on packages/volto/news/5342.documentation
> +Update volto-slate configuration to indicate it is now part of the core. @MostafaMagdyy
```suggestion
Update `volto-slate` configuration documentation to indicate it is now part of Volto core. @MostafaMagdyy
```

2024-03-17 11:29 UTC, MostafaMagdyy commented
@stevepiercy Thanks for your help regarding prioritizing the important clause. I have committed the suggested changes already. Please check if there are any other changes needed regarding this issue, **Also** I have reviewed the files within the configuration/volto-slate directory. and found these files focus on extending Volto-Slate into projects that use Volto, with guidance on creating customized plugins. So, I am not sure whether they need to be updated

**One thing I noticed that might require updating is this description is**
# `volto-slate` API

The `volto-slate` API provides methods to **integrate** the Slate editor into projects that use Plone's React-based frontend Volto.

I suggest it to be

The `volto-slate` API provides methods to **extends** the Slate editor into projects that use Plone's React-based frontend Volto.

2024-03-17 14:19 UTC, stevepiercy approved these changes

2024-03-17 14:20 UTC, stevepiercy commented
@MostafaMagdyy it is actually an integration, not an extension, so we'll leave it as is.

I also reviewed the rest of the documentation in `volto-slate`, and it does not need any revisions.

This PR is OK to merge. Thank you!

2024-03-17 14:21 UTC, stevepiercy commented
Actually, I want to make sure that all tests pass. For some reason "Acceptance Tests / Core Blocks - Listing (18.x) (pull_request)" did not pass. I restarted it to see if it is flaky and will pass this time.

2024-03-17 14:58 UTC, merged