fix(slate): fix insert/remove element edgecase bug in slate
plone/volto pull request #5926
Opened 2024-03-26 13:42 UTC by razvanMiu

2024-03-26 14:13 UTC, stevepiercy commented
@razvanMiu which issue does this PR fix? See Item 2, second bullet point in [Create a pull request from your fork](https://6.docs.plone.org/contributing/first-time.html#create-a-pull-request-from-your-fork).

2024-03-26 14:15 UTC, stevepiercy requested changes

2024-03-26 14:15 UTC, stevepiercy commented on packages/volto-slate/news/5926.bugfix
> +Fix insert/remove element edgecase bug in slate. @razvanMiu
What edge case does this fix? Please describe the edge case, and how does what you did fix it.

2024-03-26 21:04 UTC, stevepiercy commented
@razvanMiu at least copy and paste the error stack into the PR, or better yet, create an issue with the error stack after searching the issue tracker for the error message. Someone else might have reported it or is already working on it, which could save you some time and effort.

I can write up a description, once you paste the error stack, so I don't have to transcribe the videos.

Sometimes the English language can get in the way of doing good work, and if so, if it's easier to write it in your preferred language, we can use a translation service to translate it to English.

2024-03-26 23:16 UTC, razvanMiu commented
> @razvanMiu at least copy and paste the error stack into the PR, or better yet, create an issue with the error stack after searching the issue tracker for the error message. Someone else might have reported it or is already working on it, which could save you some time and effort.
> 
> I can write up a description, once you paste the error stack, so I don't have to transcribe the videos.
> 
> Sometimes the English language can get in the way of doing good work, and if so, if it's easier to write it in your preferred language, we can use a translation service to translate it to English.

I created an [issue](https://github.com/plone/volto/issues/5928)

2024-03-27 23:14 UTC, stevepiercy commented
@razvanMiu thank you! That's an excellent write-up.

@plone/volto-team all green and ready for review!

2024-03-28 06:19 UTC, tiberiuichim approved these changes

2024-03-31 11:43 UTC, merged