fix: pass down locale to IntlProvider
plone/volto pull request #5976
Opened 2024-04-23 15:53 UTC by tomschall

2024-04-24 19:31 UTC, sneridagh requested changes
@tomschall I tried it out, and it breaks in the stories that do not have a `customStore` passed down, take a look at my suggestion, I think we have to look into the generated store instead. So it takes the defaults, and the incoming `customStore`, if any. I already tried it out and works as expected.

2024-04-24 19:31 UTC, sneridagh commented on packages/volto/src/storybook.jsx
> +          >
```suggestion
          <IntlProvider
            locale={store.getState().intl.locale}
            messages={store.getState().intl.messages}
            defaultLocale={store.getState().intl.defaultLocale ?? 'en'}
          >
```

2024-04-25 13:36 UTC, tomschall commented
> @tomschall I tried it out, and it breaks in the stories that do not have a `customStore` passed down, take a look at my suggestion, I think we have to look into the generated store instead. So it takes the defaults, and the incoming `customStore`, if any. I already tried it out and works as expected.

What i am not so happy with is, that we call store.getState() 3 times in each Wrapper. I made another suggestion, that we use a const to fetch the state and then use that for the props.

2024-04-25 13:55 UTC, merged

2024-04-25 13:56 UTC, sneridagh commented
Thanks @tomschall !!