Update README.md add York College to List of sites
plone/volto pull request #5996
Opened 2024-04-30 16:58 UTC by rnunez80

Update README.md add York College to List of sites

2024-04-30 19:46 UTC, stevepiercy requested changes

2024-04-30 19:46 UTC, stevepiercy commented on README.md
> +- [York College / CUNY] (https://www.york.cuny.edu/) (York College is part of The City University of New York (CUNY), one of the largest university systems in the United States, developed in-house, 2
```suggestion
- [York College / CUNY] (https://www.york.cuny.edu/) (York College is part of The City University of New York (CUNY), one of the largest university systems in the United States. Developed in-house, 2023)
```

This is not a good look. It appears to affect only the home page, though.

![Screenshot 2024-04-30 at 12 39 13 PM](https://github.com/plone/volto/assets/102112/4049ce97-5052-491d-a669-6ac04394dc16)

```console
GET https://www.york.cuny.edu/static/css/client.0cf6c3d5.css net::ERR_ABORTED 404 (Not Found)   www.york.cuny.edu/:2
GET https://www.york.cuny.edu/static/js/runtime~client.9713af2a.js net::ERR_ABORTED 404 (Not Found)    www.york.cuny.edu/:2
GET https://www.york.cuny.edu/static/js/client.980b59bf.js net::ERR_ABORTED 404 (Not Found)   www.york.cuny.edu/:2
```

Can you check your deployment and verify it loads the missing CSS and JS files, and ping us back?

Also consider adding this to https://github.com/collective/awesome-volto

2024-04-30 20:22 UTC, rnunez80 commented
Thanks Steve,

Try now

I was in the middle of upgrading Volto to 17.15.6, every time I need to rebuild Volto even though it failover to the other Volto server, I have to manually clear the cache on the server or I get this error.

Any deployment suggestions to fail over from one Volto server to another with out having to purge the cache manually?

Also if you want you can add this other plone site https://www.epicsunpuntacana.com/

From: Steve Piercy ***@***.***>
Date: Tuesday, April 30, 2024 at 3:46 PM
To: plone/volto ***@***.***>
Cc: Rafael Nunez ***@***.***>, Author ***@***.***>
Subject: Re: [plone/volto] Update README.md add York College to List of sites (PR #5996)

* This email originates from a sender outside of CUNY. Verify the sender before replying or clicking on links and attachments. *
This email originated from ***@***.***, a sender outside of CUNY. Never send login credentials, financial information, or sensitive information by email. Report suspicious email to ***@***.***

@stevepiercy requested changes on this pull request.

________________________________

In README.md<https://urldefense.com/v3/__https://github.com/plone/volto/pull/5996*discussion_r1585447258__;Iw!!NFZiyfBF5EK0!k4yLldH8nhN6BKkOCH_Tz5i_CMc9XtyViVJgtGyY2LWR4YKANsTupB_3TcxIEUrdnIPNl660qrK1A6rPbMyE69ozrVaY$>:

> @@ -141,6 +141,7 @@ To ensure your website gets the greatest exposure, add it both to [Awesome Volto

 - [VHS Ehrenamtsportal](https://vhs-ehrenamtsportal.de<https://urldefense.com/v3/__https://vhs-ehrenamtsportal.de__;!!NFZiyfBF5EK0!k4yLldH8nhN6BKkOCH_Tz5i_CMc9XtyViVJgtGyY2LWR4YKANsTupB_3TcxIEUrdnIPNl660qrK1A6rPbMyE62UqwNe3$>) (Website to help volunteers that help refugees for the [German Adult Education Association](https://www.volkshochschule.de/<https://urldefense.com/v3/__https://www.volkshochschule.de/__;!!NFZiyfBF5EK0!k4yLldH8nhN6BKkOCH_Tz5i_CMc9XtyViVJgtGyY2LWR4YKANsTupB_3TcxIEUrdnIPNl660qrK1A6rPbMyE64_gxNWU$>), developed by [kitconcept GmbH](https://kitconcept.com<https://urldefense.com/v3/__https://kitconcept.com__;!!NFZiyfBF5EK0!k4yLldH8nhN6BKkOCH_Tz5i_CMc9XtyViVJgtGyY2LWR4YKANsTupB_3TcxIEUrdnIPNl660qrK1A6rPbMyE64iWTkhn$>), 2018)

 - [VisitModena](https://www.visitmodena.it/it<https://urldefense.com/v3/__https://www.visitmodena.it/it__;!!NFZiyfBF5EK0!k4yLldH8nhN6BKkOCH_Tz5i_CMc9XtyViVJgtGyY2LWR4YKANsTupB_3TcxIEUrdnIPNl660qrK1A6rPbMyE6z9RcSaG$>) (Tourist website of the Municipality of Modena, developed by [RedTurtle](https://www.redturtle.it<https://urldefense.com/v3/__https://www.redturtle.it__;!!NFZiyfBF5EK0!k4yLldH8nhN6BKkOCH_Tz5i_CMc9XtyViVJgtGyY2LWR4YKANsTupB_3TcxIEUrdnIPNl660qrK1A6rPbMyE6_gBA1Ff$>), 2020)

 - [WISE-Freshwater](https://water.europa.eu/freshwater<https://urldefense.com/v3/__https://water.europa.eu/freshwater__;!!NFZiyfBF5EK0!k4yLldH8nhN6BKkOCH_Tz5i_CMc9XtyViVJgtGyY2LWR4YKANsTupB_3TcxIEUrdnIPNl660qrK1A6rPbMyE68ys1MA-$>) (WISE-Freshwater, the Freshwater Information System for Europe. Developed by [Eau de web](https://eaudeweb.ro<https://urldefense.com/v3/__https://eaudeweb.ro__;!!NFZiyfBF5EK0!k4yLldH8nhN6BKkOCH_Tz5i_CMc9XtyViVJgtGyY2LWR4YKANsTupB_3TcxIEUrdnIPNl660qrK1A6rPbMyE6wKc0o3S$>) for the European Environmental Agency, 2021)

+- [York College / CUNY] (https://www.york.cuny.edu/) (York College is part of The City University of New York (CUNY), one of the largest university systems in the United States, developed in-house, 2023)
⬇️ Suggested change

-- [York College / CUNY] (https://www.york.cuny.edu/) (York College is part of The City University of New York (CUNY), one of the largest university systems in the United States, developed in-house, 2023)

+- [York College / CUNY] (https://www.york.cuny.edu/) (York College is part of The City University of New York (CUNY), one of the largest university systems in the United States. Developed in-house, 2023)

This is not a good look. It appears to affect only the home page, though.

Screenshot.2024-04-30.at.12.39.13.PM.png (view on web)<https://urldefense.com/v3/__https://github.com/plone/volto/assets/102112/4049ce97-5052-491d-a669-6ac04394dc16__;!!NFZiyfBF5EK0!k4yLldH8nhN6BKkOCH_Tz5i_CMc9XtyViVJgtGyY2LWR4YKANsTupB_3TcxIEUrdnIPNl660qrK1A6rPbMyE6zV98284$>

GET https://www.york.cuny.edu/static/css/client.0cf6c3d5.css net::ERR_ABORTED 404 (Not Found)   http://www.york.cuny.edu/:2

GET https://www.york.cuny.edu/static/js/runtime~client.9713af2a.js net::ERR_ABORTED 404 (Not Found)    http://www.york.cuny.edu/:2

GET https://www.york.cuny.edu/static/js/client.980b59bf.js net::ERR_ABORTED 404 (Not Found)   http://www.york.cuny.edu/:2

Can you check your deployment and verify it loads the missing CSS and JS files, and ping us back?

Also consider adding this to https://github.com/collective/awesome-volto<https://urldefense.com/v3/__https://github.com/collective/awesome-volto__;!!NFZiyfBF5EK0!k4yLldH8nhN6BKkOCH_Tz5i_CMc9XtyViVJgtGyY2LWR4YKANsTupB_3TcxIEUrdnIPNl660qrK1A6rPbMyE6x6diwaG$>

—
Reply to this email directly, view it on GitHub<https://urldefense.com/v3/__https://github.com/plone/volto/pull/5996*pullrequestreview-2032390556__;Iw!!NFZiyfBF5EK0!k4yLldH8nhN6BKkOCH_Tz5i_CMc9XtyViVJgtGyY2LWR4YKANsTupB_3TcxIEUrdnIPNl660qrK1A6rPbMyE6_qg2Iet$>, or unsubscribe<https://urldefense.com/v3/__https://github.com/notifications/unsubscribe-auth/AAZ7UGHF2JQ2UF4UF4P447DY77YKBAVCNFSM6AAAAABHAUT3U2VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDAMZSGM4TANJVGY__;!!NFZiyfBF5EK0!k4yLldH8nhN6BKkOCH_Tz5i_CMc9XtyViVJgtGyY2LWR4YKANsTupB_3TcxIEUrdnIPNl660qrK1A6rPbMyE6zu9P97p$>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-04-30 20:43 UTC, stevepiercy commented
@rnunez80 it looks OK now.

This PR needs a change log entry. You can add the other website when you add that entry.

I don't have any advice for your cache situation. I'd suggest asking on https://community.plone.org/.

2024-05-06 08:47 UTC, sneridagh commented
@rnunez80 please could you add the changelog entry?

2024-05-27 10:03 UTC, stevepiercy commented
@sneridagh I would not merge this until @rnunez80 adds it to https://github.com/collective/awesome-volto?tab=readme-ov-file#websites-built-with-volto, as we often copy-paste from that section to our README.md, which overwrites whatever was added here. Also @rnunez80 wanted to add a second site.

2024-05-27 10:07 UTC, stevepiercy commented
In fact, where the contributor promotes their own site in the README, I would prefer to close the PR unless they can follow contributing guidelines. Why should we do their work for them?

2024-05-27 11:33 UTC, sneridagh commented
@stevepiercy Only trying to close stale PRs in here. @rnunez80 can you take care of @stevepiercy suggestions?

2024-05-27 12:21 UTC, stevepiercy commented
@sneridagh sure, but why do their work for them? I would just close this PR. If and when they do things completely, then we can merge it.

If it were a feature or bugfix that benefits the project, then that's a different matter.

2025-04-05 02:03 UTC, stevepiercy commented
Closing as its counterpart was never done, and it now has merge conflicts. @rnunez80 please feel free to reopen, update, and add the counterpart to https://github.com/collective/awesome-volto?tab=readme-ov-file#websites-built-with-volto.

2025-04-05 02:03 UTC, closed without merging