Byday and byyear-byday buttons padding in recurrence form
plone/volto pull request #6070
Opened 2024-06-05 14:15 UTC by sabrina-bongiovanni

This PR fixes

- the byday field buttons in the recurrence widget when font-size is >16px.

<img width="1005" alt="image" src="https://github.com/plone/volto/assets/116291154/ca9c9e57-5c2d-49d3-9275-317224746d91">

- the byyear-byday buttons for the yearly recurrence when font-size is >16px.

<img width="938" alt="image" src="https://github.com/plone/volto/assets/116291154/28d30c3a-1e7a-476e-8398-9c9c08027b06">

2024-06-05 21:07 UTC, stevepiercy requested changes
Use a more explicit description from a user perspective

2024-06-05 21:07 UTC, stevepiercy commented on packages/volto/theme/themes/pastanaga/extras/widgets.less
> +// makes sure recurrence form buttons don't overflow when font is big
```suggestion
// makes sure event recurrence form buttons don't overflow when font is big
```

2024-06-05 21:07 UTC, stevepiercy commented on packages/volto/news/6070.bugfix
> +Byday and byyear-byday buttons padding in recurrence form for big fonts @sabrina-bongiovanni
```suggestion
Remove left and right padding from _Event > Edit recurrence > Repeat on_ buttons when repeating for weekly or yearly events for big fonts, preventing overflow. @sabrina-bongiovanni
```

2024-06-06 11:03 UTC, stevepiercy approved these changes
Thank you! Let's have another @plone/volto-team member review. I just do grammar. 😁

2024-06-06 11:07 UTC, sabrina-bongiovanni commented
> Thank you! Let's have another @plone/volto-team member review. I just do grammar. 😁

Thank you Steve 😊

2024-06-06 14:16 UTC, sneridagh approved these changes

2024-06-06 14:19 UTC, merged