Add optional `token` parameter to ploneClient initialization
plone/volto pull request #6077
Opened 2024-06-06 14:28 UTC by MAX-786

Fixes #6076 

----
📚 Documentation preview 📚: https://volto--6077.org.readthedocs.build/

2024-06-07 04:25 UTC, stevepiercy requested changes

2024-06-07 04:25 UTC, stevepiercy commented on packages/client/news/6076.documentation
> +Add documentaion about optional 'token' paramater to ploneClient initialization. @MAX-786
```suggestion
Add documentation about optional `token` parameter for `ploneClient` initialization. @MAX-786
```

2024-06-07 04:28 UTC, stevepiercy approved these changes
@djay I fixed spelling and some markup for @MAX-786. I think you mentioned this PR in https://github.com/collective/volto-hydra/pull/40?

2024-06-13 09:55 UTC, sneridagh approved these changes

2024-06-13 09:56 UTC, merged