When fetching content with GET_CONTENT, set the userSession.token value based on cookie
plone/volto pull request #6079
Opened 2024-06-07 07:08 UTC by tiberiuichim

A fix for #6071

The problem is like this: the userSession.token is written in 2 cases:

- normal login/logout
- [in the SSR rendered HTML from the server](https://github.com/plone/volto/blob/02fb83c812012e62cd2478de73735159c43e703d/packages/volto/src/server.jsx#L194)

With this change, when the user performs a `GET_CONTENT` (perhaps it should be a route change?), we trigger a fake login/logout success action, to mutate the `userSession.token` in the store.

2024-06-13 10:00 UTC, sneridagh commented
@tiberiuichim I assume this is WIP still, right? Ping me when you are done with it.

2024-08-02 21:36 UTC, stevepiercy commented
@tiberiuichim is this ready to merge? CI is all green.

2024-08-02 21:38 UTC, stevepiercy requested changes

2024-08-02 21:38 UTC, stevepiercy commented on packages/volto/src/middleware/api.js
> +
It's not clear why you would add commented code. Suggest removing all the above.

2024-08-27 22:04 UTC, davisagli approved these changes
Looks good and works as expected.

2024-08-27 22:13 UTC, merged