Fix typo in Appextras documentation
plone/volto pull request #6083
Opened 2024-06-07 10:23 UTC by fredvd

The ignore rule filters results from the match pattern, not from itself.

2024-06-07 10:53 UTC, stevepiercy requested changes
I took a stab at it, too, based on your intent. I also chose a couple of different words to make it easier to understand. Let me know what you think. Thank you!

2024-06-07 10:53 UTC, stevepiercy commented on docs/source/development/appextras.md
> +- `ignore`: The `ignore` key is for routes compatible with the [react-router's `matchPath`](https://v5.reactrouter.com/web/api/matchPath) property, and ignores all the results in the `match` rule.
I'd go one step further, assuming my following suggestion is correct. I don't know what a "rule" is in this context, but I do know what is a "key". Also using "ignore" as both a noun and a verb in the same sentence is very confusing.

```suggestion
- `ignore`: The `ignore` key is for routes compatible with the [react-router's `matchPath`](https://v5.reactrouter.com/web/api/matchPath) property, and excludes all the results from the `match` key.
```

2024-06-20 07:24 UTC, sneridagh commented
@fredvd could you take a look and confirm that all is good?

2025-03-29 10:51 UTC, sneridagh commented
@stevepiercy ready when you are.

2025-03-29 10:57 UTC, stevepiercy approved these changes

2025-03-29 10:57 UTC, stevepiercy approved these changes

2025-03-29 21:54 UTC, merged