fix: nonContentRoutes diff path
plone/volto pull request #6102
Opened 2024-06-14 08:30 UTC by giuliaghisini

fixed "diff" path in nonContentRoutes.
If we had a path like "/test/test-a/difference" where the last part of url contains the word 'diff' it was considered as non-content route and it was wrong

2024-06-14 08:37 UTC, pnicolli requested changes

2024-06-14 08:37 UTC, pnicolli commented on packages/volto/news/6102.fix
Change filename to 6102.bugfix, otherwise towncrier won't get it

2024-06-14 08:37 UTC, pnicolli commented on packages/volto/news/6102.fix
> +fixed 'diff' path for nonContentRoutes. @giuliaghisini
```suggestion
Fixed 'diff' path for nonContentRoutes. @giuliaghisini
```

Nice and clean with capitalized first letter 😄

2024-06-20 07:22 UTC, sneridagh approved these changes

2024-06-20 07:23 UTC, sneridagh commented
@giuliaghisini I fixed the changelog, although it seems that there is one test failing, could you please take a look? Thx!!

2024-06-25 07:46 UTC, merged