ci: make use of github actions
plone/volto pull request #6108
Opened 2024-06-17 15:47 UTC by FritzHoing

This pull-request improves the existing github-workflows:

- enhances modularity by encapsulating a common operation into a reusable action for easier maintenance
- avoids duplicating the same cleanup logic across multiple jobs

2024-06-17 15:47 UTC, mister-roboto commented
@FritzHoing you need to sign the Plone Contributor Agreement to merge this pull request. 

Learn about the Plone Contributor Agreement: https://plone.org/foundation/contributors-agreement

2024-06-18 00:26 UTC, stevepiercy commented
@FritzHoing this is a super useful contribution, but we can't accept it until you sign the [Plone Contributor Agreement](https://plone.org/foundation/contributors-agreement). This PR should also have a [change log entry](https://6.docs.plone.org/contributing/index.html#change-log-entry). Would you please take the necessary steps? Thank you!

2024-06-19 14:43 UTC, mister-roboto commented
@FritzHoing you need to sign the Plone Contributor Agreement to merge this pull request. 

Learn about the Plone Contributor Agreement: https://plone.org/foundation/contributors-agreement

2024-06-19 14:47 UTC, FritzHoing commented
Thank you very much for your feedback! I signed the Contributor Agreement on monday already and just need to wait for the approval. The changelog entry is now added in the hope that the type is set correct for ci improvements.

2024-06-20 07:17 UTC, sneridagh commented
@FritzHoing looks great! Thanks a lot for your contribution!

/cc @ericof

2024-06-20 07:18 UTC, sneridagh commented
@FritzHoing I just allowed the tests to run, could you please take a look? It seems something is missing.

2024-06-20 08:59 UTC, stevepiercy requested changes
This looks good, but tests are failing. I'll update it against `main` and see if that fixes it.

2024-06-20 08:59 UTC, stevepiercy commented on packages/volto/news/6108.internal
> +Improvement of the existing github-workflow by encapsulating a common operation into a reusable action for easier maintenance @FritzHoing
```suggestion
Improved the existing GitHub workflows by encapsulating a common operation into a reusable action for easier maintenance. @FritzHoing
```

2024-06-20 11:55 UTC, ericof approved these changes

2024-06-23 07:20 UTC, ichim-david requested changes

2024-06-23 07:20 UTC, ichim-david commented on .github/actions/pre_test_setup/action.yml
> +        run: make cypress-install
```suggestion
name: pre test Setup

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Enable corepack
      shell: bash
      run: corepack enable

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - uses: actions/cache@v4
      name: Setup pnpm cache
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      shell: bash
      run: pnpm i

    - name: Cache Cypress Binary
      uses: actions/cache@v4
      with:
        path: ~/.cache/Cypress
        key: binary-${{ inputs.node-version }}-${{ hashFiles('pnpm-lock.yaml') }}

    - name: Install Cypress if not in cache
      if: steps.cache-cypress-binary.outputs.cache-hit != 'true'
      shell: bash
      working-directory: packages/volto
      run: make cypress-install

inputs:
  node-version:
    description: 'Node.js version'
    required: true
```

2024-06-23 07:20 UTC, ichim-david commented on .github/workflows/acceptance.yml
> +        uses: ./.github/actions/pre_test_setup
```suggestion
      - uses: actions/checkout@v4

      - name: Pretest-Setup
        uses: ./.github/actions/pre_test_setup
        with:
          node-version: ${{ matrix.node-version }}
```

2024-06-23 07:20 UTC, ichim-david commented on .github/workflows/acceptance.yml
> +        uses: ./.github/actions/pre_test_setup
```suggestion
      - uses: actions/checkout@v4

      - name: Pretest-Setup
        uses: ./.github/actions/pre_test_setup
        with:
          node-version: ${{ matrix.node-version }}
```

2024-06-23 07:20 UTC, ichim-david commented on .github/workflows/acceptance.yml
> +        uses: ./.github/actions/pre_test_setup
```suggestion
      - uses: actions/checkout@v4

      - name: Pretest-Setup
        uses: ./.github/actions/pre_test_setup
        with:
          node-version: ${{ matrix.node-version }}
```

2024-06-23 07:20 UTC, ichim-david commented on .github/workflows/acceptance.yml
> +        uses: ./.github/actions/pre_test_setup
```suggestion
      - uses: actions/checkout@v4

      - name: Pretest-Setup
        uses: ./.github/actions/pre_test_setup
        with:
          node-version: ${{ matrix.node-version }}
```

2024-06-23 07:20 UTC, ichim-david commented on .github/workflows/acceptance.yml
> +        uses: ./.github/actions/pre_test_setup
```suggestion
      - uses: actions/checkout@v4

      - name: Pretest-Setup
        uses: ./.github/actions/pre_test_setup
        with:
          node-version: ${{ matrix.node-version }}
```

2024-06-23 07:20 UTC, ichim-david commented on .github/workflows/acceptance.yml
> +        uses: ./.github/actions/pre_test_setup
```suggestion
      - uses: actions/checkout@v4

      - name: Pretest-Setup
        uses: ./.github/actions/pre_test_setup
        with:
          node-version: ${{ matrix.node-version }}
```

2024-06-23 07:20 UTC, ichim-david commented on .github/workflows/acceptance.yml
> +        uses: ./.github/actions/pre_test_setup
```suggestion
      - uses: actions/checkout@v4

      - name: Pretest-Setup
        uses: ./.github/actions/pre_test_setup
        with:
          node-version: ${{ matrix.node-version }}
```

2024-06-23 07:20 UTC, ichim-david commented on .github/workflows/acceptance.yml
> +        uses: ./.github/actions/pre_test_setup
```suggestion
      - uses: actions/checkout@v4

      - name: Pretest-Setup
        uses: ./.github/actions/pre_test_setup
        with:
          node-version: ${{ matrix.node-version }}
```

2024-06-23 07:20 UTC, ichim-david commented on .github/workflows/acceptance.yml
> +        uses: ./.github/actions/pre_test_setup
```suggestion
      - uses: actions/checkout@v4

      - name: Pretest-Setup
        uses: ./.github/actions/pre_test_setup
        with:
          node-version: ${{ matrix.node-version }}
```

2024-06-23 07:20 UTC, ichim-david commented on .github/workflows/acceptance.yml
> +        uses: ./.github/actions/pre_test_setup
```suggestion
      - uses: actions/checkout@v4

      - name: Pretest-Setup
        uses: ./.github/actions/pre_test_setup
        with:
          node-version: ${{ matrix.node-version }}
```

2024-06-23 07:20 UTC, ichim-david commented on .github/workflows/acceptance.yml
> +        uses: ./.github/actions/pre_test_setup
```suggestion
      - uses: actions/checkout@v4

      - name: Pretest-Setup
        uses: ./.github/actions/pre_test_setup
        with:
          node-version: ${{ matrix.node-version }}
```

2024-06-23 07:20 UTC, ichim-david commented on .github/workflows/acceptance.yml
> +        uses: ./.github/actions/pre_test_setup
```suggestion
      - uses: actions/checkout@v4

      - name: Pretest-Setup
        uses: ./.github/actions/pre_test_setup
        with:
          node-version: ${{ matrix.node-version }}
```

2024-06-23 07:42 UTC, ichim-david approved these changes
I've commited the changes necessary to get the actions to work, tested and working.
I actually added a new pull request with the changes from this pull request plus my fixes but then I did the extra work to get commit suggestions which can commit to the parent as such I will close https://github.com/plone/volto/pull/6120

2024-06-23 08:31 UTC, stevepiercy requested changes
A couple questions, and some cleanup.

2024-06-23 08:31 UTC, stevepiercy commented on .github/workflows/acceptance.yml
> +      - uses: actions/checkout@v4
This is duplicated at line 14.

```suggestion
```

2024-06-23 08:31 UTC, stevepiercy commented on .github/actions/pre_test_setup/action.yml
> +      shell: bash
Is this necessary now? It wasn't there before. It makes sense to specify the shell when you need something that the shell provides, but not to just run a binary, as in this context.

2024-06-23 08:31 UTC, stevepiercy commented on .github/actions/pre_test_setup/action.yml
> +    - name: Install dependencies
`Install dependencies` was previously after `Cache Cypress Binary`. Does that matter, or affect performance?

2024-06-23 08:31 UTC, stevepiercy commented on packages/volto/news/6108.internal
> +Improved the existing GitHub workflows by encapsulating a common operation into a reusable action for easier maintenance. @FritzHoing
```suggestion
Improved the existing GitHub workflows by encapsulating a common operation into a reusable action for easier maintenance. @FritzHoing, @ichim-david
```

2024-06-23 08:31 UTC, stevepiercy commented on .github/actions/pre_test_setup/action.yml
> +      shell: bash
Another possibly unnecessary `shell: bash`?

2024-06-23 12:51 UTC, ichim-david commented
I made a branch out of the changes native to the volto repo in this pull request https://github.com/plone/volto/pull/6120
making it easier for me to handle change requests

2024-06-23 16:39 UTC, ichim-david commented
Closing this pull request in favor of https://github.com/plone/volto/pull/6120 since having the pull request within Volto repo makes it easier to make changes as needed.

2024-06-23 16:39 UTC, closed without merging