Fritz hoing Github actions improvements
plone/volto pull request #6120
Opened 2024-06-23 07:07 UTC by ichim-david

2024-06-23 07:43 UTC, ichim-david commented
Closing in favor of having commit suggestions to the original pull request https://github.com/plone/volto/pull/6108#pullrequestreview-2134173289

2024-06-23 12:49 UTC, ichim-david commented
@stevepiercy Have another look here, this pull request still contains the work of @FritzHoing with the right attribution plus my changes since it's very cumbersome todo suggest commits especially where it's a trial an error.
Every shell: bash is needed, you can look at the failures I got after removing them https://github.com/plone/volto/pull/6120/commits/f04c7419d0e7b85f907b9c1ef7ccdebe3a662da9
and all of the commits I did until the build was clean

2024-06-23 22:48 UTC, stevepiercy approved these changes
Thanks for the thorough verification of extracting all the repetitive steps, including bash requirement. I especially like that you added a name to an unnamed step. It's documentation! 😁 

@plone/volto-team this is good work that you could use as an example and apply to your own CI to avoid copy-pasta mistakes. Please take a moment to review.

2024-06-26 06:57 UTC, sneridagh commented
@ichim-david @FritzHoing Awesome work! Thanks for working on this. Could we find a better naming for the action? `pre_test_setup` is too vague for me, in anticipation that we could have more in the future. How about `node_pnpm_setup` or `setup_node_pnpm`? Ahhhh, naming, naming

2024-06-26 07:10 UTC, stevepiercy commented
I find naming a thing by what it does, not its tool name, is usually more descriptive and long-lived. If you ever change the tool (which _never_ happens in JavaScript), you don't have to change the name.

It creates a universal test setup, so `universal_test_setup` works for me.

2024-06-26 07:22 UTC, ichim-david commented
@sneridagh @stevepiercy I agree on the naming needs tweaking, it's for that reason that I replaced Pretest-Setup with 
name: Set up testing infrastructure when using it. Should that naming also be changed so something else?

I don't mind the universal_test_setup naming.
acceptance_test_setup?

Maybe you can come to an agreement on the naming and proposing it then, maybe talk with Eric and David and see what you guys thing makes most sense.

2024-06-26 07:37 UTC, sneridagh commented
@stevepiercy @ichim-david the fact is that it can be used outside acceptance, in unit and code quality too. It's setting up the node version and pnpm in the right way. Also, is not universal, as we can configure other things too, like Python...

2024-06-26 09:43 UTC, sneridagh commented
@stevepiercy and I, we discussed it and agreed on `node_env_setup`, @ichim-david opinion?

2024-06-26 09:45 UTC, ichim-david commented
@sneridagh I'm fine with it what about the step name?

2024-06-26 09:47 UTC, sneridagh commented
@ichim-david `Set up Node environment` ? @stevepiercy ?

2024-06-26 10:11 UTC, stevepiercy commented
Yup. We have a winner!

2024-06-26 10:17 UTC, ichim-david commented
@sneridagh done, let's see the testing and then a merge of main and I think it's good to go.

2024-06-26 10:29 UTC, stevepiercy requested changes
It's Node.js per https://nodejs.org/en

2024-06-26 10:29 UTC, stevepiercy commented on .github/actions/node_env_setup/action.yml
> +name: Set up NodeJS environment
This is the brand spelling. Please correct throughout.

```suggestion
name: Set up Node.js environment
```

2024-06-26 11:43 UTC, stevepiercy approved these changes

2024-06-26 14:02 UTC, merged