Refactored Blocks/ToC/Edits.jsx to functional component
plone/volto pull request #6167
Opened 2024-07-13 08:18 UTC by Prince0906

Ref: #4460 
### **About This PR**
This PR refactored > packages/volto/src/components/manage/Blocks/ToC/Edit.jsx from class based to functional component

**Before:**

https://github.com/user-attachments/assets/84673f37-1e76-4382-a247-02ac82645ea4

**After**

https://github.com/user-attachments/assets/b007d68f-960b-4105-b9b1-682136457548

This is my first time contrubuting to Volto .So,if I have done anything wrong in my PR, please give feedback and I will try to rectify that.

2024-07-13 17:23 UTC, Prince0906 commented
@stevepiercy Can you review my pr, it's ready to preview.

2024-07-14 06:54 UTC, stevepiercy requested changes
This needs review from a member of the @plone/volto-team.

I noticed several recent pull requests that provide similar refactors from newcomers. I'm curious whether this PR is part of a GSoC project or some other recruitment or discovery?

2024-07-14 06:54 UTC, stevepiercy commented on packages/volto/news/6167.feature
> +Refactor Blocks/Toc/Edit Component to functional component -@Prince0906
```suggestion
Refactor the table of contents block component from a class component to a functional component. @Prince0906
```

2024-07-14 06:59 UTC, ichim-david approved these changes

2024-07-14 07:33 UTC, stevepiercy approved these changes
LGTM.

2024-07-16 18:30 UTC, Prince0906 commented
> This needs review from a member of the @plone/volto-team.
> 
> I noticed several recent pull requests that provide similar refactors from newcomers. I'm curious whether this PR is part of a GSoC project or some other recruitment or discovery?

I am just exploring this things with my friends.

2024-07-16 18:30 UTC, Prince0906 commented
@sneridagh please review it

2024-07-19 14:20 UTC, Prince0906 commented
@sneridagh please review my pr

2024-07-20 12:28 UTC, stevepiercy commented
@Prince0906 you do not need to repeatedly `@` individual people. It is considered annoying and rude. I have already tagged the appropriate team.

2024-07-20 12:40 UTC, ichim-david commented
@Prince0906 Merging a pull request takes time and you need to be patient. There are some extra things to take into consideration when something is merged such as the need to mark something as breaking or not, or to think on what release version this change should be added.

The good news is that you have 2 approved reviews so this work will be merged however asking sneridan to review it
will not get your pull request merged quickly, instead you will get a notice about not repeatably messaging someone.

I know that you are anxious to have this merged  but again that takes time. While waiting if you see another issue that you would know how to tackle feel free to do so and we can help then just like we did now.

2024-07-20 13:23 UTC, Prince0906 commented
> @Prince0906 Merging a pull request takes time and you need to be patient. There are some extra things to take into consideration when something is merged such as the need to mark something as breaking or not, or to think on what release version this change should be added.
> 
> The good news is that you have 2 approved reviews so this work will be merged however asking sneridan to review it will not get your pull request merged quickly, instead you will get a notice about not repeatably messaging someone.
> 
> I know that you are anxious to have this merged but again that takes time. While waiting if you see another issue that you would know how to tackle feel free to do so and we can help then just like we did now.

Sorry for the mistake, I will be patient and will avoid making this mistake again.

2024-07-25 10:23 UTC, stevepiercy commented
I went through the original PLIP and found that this PR may duplicate work in https://github.com/plone/volto/pull/4961.

2024-07-25 10:28 UTC, Prince0906 commented
> I went through the original PLIP and found that this PR may duplicate work in #4961.

2024-07-25 10:43 UTC, Prince0906 commented
> I went through the original PLIP and found that this PR may duplicate work in #4961.

In that pr , Because of some other fixing all checks are not passing.

2024-07-25 11:02 UTC, stevepiercy commented
@Prince0906 OK. Thanks for confirming. I've put this (and dozens of other) PRs on our next Volto Team Meeting agenda. @plone/volto-team needs to do better with its management of PRs.

2024-07-27 15:27 UTC, Prince0906 commented
@stevepiercy I had updated the branch and this failed check is not related to my component.

2024-07-27 16:20 UTC, stevepiercy commented
@Prince0906 thanks for the update and confirming your results against the CI failing check. I restarted the [failing check](https://github.com/plone/volto/actions/runs/10124451422/job/27998815052?pr=6167) as it has a flaky test in it (metadata).

2024-07-27 16:33 UTC, stevepiercy commented
Flaky test passed. We need a final review before merging from @plone/volto-team to see if it is a breaking change, and compare against #4961.

2024-08-09 22:52 UTC, davisagli commented on packages/volto/src/components/manage/Blocks/ToC/Edit.jsx
> +  const { onChangeBlock, data, block, selected, navRoot, contentType, blocksErrors } = props;
```suggestion
  const {
      onChangeBlock,
      data,
      block,
      selected,
      navRoot,
      contentType,
      blocksErrors,
  } = props;
```

2024-08-10 03:54 UTC, davisagli commented on packages/volto/src/components/manage/Blocks/ToC/Edit.jsx
> +      blocksErrors,
```suggestion
    onChangeBlock,
    data,
    block,
    selected,
    navRoot,
    contentType,
    blocksErrors,
```

2024-08-10 04:27 UTC, davisagli approved these changes
Thanks for your contribution!

I'll go ahead and merge this, and take a separate look at https://github.com/plone/volto/pull/4961, which also includes a fix that is unrelated to the refactoring.

2024-08-10 04:27 UTC, merged