Refactored PersonalInformation
plone/volto pull request #6177
Opened 2024-07-21 17:32 UTC by Prince0906

Ref: #4460 
### **About This PR**
This PR refactored 

> packages/volto/src/components/manage/Preferences/PersonalInformation.jsx

 from class based to functional component.

2024-07-22 01:17 UTC, stevepiercy requested changes
Minor MyST syntax improvement.

2024-07-22 01:17 UTC, stevepiercy commented on packages/volto/news/6177.feature
> +Refactor the PersonalInformation component from a class component to a functional component. @Prince0906
```suggestion
Refactor the `PersonalInformation` component from a class component to a functional component. @Prince0906
```

2024-07-22 03:06 UTC, stevepiercy approved these changes
I approve only the news item. This PR needs a review from a @plone/volto-team member.

2024-07-22 10:22 UTC, ichim-david commented
@Prince0906 before you attempt to port the class based components to functional components you need to look also at the opened pull requests that tackle this task, in particular the ones opened by https://github.com/plone/volto/pulls/Tishasoumya-02
This is because the information from the issue is not fully up to date on what pull requests are opened
https://github.com/plone/volto/issues/4460

Doing so will ensure that you don't work for nothing doing duplicated work.

2024-08-14 04:20 UTC, davisagli commented
Thanks for your contribution, but I will close this PR because it is a duplicate of #5046 which was already in progress.

2024-08-14 04:20 UTC, closed without merging