fix: improve url regex
plone/volto pull request #6186
Opened 2024-07-23 09:07 UTC by mamico

2024-07-23 22:39 UTC, davisagli commented
@mamico Makes sense. Needs a towncrier entry before it's ready to merge.

2024-08-06 00:17 UTC, stevepiercy requested changes
Update news.

2024-08-06 00:17 UTC, stevepiercy commented on packages/volto/news/6186.feature
> +Improved url regex to allow non-public urls, such as https://intranet/ or file://server/share, e.g., for intranet. @mamico
We need to wrap URLs with backticks to make these inline literals, else linkcheckbroken attempts to visit the URL and fails.

```suggestion
Improved URL regex to allow non-public or intranet URLs, such as `https://intranet/` or `file://server/share`. @mamico
```

2024-08-06 00:20 UTC, stevepiercy approved these changes
@davisagli already approved in a comment in this PR, so I'm approving, too, so that it can be merged when CI is all green.

2024-08-06 00:30 UTC, merged