Refactored Edit component from class based to function based
plone/volto pull request #6187
Opened 2024-07-23 09:32 UTC by shiven16

### About This PR
This PR refactored:

> packages/volto-slate/src/blocks/Table/TableBlockEdit.jsx

from class based to function based component

Please review and provide feedback on my changes. I am committed to addressing any issues promptly.

2024-07-23 09:38 UTC, stevepiercy commented
@shiven16 please read and follow [Change log entry](https://6.docs.plone.org/contributing/index.html#change-log-entry) and [Linting](https://6.docs.plone.org/volto/contributing/linting.html).

2024-07-23 10:49 UTC, stevepiercy commented
@shiven16 please check [Change log entry](https://6.docs.plone.org/contributing/index.html#change-log-entry) and [Linting](https://6.docs.plone.org/volto/contributing/linting.html) again, and now check why the acceptance tests fail by comparing the GitHub workflow result against your local acceptance test run, as described in [Acceptance tests](https://6.docs.plone.org/volto/contributing/acceptance-tests.html). It might also be helpful for you to review the entire [Developer guidelines](https://6.docs.plone.org/volto/contributing/index.html#developer-guidelines), so that I don't have to keep pointing you to each thing that does not pass CI.

2024-07-23 11:06 UTC, shiven16 commented
> @shiven16 please check [Change log entry](https://6.docs.plone.org/contributing/index.html#change-log-entry) and [Linting](https://6.docs.plone.org/volto/contributing/linting.html) again, and now check why the acceptance tests fail by comparing the GitHub workflow result against your local acceptance test run, as described in [Acceptance tests](https://6.docs.plone.org/volto/contributing/acceptance-tests.html). It might also be helpful for you to review the entire [Developer guidelines](https://6.docs.plone.org/volto/contributing/index.html#developer-guidelines), so that I don't have to keep pointing you to each thing that does not pass CI.

I apologize for any inconvenience caused. I will ensure that all tests are run locally prior to committing changes to the repository.

2024-07-27 16:05 UTC, stevepiercy requested changes

2024-07-27 16:05 UTC, stevepiercy commented on packages/volto-slate/news/6187.feature
> +Refactored the Edit component(packages/volto-slate/src/blocks/Table/TableBlockEdit.jsx) from class based to function based.
Add MyST syntax. Give yourself credit!

```suggestion
Refactored the Edit component `packages/volto-slate/src/blocks/Table/TableBlockEdit.jsx` from class based to function based. @shiven16
```

2024-07-27 16:06 UTC, stevepiercy commented
@shiven16 please read and follow [Code quality](https://6.docs.plone.org/volto/contributing/index.html#code-quality). You should run all of these checks locally to ensure they pass before creating a pull request. Then you can compare your results against the GitHub workflows. 

See also [Update your pull request from your fork](https://6.docs.plone.org/contributing/first-time.html#update-your-pull-request-from-your-fork).

2024-07-27 16:10 UTC, stevepiercy reviewed
@sneridagh this component is not on the list from the PLIP #4460.

Do want the volto-slate components, including this one, to be refactored as well? If so, then would you please update the list accordingly?

2024-07-28 18:56 UTC, stevepiercy reviewed
This PR needs technical review by a @plone/volto-team member.

2024-07-28 18:58 UTC, stevepiercy commented
@shiven16 what was the result of running tests locally? Why do you think the CI checks fail?

See also [Update your pull request from your fork](https://6.docs.plone.org/contributing/first-time.html#update-your-pull-request-from-your-fork).

2026-05-18 08:01 UTC, davisagli commented
This was done in https://github.com/plone/volto/pull/7760

2026-05-18 08:01 UTC, closed without merging