Refactor Aliases.jsx.
plone/volto pull request #6196
Opened 2024-07-25 16:10 UTC by FreakForever

Refactored Aliases.jsx from class-based component to functional-based component.

See #4460.

2024-07-25 20:32 UTC, stevepiercy commented
@FreakForever please read and follow [Code quality](https://6.docs.plone.org/volto/contributing/index.html#code-quality). You should run all of these checks locally to ensure they pass before creating a pull request. Then you can compare your results against the GitHub workflows. As a bonus, fewer CI runs means consuming less electricity.

2024-07-26 13:54 UTC, stevepiercy commented
@plone/volto-team this is ready for technical review.

2024-08-13 00:46 UTC, davisagli requested changes

2024-08-13 00:46 UTC, davisagli commented on packages/volto/src/components/manage/Aliases/Aliases.jsx
> +};
The functional component should use getSelector, getLocation, and getDispatch, instead of using `connect`

2024-09-04 05:30 UTC, davisagli commented on packages/volto/src/components/manage/Aliases/Aliases.jsx
> +};
I'll close this to reduce noise in the list of PRs for review. If you update it, you can ask us to reopen it.

2024-09-04 05:30 UTC, closed without merging