Refactor DatetimeWidget
plone/volto pull request #6213
Opened 2024-07-28 14:31 UTC by Raman-Luhach

Refactored DatetimeWidget.jsx from class-based to functional-based component.

2024-08-05 10:44 UTC, Tishasoumya-02 commented
@Raman-Luhach  Since you opened this PR from a forked repo , it will be a hassle to test this on our local machine, it would be better if you create a branch in this repo and then have a PR for it. Same goes for your other open PRs also.

2024-08-13 00:47 UTC, davisagli requested changes

2024-08-13 00:47 UTC, davisagli commented on packages/volto/src/components/manage/Widgets/DatetimeWidget.jsx
> +    intl,
The functional component should use useIntl instead of getting passed `intl` as a prop.

2024-08-21 20:07 UTC, Raman-Luhach commented
@davisagli I have made changes as requested. Sorry for the delay. Please review the code.

2024-08-24 04:39 UTC, davisagli requested changes

2024-08-24 04:39 UTC, davisagli commented on packages/volto/src/components/manage/Widgets/DatetimeWidget.jsx
> +    lang,
```suggestion
```

2024-08-24 04:39 UTC, davisagli commented on packages/volto/src/components/manage/Widgets/DatetimeWidget.jsx
> +  const intl = useIntl();
```suggestion
  const intl = useIntl();
  const lang = intl.locale;
```

2024-08-24 04:39 UTC, davisagli commented on packages/volto/src/components/manage/Widgets/DatetimeWidget.jsx
>  )(DatetimeWidgetComponent);
Replace lines 293-299 with:
```
export default injectLazyLibs(['reactDates', 'moment'])(DatetimeWidgetComponent);
```

2024-09-04 04:49 UTC, davisagli approved these changes
Thanks!

2024-09-04 04:49 UTC, merged