Add Cypress test for search block sort on property
plone/volto pull request #6224
Opened 2024-08-01 15:35 UTC by iRohitSingh

2024-08-01 15:35 UTC, iRohitSingh commented
<img width="483" alt="Screenshot 2024-08-01 at 9 00 43 PM" src="https://github.com/user-attachments/assets/c40ed039-a551-4efe-a150-65cad711e95c">

2024-08-02 07:19 UTC, nileshgulia1 reviewed
LGTM. Also please add a changelog.

2024-08-02 07:49 UTC, stevepiercy requested changes
For `it` statements, we should use the common name, not a technical name. I removed trailing spaces from several selectors. I fixed some grammatical and other issues in comments and `it` statements.

2024-08-02 07:49 UTC, stevepiercy commented on packages/volto/cypress/tests/core/blocks/blocks-search.js
> +  it('Search block - test on select 1 sort on in listin criteria sorton', () => {
```suggestion
  it('Search block - test on select 1 sort on in listing criteria sort on', () => {
```

2024-08-02 07:49 UTC, stevepiercy commented on packages/volto/cypress/tests/core/blocks/blocks-search.js
> +    // Add one soron options below
```suggestion
    // Add one sort on option below
```

2024-08-02 07:49 UTC, stevepiercy commented on packages/volto/cypress/tests/core/blocks/blocks-search.js
> +  it('Search block - test on Only one sortOn options below.', () => {
```suggestion
  it('Search block - test on only one sort on option below.', () => {
```

2024-08-02 07:49 UTC, stevepiercy commented on packages/volto/cypress/tests/core/blocks/blocks-search.js
> +  it('Search block - test on Select both Listing sorton and Sorton options', () => {
```suggestion
  it('Search block - test on select both listing sort on and sort on options', () => {
```

2024-08-02 07:49 UTC, stevepiercy commented on packages/volto/cypress/tests/core/blocks/blocks-search.js
> +    //save page
```suggestion
    // save page
```

2024-08-02 07:49 UTC, stevepiercy commented on packages/volto/cypress/tests/core/blocks/blocks-search.js
> +    cy.get('#select-search-sort-on  ').click();
```suggestion
    cy.get('#select-search-sort-on').click();
```

2024-08-02 07:49 UTC, stevepiercy commented on packages/volto/cypress/tests/core/blocks/blocks-search.js
> +    cy.get('#select-search-sort-on  ').click();
```suggestion
    cy.get('#select-search-sort-on').click();
```

2024-08-02 07:49 UTC, stevepiercy commented on packages/volto/cypress/tests/core/blocks/blocks-search.js
> +    cy.get('#select-search-sort-on  ').click();
```suggestion
    cy.get('#select-search-sort-on').click();
```

2024-08-02 09:04 UTC, iRohitSingh commented on packages/volto/cypress/tests/core/blocks/blocks-search.js
> +  it('Search block - test on select 1 sort on in listin criteria sorton', () => {
Done.

2024-08-02 09:04 UTC, iRohitSingh commented on packages/volto/cypress/tests/core/blocks/blocks-search.js
> +  it('Search block - test on Select both Listing sorton and Sorton options', () => {
Done.

2024-08-02 09:04 UTC, iRohitSingh commented on packages/volto/cypress/tests/core/blocks/blocks-search.js
> +    //save page
Done

2024-08-02 09:04 UTC, iRohitSingh commented on packages/volto/cypress/tests/core/blocks/blocks-search.js
> +    cy.get('#select-search-sort-on  ').click();
Done.

2024-08-02 09:04 UTC, iRohitSingh commented on packages/volto/cypress/tests/core/blocks/blocks-search.js
> +    cy.get('#select-search-sort-on  ').click();
Done.

2024-08-02 09:05 UTC, iRohitSingh commented on packages/volto/cypress/tests/core/blocks/blocks-search.js
> +    // Add one soron options below
Done.

2024-08-02 09:43 UTC, stevepiercy approved these changes
LGTM.

2024-08-02 09:55 UTC, stevepiercy commented
I'll rerun the failing CI checks to see if they're just flaky.

2024-08-02 16:05 UTC, davisagli approved these changes

2024-08-02 16:05 UTC, merged