Move Tags component to the slot belowContent
plone/volto pull request #6269
Opened 2024-08-23 20:58 UTC by wesleybl

Also remove showTags setting.

Ref: https://github.com/plone/volto/pull/4381#issuecomment-2276168262

2024-08-23 21:11 UTC, wesleybl commented
I removed showTags, but I don't know if it's the best option. It might make it easier to remove the tags.

CC @davisagli

2024-08-23 23:03 UTC, stevepiercy requested changes
Add a little MyST markup to the news.

Otherwise this looks OK to me, but one more person should give a technical review.

2024-08-24 04:25 UTC, davisagli reviewed
I think this makes sense for Volto 18. Removing the showTags setting and changing the parameters expected by the Tags component are breaking changes that can't be backported.

2024-08-24 14:46 UTC, erral requested changes
Here you are changing the internal contract or the Tags component, which needs proper Upgrade Notes.

If it isn't completely necessary I wouldn't change the component itself, I would just do the slots thing.

2024-08-26 02:18 UTC, davisagli commented
> If it isn't completely necessary I wouldn't change the component itself, I would just do the slots thing.

@erral The change is necessary in order to accept the parameters that are passed to slot components. (They get `content`, not `tags`.)

2024-08-26 12:56 UTC, wesleybl commented
@erral @davisagli I changed the news to breaking and put a note in the update guide.

2024-08-26 13:01 UTC, erral approved these changes

2024-08-26 15:58 UTC, davisagli commented
@wesleybl On second thought, I think we should keep the `showTags` setting. It's very easy to check it (inside the Tags component) and makes it easier for someone who is upgrading a site that disabled the tags (so they don't need to figure out how to override the slot component).

2024-08-26 18:25 UTC, wesleybl commented
@davisagli I brought the `showTags` setting back.

2024-08-26 18:29 UTC, davisagli commented on packages/volto/news/6269.breaking
> +Move Tags component to the slot `belowContent`. @wesleybl
```suggestion
Move `Tags` component to the slot `belowContent`. @wesleybl
```

2024-08-26 18:30 UTC, davisagli approved these changes

2024-08-26 18:45 UTC, merged