Core js splitting - second part
plone/volto pull request #6310
Opened 2024-09-24 13:56 UTC by giuliaghisini

2024-09-27 08:15 UTC, pnicolli requested changes

2024-09-27 08:15 UTC, pnicolli commented on packages/volto/src/components/theme/Widgets/DatetimeWidget.test.js
> +// );
Cleanup

2024-09-27 12:55 UTC, giuliaghisini commented
@ichim-david @sneridagh pr is ready for review. 
Unfortunatly a cypress test for 'locking' fails, but i don't understand why... no code related to locking is touched by this pr.. do you have some idea?

2024-09-27 12:58 UTC, ichim-david commented
@giuliaghisini maybe it's a flaky test that passes after a re run or increase of wait timer. I will have a look at this next week when I'm back to work, right now I'm waiting for the flight delay to pass :)
Thank you for the work so far, I cannot wait to test it :)

2024-10-29 10:59 UTC, pnicolli commented
@ichim-david yeah I was looking at this right now and I don't think there will be time to polish this before thursday. The fact that most acceptance runs break makes me think something needs to be fixed and it's not just flakiness

2026-05-18 10:37 UTC, davisagli commented
There was a test stability problem that was never resolved, and by now this has a lot of conflicts. We can revisit this if someone is willing to bring it up to date.

2026-05-18 10:37 UTC, closed without merging