Increase specificity of table header style selector
plone/volto pull request #6333
Opened 2024-09-26 09:23 UTC by jackahl

2024-09-26 10:54 UTC, JeffersonBledsoe commented
Some details on the change:
Current contrast ratio as tested by [WebAIM](https://webaim.org/resources/contrastchecker/) is 6.66:1 which surpasses the 4.5:1 contrast ratio required for 'normal' size text required by WCAG 2.2 SC 1.4.3 Contrast Minimum (AA). The body text doesn't meet SC 1.4.6 Contrast Enhanced, but I don't see this as an issue as we generally don't aim for AAA.

Screenshot of the PR in it's current state is below. 

<img width="865" alt="Screenshot showing light blue text against a dark background" src="https://github.com/user-attachments/assets/c35763d4-ac16-4c63-87f4-aa3dbbb45486">.

2024-09-26 10:55 UTC, JeffersonBledsoe requested changes

2024-09-26 12:30 UTC, JeffersonBledsoe approved these changes
Looks good!

2024-09-27 23:17 UTC, pnicolli approved these changes

2024-09-27 23:17 UTC, merged