fixes issue #6283 and #6300
plone/volto pull request #6337
Opened 2024-09-26 12:44 UTC by viveak910

Fixed issue https://github.com/plone/volto/issues/6283 with proxy requests not setting `X-Real-IP`, `X-Forwarded-For`, and `X-Forwarded-Host` headers correctly.

2024-09-26 15:12 UTC, viveak910 commented
Could someone take a look when they get a chance? Let me know if anything needs to be changed or if it’s good to go! 🙌

2024-09-26 22:38 UTC, stevepiercy requested changes

2024-09-26 22:38 UTC, stevepiercy commented on packages/volto/CHANGELOG.md
Do not edit this file. Instead see https://6.docs.plone.org/contributing/index.html#change-log-entry

2024-09-26 22:38 UTC, stevepiercy commented on packages/volto/src/express-middleware/devproxy.js
The comments are excessive and redundant. Just one is fine, thank you!

2024-09-27 17:36 UTC, viveak910 commented
yeah got it @stevepiercy

2024-09-27 20:59 UTC, stevepiercy approved these changes
News is OK. This needs technical review from @plone/volto-team.

2024-09-27 20:59 UTC, stevepiercy commented on packages/volto/news/6283.bugfix
> +- Fixed proxy request handling by setting appropriate headers in `devproxy.js` @viveak910
```suggestion
- Fixed proxy request handling by setting appropriate headers in `devproxy.js`. @viveak910
```

2024-09-27 21:17 UTC, stevepiercy commented
@viveak910 did you run tests locally? Please take care. See https://6.docs.plone.org/volto/contributing/testing.html and https://6.docs.plone.org/volto/contributing/acceptance-tests.html

2024-10-02 11:05 UTC, sneridagh commented
@djay @JeffersonBledsoe could you review this, please?

2024-10-04 17:56 UTC, djay approved these changes

2024-10-05 02:45 UTC, viveak910 commented
Hi, everyone. I’m new to this process, and I wanted to check if my PR has been merged or just approved. Should I close the PR myself now that the changes have been approved, or will someone else handle it? Thanks!

2024-10-05 03:25 UTC, stevepiercy commented
@viveak910 a member of the Volto Team will merge the PR. Please do not close and reopen the PR, as each action sends a notification to all subscribers, needlessly spamming them and making them grumpy.

2024-10-15 22:20 UTC, davisagli requested changes

2024-10-15 22:20 UTC, davisagli commented on packages/volto/src/express-middleware/devproxy.js
> +      proxyReq.setHeader('X-Forwarded-For', req.ip);
If the incoming request already has X-Forwarded-For from another proxy, we should keep that value and add req.ip to the end of the list: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For

2024-10-22 03:25 UTC, davisagli requested changes

2024-10-22 03:25 UTC, davisagli commented on package.json
> +    "vitest": "^2.1.2"
Why/how did you update these dependencies? They should not be included in the PR unless they are required for the change to the proxy. (Same thing for the changes in pnpm-lock.yaml)

2024-12-19 17:51 UTC, closed without merging