Update Italian Italian translations. @gianniftp
plone/volto pull request #6342
Opened 2024-09-27 09:21 UTC by gianniftp

https://github.com/plone/volto/pull/6340#discussion_r1777333114

2024-09-27 11:19 UTC, pnicolli commented on packages/volto/locales/it/LC_MESSAGES/volto.po
> +msgstr "Vuoi cancellare l'elemento sezionato?"
```suggestion
msgstr "Vuoi cancellare l'elemento selezionato?"
```

2024-09-27 11:19 UTC, pnicolli commented on packages/volto/locales/it/LC_MESSAGES/volto.po
> +msgstr "Non è consentito selezionare contemporaneamente la definizione della password e la richiesta dell'invio del messaggio di reimpostazione della password tramite e-mail. È necessario selezionare
```suggestion
msgstr "Non è consentito effettuare contemporaneamente l'inserimento della password e la richiesta dell'invio del messaggio di reimpostazione della password tramite e-mail. È necessario selezionare una di esse."
```

2024-09-27 11:19 UTC, pnicolli commented on packages/volto/locales/it/LC_MESSAGES/volto.po
> +msgstr "Non è consentito selezionare contemporaneamente la definizione della password e la richiesta dell'invio del messaggio di reimpostazione della password tramite e-mail. È necessario selezionare
Suggerisco questa versione che mi sembra più semplice e diretta

2024-09-27 13:36 UTC, Wagner3UB approved these changes

2024-09-27 23:11 UTC, pnicolli approved these changes

2024-09-27 23:15 UTC, pnicolli requested changes

2024-09-27 23:15 UTC, pnicolli commented on packages/volto/news/+update_it.feature
Rename this file to `6342.feature`

2024-09-27 23:15 UTC, pnicolli commented on packages/volto/news/+update_it.feature
> +Update Italian Italian translations. @gianniftp
```suggestion
Updated Italian translations. @gianniftp
```
We usually try to use past tenses in order to tell "what was done" in the PR

2024-09-29 07:23 UTC, pnicolli approved these changes

2024-09-29 07:23 UTC, merged