Video block new embed
plone/volto pull request #6359
Opened 2024-10-01 09:06 UTC by jackahl

Replacing the semantic ui embed component with a custom one, to allow for more flexibility especially in regards to accessibility. This does mainly address issues raised in #5731.

2024-10-01 15:28 UTC, jackahl commented
@sneridagh should this new component be moved to the volto components package or shall it stay in there core package?

2024-10-02 11:38 UTC, sneridagh commented
@jackahl LGTM, however, I'd put the component as general available component (and, eventually, transfer it to `@plone/components`, but that's for later, if Volto has to use it right away).

2024-10-09 05:13 UTC, stevepiercy requested changes
Grammar fixes.

2024-10-09 05:13 UTC, stevepiercy commented on packages/volto/news/6359.feature
> +create new video embed component for usage in video block helping to fix a11y issues with the semantic ui one @jackahl
```suggestion
Created a new `VideoEmbed` component for usage in a video block, helping to fix a11y issues with the Semantic UI one. @jackahl
```

2024-10-09 05:13 UTC, stevepiercy commented on packages/volto/locales/volto.pot
> +#. Default: "The videos title is not displayed, but only used for accessibility reasons to identify the video for screen reader users. If the Video is already sufficiently titled by a headline above,
There was a bad copy paste throughout, so I will only make a suggestion on this one instance which should be applied to all instances.

```suggestion
#. Default: "The video's title is not displayed, but only used for accessibility reasons to identify the video for screen reader users. If the video is already sufficiently titled by a headline above, then leave this field empty."
```

2025-04-07 11:11 UTC, iRohitSingh commented
@sneridagh What should be the behavior when someone pass the autoplay:true in video block. Video should start playing automatically when page loads right?

2025-07-24 13:15 UTC, sneridagh commented
@iRohitSingh please make CI pass too, and solve conflicts.

2025-09-08 14:58 UTC, davisagli commented
@jackahl Btw, this probably has to be merged with the work that is almost ready to merge in https://github.com/plone/volto/pull/7318

2025-12-01 08:37 UTC, iRohitSingh commented
@jackahl @davisagli Any progress regarding this ?

2025-12-16 11:19 UTC, jackahl commented
@iRohitSingh this still needs some work on it to get it correctly working, simplify the source detection syntax and get tests passing. If you have the time to work on that, please do

2026-02-05 05:49 UTC, davisagli commented on packages/volto/locales/ca/LC_MESSAGES/volto.po
> -msgstr "Introduïu un URL vàlid suprimint el bloc i afegint un bloc de vídeo nou."
Make sure we don't remove existing translations. (here and in the other locales)

2026-02-05 05:51 UTC, davisagli commented on packages/volto/src/components/manage/Blocks/Video/schema.js
> +      'The videos title is not displayed, but only used for accessibility reasons to identify the video for screen reader users. If the Video is already sufficiently titled by a headline above, pleas
```suggestion
    id: 'VideoTitleDescription',
    defaultMessage:
      'The video's title is not displayed, but only used for accessibility reasons to identify the video for screen reader users. If the video is already sufficiently titled by a headline above, please leave this field empty.',
```
(and make sure you update i18n)

2026-02-05 05:54 UTC, davisagli commented on packages/volto/news/6359.breaking
This should be .breaking since it's in the public UI and potentially breaks styles written for the old markup.

@sneridagh Can we include this for volto 19?

2026-02-05 05:54 UTC, davisagli commented on packages/volto/src/components/index.js
> +export { default as VideoEmbed } from '@plone/volto/components/theme/VideoEmbed/VideoEmbed';
Don't add this, we are trying to get rid of barrel imports, not add to them.

2026-02-05 06:00 UTC, davisagli commented on packages/volto/src/components/theme/VideoEmbed/VideoEmbed.jsx
> +  const PlayVideo = () => {
This should use useCallback so that a new function isn't created on every render.

2026-02-05 06:00 UTC, davisagli commented on packages/volto/src/components/theme/VideoEmbed/VideoEmbed.jsx
> +  const getSrc = () => {
This should use useCallback so that a new function isn't created on every render.

2026-02-05 06:12 UTC, davisagli commented on packages/volto/src/components/manage/Blocks/Video/Body.jsx
> +            <iframe title="Peertube video iframe" {...iframeSettings}></iframe>
It's a little inconsistent that showing a peertube video does NOT use the VideoEmbed component even though it also uses an iframe. Don't we want peertube videos to use the same play button, support the preview image, etc?

2026-02-09 22:17 UTC, stevepiercy commented on docs/source/blocks/settings.md
> +[Peertube](https://joinpeertube.org/) is a free and open-source, decentralized, ActivityPub federated video platform.
```suggestion
[Peertube](https://joinpeertube.org/) is a free and open source, decentralized, ActivityPub federated video platform.
```

2026-02-09 22:17 UTC, stevepiercy commented on docs/source/blocks/settings.md
> +You can configure the video block to use other instances of Peertube by adding them to the `allowedPeertubeInstances` array in your project configuration object, as shown in the following example.
```suggestion
To configure the video block to use other instances of Peertube, add them to the `allowedPeertubeInstances` array in your project configuration object, as shown in the following example.
```

2026-02-09 22:18 UTC, stevepiercy commented on packages/volto/news/6870.feature
> +Allow other sources like peertube instances in Video block via blocks configuration. @ionlizarazu
```suggestion
Allow other sources, including Peertube instances, in the Video block via blocks configuration. @ionlizarazu
```

2026-02-09 22:19 UTC, stevepiercy commented on packages/volto/news/6359.feature
> +Created a new `VideoEmbed` component for usage in a video block, helping to fix a11y issues with the Semantic UI one. @jackahl
Better to spell out abbreviations in a change log.

```suggestion
Created a new `VideoEmbed` component for usage in a video block, helping to fix accessibility issues with the Semantic UI one. @jackahl
```

2026-02-09 22:21 UTC, stevepiercy commented on packages/volto/locales/volto.pot
> +#. Default: "The videos title is not displayed, but only used for accessibility reasons to identify the video for screen reader users. If the Video is already sufficiently titled by a headline above,
This should not have been resolved. Please use the possessive form, not the plural, and apply throughout. Thank you!

2026-02-09 22:27 UTC, davisagli commented on packages/volto/locales/volto.pot
> +#. Default: "The videos title is not displayed, but only used for accessibility reasons to identify the video for screen reader users. If the Video is already sufficiently titled by a headline above,
@stevepiercy I resolved it because I made a new comment with the same feedback in the location where the message is actually defined. Once it's fixed there, `make i18n` will update the default in all the .po files.

2026-02-10 14:02 UTC, iRohitSingh commented on packages/volto/locales/ca/LC_MESSAGES/volto.po
> -msgstr "Introduïu un URL vàlid suprimint el bloc i afegint un bloc de vídeo nou."
Done.

2026-02-10 14:02 UTC, iRohitSingh commented on packages/volto/src/components/manage/Blocks/Video/schema.js
> +      'The videos title is not displayed, but only used for accessibility reasons to identify the video for screen reader users. If the Video is already sufficiently titled by a headline above, pleas
Done

2026-02-10 14:02 UTC, iRohitSingh commented on packages/volto/src/components/index.js
> +export { default as VideoEmbed } from '@plone/volto/components/theme/VideoEmbed/VideoEmbed';
Done

2026-02-10 14:02 UTC, iRohitSingh commented on packages/volto/src/components/theme/VideoEmbed/VideoEmbed.jsx
> +  const PlayVideo = () => {
Done.

2026-02-10 14:03 UTC, iRohitSingh commented on packages/volto/src/components/theme/VideoEmbed/VideoEmbed.jsx
> +  const getSrc = () => {
Done.

2026-02-10 14:03 UTC, iRohitSingh commented on packages/volto/src/components/manage/Blocks/Video/Body.jsx
> +            <iframe title="Peertube video iframe" {...iframeSettings}></iframe>
Done

2026-02-10 14:03 UTC, iRohitSingh commented on docs/source/blocks/settings.md
> +[Peertube](https://joinpeertube.org/) is a free and open-source, decentralized, ActivityPub federated video platform.
Done.

2026-02-10 14:03 UTC, iRohitSingh commented on docs/source/blocks/settings.md
> +You can configure the video block to use other instances of Peertube by adding them to the `allowedPeertubeInstances` array in your project configuration object, as shown in the following example.
Done.

2026-02-10 14:03 UTC, iRohitSingh commented on packages/volto/news/6870.feature
> +Allow other sources like peertube instances in Video block via blocks configuration. @ionlizarazu
Done.

2026-02-10 14:03 UTC, iRohitSingh commented on packages/volto/news/6359.feature
> +Created a new `VideoEmbed` component for usage in a video block, helping to fix a11y issues with the Semantic UI one. @jackahl
Done.

2026-02-11 23:55 UTC, davisagli commented on packages/volto/locales/ca/LC_MESSAGES/volto.po
> -msgstr "Introduïu un URL vàlid suprimint el bloc i afegint un bloc de vídeo nou."
@iRohitSingh I meant for ALL of the locales. This is not the only one where this translation was removed.

2026-02-12 00:01 UTC, davisagli commented on packages/volto/src/components/theme/VideoEmbed/VideoEmbed.jsx
> +  const PlayVideo = () => {
@iRohitSingh The PlayVideo function is still created on every render.

2026-02-17 08:23 UTC, iFlameing commented
@davisagli can you please review this pr. I think it is ready.

2026-02-17 18:25 UTC, davisagli commented
@iFlameing See above, I already made some new comments after @iRohitSingh's latest changes.

Here is what still needs to be fixed:
- don't remove existing translations (for all locales)
- changelog should be .breaking
- the PlayVideo function should use useCallback so it is not created on every render

2026-02-18 07:38 UTC, sneridagh commented on packages/volto/news/6359.breaking
@davisagli yes, we can include it in 19!

@jackahl @iRohitSingh What is left to do in here? Could you please got through David's suggestions? Thanks!

2026-02-18 14:17 UTC, iFlameing commented
@davisagli I did the review of code and now.

1. don't remove existing translations (for all locales)(I checked and now we are only adding.)
2. changelog should be .breaking (done)
3. the PlayVideo function should use useCallback so it is not created on every render (it is also wrapped in callback).

cc @sneridagh

2026-02-18 15:54 UTC, sneridagh commented on docs/source/blocks/settings.md
> +To configure the video block to use other instances of Peertube, add them to the `allowedPeertubeInstances` array in your project configuration object, as shown in the following example.
Not clear why people need to do that. Do we whitelist them in the code?

2026-02-18 22:29 UTC, stevepiercy commented on docs/source/blocks/settings.md
> +To configure the video block to use other instances of Peertube, add them to the `allowedPeertubeInstances` array in your project configuration object, as shown in the following example.
PeerTube is federated and not centralized, like Mastodon. Plone has its own Mastodon instance of plone.social, as an example.

2026-02-19 03:18 UTC, davisagli commented on docs/source/blocks/settings.md
> +To configure the video block to use other instances of Peertube, add them to the `allowedPeertubeInstances` array in your project configuration object, as shown in the following example.
This is the whitelist.

2026-02-19 03:19 UTC, davisagli approved these changes
LGTM

2026-02-19 07:50 UTC, merged