Volto form block fixes
plone/volto pull request #6370
Opened 2024-10-03 15:09 UTC by robgietema

- [ ] I signed and returned the [Plone Contributor Agreement](https://plone.org/foundation/contributors-agreement), and received and accepted an invitation to join a team in the Plone GitHub organization.
- [ ] I verified there aren't other open [pull requests](https://github.com/plone/volto/pulls) for the same change.
- [ ] I followed the guidelines in [Contributing to Volto](https://6.docs.plone.org/volto/contributing/index.html).
- [ ] I succesfully ran [code linting checks](https://6.docs.plone.org/volto/contributing/linting.html) on my changes locally.
- [ ] I succesfully ran [unit tests](https://6.docs.plone.org/volto/contributing/testing.html) on my changes locally.
- [ ] I succesfully ran [acceptance tests](https://6.docs.plone.org/volto/contributing/acceptance-tests.html) on my changes locally.
- [ ] If needed, I added new tests for my changes.
- [ ] If needed, I added [documentation](https://6.docs.plone.org/volto/contributing/documentation.html#narrative-documentation) for my changes, either in the Storybook or narrative documentation.
- [ ] I included a [change log entry](https://6.docs.plone.org/contributing/index.html#contributing-change-log-label) in my commits.

-----

If your pull request closes an open issue, include the exact text below, immediately followed by the issue number. When your pull request gets merged, then that issue will close automatically.

Closes #

2024-10-04 00:58 UTC, davisagli requested changes
Please add release notes and fix the lint errors.

2024-10-17 08:49 UTC, stevepiercy commented
This PR should also render its Storybook. We recently merged a PR that should fix the pull request preview build on Netlify:
https://github.com/plone/volto/pull/6410

The Netlify build currently fails to recognize changes in the most recent commit:
https://app.netlify.com/sites/plone-components/deploys/670fb4bff3f6740008e0d09f

2024-12-21 09:06 UTC, stevepiercy requested changes
I reviewed only the `.pot` and news, both of which look good, with a couple of MyST markup enhancements and a question.

Will this PR need developer documentation? For example:

- https://6.docs.plone.org/volto/development/widget.html

2024-12-23 22:30 UTC, robgietema commented
> I reviewed only the `.pot` and news, both of which look good, with a couple of MyST markup enhancements and a question.
> 
> Will this PR need developer documentation? For example:
> 
> * https://6.docs.plone.org/volto/development/widget.html

The issues are fixed. The page for those widgets is about declaring widgets in the backend not the frontend so doesn't make sense to add anything on that page.

2024-12-23 22:35 UTC, robgietema commented
> Please add release notes and fix the lint errors and failing unit tests.

Done

2025-01-28 06:15 UTC, davisagli requested changes
In general this has a lot of useful improvements, but still some rough edges and missing docs.

2025-01-28 06:15 UTC, davisagli commented on packages/volto/src/components/manage/Widgets/RadioGroupWidget.jsx
> +class RadioGroupWidget extends Component {
It would be nice to add new components as function-style components so we don't have to rewrite them later.

2025-01-28 06:15 UTC, davisagli commented on packages/volto/src/components/manage/Blocks/Block/BlocksForm.jsx
> +    if (e.key === 'Enter' && !disableEnter && !blockConfig.disableEnter) {
disableEnter in blockConfig is not documented

2025-01-28 06:15 UTC, davisagli commented on packages/volto/src/components/manage/Form/Form.jsx
> +                      component={this.props.component}
Why do you pass `component` to the Field here and on line 949? I don't see where it is used?

2025-01-28 06:15 UTC, davisagli commented on packages/volto/news/6370.feature
> +Add option to choose bewteen icon and text buttons in the form component. @robgietema
```suggestion
Add option to choose between icon and text buttons in the form component. @robgietema
```

2025-01-28 06:15 UTC, davisagli commented on packages/volto/src/components/manage/Form/Form.jsx
> +    if (requestError && prevProps.requestError !== requestError) {
This looks like a bugfix which isn't mentioned in the changelog.

2025-01-28 06:15 UTC, davisagli commented on packages/volto/src/components/manage/Form/Form.jsx
> +          ),
Missing in changelog?

2025-01-28 06:28 UTC, davisagli requested changes

2025-01-28 06:28 UTC, davisagli commented on packages/volto/src/components/manage/Widgets/SchemaWidget.jsx
> +      },
I tried adding a queryParameterName to a field in a content type schema, but it doesn't do anything.

2025-01-28 06:28 UTC, davisagli commented on packages/volto/src/components/manage/Widgets/SchemaWidget.jsx
> +      },
This seems to be shown even if there is only one fieldset available, which is distracting.

2025-01-28 06:28 UTC, davisagli commented on packages/volto/src/components/manage/Widgets/SchemaWidget.jsx
> +        },
I tried adding a placeholder to a text field in a content type schema, but it didn't show up when I edited the content type.

2025-03-11 11:13 UTC, robgietema commented on packages/volto/src/components/manage/Widgets/SchemaWidget.jsx
> +        },
It's a property of the field which can be used by the widget (or not). In this case the current widget in Plone doesn't use the value but when you use a custom widget (react-aria-components for example) you can use those properties.

2025-03-11 11:16 UTC, robgietema commented on packages/volto/src/components/manage/Widgets/SchemaWidget.jsx
> +      },
This is not a change in this PR. It is already like this in the main branch.

2025-03-11 11:34 UTC, robgietema commented on packages/volto/news/6370.feature
> +Add option to choose bewteen icon and text buttons in the form component. @robgietema
Fixed.

2025-03-11 11:42 UTC, robgietema commented on packages/volto/src/components/manage/Form/Form.jsx
> +                      component={this.props.component}
This can be left empty. But if used this is a way to provide an inner (dumb) widget to your component.

2025-03-11 11:48 UTC, robgietema commented on packages/volto/src/components/manage/Form/ModalForm.jsx
> +   * also the first Tab to have any errors will be selected
Correct, I've changed the lines.

2025-03-11 11:54 UTC, robgietema commented on packages/volto/src/helpers/FormValidation/FormValidation.jsx
> +        formData[requiredField] !== true)
From a users perspective this is really weird. It will present a checkbox but the user doesn't know when it's unchecked if it doesn't have a value specified or somebody check or unchecked the checkbox. So in my opinion the required makes a lot more sense to actually be true. Stock Plone doesn't user required on any of the boolean fields as far as I know so that won't break. What could break are custom content types. But what is expected in that case when required is set to true from a user perspective?

2025-03-11 11:59 UTC, robgietema commented on packages/volto/src/components/manage/Widgets/index.tsx
> +
Looking at the current docs I only see docs on how to trigger a widget from backend code. There is no documentation of the current widgets on how to use them client side. What is documented are the "new" widgets using react-aria-components. At the moment I don't see where docs about this widget will fit in. Any suggestions?

2025-03-11 12:45 UTC, stevepiercy requested changes
Minor MyST enhancements.

2025-03-11 12:45 UTC, stevepiercy commented on docs/source/blocks/settings.md
> +Normally when a block is selected and you press `enter` a new block is inserted below.
```suggestion
Normally when a block is selected and you press {kbd}`enter`, a new block is inserted below the active one.
```

2025-03-11 12:45 UTC, stevepiercy commented on docs/source/blocks/settings.md
> +When you don't want this behavior and want to handle the `enter` input yourself inside the block you can set `disableEnter` to `true`.
```suggestion
When you don't want this behavior and want to handle the {kbd}`enter` input yourself inside the block, set `disableEnter` to `true`.
```

2025-03-11 12:54 UTC, robgietema commented on docs/source/blocks/settings.md
> +When you don't want this behavior and want to handle the `enter` input yourself inside the block you can set `disableEnter` to `true`.
Fixed

2025-03-11 12:54 UTC, robgietema commented on docs/source/blocks/settings.md
> +Normally when a block is selected and you press `enter` a new block is inserted below.
Fixed

2025-03-11 12:57 UTC, stevepiercy requested changes

2025-03-11 12:57 UTC, stevepiercy commented on docs/source/blocks/settings.md
> +When you don't want this behavior and want to handle the {kbd}`enter` input yourself inside the block you can set `disableEnter` to `true`.
Something got lost in my earlier suggestion. This is grammatically correct.

```suggestion
When you don't want this behavior and want to handle the {kbd}`enter` input yourself inside the block, set `disableEnter` to `true`.
```

2025-03-11 13:29 UTC, robgietema commented on docs/source/blocks/settings.md
> +When you don't want this behavior and want to handle the {kbd}`enter` input yourself inside the block you can set `disableEnter` to `true`.
Fixed

2025-03-11 16:22 UTC, robgietema commented on packages/volto/src/components/manage/Widgets/index.tsx
> +
In the docs all the widgets are linked to the storybook docs, I've added all the new widgets there.

2025-03-12 03:15 UTC, davisagli commented on packages/volto/src/components/manage/Widgets/SchemaWidget.jsx
> +      },
If it doesn't do anything, it's bad UX to show it when editing a content type schema in the schemaeditor.

2025-03-12 03:16 UTC, davisagli commented on packages/volto/src/components/manage/Widgets/SchemaWidget.jsx
> +        },
We can't just add properties to the schema editor that look useful but don't do anything. That's a recipe for frustration!

2025-03-12 05:31 UTC, stevepiercy commented on packages/volto/src/components/manage/Widgets/index.tsx
> +
An example of how to do that is in the introduction in https://6.docs.plone.org/volto/development/color-picker-widget.html.

> You can [try a demo of the default color picker](https://6.docs.plone.org/storybook/?path=/story/edit-widgets-colorpicker--default).

If you can find a relevant place for such a sentence for each widget in `docs/src/development`, then use that. Some may already have such a sentence. Else let's discuss what remains.

2025-03-12 07:30 UTC, sneridagh commented
Just as a reminder, we do have a storybook for every widget in core Volto eg.:

https://6.docs.plone.org/storybook/?path=/story/edit-widgets-array--default

We would need them too in order to be complete.

2025-03-12 10:55 UTC, robgietema commented on packages/volto/src/components/manage/Widgets/SchemaWidget.jsx
> +      },
I disagree, the schema widget is not tied to a specific form library and set of widgets. You can decide to use your own set of widgets which do make use of these values. This is not something new in Plone, there are plenty of fields on a content type or settings in the control panels which are not used by stock plone or shown in the ui but can be used if somebody wants that.

2025-03-12 10:55 UTC, robgietema commented on packages/volto/src/components/manage/Widgets/SchemaWidget.jsx
> +        },
See above comment.

2025-03-13 08:03 UTC, sneridagh approved these changes
Some small comments, humongous work! Congrats!

2025-03-13 08:03 UTC, sneridagh commented on packages/volto/src/components/manage/Widgets/__snapshots__/RadioGroupWidget.test.jsx.snap
> +            </label>
I don't see the vocabulary being passed in the test.

2025-03-13 10:36 UTC, pnicolli requested changes
Huge and very very useful work, thanks!!!! Left a few notes with the goal of having this as polished as possible.

2025-03-13 10:36 UTC, pnicolli commented on packages/volto/src/components/manage/Widgets/RadioGroupWidget.jsx
> +export default compose(
Same here, I would remove the useless `compose` call here

2025-03-13 10:36 UTC, pnicolli commented on packages/volto/src/components/manage/Widgets/SelectWidget.jsx
> +        ...map(additionalChoices, (choice) => ({
I would start using standard js for these easy things, instead of using lodash. Nowadays we don't need lodash for these simple things like map or the filter a few lines below imho

2025-03-13 10:36 UTC, pnicolli commented on packages/volto/src/config/Widgets.jsx
Do we also need views widgets for radiogroup, checkboxgroup and time widgets?

2025-03-13 10:36 UTC, pnicolli commented on packages/volto/src/helpers/Utils/Utils.jsx
> +  if (includes(slugs, slug)) {
I would also use standard js here instead of lodash

2025-03-13 10:36 UTC, pnicolli commented on packages/volto/theme/themes/pastanaga/collections/form.overrides
> +  margin: @8px 0;
`@8px` is a typo or is it a syntax I am not familiar with?

2025-03-13 10:36 UTC, pnicolli commented on packages/volto/src/components/manage/Widgets/SchemaWidget.jsx
> +  ['URL', 'Password', 'label_password_field', 'Email', 'label_email'],
I would start using standard js for these easy things, instead of using lodash. Nowadays we don't need lodash for these simple things like map. Also, since we are not really using the output from map here, I would suggest simply doing

```javascript
['URL', 'Password', 'label_password_field', 'Email', 'label_email'].forEach
```

2025-03-13 10:36 UTC, pnicolli commented on packages/volto/src/components/manage/Form/Form.jsx
> +                            component={this.props.component}
If I understand correctly, `this.props.component` is a Form component of some kind here, either the default or a provided one, so maybe this should not be passed to the Field component, right?

2025-03-19 15:53 UTC, robgietema commented on packages/volto/src/components/manage/Widgets/SchemaWidget.jsx
> +      },
Both query param and placeholder are now opt-in.

2025-03-19 15:53 UTC, robgietema commented on packages/volto/src/components/manage/Widgets/SchemaWidget.jsx
> +        },
Both query param and placeholder are now opt-in.

2025-03-19 15:56 UTC, robgietema commented on packages/volto/src/components/manage/Form/Form.jsx
> +                        secondary
I see what you mean but the basic and secondary are properties which most button do and should handle. The current implementation also doesn't let you override those variables.

2025-03-19 15:57 UTC, robgietema commented on packages/volto/src/components/manage/Widgets/CheckboxGroupWidget.jsx
Since this one is based on the ArrayWidget it is also a class. When all widgets will be converted to classes we can convert this one also.

2025-03-19 15:58 UTC, robgietema commented on packages/volto/theme/themes/pastanaga/collections/form.overrides
> +  margin: @8px 0;
That is indeed a syntax you are not familiar with :), it's used all around the pastanaga theme.

2025-03-19 15:59 UTC, robgietema commented on packages/volto/src/components/manage/Widgets/SchemaWidget.jsx
> +  ['URL', 'Password', 'label_password_field', 'Email', 'label_email'],
Agree, fixed.

2025-03-19 19:46 UTC, robgietema commented on packages/volto/src/components/manage/Form/Form.jsx
> +                            component={this.props.component}
This is a way to use a high level component (wrapper widget) with logic and a low level widget with just the widget markup (like the widgets in plone/components). You can check the wrapper components in the 4.x.x branch of volto-form-block.

2025-03-19 19:47 UTC, robgietema commented on packages/volto/src/config/Widgets.jsx
For now they are not used anywhere. When we do need them they can be added.

2025-03-19 19:47 UTC, robgietema commented on packages/volto/src/components/manage/Widgets/SelectWidget.jsx
> +        ...map(additionalChoices, (choice) => ({
Agree, fixed.

2025-03-20 08:59 UTC, stevepiercy reviewed
@davisagli mentioned missing docs. Not much for me to review yet.

2025-03-20 08:59 UTC, stevepiercy commented on packages/volto/src/components/manage/Widgets/SchemaWidget.jsx
> +config.registerUtility({
This one is missing a `['Time'...]` wrapper. Does that matter? I noticed several others lack this pattern.

2025-03-21 09:11 UTC, sneridagh commented
@pnicolli ready for a final review!

2025-03-21 18:35 UTC, robgietema commented on packages/volto/src/components/manage/Widgets/SchemaWidget.jsx
> +config.registerUtility({
This is how it is suppose to be. The array notation is used to register multiple factories, without is just registering one.

All needed docs are added, I replied to David in this PR above.

2025-03-24 12:24 UTC, pnicolli commented on packages/volto/src/components/manage/Form/Form.jsx
> +                            component={this.props.component}
I don't get it, maybe I need to see an example. Let's see it very briefly at the Bucharest sprint.

2025-03-24 12:37 UTC, pnicolli commented on packages/volto/src/components/manage/Form/Form.jsx
> +                        secondary
The current implementation doesn't let you override the button entirely, so it handles it, they don't get drilled down to the rendered html, while this PR implementation actually allows that.
This being said, I don't have a clear solution here yet.

But let's say I want to use `@plone/components` here, I would need to do something like this:

```jsx
import { Button } from '@plone/components';

<Form buttonComponent={{(basic, primary, secondary, floated, children, ...otherProps) => (
  <Button
    className={cx(basic, primary, secondary, floated, otherProps.className)}
    {...otherProps}
  >
    {children}
  </Button>
  // ....
/>
```

and `className` here is just one situation but we could have more.

I could be ok with delegating the proper implementation to the user like I did here, but we need it to be documented (typescript would be enough since you could have mandatory props), I'm thinking if there is no better option for this.

2025-03-24 13:41 UTC, robgietema commented on packages/volto/src/components/manage/Form/Form.jsx
> +                            component={this.props.component}
It's removed for now.

2025-03-24 13:47 UTC, pnicolli approved these changes

2025-03-24 15:19 UTC, merged