Pass the `user`, `navRoot` and `contentType` objects to the `restricted` function of the block settings
plone/volto pull request #6375
Opened 2024-10-04 18:31 UTC by wesleybl

Backport of #6271 and #6293 to Volto 17

Fixes #6264

2024-10-04 19:35 UTC, avoinea approved these changes

2024-10-04 21:36 UTC, stevepiercy requested changes

2024-10-04 21:36 UTC, stevepiercy commented on news/6264.feature
> +Pass the `user`, `navRoot` and `contentType` objects to the `restricted` function of the block settings. @wesleybl
```suggestion
Pass the `user`, `navRoot`, and `contentType` objects to the `restricted` function of the block settings. @wesleybl
```

2024-10-04 23:01 UTC, stevepiercy commented
Vale is busted for 17.x.x, so I created a PR here https://github.com/plone/volto/pull/6377. It works now. I'll merge that and update this branch.

2024-10-04 23:53 UTC, stevepiercy approved these changes
LGTM.

2024-10-05 00:29 UTC, stevepiercy commented
All green. One final pass from @davisagli or @sneridagh?

2024-10-05 05:00 UTC, merged