Shows working copy options for Plone Site
plone/volto pull request #6393
Opened 2024-10-10 13:21 UTC by wesleybl

This PR should be tested together with the following PRs:

https://github.com/plone/plone.restapi/pull/1823
https://github.com/plone/plone.app.iterate/pull/128
https://github.com/plone/plone.app.versioningbehavior/pull/87
https://github.com/plone/Products.CMFEditions/pull/113

- [ ] I signed and returned the [Plone Contributor Agreement](https://plone.org/foundation/contributors-agreement), and received and accepted an invitation to join a team in the Plone GitHub organization.
- [ ] I verified there aren't other open [pull requests](https://github.com/plone/volto/pulls) for the same change.
- [ ] I followed the guidelines in [Contributing to Volto](https://6.docs.plone.org/volto/contributing/index.html).
- [ ] I succesfully ran [code linting checks](https://6.docs.plone.org/volto/contributing/linting.html) on my changes locally.
- [ ] I succesfully ran [unit tests](https://6.docs.plone.org/volto/contributing/testing.html) on my changes locally.
- [ ] I succesfully ran [acceptance tests](https://6.docs.plone.org/volto/contributing/acceptance-tests.html) on my changes locally.
- [ ] If needed, I added new tests for my changes.
- [ ] If needed, I added [documentation](https://6.docs.plone.org/volto/contributing/documentation.html#narrative-documentation) for my changes, either in the Storybook or narrative documentation.
- [ ] I included a [change log entry](https://6.docs.plone.org/contributing/index.html#contributing-change-log-label) in my commits.

-----

If your pull request closes an open issue, include the exact text below, immediately followed by the issue number. When your pull request gets merged, then that issue will close automatically.

Closes #5284

2024-10-25 16:42 UTC, pnicolli commented on packages/volto/cypress/tests/workingCopy/create.js
> +  it('Portal root have create option', function () {
```suggestion
  it('Portal root has create option', function () {
```

2025-01-25 05:31 UTC, davisagli commented
@plone/volto-team I think this change can be reviewed and merged independently from the other PRs related to supporting working copies for the Plone site. It's updating the logic for when Volto displays the checkin/checkout actions in the More menu, so that it's based on the `@actions` endpoint.

2025-01-25 05:32 UTC, davisagli commented on packages/volto/news/5284.feature
> +Shows working copy options for Plone Site. @wesleybl
```suggestion
Show the working copy actions (checkin/checkout) based on whether they are enabled in the backend, instead of the `hasWorkingCopySupport` setting. @wesleybl, @davisagli
```

2025-01-28 07:41 UTC, stevepiercy requested changes
Use a more appropriate admonition of `versionremoved`, not `deprecated`. Otherwise some minor wording and style fixes. I'll commit them.

2025-01-28 07:41 UTC, stevepiercy commented on docs/source/configuration/settings-reference.md
> +
```suggestion
```

2025-01-28 07:41 UTC, stevepiercy commented on docs/source/configuration/settings-reference.md
> +    This setting is no longer used. Working copy support is now based on whether the `plone.app.iterate` add-on is installed in the backend.
```suggestion
    This setting is unnecessary since Volto 18.8.0.
    Working copy support is now based on whether the `plone.app.iterate` add-on is installed in the backend.
```

2025-01-28 07:41 UTC, stevepiercy commented on docs/source/configuration/settings-reference.md
> +    This setting will enable working copy support in your site. You need to install the `plone.app.iterate` add-on in your Plone site in order for it to work.
```suggestion
    For Plone sites using Volto versions prior to 18.8.0, this setting enables working copy support.
    To make it work, you need to install the add-on `plone.app.iterate` in your Plone site.
```

2025-01-28 07:41 UTC, stevepiercy commented on docs/source/configuration/workingcopy.md
> +Volto provides support for Plone's Working Copy feature. You need to install the `plone.app.iterate` add-on in your Plone site. You can do that in Plone's Add-ons control panel or using the `GenericS
```suggestion
Volto supports Plone's working copy feature.
To enable it, you need to install the add-on `plone.app.iterate` in your Plone site.
You can do that either in Plone's {guilabel}`Add-ons` control panel or using the `GenericSetup` facility.
```

2025-01-28 07:41 UTC, stevepiercy commented on docs/source/configuration/workingcopy.md
> +
```suggestion
```

2025-01-28 07:41 UTC, stevepiercy commented on docs/source/configuration/workingcopy.md
> +If you have an older version of volto, you also need to enable working copy support in Volto's configuration object:
```suggestion
If you have an older version of Volto, you also need to enable working copy support in Volto's configuration object as follows.
```

2025-01-28 07:41 UTC, stevepiercy commented on docs/source/configuration/settings-reference.md
> +    ```{deprecated} Volto 18.8.0
```suggestion
    ```{versionremoved} Volto 18.8.0
```

2025-01-28 07:41 UTC, stevepiercy commented on docs/source/configuration/workingcopy.md
> +```{deprecated} Volto 18.8.0
```suggestion
```{versionremoved} Volto 18.8.0
```

2025-01-28 07:43 UTC, stevepiercy approved these changes
Docs LGTM now. I'll double-check the PR preview build.

2025-01-28 07:51 UTC, stevepiercy commented
I lied. There is a build error in RTD that appears to be this recently reported issue, and a release is pending. Something for y'all to watch out for in your builds.

https://github.com/nodejs/corepack/issues/612

See the build log for error message.

https://app.readthedocs.org/projects/volto/builds/26990887/

2025-01-28 07:53 UTC, stevepiercy commented
We can ignore the failing readme linkcheck. https://2021.ploneconf.org/ is not returning a 500 ISE, although this is not the first time it has done so.

2025-01-28 08:04 UTC, stevepiercy commented
I checked out this PR, built the docs, and made one more change. The docs look good now.

2025-01-29 08:55 UTC, mauritsvanrees approved these changes
I can't comment on the technical side of this PR.  But I tried it out and it works.

2025-01-29 11:49 UTC, sneridagh approved these changes
LGTM!

2025-01-29 11:49 UTC, sneridagh commented on packages/seven/Makefile
>  working-copy-acceptance-frontend-prod-start: build-deps ## Start acceptance frontend in production mode for working copy tests
We could unify this into the main tests then, but it does not hurt to have them separated.

2025-01-29 11:50 UTC, merged