Replace all `yarn` appearences with `pnpm`
plone/volto pull request #6433
Opened 2024-10-24 11:31 UTC by sneridagh

- [ ] I signed and returned the [Plone Contributor Agreement](https://plone.org/foundation/contributors-agreement), and received and accepted an invitation to join a team in the Plone GitHub organization.
- [ ] I verified there aren't other open [pull requests](https://github.com/plone/volto/pulls) for the same change.
- [ ] I followed the guidelines in [Contributing to Volto](https://6.docs.plone.org/volto/contributing/index.html).
- [ ] I succesfully ran [code linting checks](https://6.docs.plone.org/volto/contributing/linting.html) on my changes locally.
- [ ] I succesfully ran [unit tests](https://6.docs.plone.org/volto/contributing/testing.html) on my changes locally.
- [ ] I succesfully ran [acceptance tests](https://6.docs.plone.org/volto/contributing/acceptance-tests.html) on my changes locally.
- [ ] If needed, I added new tests for my changes.
- [ ] If needed, I added [documentation](https://6.docs.plone.org/volto/contributing/documentation.html#narrative-documentation) for my changes, either in the Storybook or narrative documentation.
- [ ] I included a [change log entry](https://6.docs.plone.org/contributing/index.html#contributing-change-log-label) in my commits.

-----

If your pull request closes an open issue, include the exact text below, immediately followed by the issue number. When your pull request gets merged, then that issue will close automatically.

Closes #

2024-10-25 00:04 UTC, davisagli requested changes

2024-10-25 00:04 UTC, davisagli commented on docs/source/development/creating-project.md
> +As a bonus, it will contain the meaning for deploying your project.
```suggestion
As a bonus, it will contain the means for deploying your project.
```

2024-10-25 00:04 UTC, davisagli commented on docs/source/development/lazyload.md
> +pnpm analyze
```suggestion
pnpm --filter=volto analyze
```

(just pnpm analyze gives a "Command "analyze" not found" error)

2024-10-25 16:09 UTC, davisagli approved these changes

2024-10-26 11:07 UTC, stevepiercy requested changes
I'll make the changes, then it's GTG

2024-10-26 11:07 UTC, stevepiercy commented on docs/source/development/creating-project.md
> +[Cookieplone](https://github.com/plone/cookieplone) is now the recommended way to develop Volto projects, using it as a boilerplate generator.
````suggestion
```{versionadded} Volto 18.0.0
```

[Cookieplone](https://github.com/plone/cookieplone) is now the recommended way to develop Volto projects, using it as a boilerplate generator.
````

2024-10-26 11:07 UTC, stevepiercy commented on docs/source/development/creating-project.md
> +Even if you don't need the backend, create a Plone project, then use only the {file}`frontend` folder for your purposes.
```suggestion
Even if you don't need the backend, you can create a Plone project, then use only the {file}`frontend` folder for your purposes.
```

2024-10-26 11:07 UTC, stevepiercy commented on docs/source/development/creating-project.md
> +[Cookieplone](https://github.com/plone/cookieplone) is now the recommended way to develop Volto projects, using it as a boilerplate generator.
Removal of two terms is in https://github.com/plone/documentation/pull/1747

2024-10-26 11:09 UTC, stevepiercy requested changes
oopsie, specify exact alpha version.

2024-10-26 11:09 UTC, stevepiercy commented on docs/source/development/creating-project.md
> +```{versionadded} Volto 18.0.0
```suggestion
```{versionadded} Volto 18.0.0-alpha.43
```

2024-10-26 11:11 UTC, stevepiercy commented on docs/source/configuration/environmentvariables.md
> +    ADDONS=volto-slate:asDefault pnpm start
Agreed. Do we have another add-on that we could use, perhaps VLT?

2024-10-26 11:12 UTC, stevepiercy approved these changes
Approve, pending resolution of @pnicolli's comment.

@sneridagh this PR needs a change log entry.

2024-10-26 11:40 UTC, sneridagh commented on docs/source/configuration/environmentvariables.md
> +    ADDONS=volto-slate:asDefault pnpm start
Done.

2024-10-26 11:41 UTC, sneridagh commented
@stevepiercy GTG

2024-10-26 11:42 UTC, stevepiercy approved these changes

2024-10-26 11:52 UTC, merged