[Next.js] Better Vercel deployment
plone/volto pull request #6441
Opened 2024-10-25 21:46 UTC by sneridagh

- [ ] I signed and returned the [Plone Contributor Agreement](https://plone.org/foundation/contributors-agreement), and received and accepted an invitation to join a team in the Plone GitHub organization.
- [ ] I verified there aren't other open [pull requests](https://github.com/plone/volto/pulls) for the same change.
- [ ] I followed the guidelines in [Contributing to Volto](https://6.docs.plone.org/volto/contributing/index.html).
- [ ] I succesfully ran [code linting checks](https://6.docs.plone.org/volto/contributing/linting.html) on my changes locally.
- [ ] I succesfully ran [unit tests](https://6.docs.plone.org/volto/contributing/testing.html) on my changes locally.
- [ ] I succesfully ran [acceptance tests](https://6.docs.plone.org/volto/contributing/acceptance-tests.html) on my changes locally.
- [ ] If needed, I added new tests for my changes.
- [ ] If needed, I added [documentation](https://6.docs.plone.org/volto/contributing/documentation.html#narrative-documentation) for my changes, either in the Storybook or narrative documentation.
- [ ] I included a [change log entry](https://6.docs.plone.org/contributing/index.html#contributing-change-log-label) in my commits.

-----

If your pull request closes an open issue, include the exact text below, immediately followed by the issue number. When your pull request gets merged, then that issue will close automatically.

Closes #

2024-10-25 22:12 UTC, stevepiercy requested changes

2024-10-25 22:12 UTC, stevepiercy commented on apps/nextjs/README.md
> +For production deployments, we need to force the deployment URL, otherwise, we have CORS problems.
```suggestion
For production deployments, you need to force the deployment URL, otherwise you will have issues with CORS.
```

2024-10-25 22:12 UTC, stevepiercy commented on apps/nextjs/README.md
> +We need another environment variable to set the production URL: `NEXT_PRODUCTION_URL`.
```suggestion
To do so, set another environment variable for the production URL, `NEXT_PRODUCTION_URL`.
```

2024-10-25 22:12 UTC, stevepiercy commented on apps/nextjs/README.md
> +This URL needs to be schema-less, so without `http` or `https`:
```suggestion
This URL needs to be scheme-less, without `http` or `https`, and consist only of the domain name:
```

2024-10-26 07:40 UTC, sneridagh commented
@stevepiercy thanks!

2024-10-26 08:31 UTC, stevepiercy approved these changes
I made some quick edits to docs and comments. LGTM!

2024-10-26 09:25 UTC, stevepiercy commented
@sneridagh needs change log entry.

2024-10-26 11:44 UTC, sneridagh commented
@stevepiercy since it's an experimental PoC, we agreed on not to add Changelog for now.

2024-10-26 11:49 UTC, stevepiercy commented
@sneridagh OK, and we can skip the failing readme linkcheck.

2024-10-26 11:52 UTC, merged