Fix types, better exports and use tsup for build, remove parcel
plone/volto pull request #6461
Opened 2024-11-03 23:26 UTC by sneridagh

2024-11-03 23:46 UTC, davisagli reviewed
Could you explain more about the switch from parcel to tsup? What's the motivation and are there any tradeoffs?

2024-11-03 23:46 UTC, davisagli commented on packages/registry/package.json
>      "watch": "parcel watch",
There's still a parcel command here.

2024-11-04 07:43 UTC, sneridagh commented
@davisagli just added some more background in the description.

2024-11-04 08:41 UTC, stevepiercy requested changes
Was `parcel` something the developer directly called? If so, does its replacement merit more than a change log entry?

2024-11-04 08:41 UTC, stevepiercy commented on packages/registry/news/6461.bugfix
> +Fix types for addons TS, fix tsconfig for node side @sneridagh
```suggestion
Fix types for add-on's TypeScript. Fix `.tsconfig` for Node.js side. @sneridagh
```

2024-11-04 08:41 UTC, stevepiercy commented on packages/registry/news/6461.internal
> +Replace `parcel` with `tsup` for build @sneridagh
```suggestion
Replace `parcel` with `tsup` for build. @sneridagh
```

2024-11-04 08:41 UTC, stevepiercy commented on packages/scripts/news/6461.internal
> +Improve exports in @plone/registry, adapt the detection in i18n script @sneridagh
```suggestion
Improve exports in `@plone/registry`. Adapt its detection in i18n script. @sneridagh
```

2024-11-04 19:33 UTC, merged