Solved issue Number-6143
plone/volto pull request #6484
Opened 2024-11-16 14:36 UTC by Harshit-7373

When selecting a start datetime, the end datetime should be after the start datetime. #6143.

github - Harshit-7373.

- [ ] I signed and returned the [Plone Contributor Agreement](https://plone.org/foundation/contributors-agreement), and received and accepted an invitation to join a team in the Plone GitHub organization.
- [ ] I verified there aren't other open [pull requests](https://github.com/plone/volto/pulls) for the same change.
- [ ] I followed the guidelines in [Contributing to Volto](https://6.docs.plone.org/volto/contributing/index.html).
- [ ] I succesfully ran [code linting checks](https://6.docs.plone.org/volto/contributing/linting.html) on my changes locally.
- [ ] I succesfully ran [unit tests](https://6.docs.plone.org/volto/contributing/testing.html) on my changes locally.
- [ ] I succesfully ran [acceptance tests](https://6.docs.plone.org/volto/contributing/acceptance-tests.html) on my changes locally.
- [ ] If needed, I added new tests for my changes.
- [ ] If needed, I added [documentation](https://6.docs.plone.org/volto/contributing/documentation.html#narrative-documentation) for my changes, either in the Storybook or narrative documentation.
- [ ] I included a [change log entry](https://6.docs.plone.org/contributing/index.html#contributing-change-log-label) in my commits.

-----

If your pull request closes an open issue, include the exact text below, immediately followed by the issue number. When your pull request gets merged, then that issue will close automatically.

Closes #

2024-11-16 14:36 UTC, mister-roboto commented
@Harshit-7373 you need to sign the Plone Contributor Agreement to merge this pull request.

Learn about the Plone Contributor Agreement: https://plone.org/foundation/contributors-agreement

If you have already signed the agreement, please allow a week for your agreement to be processed.
Once it is processed, you will receive an email invitation to join the `plone` GitHub organization as a Contributor.

If after a week you have not received an invitation, then please contact agreements@plone.org.

2024-11-16 16:36 UTC, davisagli requested changes
Sorry, this is not an acceptable solution. This validation should happen on the client side using the existing validation framework that's integrated with the form components in packages/volto. Your solution bypasses most of how Volto works, and only tries to solve this for the experimental vite app.

2024-11-16 16:40 UTC, Harshit-7373 commented
Thank you for the feedback. I understand now that the validation should be handled on the client side using the existing validation framework integrated with the form components in the packages/volto. I’ll make sure to align with Volto’s existing structure and ensure that the solution does not bypass its core functionality. I’ll update my approach accordingly to work seamlessly with the current framework.

Please let me know if you have any further suggestions or if there’s anything else I should consider.

2024-11-16 19:18 UTC, stevepiercy commented
@Harshit-7373 you can start here https://6.docs.plone.org/volto/configuration/validation.html

2025-01-29 04:10 UTC, davisagli commented
Closing old PR with no follow-up

2025-01-29 04:10 UTC, closed without merging