Add french translations
plone/volto pull request #6508
Opened 2024-11-30 14:56 UTC by duchenean

- [x] I signed and returned the [Plone Contributor Agreement](https://plone.org/foundation/contributors-agreement), and received and accepted an invitation to join a team in the Plone GitHub organization.
- [x] I verified there aren't other open [pull requests](https://github.com/plone/volto/pulls) for the same change.
- [x] I followed the guidelines in [Contributing to Volto](https://6.docs.plone.org/volto/contributing/index.html).
- [ ] I succesfully ran [code linting checks](https://6.docs.plone.org/volto/contributing/linting.html) on my changes locally.
- [ ] I succesfully ran [unit tests](https://6.docs.plone.org/volto/contributing/testing.html) on my changes locally.
- [ ] I succesfully ran [acceptance tests](https://6.docs.plone.org/volto/contributing/acceptance-tests.html) on my changes locally.
- [ ] If needed, I added new tests for my changes.
- [ ] If needed, I added [documentation](https://6.docs.plone.org/volto/contributing/documentation.html#narrative-documentation) for my changes, either in the Storybook or narrative documentation.
- [ ] I included a [change log entry](https://6.docs.plone.org/contributing/index.html#contributing-change-log-label) in my commits.

-----

If your pull request closes an open issue, include the exact text below, immediately followed by the issue number. When your pull request gets merged, then that issue will close automatically.

Closes #

2024-11-30 16:54 UTC, gbastien requested changes
Juste vérifie l'orthographe et majuscules par rapport au "Default"
Merci et bonne journée!
Gauthier

2024-11-30 16:54 UTC, gbastien commented on packages/volto/locales/fr/LC_MESSAGES/volto.po
> +msgstr "Referencement de cet élément comme élément lié"
Référencement

2024-11-30 16:54 UTC, gbastien commented on packages/volto/locales/fr/LC_MESSAGES/volto.po
> +msgstr "Referencement de cet élément avec {relationship}"
Référencement

2024-11-30 16:54 UTC, gbastien commented on packages/volto/locales/fr/LC_MESSAGES/volto.po
> +msgstr "Référence"
Vérifier si minuscule/majuscule pour commencer le mot

2024-11-30 16:54 UTC, gbastien commented on packages/volto/locales/fr/LC_MESSAGES/volto.po
> +msgstr "Références"
Vérifier si minuscule/majuscule pour commencer le mot

2024-11-30 16:54 UTC, gbastien commented on packages/volto/locales/fr/LC_MESSAGES/volto.po
> +msgstr "Chemin des sources"
Vérifier si minuscule/majuscule pour commencer le mot

2024-11-30 16:54 UTC, gbastien commented on packages/volto/locales/fr/LC_MESSAGES/volto.po
> +msgstr "Chemin de la cible"
Vérifier si minuscule/majuscule pour commencer le mot

2024-11-30 19:10 UTC, remdub requested changes

2024-11-30 19:10 UTC, remdub commented on packages/volto/locales/fr/LC_MESSAGES/volto.po
> +msgstr "Corrifer les relations"
Corriger

2024-11-30 19:10 UTC, remdub commented on packages/volto/locales/fr/LC_MESSAGES/volto.po
> +msgstr "Aprçu des relations de tous les éléments de contenu"
Aperçu

2024-11-30 19:10 UTC, remdub commented on packages/volto/locales/fr/LC_MESSAGES/volto.po
> +msgstr "Relations mise à jour"
mises

2024-11-30 19:10 UTC, remdub commented on packages/volto/locales/fr/LC_MESSAGES/volto.po
> +msgstr "Utilisateur mise à jour avec succès"
mis

2024-12-11 16:33 UTC, sneridagh commented
@duchenean could you please amend your PR with the suggestions? Thanks!

2025-01-29 04:11 UTC, davisagli commented
Closing since the original submitter has not responded to feedback.

2025-01-29 04:11 UTC, closed without merging