Remove devserver settings for HMR of volto
plone/volto pull request #6511
Opened 2024-12-04 23:58 UTC by davisagli

It still seems to work without this, and it was showing some warnings on startup. (Reported in https://community.plone.org/t/warnings-durung-volto-start-using-2024-training/20205)

2024-12-05 00:05 UTC, stevepiercy requested changes
Sprinkle some MyST

2024-12-05 00:05 UTC, stevepiercy commented on packages/volto/news/6511.bugfix
> +Fix warnings related to snapshot.managedPaths on startup. @davisagli
```suggestion
Fix warnings related to `snapshot.managedPaths` on startup. @davisagli
```

2024-12-05 17:19 UTC, sneridagh approved these changes

2024-12-05 17:19 UTC, merged

2025-03-31 12:54 UTC, wesleybl commented
@davisagli  In an `app` generated with `generator-volto`, Volto's hot reload of files doesn't work without it. I get:

```
✔ Client
  Compiled successfully in 1.66s

✔ Server
  

sswp> Cannot find update.
assets by status 31.3 MiB [cached] 86 assets
asset ../assets.json 16.4 KiB [emitted]
Entrypoint client [big] 22.2 MiB (19.3 MiB) = static/js/runtime~client.js 50.8 KiB static/js/client.js 22.2 MiB 38 auxiliary assets
cached modules 22.7 MiB (javascript) 34.1 KiB (runtime) [cached] 3987 modules
./locales/ lazy ^\.\/.*\.json$ namespace object 160 bytes [built]
webpack 5.90.1 compiled successfully in 1664 ms
```

Can we return this?