Remove SemanticUI CSS declaration `overflow-x: hidden` in BODY tag.
plone/volto pull request #6513
Opened 2024-12-05 16:54 UTC by sneridagh

We had this behavior:

https://github.com/user-attachments/assets/f43aadc6-83af-4734-9269-79cb74698323

Turns out that SemanticUI is forcing `overflow-x: hidden` in the BODY class. That provokes the screen to jump when the popover is shown.

This PR resets this declaration.

2025-03-23 17:11 UTC, pnicolli commented
At RedTurtle we bumped into this a couple times already and didn't notice this PR.
Love this, but I think it's definitely a breaking change. On the other hand, this could be considered almost like a blocker for properly adopting RAC if one wants to. Maybe putting this in 19 and documenting it is enough? 🤔

2025-03-25 16:26 UTC, pnicolli approved these changes

2025-03-25 21:28 UTC, stevepiercy commented on packages/volto/news/6513.bugfix
> +Removed SemanticUI CSS declaration `overflow-x: hidden` in BODY tag. @sneridagh
```suggestion
Removed Semantic UI CSS declaration `overflow-x: hidden` from the `body` tag. @sneridagh
```

2025-03-25 21:33 UTC, stevepiercy requested changes

2025-03-25 21:33 UTC, stevepiercy commented on packages/volto/theme/themes/pastanaga/extras/main.less
> +  // that forces `overflow-x: hidden` on the BODY.
I have no idea what RAC means, but this is my guess. Please correct me if it is wrong.

```suggestion
  // React Autocomplete Component popovers have problems with the default declaration
  // in Semantic UI that forces `overflow-x: hidden` on the body.
```

2025-03-26 06:31 UTC, sneridagh commented on packages/volto/theme/themes/pastanaga/extras/main.less
> +  // that forces `overflow-x: hidden` on the BODY.
LOLOLOL

2025-03-26 06:33 UTC, sneridagh commented on packages/volto/theme/themes/pastanaga/extras/main.less
> +  // that forces `overflow-x: hidden` on the BODY.
Fixed.

2025-03-26 06:44 UTC, stevepiercy approved these changes

2025-03-26 07:42 UTC, merged