feat: improve link integrity popup
plone/volto pull request #6516
Opened 2024-12-06 13:29 UTC by giuliaghisini

fixed and improved link integrity popup when deleting item/items from folder contents. 
Moved all login in a separate component 'ContentsDeleteModal'.

Added loader when loading references. If the call to @linkintegrity took a long time to load, it wasn't clear to the user that it was checking for broken references:
 
<img width="1311" alt="loading" src="https://github.com/user-attachments/assets/4ff90bfb-4176-4e1b-afed-0b9d8a5a6190">

If only one item is selected to delete, it will display all the possibile broken references in a table, instead in a list:
<img width="1191" alt="1-selected-item" src="https://github.com/user-attachments/assets/1035c15e-a4d4-4de0-9680-d4243b5dd1fe">

If more than one item is selected to delete, it will not display the possibile broken references, but only the number, because it  will be a very long list (It worked like that before too):
<img width="1146" alt="more-than-one-selected" src="https://github.com/user-attachments/assets/42ac64de-7666-4de5-950c-7567613ddc9b">

2024-12-06 13:38 UTC, stevepiercy requested changes
I only reviewed the message strings and defaults. This still requires a technical review. But it looks pretty good.

2024-12-06 13:38 UTC, stevepiercy commented on packages/volto/locales/volto.pot
> +msgid "Navigate to this items"
This should be either "Navigate to this item" or the "Navigate to these items", and align with the Default. I'm not sure whether it should be plural or singular. Please advise.

2024-12-06 13:38 UTC, stevepiercy commented on packages/volto/locales/volto.pot
> +#. Default: "Checking references..."
Let's not introduce punctuation that might not be translatable.

```suggestion
#. Default: "Checking references"
```

2024-12-06 14:04 UTC, stevepiercy approved these changes
Messages only approved. Still requires technical review.

2024-12-08 10:18 UTC, sneridagh commented
@giuliaghisini we merged #6509 so now importing from barrel files in core is not allowed anymore, so expect some ESlint failures. Could you please update the PR accordingly? Thanks!

2024-12-09 09:40 UTC, pnicolli commented on packages/volto/.env.local
Remove this file (maybe we should gitignore *.local files? @sneridagh )

2024-12-10 00:16 UTC, davisagli approved these changes
@giuliaghisini Nice improvements, thank you.

2024-12-11 16:32 UTC, merged