Fix precedence of the quanta layer by adding a base layer for all the…
plone/volto pull request #6539
Opened 2024-12-14 11:10 UTC by sneridagh

@pnicolli I found a bug in the definition of the layers, the quanta `plone-components.quanta` layer needs to have more priority than the base one. I misunderstood how nested layers worked.

I added a nested `plone-components.base` layer to all basic components. So, if we want to override declarations in the nested (default) layers, we only have to scope them to the main layer.

Also, I added the ability to setup the layers at the top (`Html.jsx` component), so we have a "main" centralized entry point to define them in Volto.

2024-12-14 12:26 UTC, stevepiercy requested changes

2024-12-14 12:26 UTC, stevepiercy commented on packages/components/src/stories/Introduction.mdx
> +Using the package manager of your choice (npm, yarn, pnpm) to install the package in your app.
```suggestion
You can use your choice of package manager (npm, yarn, or pnpm) to install the package in your app.
```

2024-12-14 12:26 UTC, stevepiercy commented on packages/components/src/stories/Introduction.mdx
> +Use pnpm in case you are adding them a Volto add-on/workspace:
```suggestion
If you add the components to a Volto add-on or workspace, use pnpm, as shown.
```

2024-12-14 12:26 UTC, stevepiercy commented on packages/components/src/stories/Introduction.mdx
> +This package use CSS layers to provide a way to style the components in a more flexible way.
```suggestion
This package uses CSS layers to style the components in a more flexible way.
```

2024-12-14 12:26 UTC, stevepiercy commented on packages/components/src/stories/Introduction.mdx
> +These components use the basic styling as a baseline, extending them to achieve Quanta look and feel.
```suggestion
These components use the basic styling as a baseline, extending them to achieve the Quanta look and feel.
```

2024-12-14 12:26 UTC, stevepiercy commented on packages/types/news/6539.feature
> +Added the type for a setting in config object for setting the site's CSS layers. @sneridagh
```suggestion
Added the typing for the new `cssLayers` configuration object setting. @sneridagh
```

2024-12-14 12:26 UTC, stevepiercy commented on packages/volto/news/6539.feature
> +Added a setting in config object for setting the site's CSS layers, if required. @sneridagh
```suggestion
Added a setting in the `config` object to set the site's CSS layers, if required. @sneridagh
```

2024-12-14 12:26 UTC, stevepiercy commented on packages/components/news/6539.bugfix
> +Fixed precedence of the quanta layer by adding a base layer for all the basic components. @sneridagh
```suggestion
Fixed precedence of the Quanta layer by adding a base layer for all the basic components. @sneridagh
```

2024-12-14 12:26 UTC, stevepiercy commented on docs/source/configuration/settings-reference.md
> +    If you want to use CSS layers in Volto styling, it's possible to define them making sure that they are defined and applied at the very top level of the page (head tag).
```suggestion
   To use CSS layers when styling Volto, you can define and apply them at the very top level of the page, where they appear in the `<head>` tag.
```

2024-12-14 12:26 UTC, stevepiercy commented on packages/components/README.md
> +This package use CSS layers to provide a way to style the components in a more flexible way.
```suggestion
This package uses CSS layers to style the components in a more flexible way.
```

2024-12-14 12:26 UTC, stevepiercy commented on packages/components/src/stories/Introduction.mdx
>  ## Quanta
I think this needs to increase a level because it is under Styling, not a sibling to it.

```suggestion
### Quanta
```

2024-12-14 12:26 UTC, stevepiercy commented on packages/components/README.md
> +These components use the basic styling as a baseline, extending them to achieve Quanta look and feel.
```suggestion
These components use the basic styling as a baseline, extending them to achieve the Quanta look and feel.
```

2024-12-14 21:42 UTC, stevepiercy approved these changes
Docs and news LGTM.

2024-12-16 01:15 UTC, davisagli approved these changes

2024-12-16 08:11 UTC, pnicolli approved these changes

2024-12-16 17:52 UTC, merged