Bugfix remove query string inclusion in body class generation logic
plone/volto pull request #6547
Opened 2024-12-18 16:39 UTC by Abhishek-17h

- [x] I signed and returned the [Plone Contributor Agreement](https://plone.org/foundation/contributors-agreement), and received and accepted an invitation to join a team in the Plone GitHub organization.
- [x] I verified there aren't other open [pull requests](https://github.com/plone/volto/pulls) for the same change.
- [x] I followed the guidelines in [Contributing to Volto](https://6.docs.plone.org/volto/contributing/index.html).
- [x] I succesfully ran [code linting checks](https://6.docs.plone.org/volto/contributing/linting.html) on my changes locally.
- [x] I succesfully ran [unit tests](https://6.docs.plone.org/volto/contributing/testing.html) on my changes locally.
- [x] I succesfully ran [acceptance tests](https://6.docs.plone.org/volto/contributing/acceptance-tests.html) on my changes locally.
- [ ] If needed, I added new tests for my changes.
- [ ] If needed, I added [documentation](https://6.docs.plone.org/volto/contributing/documentation.html#narrative-documentation) for my changes, either in the Storybook or narrative documentation.
- [x] I included a [change log entry](https://6.docs.plone.org/contributing/index.html#contributing-change-log-label) in my commits.

-----

If your pull request closes an open issue, include the exact text below, immediately followed by the issue number. When your pull request gets merged, then that issue will close automatically.

After fix body class only include the ?type= query_string in is-adding-contenttype class. All other query strings are ignored. If there's no type, no is-adding-contenttype class will be present.

Screenshots after fixing bug:
![Screenshot from 2024-12-18 21-54-48](https://github.com/user-attachments/assets/45756093-fc28-4005-92cb-40b88fc83605)
![Screenshot from 2024-12-18 21-54-24](https://github.com/user-attachments/assets/5259d774-f05b-40be-83b9-a652371a0528)

Closes #6493

2024-12-18 16:50 UTC, Abhishek-17h commented
Need Review @stevepiercy @Wagner3UB @sneridagh

2024-12-19 11:00 UTC, stevepiercy requested changes
Thanks for the pull request! This needs review by the @plone/volto-team, but it looks good to me.

2024-12-19 11:00 UTC, stevepiercy commented on packages/volto/news/6493.bugfix
> +Fixed body class handling to prevent query string inclusion in is-adding-contenttype.@Abhishek-17h
A change log entry should say what the problem was and what was fixed. We publish some guidance at https://6.docs.plone.org/contributing/index.html#write-a-good-change-log-entry.

```suggestion
No longer add classes from the query string search text in the `body` tag. @Abhishek-17h
```

2024-12-19 11:07 UTC, stevepiercy approved these changes
News LGTM! Thank you for the quick response.

2024-12-19 11:13 UTC, Abhishek-17h commented
@stevepiercy Glad to hear that! Let me know if there's anything else needed.

2024-12-19 11:31 UTC, giuliaghisini approved these changes

2024-12-19 17:01 UTC, davisagli reviewed
This could still produce a weird class if the querystring has both type and some other parameters, but it's definitely an improvement.

2024-12-19 17:02 UTC, merged