Block examples documentation
plone/volto pull request #6560
Opened 2024-12-30 16:00 UTC by erral

- [ ] I signed and returned the [Plone Contributor Agreement](https://plone.org/foundation/contributors-agreement), and received and accepted an invitation to join a team in the Plone GitHub organization.
- [ ] I verified there aren't other open [pull requests](https://github.com/plone/volto/pulls) for the same change.
- [ ] I followed the guidelines in [Contributing to Volto](https://6.docs.plone.org/volto/contributing/index.html).
- [ ] I succesfully ran [code linting checks](https://6.docs.plone.org/volto/contributing/linting.html) on my changes locally.
- [ ] I succesfully ran [unit tests](https://6.docs.plone.org/volto/contributing/testing.html) on my changes locally.
- [ ] I succesfully ran [acceptance tests](https://6.docs.plone.org/volto/contributing/acceptance-tests.html) on my changes locally.
- [ ] If needed, I added new tests for my changes.
- [ ] If needed, I added [documentation](https://6.docs.plone.org/volto/contributing/documentation.html#narrative-documentation) for my changes, either in the Storybook or narrative documentation.
- [ ] I included a [change log entry](https://6.docs.plone.org/contributing/index.html#contributing-change-log-label) in my commits.

-----

I have reviewed the block documentation, converted some code blocks from class components to functional components, and provide an example of a simple block.

2025-01-03 05:47 UTC, stevepiercy requested changes
This is great stuff. Thank you!

I created a related PR to define Glossary terms at https://github.com/plone/documentation/pull/1829, which needs to be merged before this PR to pull them into this PR's docs preview.

2025-01-03 05:47 UTC, stevepiercy commented on docs/source/blocks/examples/customviewvariationsandschemaenhancer.md
> +A {term}`schema enhancer` is an option of a variation. Using this schema enhancer, the block schema can be extended to have additional fields.
We need to add this term to the `plone/documentation` `glossary.md`.

```markdown
schema enhancer
    A schema enhancer uses the `schemaEnhancer` function, which can modify the schema used by the `InlineForm` component.
    Any registered extension plugin can provide a `schemaEnhancer` function.
    This function receives an object with `formData`, which is the block data; `schema`, which is the original schema to modify; and the injected `intl`, which aids with internationalization.
```

```suggestion
A {term}`schema enhancer` is an option of a variation.
Using this schema enhancer, you can extend the block schema to have additional fields.
```

2025-01-03 05:47 UTC, stevepiercy commented on docs/source/blocks/examples/customviewvariationsandschemaenhancer.md
> +What we need to do is to define the schema, the view component, the variations, the schema enhancer and configure the block settings.
```suggestion
To do so, define the schema, view component, variations, and schema enhancer, then configure the block settings.
```

2025-01-03 05:47 UTC, stevepiercy commented on docs/source/blocks/examples/customviewvariationsandschemaenhancer.md
> +In your volto addon, create a folder inside the {file}`components` folder to save all the files required to create a block.
```suggestion
In your Volto add-on, create a subfolder {file}`ExampleBlock06` inside the {file}`components` folder to save all the files required to create a block.
```

2025-01-03 05:47 UTC, stevepiercy commented on docs/source/blocks/examples/customviewvariationsandschemaenhancer.md
> +Name this folder as {file}`ExampleBlock06`.
```suggestion
```

2025-01-03 05:47 UTC, stevepiercy commented on docs/source/blocks/examples/customviewvariationsandschemaenhancer.md
> +Create a {file}`Schema.js` file inside the {file}`ExampleBlock06` folder, with the following contents:
```suggestion
Create a {file}`Schema.js` file inside the {file}`ExampleBlock06` folder, with the following contents.
```

2025-01-03 05:47 UTC, stevepiercy commented on docs/source/blocks/examples/customviewvariationsandschemaenhancer.md
> +As you have noted, we have prepared the block to be internationalized, {term}`internanationalization` (i18n), is the process of creating user interfaces which are suitable for different languages and
```suggestion
As you may have noted, you prepared the block for internationalization.
{term}`Internationalization` (i18n) is the process of creating user interfaces which are suitable for different languages and cultural contexts.
```

2025-01-03 05:47 UTC, stevepiercy commented on docs/source/blocks/examples/customviewvariationsandschemaenhancer.md
> +So we need a file {file}`messages.js` in the same {file}`ExampleBlock06` folder with the following contents:
```suggestion
Create a file {file}`messages.js` in the same {file}`ExampleBlock06` folder with the following contents.
```

2025-01-03 05:47 UTC, stevepiercy commented on docs/source/blocks/examples/customviewvariationsandschemaenhancer.md
> +In this case, as we are using variations, the view component needs to use the variation template to render the contents of the block.
```suggestion
For variations, the view component needs to use the variation template to render the contents of the block.
```

2025-01-03 05:47 UTC, stevepiercy commented on docs/source/blocks/examples/customviewvariationsandschemaenhancer.md
> +This is easily achieved using the `variation` coming on the `props` of the block.
```suggestion
You can do so using the `variation` from the `props` of the block.
```

2025-01-03 05:47 UTC, stevepiercy commented on docs/source/blocks/examples/customviewvariationsandschemaenhancer.md
> +Create a file {file}`View.jsx` in the {file}`ExampleBlock06` folder with the following contents:
```suggestion
Create a file {file}`View.jsx` in the {file}`ExampleBlock06` folder with the following contents.
```

2025-01-03 05:47 UTC, stevepiercy commented on docs/source/blocks/examples/customviewvariationsandschemaenhancer.md
> +  // data holds the values entered in the block edit form
```suggestion
  // `data` holds the values entered in the block edit form
```

2025-01-03 05:47 UTC, stevepiercy commented on docs/source/blocks/examples/customviewvariationsandschemaenhancer.md
> +  // className holds the CSS class names injected to this block by Volto's `styleClassNameExtenders`
```suggestion
  // `className` holds the CSS class names injected into this block by Volto's `styleClassNameExtenders`
```

2025-01-03 05:47 UTC, stevepiercy commented on docs/source/blocks/examples/customviewvariationsandschemaenhancer.md
> +  // style holds the CSS properties injected to this block by Volto's `Block Sytle Wrapper`
```suggestion
  // `style` holds the CSS properties injected into this block by Volto's `Block Style Wrapper`
```

2025-01-03 05:47 UTC, stevepiercy commented on docs/source/blocks/examples/customviewvariationsandschemaenhancer.md
> +  // variation holds the variation selected in the block editor, and it is an object as defined in the block configuration
```suggestion
  // `variation` holds the variation selected in the block editor, and it is an object as defined in the block configuration
```

2025-01-03 05:47 UTC, stevepiercy commented on docs/source/blocks/examples/customviewvariationsandschemaenhancer.md
> +  // so we need to define the new property under `schema.properties`
```suggestion
  // so you need to define the new property under `schema.properties`
```

2025-01-03 05:47 UTC, stevepiercy commented on docs/source/blocks/examples/customviewvariationsandschemaenhancer.md
> +  // and push its name to the relevant fieldset, in our case the first one (note the `fieldsets[0]`)
```suggestion
  // and push its name to the relevant fieldset, in this case the first one (note the `fieldsets[0]`)
```

2025-01-03 05:47 UTC, stevepiercy commented on docs/source/blocks/examples/customviewvariationsandschemaenhancer.md
> +Create a file {file}`VariationView02.jsx` in the {file}`ExampleBlock06` folder with the following contents:
```suggestion

Create a file {file}`VariationView02.jsx` in the {file}`ExampleBlock06` folder with the following contents.
```

2025-01-03 05:47 UTC, stevepiercy commented on docs/source/blocks/examples/customviewvariationsandschemaenhancer.md
> +Create a file {file}`enhancers.js` in the {file}`BlockSchema` folder with the following content:
```suggestion
Create a file {file}`enhancers.js` in the {file}`BlockSchema` folder with the following content.
```

2025-01-03 05:47 UTC, stevepiercy commented on docs/source/blocks/examples/customviewvariationsandschemaenhancer.md
> +We need to configure the schema enhancer function. In this case we will be adding a new field named `color` when using the Variation 2.
```suggestion
Next you need to configure the schema enhancer function.
In this example, you will add a new field named `color` when using `schemaEnhancerVariation02`.
```

2025-01-03 05:47 UTC, stevepiercy commented on docs/source/blocks/examples/customviewvariationsandschemaenhancer.md
> +Now we need to create one or more variations that will be available for this block.
```suggestion
Next create one or more variations that will be available for this block.
```

2025-01-03 05:47 UTC, stevepiercy commented on docs/source/blocks/examples/customviewvariationsandschemaenhancer.md
> +Create a file {file}`VariationView01.jsx` in the {file}`ExampleBlock06` folder with the following contents:
```suggestion
Create a file {file}`VariationView01.jsx` in the {file}`ExampleBlock06` folder with the following contents.
```

2025-01-03 05:47 UTC, stevepiercy commented on docs/source/blocks/examples/customviewvariationsandschemaenhancer.md
> +As you can see, in this case the variations are pretty much the same, the only difference is the text that is rendered in the `<h2>` tag. But it can be anything.
```suggestion
As you can see, the variations are pretty much the same.
The only difference is the text that is rendered in the `<h2>` tag.
But it can be anything.
```

2025-01-03 05:47 UTC, stevepiercy commented on docs/source/blocks/examples/customviewvariationsandschemaenhancer.md
> +To do so, open your addon's {file}`index.js` file, that will have the following contents:
```suggestion
To do so, open your add-on's {file}`index.js` file, and add the following contents.
```

2025-01-03 05:47 UTC, stevepiercy commented on docs/source/blocks/examples/customviewvariationsandschemaenhancer.md
> +And before the last `return config;` statement, write the following configuration:
```suggestion
Before the last `return config;` statement, write the following configuration.
```

2025-01-03 05:47 UTC, stevepiercy commented on docs/source/blocks/examples/customviewvariationsandschemaenhancer.md
> +
```suggestion
```

2025-01-03 05:47 UTC, stevepiercy commented on docs/source/blocks/examples/customviewvariationsandschemaenhancer.md
> +On the top of the file you will need to import the relevant components, as follows:
```suggestion
At the top of the file, import the relevant components as follows.
```

2025-01-03 05:47 UTC, stevepiercy commented on docs/source/blocks/examples/customviewvariationsandschemaenhancer.md
> +Restart your Volto site and you will be able to add it using the block add form.
```suggestion
Restart your Volto site, and you can add it using the block add form.
```

2025-01-03 09:39 UTC, ichim-david commented
@erral once you apply @stevepiercy suggestions and you feel that the work is ready for review you can add me as a reviewer if you would like, I volunteer to read the docs and give any potential suggestions if needed.

2025-01-03 14:50 UTC, erral commented on docs/source/blocks/settings.md
> +    // in case that the `edit` setting of the block is set to `null`
The `blockSchema` property can either be a schema by itself (a JavaScript object describing the schema), or a function that returns a schema.

2025-01-03 14:55 UTC, erral commented on docs/source/blocks/examples/customviewandvariations.md
> +We can create a block that uses `variations`. A {term}`variation` is an alternative view of a block. This variation is shown as an additional option in the schema editor and lets the webmaster to cha
No, in this case it should be the editor. When registering a `variation` we let the editor select how the block will be shown.

2025-01-03 15:02 UTC, erral commented on docs/source/blocks/examples/customviewandvariations.md
> +// the `withBlockExtensions` HOC, makes the variation selector available in the block edit form
HOC: High Order Component. We should add a term indicator here.

2025-01-03 15:07 UTC, erral commented
Thanks @stevepiercy for your excellent review!

2025-01-03 23:09 UTC, stevepiercy commented on docs/source/blocks/examples/customviewandvariations.md
> +We can create a block that uses `variations`. A {term}`variation` is an alternative view of a block. This variation is shown as an additional option in the schema editor and lets the webmaster to cha
Updated suggestion.

2025-01-03 23:10 UTC, stevepiercy commented on docs/source/blocks/examples/customviewandvariations.md
> +// the `withBlockExtensions` HOC, makes the variation selector available in the block edit form
Done in 836d0944772159859c9e26ada9af9b8b9e99d411. However, we can't use terms in code blocks, so we need it somewhere in the narrative text.

2025-01-03 23:14 UTC, stevepiercy commented on docs/source/blocks/settings.md
> +    // in case that the `edit` setting of the block is set to `null`
Perfect.

```suggestion
    // The `blockSchema` property can either be a schema by itself
    // (a JavaScript object describing the schema),
    // or a function that returns a schema.
```

2025-01-03 23:17 UTC, stevepiercy requested changes
Update comment suggestion

2025-01-03 23:17 UTC, stevepiercy commented on docs/source/blocks/settings.md
> +    // A block can have a function that returns the schema or directly the schema
```suggestion
```

2025-01-03 23:17 UTC, stevepiercy commented on docs/source/blocks/settings.md
> +    // of the block that will be automatically rendered in the sidebar editor
```suggestion
```

2025-01-04 09:22 UTC, stevepiercy commented
Direct link to preview.

https://volto--6560.org.readthedocs.build/blocks/examples/custom-schema-and-view.html#see-it-in-action

We need to fix some syntax here.

2025-01-04 09:44 UTC, stevepiercy commented on docs/source/blocks/examples/customviewandvariations.md
> +// the `withBlockExtensions` HOC, makes the variation selector available in the block edit form
Done in https://github.com/plone/volto/pull/6560/commits/3d83b5497c3ee0dd8f2f0709a7c6cce834ad3f3b

2025-01-04 09:58 UTC, stevepiercy requested changes
Just a bunch of nitpicky stuff, except for changing webmaster or developer to editor. I'll merge these. Over to @ichim-david!

2025-01-04 09:58 UTC, stevepiercy commented on docs/source/blocks/examples/custom-view-and-variations.md
> +
```suggestion
```

2025-01-04 09:58 UTC, stevepiercy commented on docs/source/blocks/examples/custom-view-and-variations.md
> +Your block is ready to be used in your site.
```suggestion
Your block is ready to use in your site.
```

2025-01-04 09:58 UTC, stevepiercy commented on docs/source/blocks/examples/custom-schema-and-view.md
> +Your block is ready to be used in your site.
```suggestion
Your block is ready to use in your site.
```

2025-01-04 09:58 UTC, stevepiercy commented on docs/source/blocks/examples/custom-view-variations-and-schema-enhancer.md
> +# Block with a custom schema, variations, and a schema enhancer in a variation.
```suggestion
# Block with a custom schema, variations, and a schema enhancer in a variation
```

2025-01-04 09:58 UTC, stevepiercy commented on docs/source/blocks/examples/custom-view-variations-and-schema-enhancer.md
> +The variation is shown as an additional option in the schema editor, and lets the developer change how this block is viewed.
```suggestion
The variation is shown as an additional option in the schema editor, and lets the editor change how this block is viewed.
```

2025-01-04 09:58 UTC, stevepiercy commented on docs/source/blocks/examples/custom-view-variations-and-schema-enhancer.md
> +  // `data` holds the values entered in the block edit form
```suggestion
  // `data` holds the values entered in the block edit form.
```

2025-01-04 09:58 UTC, stevepiercy commented on docs/source/blocks/examples/custom-view-variations-and-schema-enhancer.md
> +  // className holds the CSS class names injected to this block by Volto's `styleClassNameExtenders`
```suggestion
  // `className` holds the CSS class names injected to this block by Volto's `styleClassNameExtenders`.
```

2025-01-04 09:58 UTC, stevepiercy commented on docs/source/blocks/examples/custom-view-variations-and-schema-enhancer.md
> +  // `style` holds the CSS properties injected into this block by Volto's `Block Style Wrapper`
```suggestion
  // `style` holds the CSS properties injected into this block by Volto's `Block Style Wrapper`.
```

2025-01-04 09:58 UTC, stevepiercy commented on docs/source/blocks/examples/custom-view-variations-and-schema-enhancer.md
> +  // `variation` holds the variation selected in the block editor, and it is an object as defined in the block configuration
```suggestion
  // `variation` holds the variation selected in the block editor, and it is an object as defined in the block configuration.
```

2025-01-04 09:58 UTC, stevepiercy commented on docs/source/blocks/examples/custom-view-variations-and-schema-enhancer.md
> +// the `withBlockExtensions` HOC, makes the variation selector available in the block edit form
```suggestion
```

2025-01-04 09:58 UTC, stevepiercy commented on docs/source/blocks/examples/custom-view-variations-and-schema-enhancer.md
> +// and provides the `variation` property in the props.
```suggestion
```

2025-01-04 09:58 UTC, stevepiercy commented on docs/source/blocks/examples/custom-view-variations-and-schema-enhancer.md
> +
```suggestion

The `withBlockExtensions` {term}`HOC` makes the variation selector available in the block edit form and provides the `variation` property in the props.

```

2025-01-04 09:58 UTC, stevepiercy commented on docs/source/blocks/examples/custom-view-variations-and-schema-enhancer.md
> +Your block is ready to be used in your site.
```suggestion
Your block is ready to use in your site.
```

2025-01-04 09:59 UTC, stevepiercy approved these changes

2025-01-04 10:03 UTC, stevepiercy commented
Glossary terms link now.

https://volto--6560.org.readthedocs.build/blocks/examples/custom-view-and-variations.html#view-component

According to the React docs, HOC is no longer used in modern React, so should we use them anymore?

2025-01-04 11:15 UTC, ichim-david requested changes
@erral thank you again for taking the time to write these examples.

I think we are missing an example where you also define a custom edit view since we have created the view component, the schema and the schema enhancer.

What we haven't shown yet to the user is how they can also create a custom edit component.
It can also come in another pull request or added by Steve or anyone else I'm not saying it's mandatory for that example to also be created in this pull request but I think it would have been useful to have that example as well.

Again thank you for your work.

2025-01-04 11:15 UTC, ichim-david commented on docs/source/blocks/examples/custom-view-and-variations.md
> +  // `className` holds the CSS class names injected into this block by Volto's `styleClassNameExtenders`.
@erral it would be great to split the comments in such a way that you can view it without having to use any scrollbars.
See this screen capture in order to understand what i mean i would like not to have to horizontally scroll in order to read what was the suggestion or documentation for the options used in the block config

![comments-visible](https://github.com/user-attachments/assets/1769a935-f9f8-496a-922d-8d2bf4c0cc04)

2025-01-04 11:15 UTC, ichim-david commented on docs/source/blocks/examples/custom-view-variations-and-schema-enhancer.md
> +    title: 'Color',
@erral Since you are teaching the users to use the Intl message format, I think it would be worth it to use it also in the schema enhancer example. Therefore, we always teach them to create add-ons the proper way, thinking of internationalization for other users as well.

2025-01-04 11:15 UTC, ichim-david commented on docs/source/blocks/examples/custom-view-variations-and-schema-enhancer.md
> +As you can see, the variations are pretty much the same.
This is wrong since you have created a schema enhancer and you have defined the color property we should have a rendering of this color property so they can clearly see the difference when rendering the first variation and the second variation

2025-01-04 12:38 UTC, erral commented on docs/source/blocks/examples/custom-schema-and-view.md
> +In your Volto add-on, create a subfolder {file}`ExampleBlock02` inside the {file}`components` folder to save all the files required to create a block.
wrll, this comes from examples I have written for my team. There are 6 examples, but I have brought here only 3, the most relevant ones. I have copy-pasted the code, so that's why we have 2, 5 and 6.

I haven't copied the following ones:

- Block just with schema (automatic view and edit)
- Custom edit component (I will add this following your suggestion)
- Block with 'manual' variations: adding the variation field manually in the schema

2025-01-05 17:32 UTC, erral commented on docs/source/blocks/examples/custom-schema-and-view.md
> +const applyConfig = (config) => {
I will rewrite this, saying to add the block configuration form before the `return config`, that will be easier to understand.

2025-01-05 17:49 UTC, erral commented
Thanks @ichim-david and @stevepiercy for your comments.

I have made some modifications in the docs:

- I have included the example with a custom edit component
- I have renamed the examples 1,2,3,4 instead of the previous 2, 5 and 6 :sweat_smile: 
- I have changed the block configuration settings part. I have reworded where the configuration should be included to be clearer for the reader.

2025-01-05 23:07 UTC, stevepiercy requested changes
More nitpicky stuff. I'll merge these.

2025-01-05 23:07 UTC, stevepiercy commented on docs/source/blocks/examples/custom-schema-view-and-edit.md
> +Restart your Volto site, and now you can add the new block from the block chooser found in the `edit` or `add` new content views.
I'm gonna make this silver fancy dancing pants. 🪩 🕺 

```suggestion
Restart your Volto site, and now you can add the new block from the block chooser found in the {guilabel}`Edit` <img alt="Edit icon" src="../../_static/pen.svg" class="inline"> or {guilabel}`Add` <img alt="Add icon" src="../../_static/add-document.svg" class="inline"> content views.
```

2025-01-05 23:14 UTC, stevepiercy requested changes
I'm waiting for the RTD PR preview to complete building before committing these suggestions.

2025-01-05 23:14 UTC, stevepiercy commented on docs/source/blocks/examples/custom-schema-and-view.md
> +Restart your Volto site, and now you can add the new block from the block chooser found in the `edit` or `add` new content views.
```suggestion
Restart your Volto site, and now you can add the new block from the block chooser found in the {guilabel}`Edit` <img alt="Edit icon" src="../../_static/pen.svg" class="inline"> or {guilabel}`Add` <img alt="Add icon" src="../../_static/add-document.svg" class="inline"> content views.
```

2025-01-05 23:14 UTC, stevepiercy commented on docs/source/blocks/examples/custom-view-and-variations.md
> +Restart your Volto site, and you can add it using the block add form.
```suggestion
Restart your Volto site, and now you can add the new block from the block chooser found in the {guilabel}`Edit` <img alt="Edit icon" src="../../_static/pen.svg" class="inline"> or {guilabel}`Add` <img alt="Add icon" src="../../_static/add-document.svg" class="inline"> content views.
```

2025-01-05 23:14 UTC, stevepiercy commented on docs/source/blocks/examples/custom-view-variations-and-schema-enhancer.md
> +Restart your Volto site, and you can add it using the block add form.
```suggestion
Restart your Volto site, and now you can add the new block from the block chooser found in the {guilabel}`Edit` <img alt="Edit icon" src="../../_static/pen.svg" class="inline"> or {guilabel}`Add` <img alt="Add icon" src="../../_static/add-document.svg" class="inline"> content views.
```

2025-01-05 23:18 UTC, stevepiercy approved these changes
This looks great. Thank you @erral for sharing your work, and @ichim-david for the suggesstions for improvement. ✋ 

@ichim-david one more review from you, and if you approve, please go ahead and merge.

2025-01-06 11:37 UTC, ichim-david approved these changes
@erral and @stevepiercy. I built locally and the code examples look good now without any extra
overflow scrollbars and the build is passing.
Again thank you erral for this work.

2025-01-06 11:37 UTC, merged

2025-01-08 01:28 UTC, davisagli commented
@erral @ichim-david @stevepiercy Nice work!